import type { ContentData, LegalKind } from "./types";

/**
 * The long-form bodies that most visitors never read.
 *
 * `seed.ts` is reachable from `main.tsx`, so anything it imports statically is in
 * the entry chunk and is downloaded and parsed before the homepage paints. Two of
 * its imports were large and route-specific:
 *
 *   blogs.seed.json   42,575 chars, 89% of it the HTML of nine articles that only
 *                     /blog/: slug renders
 *   legal.seed.json   54,806 chars, 54,064 of it the four policy documents that
 *                     only /privacy, /terms, /refund and /disclaimer render
 *
 * The seed now carries only their metadata (titles, excerpts, covers, dates, 
 * 5,116 chars, generated by scripts/split-content.mjs). The bodies live behind the
 * dynamic import below, so Rollup emits them as their own chunk and the four pages
 * that want them are the only pages that fetch them.
 *
 * This is a lazy read, not a background prefetch: nothing calls it until a page
 * that needs a body mounts.
 */

interface DeferredBodies {
  /** Blog post id (as a string, matching BlogPost.id) → HTML body. */
  posts: Record<string, string>;
  /** Legal document kind → HTML body. */
  legal: Record<LegalKind, string>;
}

let pending: Promise<DeferredBodies> | null = null;

/** Fetch (once) the blog and legal bodies. Subsequent calls share the promise. */
export function loadDeferredBodies(): Promise<DeferredBodies> {
  if (!pending) {
    pending = Promise.all([
      import("./data/blogs.seed.json"),
      import("./data/legal.seed.json"),
    ]).then(([blogs, legal]) => {
      const posts: Record<string, string> = {};
      for (const [i, raw] of ((blogs.default ?? blogs) as any[]).entries()) {
        posts[String(raw.id ?? i + 1)] = raw.content || "";
      }
      const legalSrc = (legal.default ?? legal) as Record<string, { body?: string }>;
      const legalBodies = {} as Record<LegalKind, string>;
      for (const [kind, doc] of Object.entries(legalSrc)) {
        legalBodies[kind as LegalKind] = doc?.body ?? "";
      }
      return { posts, legal: legalBodies };
    });
  }
  return pending;
}

/**
 * Put the bodies back into a content snapshot.
 *
 * Only fills a body that is still empty, so an edit made in /admin, or a
 * Supabase row, or a localStorage snapshot: always wins over the seeded text.
 * Returns the same object when there is nothing to do, so React can skip the
 * re-render.
 */
export function fillDeferredBodies(data: ContentData, bodies: DeferredBodies): ContentData {
  let changed = false;

  const posts = data.posts.map((post) => {
    if (post.body) return post;
    const body = bodies.posts[post.id];
    if (!body) return post;
    changed = true;
    return {...post, body };
  });

  const legal = {...data.legal };
  for (const kind of Object.keys(legal) as LegalKind[]) {
    if (legal[kind]?.body) continue;
    const body = bodies.legal[kind];
    if (!body) continue;
    changed = true;
    legal[kind] = {...legal[kind], body };
  }

  return changed ? {...data, posts, legal }: data;
}
