/**
 * d1-family-dentist: Sheesham Family Dental Clinic, Gomti Nagar, Lucknow.
 * A neighbourhood family practice: one lead dentist, one associate and two
 * visiting MDS specialists, split sessions, WhatsApp-first booking, bilingual.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md. Everything here is fiction: the clinic, the doctors,
 * the reviews, the rating and the trust figures are SAMPLE content and carry
 * the SampleNote label until the clinic replaces them. No case has a photo.
 * The name forms must stay exactly as in TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Sheesham Family Dental Clinic",
  shortName: "Sheesham Dental",
  tagline: "Check-ups, root canal, fillings, kids dentistry and dentures, in Gomti Nagar, Lucknow.",
  city: "Lucknow",
  state: "Uttar Pradesh",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2012",
  establishedYear: "2012",
  sitePages: [...DENTAL_PAGE_SETS["d1-family-dentist"]],
  heroImage: "/demo/img/dental/hero-consultation-chair-800.webp",
  sectionPhotos: { about: "/demo/img/dental/interior-waiting-teal-640.webp" },
  photos: [
    { src: "/demo/img/dental/interior-waiting-teal-640.webp", alt: "", category: "Clinic", caption: "Waiting area", hi: { category: "क्लिनिक", caption: "प्रतीक्षा कक्ष" } },
    { src: "/demo/img/dental/interior-teal-suite-640.webp", alt: "", category: "Clinic", caption: "Treatment room", hi: { category: "क्लिनिक", caption: "इलाज का कमरा" } },
    { src: "/demo/img/dental/sterile-autoclave-640.webp", alt: "", category: "Sterilisation", caption: "Autoclave and sealed pouches", hi: { category: "स्टरलाइज़ेशन", caption: "ऑटोक्लेव और सील पाउच" } },
    { src: "/demo/img/dental/tech-xray-monitor-640.webp", alt: "", category: "Diagnosis", caption: "Digital X-ray on screen", hi: { category: "जाँच", caption: "स्क्रीन पर डिजिटल एक्स-रे" } },
  ],
  about:
    "Sheesham Family Dental Clinic opened in 2012 as a single-chair practice above a pharmacy in Gomti Nagar. Today it has two treatment rooms, a separate sterilisation area and a small team that knows most families by name.\n\nWe look after grandparents, parents and children in the same household, so we keep things simple: explain the problem on the X-ray, give a written estimate, and do the work in as few visits as is clinically sensible. Specialists for braces and children visit on fixed days, so you do not have to cross the city for them.",
  mission: "Everyday dental care for families in Gomti Nagar, explained plainly and priced before we start.",
  vision: "A neighbourhood clinic where a check-up feels routine, not frightening, for every age.",
  hi: {
    instituteName: "शीशम फ़ैमिली डेंटल क्लिनिक",
    shortName: "शीशम डेंटल",
    tagline: "चेक-अप, रूट कैनाल, फ़िलिंग, बच्चों के दाँत और डेंचर, गोमती नगर, लखनऊ में।",
    city: "लखनऊ",
    state: "उत्तर प्रदेश",
    established: "2012 से",
    establishedYear: "2012",
    about:
      "शीशम फ़ैमिली डेंटल क्लिनिक 2012 में गोमती नगर में एक दवा की दुकान के ऊपर एक कुर्सी वाले क्लिनिक के रूप में शुरू हुआ। आज यहाँ इलाज के दो कमरे, अलग स्टरलाइज़ेशन कक्ष और एक छोटी टीम है जो ज़्यादातर परिवारों को नाम से जानती है।\n\nहम एक ही घर के दादा-दादी, माता-पिता और बच्चों का इलाज करते हैं, इसलिए बात सीधी रखते हैं: एक्स-रे पर समस्या समझाना, लिखित अनुमान देना, और जितनी कम विज़िट में सही हो, उतने में काम पूरा करना। ब्रेसेज़ और बच्चों के विशेषज्ञ तय दिनों पर आते हैं, ताकि आपको शहर पार न करना पड़े।",
    mission: "गोमती नगर के परिवारों के लिए रोज़मर्रा की दाँतों की देखभाल, साफ़ शब्दों में समझाई हुई और शुरू करने से पहले तय क़ीमत के साथ।",
    vision: "पड़ोस का ऐसा क्लिनिक जहाँ हर उम्र के लिए चेक-अप डर नहीं, आम बात लगे।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "hello@example.com",
    addressLines: ["Example Road", "Gomti Nagar, Lucknow 226000"],
    hours: "Mon to Sat, 10 am to 1:30 pm and 5 to 8:30 pm. Sun, 10 am to 1 pm",
    landmark: "First floor, above a pharmacy, near the Patrakarpuram crossing",
    mapQuery: "Gomti Nagar, Lucknow",
    hi: {
      addressLines: ["उदाहरण रोड", "गोमती नगर, लखनऊ 226000"],
      hours: "सोम से शनि, सुबह 10 से दोपहर 1:30 और शाम 5 से 8:30। रवि, सुबह 10 से दोपहर 1",
      landmark: "पहली मंज़िल, दवा की दुकान के ऊपर, पत्रकारपुरम चौराहे के पास",
    },
  },
  stats: [
    { value: "14", label: "Years in Gomti Nagar", basis: "Since 2012", hi: { label: "साल गोमती नगर में", basis: "2012 से" } },
    { value: "2", label: "MDS specialists on fixed days", basis: "Orthodontics and children's dentistry", hi: { label: "MDS विशेषज्ञ तय दिनों पर", basis: "ऑर्थोडॉन्टिक्स और बच्चों के दाँत" } },
    { value: "4", label: "Languages spoken", basis: "Hindi, English, Urdu, Awadhi", hi: { label: "भाषाएँ बोली जाती हैं", basis: "हिंदी, अंग्रेज़ी, उर्दू, अवधी" } },
  ],
  rating: { value: "4.8", count: "186", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "I had put off a root canal for a year out of fear. Dr. Saxena showed me the X-ray, explained each step and let me raise a hand whenever I needed a break. Two visits and it was done.", relation: "Patient, root canal", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Root canal", hi: { quote: "डर के कारण मैंने एक साल तक रूट कैनाल टाला। डॉ. सक्सेना ने एक्स-रे दिखाया, हर क़दम समझाया और कहा कि जब भी रुकना हो, हाथ उठा दूँ। दो विज़िट में काम पूरा हो गया।", relation: "मरीज़, रूट कैनाल", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "रूट कैनाल" } },
    { quote: "We bring both kids here for six-monthly check-ups. The children's specialist on Saturdays is patient with my younger one, who used to cry at the gate.", relation: "Parent of two, check-ups", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Kids", hi: { quote: "हम दोनों बच्चों को हर छह महीने चेक-अप के लिए यहाँ लाते हैं। शनिवार को आने वाली बच्चों की विशेषज्ञ मेरे छोटे बेटे के साथ बहुत धैर्य रखती हैं, जो पहले गेट पर ही रोने लगता था।", relation: "दो बच्चों के माता-पिता, चेक-अप", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "बच्चे" } },
    { quote: "My mother's new dentures took three fittings to get right, and they did not rush any of them. She eats rotis again without trouble.", relation: "Son of a patient, dentures", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Dentures", hi: { quote: "माँ के नए डेंचर को ठीक बैठाने में तीन फ़िटिंग लगीं, और किसी में भी जल्दबाज़ी नहीं की गई। अब वह आराम से फिर से रोटी खा लेती हैं।", relation: "मरीज़ के बेटे, डेंचर", source: "गूगल रिव्यू", date: "जून 2026", category: "डेंचर" } },
    { quote: "Clear estimate on WhatsApp before the filling, and the bill matched it. The clinic is small but very clean.", relation: "Patient, fillings", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Fillings", hi: { quote: "फ़िलिंग से पहले व्हाट्सऐप पर साफ़ अनुमान मिला, और बिल उसी के बराबर आया। क्लिनिक छोटा है पर बहुत साफ़ है।", relation: "मरीज़, फ़िलिंग", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "फ़िलिंग" } },
    { quote: "Woke up with a swollen cheek on a Sunday. They saw me in the morning session, drained it and started treatment. Good that they open on Sundays.", relation: "Patient, emergency visit", rating: "4", source: "Google review", date: "May 2026", consent: true, category: "Emergency", hi: { quote: "रविवार को गाल सूजा हुआ था। उन्होंने सुबह के सेशन में देखा, पस निकाला और इलाज शुरू किया। अच्छा है कि रविवार को भी खुलता है।", relation: "मरीज़, इमरजेंसी विज़िट", source: "गूगल रिव्यू", date: "मई 2026", category: "इमरजेंसी" } },
    { quote: "Scaling was quick and the doctor showed me how to brush along the gums. Waiting time was a bit long in the evening, so book ahead.", relation: "Patient, cleaning", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Cleaning", hi: { quote: "स्केलिंग जल्दी हो गई और डॉक्टर ने मसूड़ों के साथ ब्रश करना सिखाया। शाम को इंतज़ार थोड़ा लंबा था, इसलिए पहले से बुक करें।", relation: "मरीज़, सफ़ाई", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "सफ़ाई" } },
  ],
  posts: [
    {
      slug: "what-happens-in-a-root-canal", title: "What actually happens in a root canal", date: "16 Sep 2026", category: "Root canal", treatment: "root-canal-treatment",
      author: "Dr. Nidhi Saxena", reviewedBy: "Medically reviewed by Dr. Nidhi Saxena, MDS (Conservative Dentistry and Endodontics)",
      excerpt: "Most of the fear comes from not knowing the steps. Here they are, in order, with what you will feel.",
      body: "A root canal treats the soft pulp inside a tooth when it is infected or badly inflamed. The aim is to keep your own tooth instead of removing it.\n\nFirst, an X-ray shows how far the infection has spread and how many canals the tooth has. The area is then numbed with a local anaesthetic, and a thin rubber sheet keeps the tooth dry.\n\nThe dentist makes a small opening, cleans the canals with fine files and rinses them. They are then filled and sealed. Most teeth need one or two visits of about an hour.\n\nFor a day or two the tooth can feel tender when you bite. A back tooth usually needs a crown afterwards, because a treated tooth is more brittle and can crack.\n\nAsk to see your X-ray before and after. It shows you exactly what was done.",
      hi: {
        title: "रूट कैनाल में असल में क्या होता है", date: "16 सितंबर 2026", category: "रूट कैनाल", author: "डॉ. निधि सक्सेना", reviewedBy: "डॉ. निधि सक्सेना, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "ज़्यादातर डर इसलिए होता है क्योंकि पता नहीं होता कि क्या होगा। यहाँ हर चरण क्रम से है, और आप क्या महसूस करेंगे।",
        body: "रूट कैनाल दाँत के अंदर की नरम पल्प का इलाज है, जब वह संक्रमित हो या उसमें ज़्यादा सूजन हो। मक़सद है दाँत निकालने के बजाय आपका अपना दाँत बचाना।\n\nपहले एक्स-रे से पता चलता है कि संक्रमण कितना फैला है और दाँत में कितनी नलिकाएँ हैं। फिर लोकल एनेस्थीसिया से जगह सुन्न की जाती है, और एक पतली रबर शीट दाँत को सूखा रखती है।\n\nडेंटिस्ट एक छोटा रास्ता बनाकर बारीक फ़ाइलों से नलिकाएँ साफ़ करते हैं और धोते हैं। फिर उन्हें भरकर सील किया जाता है। ज़्यादातर दाँतों में लगभग एक घंटे की एक या दो विज़िट लगती हैं।\n\nएक-दो दिन काटने पर दाँत नाज़ुक लग सकता है। पीछे के दाँत पर बाद में आमतौर पर क्राउन लगता है, क्योंकि इलाज के बाद दाँत ज़्यादा भुरभुरा होता है और टूट सकता है।\n\nइलाज से पहले और बाद का एक्स-रे दिखाने को कहें। उससे साफ़ पता चलता है कि क्या किया गया।",
      },
    },
    {
      slug: "childs-first-dental-visit", title: "Your child's first dental visit: when, and what to expect", date: "2 Sep 2026", category: "Kids", treatment: "childrens-dentistry",
      author: "Dr. Shalini Verma", reviewedBy: "Medically reviewed by Dr. Shalini Verma, MDS (Paediatric and Preventive Dentistry)",
      excerpt: "The first visit should come by the first birthday, long before any problem. It is short, and mostly a conversation.",
      body: "Book the first visit when the first tooth appears, or by your child's first birthday. Early visits are about prevention, and they let your child get used to the clinic before anything needs treating.\n\nThe first visit is short. Your child usually sits on your lap. The dentist counts the teeth, looks at the gums, and checks for early signs of decay, often the white chalky lines that appear before a cavity.\n\nMost of the time is spent with you: how to brush a toddler's teeth, how much toothpaste to use (a smear the size of a rice grain under three), and why a bottle of milk at bedtime is a common cause of decay in milk teeth.\n\nMilk teeth matter. They hold space for the adult teeth, and a painful milk tooth affects eating, sleep and school. After the first visit, a check every six months is usual.",
      hi: {
        title: "बच्चे की पहली डेंटल विज़िट: कब, और क्या उम्मीद करें", date: "2 सितंबर 2026", category: "बच्चे", author: "डॉ. शालिनी वर्मा", reviewedBy: "डॉ. शालिनी वर्मा, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "पहली विज़िट पहले जन्मदिन तक होनी चाहिए, किसी परेशानी से बहुत पहले। यह छोटी होती है, और ज़्यादातर बातचीत।",
        body: "पहला दाँत निकलते ही, या बच्चे के पहले जन्मदिन तक पहली विज़िट बुक करें। शुरुआती विज़िट बचाव के लिए होती हैं, और इलाज की ज़रूरत पड़ने से पहले बच्चा क्लिनिक से परिचित हो जाता है।\n\nपहली विज़िट छोटी होती है। बच्चा आमतौर पर आपकी गोद में बैठता है। डेंटिस्ट दाँत गिनते हैं, मसूड़े देखते हैं, और कीड़े के शुरुआती निशान देखते हैं, अक्सर सफ़ेद चॉक जैसी रेखाएँ जो कैविटी से पहले दिखती हैं।\n\nज़्यादातर समय आपसे बात होती है: छोटे बच्चे के दाँत कैसे ब्रश करें, कितना टूथपेस्ट लें (तीन साल से कम में चावल के दाने जितना), और सोते समय दूध की बोतल दूध के दाँतों में कीड़े की आम वजह क्यों है।\n\nदूध के दाँत ज़रूरी हैं। वे पक्के दाँतों के लिए जगह रखते हैं, और दर्द वाला दूध का दाँत खाने, नींद और स्कूल पर असर डालता है। पहली विज़िट के बाद हर छह महीने में जाँच आम है।",
      },
    },
    {
      slug: "bleeding-gums-when-brushing", title: "Bleeding gums when you brush: what it means", date: "19 Aug 2026", category: "Gums", treatment: "gum-care",
      author: "Dr. Faraz Siddiqui", reviewedBy: "Medically reviewed by Dr. Nidhi Saxena, MDS (Conservative Dentistry and Endodontics)",
      excerpt: "Blood in the sink is not normal, and it is not a reason to brush less. Usually it is early gum disease, and it can be reversed.",
      body: "Healthy gums do not bleed when you brush. Bleeding is most often gingivitis, an early gum inflammation caused by plaque left along the gum line.\n\nThe common reaction is to brush more gently or avoid the area. That lets more plaque build up. Keep brushing twice a day with a soft brush, angled towards the gum, and clean between teeth once a day.\n\nIf bleeding does not settle in two weeks, see a dentist. Hardened plaque (tartar) cannot be brushed off and needs scaling. Left alone, gingivitis can progress to periodontitis, where the bone around the teeth is lost and teeth can loosen.\n\nSome things raise the risk: diabetes, smoking and gutka, pregnancy, and some medicines. Tell your dentist about them. Bleeding with bruising elsewhere or unexplained tiredness needs a doctor's check as well.",
      hi: {
        title: "ब्रश करते समय मसूड़ों से ख़ून: इसका मतलब क्या है", date: "19 अगस्त 2026", category: "मसूड़े", author: "डॉ. फ़राज़ सिद्दीक़ी", reviewedBy: "डॉ. निधि सक्सेना, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "सिंक में ख़ून सामान्य नहीं है, और यह कम ब्रश करने की वजह नहीं है। आमतौर पर यह मसूड़ों की शुरुआती बीमारी है, जो ठीक हो सकती है।",
        body: "स्वस्थ मसूड़ों से ब्रश करते समय ख़ून नहीं आता। ख़ून आना अक्सर जिंजिवाइटिस है, यानी मसूड़े की रेखा पर जमे प्लाक से मसूड़ों की शुरुआती सूजन।\n\nआम तौर पर लोग धीरे ब्रश करने लगते हैं या उस जगह से बचते हैं। इससे और प्लाक जमता है। दिन में दो बार नरम ब्रश से, मसूड़े की ओर झुकाकर ब्रश करते रहें, और दिन में एक बार दाँतों के बीच सफ़ाई करें।\n\nअगर दो हफ़्ते में ख़ून बंद न हो, तो डेंटिस्ट को दिखाएँ। सख़्त हो चुका प्लाक (टार्टर) ब्रश से नहीं हटता और स्केलिंग से ही साफ़ होता है। छोड़ देने पर जिंजिवाइटिस पेरियोडॉन्टाइटिस बन सकता है, जिसमें दाँतों के आसपास की हड्डी घटती है और दाँत ढीले हो सकते हैं।\n\nकुछ चीज़ें ख़तरा बढ़ाती हैं: डायबिटीज़, धूम्रपान और गुटखा, गर्भावस्था, और कुछ दवाइयाँ। इनके बारे में डेंटिस्ट को बताएँ। अगर शरीर पर और जगह नील पड़ें या बिना वजह थकान हो, तो डॉक्टर से भी जाँच करवाएँ।",
      },
    },
  ],
  faq: [
    { title: "Do I need an appointment, or can I walk in?", body: "Walk-ins are seen between booked patients, so there can be a wait. A booking on WhatsApp or by phone gets you a fixed time. Tooth pain and swelling are fitted in the same day where possible.", group: "Visiting", hi: { title: "क्या अपॉइंटमेंट ज़रूरी है, या सीधे आ सकते हैं?", body: "बिना बुकिंग आने वालों को बुक किए मरीज़ों के बीच देखा जाता है, इसलिए इंतज़ार हो सकता है। व्हाट्सऐप या फ़ोन पर बुकिंग से तय समय मिलता है। दाँत दर्द और सूजन को जहाँ तक हो सके उसी दिन देखा जाता है।", group: "विज़िट" } },
    { title: "What does the first visit cost?", body: "The consultation fee is Rs 300. If you need an X-ray, a single tooth X-ray is Rs 200. You get a written estimate for any treatment before it starts.", group: "Fees", hi: { title: "पहली विज़िट का ख़र्च कितना है?", body: "परामर्श शुल्क 300 रुपये है। एक्स-रे की ज़रूरत हो तो एक दाँत का एक्स-रे 200 रुपये का है। किसी भी इलाज से पहले आपको लिखित अनुमान मिलता है।", group: "फ़ीस" } },
    { title: "Does a root canal hurt?", body: "It is done under local anaesthesia, so most people feel pressure rather than pain during it. The tooth can be sore for two or three days afterwards; a simple painkiller usually helps. We stop whenever you raise a hand.", group: "Treatment", hi: { title: "क्या रूट कैनाल में दर्द होता है?", body: "यह लोकल एनेस्थीसिया में होता है, इसलिए ज़्यादातर लोगों को दर्द नहीं, दबाव महसूस होता है। बाद में दो-तीन दिन दाँत में हल्का दर्द रह सकता है, जो आम दर्द निवारक दवा से ठीक हो जाता है। आप हाथ उठाएँ तो हम रुक जाते हैं।", group: "इलाज" } },
    { title: "Can I pay in instalments?", body: "For treatment above Rs 10,000, card EMI may be available through your bank, subject to its approval. For dentures and crowns we can also split payment across visits. Ask at the desk.", group: "Fees", hi: { title: "क्या किस्तों में भुगतान हो सकता है?", body: "10,000 रुपये से ज़्यादा के इलाज पर आपके बैंक के कार्ड से EMI मिल सकती है, बैंक की मंज़ूरी पर। डेंचर और क्राउन के लिए भुगतान विज़िट के हिसाब से बाँटा भी जा सकता है। काउंटर पर पूछें।", group: "फ़ीस" } },
    { title: "How are instruments cleaned?", body: "Every instrument is washed, sealed in a pouch and sterilised in a Class B autoclave. Pouches are opened in front of you. Needles, gloves, suction tips and cups are single use.", group: "Safety", hi: { title: "औज़ार कैसे साफ़ किए जाते हैं?", body: "हर औज़ार धोया जाता है, पाउच में सील होता है और क्लास B ऑटोक्लेव में स्टरलाइज़ होता है। पाउच आपके सामने खोले जाते हैं। सुई, दस्ताने, सक्शन टिप और कप एक बार ही इस्तेमाल होते हैं।", group: "सुरक्षा" } },
    { title: "At what age should my child first see a dentist?", body: "By the first birthday, or within six months of the first tooth. The first visit is mostly a chat and a look, with the child on your lap.", group: "Children", hi: { title: "बच्चे को पहली बार डेंटिस्ट के पास कब ले जाएँ?", body: "पहले जन्मदिन तक, या पहला दाँत आने के छह महीने के अंदर। पहली विज़िट में ज़्यादातर बातचीत और एक नज़र देखना होता है, बच्चा आपकी गोद में रहता है।", group: "बच्चे" } },
    { title: "Is there parking and is the clinic accessible?", body: "Two-wheelers park in front; cars park along the service lane. The clinic is on the first floor with a lift. Tell us when you book if you need help on arrival.", group: "Visiting", hi: { title: "क्या पार्किंग है और क्लिनिक तक पहुँचना आसान है?", body: "दोपहिया सामने खड़े होते हैं; कारें सर्विस लेन में। क्लिनिक पहली मंज़िल पर है और लिफ़्ट है। अगर पहुँचने पर मदद चाहिए तो बुकिंग के समय बता दें।", group: "विज़िट" } },
    { title: "Do you treat patients with diabetes or heart conditions?", body: "Yes. Bring your prescriptions and recent reports to the first visit. For some treatments we check with your physician first, and we plan extractions around blood thinners with their advice.", group: "Treatment", hi: { title: "क्या डायबिटीज़ या दिल की बीमारी वाले मरीज़ों का इलाज होता है?", body: "हाँ। पहली विज़िट में अपनी दवाओं की पर्ची और हाल की रिपोर्ट लाएँ। कुछ इलाज से पहले हम आपके डॉक्टर से बात करते हैं, और ख़ून पतला करने वाली दवा हो तो उनकी सलाह से दाँत निकालने की योजना बनाते हैं।", group: "इलाज" } },
  ],
  dental: {
    legalName: "Sheesham Dental Care LLP (sample)",
    hi: { legalName: "शीशम डेंटल केयर LLP (नमूना)" },
    hero: {
      pill: "Open 7 days, evenings until 8:30 pm Mon to Sat",
      headline: "Gentle, *everyday dental care* for the whole family",
      lead: "Check-ups, root canal, fillings, kids dentistry and dentures, in Gomti Nagar, Lucknow.",
      nextSlot: "Evening slots from 5 pm, Mon to Sat",
      credential: "Dr. Nidhi Saxena, BDS, MDS (Conservative Dentistry and Endodontics)",
      hi: {
        pill: "सातों दिन खुला, सोम से शनि शाम 8:30 तक",
        headline: "पूरे परिवार के लिए *रोज़ की, सधी हुई* दाँतों की देखभाल",
        lead: "चेक-अप, रूट कैनाल, फ़िलिंग, बच्चों के दाँत और डेंचर, गोमती नगर, लखनऊ में।",
        nextSlot: "शाम 5 बजे से स्लॉट, सोम से शनि",
        credential: "डॉ. निधि सक्सेना, BDS, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स)",
      },
    },
    doctors: [
      {
        slug: "nidhi-saxena", name: "Dr. Nidhi Saxena", photo: "/demo/img/people/dentist-w04-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Conservative Dentistry and Endodontics)", specialisation: "Endodontist",
        focus: "Root canal treatment, fillings, crowns, family check-ups", experience: "16 years in practice",
        languages: ["Hindi", "English", "Awadhi"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat, both sessions",
        bio: "Dr. Nidhi Saxena founded the clinic in 2012 after six years in hospital and private practice in Lucknow. Most of her day is root canal treatment, fillings and crowns, and the check-ups that stop small problems becoming big ones.\n\nShe shows every patient their X-ray on the screen before suggesting anything, and writes the estimate down. Families who started with her as young parents now bring their own children.",
        quote: "If you can see the problem on the X-ray, you can decide about it calmly.",
        training: ["BDS, Lucknow, 2006 (sample)", "MDS, Conservative Dentistry and Endodontics (sample)", "Rotary endodontics course (sample)"],
        memberships: ["Indian Dental Association (sample)", "Indian Endodontic Society (sample)"],
        hi: {
          name: "डॉ. निधि सक्सेना", qualification: "BDS, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स)", specialisation: "एंडोडॉन्टिस्ट",
          focus: "रूट कैनाल, फ़िलिंग, क्राउन, परिवार का चेक-अप", experience: "16 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "अवधी"],
          regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि, दोनों सेशन",
          bio: "डॉ. निधि सक्सेना ने लखनऊ के अस्पताल और निजी प्रैक्टिस में छह साल काम करने के बाद 2012 में यह क्लिनिक शुरू किया। उनका ज़्यादातर दिन रूट कैनाल, फ़िलिंग और क्राउन में जाता है, और उन चेक-अप में जो छोटी समस्या को बड़ा होने से रोकते हैं।\n\nवे कुछ भी सुझाने से पहले हर मरीज़ को स्क्रीन पर उसका एक्स-रे दिखाती हैं और अनुमान लिखकर देती हैं। जो परिवार युवा माता-पिता के रूप में उनके पास आए थे, वे अब अपने बच्चों को लाते हैं।",
          quote: "जब समस्या एक्स-रे पर दिख जाती है, तो उस पर शांति से फ़ैसला लिया जा सकता है।",
          training: ["BDS, लखनऊ, 2006 (नमूना)", "MDS, कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स (नमूना)", "रोटरी एंडोडॉन्टिक्स कोर्स (नमूना)"],
          memberships: ["इंडियन डेंटल एसोसिएशन (नमूना)", "इंडियन एंडोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "faraz-siddiqui", name: "Dr. Faraz Siddiqui", photo: "/demo/img/people/dentist-m04-240.webp", gender: "male",
        qualification: "BDS", specialisation: "General dentist", focus: "Check-ups, cleaning, extractions, dentures",
        experience: "7 years in practice", languages: ["Hindi", "English", "Urdu"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat, evening session; Sun morning",
        quote: "Most people need less work than they fear. A clean and a check tells us which.",
        hi: {
          name: "डॉ. फ़राज़ सिद्दीक़ी", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "चेक-अप, सफ़ाई, दाँत निकालना, डेंचर",
          experience: "7 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "उर्दू"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि, शाम का सेशन; रवि सुबह",
          quote: "ज़्यादातर लोगों को जितना डर होता है, उससे कम इलाज की ज़रूरत होती है। सफ़ाई और जाँच से यह पता चल जाता है।",
        },
      },
      {
        slug: "alok-tewari", name: "Dr. Alok Tewari", photo: "/demo/img/people/dentist-m02-240.webp", gender: "male", visiting: true,
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist", focus: "Braces and clear aligners for teenagers and adults",
        experience: "12 years in practice", languages: ["Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Thursdays, 5 to 8 pm",
        hi: {
          name: "डॉ. आलोक तिवारी", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट", focus: "किशोरों और वयस्कों के लिए ब्रेसेज़ और क्लियर अलाइनर",
          experience: "12 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "गुरुवार, शाम 5 से 8",
        },
      },
      {
        slug: "shalini-verma", name: "Dr. Shalini Verma", photo: "/demo/img/people/dentist-w06-240.webp", gender: "female", visiting: true,
        qualification: "BDS, MDS (Paediatric and Preventive Dentistry)", specialisation: "Paediatric dentist", focus: "Children's check-ups, fillings in milk teeth, fluoride and sealants",
        experience: "9 years in practice", languages: ["Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Saturdays, 10 am to 1:30 pm",
        hi: {
          name: "डॉ. शालिनी वर्मा", qualification: "BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)", specialisation: "बच्चों की डेंटिस्ट", focus: "बच्चों का चेक-अप, दूध के दाँतों की फ़िलिंग, फ़्लोराइड और सीलेंट",
          experience: "9 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "शनिवार, सुबह 10 से दोपहर 1:30",
        },
      },
    ],
    treatments: [
      {
        slug: "dental-check-up", name: "Dental check-up", category: "Everyday care", icon: "checkup", image: "/demo/img/dental/patient-man-checkup-640.webp", featured: true, reason: "checkup",
        summary: "A full look at teeth and gums, an X-ray only if needed, and a plain-words plan.",
        what: "A check-up is a careful examination of every tooth, your gums, bite and the soft tissues of the mouth. We look for early decay, worn fillings, gum inflammation and anything unusual, and we take an X-ray only when the eye cannot answer the question. You leave with a short written note of what we found and what, if anything, needs doing.",
        symptoms: ["It has been more than a year since your last check-up", "Food catches between two teeth", "Gums bleed when you brush", "A tooth is sensitive to cold or sweets"],
        whoNeedsIt: ["Adults and children, every six to twelve months", "Anyone starting a new medicine or a pregnancy", "Seniors with dentures or many fillings"],
        steps: [
          { title: "Talk", body: "Your concerns, medicines and any past dental problems.", hi: { title: "बातचीत", body: "आपकी परेशानी, दवाएँ और पहले की दाँतों की समस्याएँ।" } },
          { title: "Examine", body: "Each tooth, the gums and the bite, with a mirror and a gentle probe.", hi: { title: "जाँच", body: "हर दाँत, मसूड़े और काटने का तरीक़ा, शीशे और हल्के प्रोब से।" } },
          { title: "X-ray if needed", body: "A digital X-ray of one area, shown to you on the screen.", hi: { title: "ज़रूरत हो तो एक्स-रे", body: "एक हिस्से का डिजिटल एक्स-रे, जो आपको स्क्रीन पर दिखाया जाता है।" } },
          { title: "Plan", body: "What needs doing now, what can wait, and a written estimate.", hi: { title: "योजना", body: "अभी क्या ज़रूरी है, क्या रुक सकता है, और लिखित अनुमान।" } },
        ],
        duration: "One visit", visits: "1 visit of about 20 minutes", recovery: "None. You can eat and work straight after.",
        comfort: "Nothing is done without telling you first. A check-up involves no injections.",
        faqs: [
          { title: "Will you push treatment I do not need?", body: "We show you the finding on the X-ray or in a mirror and mark what can wait. The choice is yours.", hi: { title: "क्या बेवजह इलाज कराने को कहेंगे?", body: "हम एक्स-रे या शीशे में समस्या दिखाते हैं और बताते हैं कि क्या रुक सकता है। फ़ैसला आपका है।" } },
          { title: "How often should I come?", body: "Every six months for most people; once a year if your teeth and gums are healthy and you have few fillings.", hi: { title: "कितनी बार आना चाहिए?", body: "ज़्यादातर लोगों के लिए हर छह महीने; दाँत और मसूड़े स्वस्थ हों और फ़िलिंग कम हों तो साल में एक बार।" } },
        ],
        fromPrice: "300", priceNote: "consultation",
        hi: {
          name: "दाँतों का चेक-अप", category: "रोज़ की देखभाल",
          summary: "दाँतों और मसूड़ों की पूरी जाँच, ज़रूरत हो तभी एक्स-रे, और सीधी भाषा में योजना।",
          what: "चेक-अप में हर दाँत, मसूड़ों, काटने के तरीक़े और मुँह के अंदर की नरम त्वचा की ध्यान से जाँच होती है। हम शुरुआती कीड़ा, घिसी फ़िलिंग, मसूड़ों की सूजन और कोई भी असामान्य चीज़ देखते हैं, और एक्स-रे तभी लेते हैं जब आँख से जवाब न मिले। आपको एक छोटा लिखित नोट मिलता है कि क्या मिला और क्या करना ज़रूरी है।",
          symptoms: ["पिछले चेक-अप को एक साल से ज़्यादा हो गया", "दो दाँतों के बीच खाना फँसता है", "ब्रश करते समय मसूड़ों से ख़ून आता है", "ठंडा या मीठा लगने पर दाँत में झनझनाहट"],
          whoNeedsIt: ["बड़े और बच्चे, हर छह से बारह महीने में", "नई दवा या गर्भावस्था शुरू होने पर", "डेंचर या कई फ़िलिंग वाले बुज़ुर्ग"],
          duration: "एक विज़िट", visits: "लगभग 20 मिनट की 1 विज़िट", recovery: "कुछ नहीं। तुरंत खा सकते हैं और काम पर जा सकते हैं।",
          comfort: "आपको बताए बिना कुछ नहीं किया जाता। चेक-अप में कोई इंजेक्शन नहीं लगता।", priceNote: "परामर्श",
        },
      },
      {
        slug: "scaling-and-cleaning", name: "Scaling and cleaning", category: "Everyday care", icon: "cleaning", image: "/demo/img/dental/doctor-at-work-teal-640.webp", reason: "cleaning",
        summary: "Removes hardened tartar above and just below the gum line, then polishes the teeth.",
        what: "Tartar is plaque that has hardened on the teeth. A toothbrush cannot remove it, and it keeps the gums inflamed. Scaling uses a fine ultrasonic tip and hand instruments to lift it off, and polishing smooths the surface so plaque sticks less. It is the single most useful thing for bleeding gums and bad breath.",
        symptoms: ["Gums bleed when you brush or floss", "Yellow or brown deposits near the gums", "Bad breath that does not go away", "Gums look red or puffy"],
        whoNeedsIt: ["Most adults, once or twice a year", "Smokers and tobacco chewers", "People with diabetes, whose gums are more prone to infection"],
        steps: [
          { title: "Check the gums", body: "We measure the gum pockets to see if a deeper clean is needed.", hi: { title: "मसूड़ों की जाँच", body: "हम मसूड़ों की जेब नापते हैं कि गहरी सफ़ाई चाहिए या नहीं।" } },
          { title: "Ultrasonic scaling", body: "A fine vibrating tip with a water spray lifts off the tartar.", hi: { title: "अल्ट्रासोनिक स्केलिंग", body: "पानी की फुहार के साथ बारीक कंपन वाली टिप टार्टर हटाती है।" } },
          { title: "Polish", body: "A soft cup and paste smooth the teeth.", hi: { title: "पॉलिश", body: "नरम कप और पेस्ट से दाँत चिकने किए जाते हैं।" } },
          { title: "Home care", body: "We show you the brushing angle and the floss or brush for your gaps.", hi: { title: "घर पर देखभाल", body: "हम ब्रश का सही कोण और आपके दाँतों के बीच के लिए फ़्लॉस या ब्रश दिखाते हैं।" } },
        ],
        duration: "One visit", visits: "1 visit of 30 to 45 minutes", recovery: "Gums may feel tender and teeth a little sensitive for a day or two.",
        comfort: "Most people need no anaesthetic. If your gums are very sensitive we can numb them first.",
        faqs: [
          { title: "Does scaling loosen teeth or make gaps?", body: "No. The gaps were filled with tartar; once it is gone you may notice them, and healthier gums then tighten around the teeth.", hi: { title: "क्या स्केलिंग से दाँत ढीले होते हैं या गैप बनते हैं?", body: "नहीं। गैप में पहले टार्टर भरा था; उसके हटने पर वे दिखते हैं, और मसूड़े स्वस्थ होने पर दाँतों के चारों ओर कस जाते हैं।" } },
        ],
        fromPrice: "1,000", priceNote: "full mouth",
        hi: {
          name: "स्केलिंग और सफ़ाई", category: "रोज़ की देखभाल",
          summary: "मसूड़ों के ऊपर और ठीक नीचे जमा सख़्त टार्टर हटाकर दाँतों को पॉलिश किया जाता है।",
          what: "टार्टर वह प्लाक है जो दाँतों पर सख़्त हो गया है। ब्रश से यह नहीं हटता और मसूड़ों में सूजन बनाए रखता है। स्केलिंग में बारीक अल्ट्रासोनिक टिप और हाथ के औज़ारों से इसे हटाया जाता है, और पॉलिश से सतह चिकनी होती है ताकि प्लाक कम चिपके। मसूड़ों से ख़ून और मुँह की बदबू के लिए यह सबसे उपयोगी इलाज है।",
          symptoms: ["ब्रश या फ़्लॉस करते समय मसूड़ों से ख़ून", "मसूड़ों के पास पीली या भूरी परत", "मुँह की बदबू जो जाती नहीं", "मसूड़े लाल या फूले दिखते हैं"],
          whoNeedsIt: ["ज़्यादातर वयस्क, साल में एक या दो बार", "धूम्रपान या तंबाकू खाने वाले", "डायबिटीज़ वाले लोग, जिनके मसूड़ों में संक्रमण जल्दी होता है"],
          duration: "एक विज़िट", visits: "30 से 45 मिनट की 1 विज़िट", recovery: "एक-दो दिन मसूड़े नाज़ुक और दाँत थोड़े संवेदनशील लग सकते हैं।",
          comfort: "ज़्यादातर लोगों को सुन्न करने की ज़रूरत नहीं होती। मसूड़े बहुत संवेदनशील हों तो पहले सुन्न कर सकते हैं।", priceNote: "पूरा मुँह",
        },
      },
      {
        slug: "tooth-coloured-fillings", name: "Tooth-coloured fillings", category: "Fillings and root canal", icon: "filling", image: "/demo/img/dental/doctor-lamp-adjust-640.webp", reason: "checkup",
        summary: "Small cavities cleaned and sealed with a composite that matches your tooth.",
        what: "When decay has made a hole that has not reached the nerve, we remove the soft decayed part and fill the space with composite resin, a tooth-coloured material that bonds to the tooth. It is shaped to your bite and hardened with a blue light, so you can eat normally the same day.",
        symptoms: ["A dark spot or a hole you can feel with your tongue", "Sharp twinge with cold, hot or sweet food", "An old filling that is chipped or leaking"],
        whoNeedsIt: ["Adults and children with small to medium cavities", "Anyone replacing an old metal filling that has failed"],
        steps: [
          { title: "Numb if needed", body: "Local anaesthetic for deeper cavities; small ones often need none.", hi: { title: "ज़रूरत हो तो सुन्न करना", body: "गहरे कीड़े के लिए लोकल एनेस्थीसिया; छोटे में अक्सर ज़रूरत नहीं।" } },
          { title: "Clean out decay", body: "Only the soft, decayed part is removed.", hi: { title: "कीड़ा साफ़ करना", body: "सिर्फ़ नरम, सड़ा हुआ हिस्सा हटाया जाता है।" } },
          { title: "Fill and shape", body: "Composite is added in layers, shaped and set with a light.", hi: { title: "भरना और आकार देना", body: "कम्पोज़िट परतों में भरा, आकार दिया और लाइट से सख़्त किया जाता है।" } },
          { title: "Check the bite", body: "We polish and adjust until your teeth meet evenly.", hi: { title: "काटने की जाँच", body: "दाँत बराबर मिलने तक पॉलिश और हल्का सुधार।" } },
        ],
        duration: "One visit", visits: "1 visit of 30 to 45 minutes per tooth", recovery: "Numbness wears off in 2 to 3 hours. Mild sensitivity for a few days is common.",
        comfort: "Done under local anaesthesia when the cavity is deep. You can ask for a pause at any time.",
        faqs: [
          { title: "How long does a composite filling last?", body: "Often many years, depending on its size, your bite and how you care for it. We check it at every visit.", hi: { title: "कम्पोज़िट फ़िलिंग कितने समय चलती है?", body: "अक्सर कई साल, उसके आकार, आपके काटने के तरीक़े और देखभाल पर निर्भर। हम हर विज़िट में जाँचते हैं।" } },
        ],
        fromPrice: "800", priceNote: "per tooth",
        hi: {
          name: "दाँत के रंग की फ़िलिंग", category: "फ़िलिंग और रूट कैनाल",
          summary: "छोटे कीड़े साफ़ करके दाँत के रंग वाले कम्पोज़िट से भरे जाते हैं।",
          what: "जब कीड़े ने छेद कर दिया हो पर नस तक न पहुँचा हो, तो हम सड़ा हुआ नरम हिस्सा हटाकर जगह को कम्पोज़िट रेज़िन से भरते हैं, जो दाँत के रंग का होता है और दाँत से चिपक जाता है। इसे आपके काटने के हिसाब से आकार देकर नीली लाइट से सख़्त किया जाता है, इसलिए उसी दिन सामान्य खाना खा सकते हैं।",
          symptoms: ["काला धब्बा या छेद जो जीभ से महसूस हो", "ठंडा, गरम या मीठा खाने पर तेज़ झनझनाहट", "पुरानी फ़िलिंग टूटी या रिसती हुई"],
          whoNeedsIt: ["छोटे से मध्यम कीड़े वाले बड़े और बच्चे", "पुरानी धातु की ख़राब फ़िलिंग बदलवाने वाले"],
          duration: "एक विज़िट", visits: "हर दाँत के लिए 30 से 45 मिनट की 1 विज़िट", recovery: "सुन्नपन 2 से 3 घंटे में जाता है। कुछ दिन हल्की संवेदनशीलता आम है।",
          comfort: "गहरे कीड़े में लोकल एनेस्थीसिया दिया जाता है। आप कभी भी रुकने को कह सकते हैं।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "root-canal-treatment", name: "Root canal treatment", category: "Fillings and root canal", icon: "root-canal", image: "/demo/img/dental/tech-xray-monitor-640.webp", featured: true, reason: "root-canal",
        summary: "Saves a tooth whose nerve is infected or inflamed, usually in one or two visits.",
        what: "Inside every tooth is a soft pulp of nerves and blood vessels. Deep decay or a crack can infect it, which causes pain and, left alone, an abscess. Root canal treatment removes the infected pulp, cleans and shapes the canals with fine rotary files, and seals them. Back teeth usually need a crown afterwards to protect them from breaking.",
        symptoms: ["Throbbing pain, often worse at night", "Pain on biting that lingers", "Sensitivity to hot drinks that stays after the drink", "A swelling or pimple on the gum near a tooth", "A tooth that has turned darker"],
        whoNeedsIt: ["Anyone whose tooth can still be saved but whose nerve is damaged", "Teeth with deep decay or old large fillings", "Teeth that need a crown for a bridge"],
        steps: [
          { title: "X-ray and diagnosis", body: "We confirm which tooth and how many canals it has.", hi: { title: "एक्स-रे और निदान", body: "हम पक्का करते हैं कि कौन सा दाँत है और उसमें कितनी नलिकाएँ हैं।" } },
          { title: "Numb and isolate", body: "Local anaesthesia, then a rubber sheet keeps the tooth dry and clean.", hi: { title: "सुन्न और अलग करना", body: "लोकल एनेस्थीसिया, फिर रबर शीट से दाँत सूखा और साफ़ रखा जाता है।" } },
          { title: "Clean and shape", body: "Rotary files remove the infected pulp; the canals are rinsed with disinfectant.", hi: { title: "सफ़ाई और आकार", body: "रोटरी फ़ाइलें संक्रमित गूदा हटाती हैं; नलिकाएँ कीटाणुनाशक से धोई जाती हैं।" } },
          { title: "Seal", body: "The canals are filled and sealed; a filling closes the top.", hi: { title: "सील करना", body: "नलिकाएँ भरकर सील की जाती हैं; ऊपर फ़िलिंग लगती है।" } },
          { title: "Crown if needed", body: "A crown is fitted a week or two later on most back teeth.", hi: { title: "ज़रूरत हो तो क्राउन", body: "ज़्यादातर पीछे के दाँतों पर एक-दो हफ़्ते बाद क्राउन लगता है।" } },
        ],
        duration: "1 to 2 visits, plus a crown visit", visits: "Each visit 45 to 90 minutes. Single-visit root canal where clinically suitable.",
        recovery: "Tenderness on biting for 2 to 3 days is normal. Avoid chewing hard food on that side until the crown is fitted.",
        comfort: "Root canal treatment under local anaesthesia, with comfort breaks when you need them. Most people compare it to having a filling.",
        faqs: [
          { title: "Is it better to remove the tooth?", body: "A saved tooth keeps your bite and bone as they are. Removing it is quicker and cheaper today, but a gap often leads to a bridge or implant later. We explain both options with their costs.", hi: { title: "क्या दाँत निकलवाना बेहतर है?", body: "बचाया गया दाँत काटने के तरीक़े और हड्डी को वैसा ही रखता है। निकलवाना आज जल्दी और सस्ता है, पर ख़ाली जगह के लिए बाद में ब्रिज या इम्प्लांट लग सकता है। हम दोनों विकल्प ख़र्च के साथ समझाते हैं।" } },
          { title: "Can it be done in one visit?", body: "Often yes, when there is no active swelling and the canals are straightforward. Infected or curved canals may need a second visit with medicine inside.", hi: { title: "क्या यह एक विज़िट में हो सकता है?", body: "अक्सर हाँ, जब सूजन न हो और नलिकाएँ सीधी हों। संक्रमित या मुड़ी नलिकाओं में अंदर दवा रखकर दूसरी विज़िट लग सकती है।" } },
        ],
        fromPrice: "3,500", priceNote: "per tooth, front teeth; molars from Rs 5,000",
        hi: {
          name: "रूट कैनाल ट्रीटमेंट", category: "फ़िलिंग और रूट कैनाल",
          summary: "जिस दाँत की नस संक्रमित या सूजी हो, उसे बचाता है, आमतौर पर एक या दो विज़िट में।",
          what: "हर दाँत के अंदर नसों और ख़ून की नलियों वाला नरम गूदा होता है। गहरा कीड़ा या दरार इसे संक्रमित कर सकती है, जिससे दर्द होता है और छोड़ने पर फोड़ा बन सकता है। रूट कैनाल में संक्रमित गूदा निकाला जाता है, बारीक रोटरी फ़ाइलों से नलिकाओं को साफ़ किया जाता है और सील किया जाता है। पीछे के दाँतों को टूटने से बचाने के लिए बाद में अक्सर क्राउन लगता है।",
          symptoms: ["धड़कता दर्द, अक्सर रात में ज़्यादा", "चबाने पर दर्द जो देर तक रहे", "गरम पीने के बाद भी रहने वाली झनझनाहट", "दाँत के पास मसूड़े पर सूजन या दाना", "दाँत का रंग गहरा होना"],
          whoNeedsIt: ["जिनका दाँत बच सकता है पर नस ख़राब है", "गहरे कीड़े या पुरानी बड़ी फ़िलिंग वाले दाँत", "ब्रिज के लिए क्राउन चाहने वाले दाँत"],
          duration: "1 से 2 विज़िट, और क्राउन के लिए एक विज़िट", visits: "हर विज़िट 45 से 90 मिनट। जहाँ क्लिनिकली सही हो, वहाँ एक विज़िट में रूट कैनाल।",
          recovery: "2 से 3 दिन चबाने पर हल्का दर्द सामान्य है। क्राउन लगने तक उस तरफ़ सख़्त चीज़ न चबाएँ।",
          comfort: "रूट कैनाल लोकल एनेस्थीसिया में, और जब चाहें तब आराम के लिए रुकावट। ज़्यादातर लोग इसे फ़िलिंग जैसा बताते हैं।",
          priceNote: "प्रति दाँत, आगे के दाँत; दाढ़ 5,000 रुपये से",
        },
      },
      {
        slug: "crowns-and-bridges", name: "Crowns and bridges", category: "Replacing teeth", icon: "crown", image: "/demo/img/dental/implant-ceramic-crowns-640.webp", reason: "not-sure",
        summary: "A cap that protects a weak tooth, or a bridge that fills a gap using the teeth beside it.",
        what: "A crown covers a tooth that is broken, heavily filled or root-canal treated, so it can chew safely again. A bridge replaces one missing tooth by joining a false tooth to crowns on the teeth either side. We offer metal-ceramic and all-ceramic (zirconia) options and explain where each one suits.",
        symptoms: ["A back tooth after root canal treatment", "A tooth with a large, cracked filling", "One missing tooth with sound teeth on both sides"],
        whoNeedsIt: ["Adults with weakened teeth", "People who prefer a fixed option to a removable denture for a single gap"],
        steps: [
          { title: "Prepare", body: "The tooth is shaped under local anaesthesia and a temporary crown fitted.", hi: { title: "तैयारी", body: "लोकल एनेस्थीसिया में दाँत को आकार देकर अस्थायी क्राउन लगाया जाता है।" } },
          { title: "Measure", body: "An impression and a shade match are sent to the dental lab.", hi: { title: "नाप", body: "नाप और रंग का मिलान डेंटल लैब भेजा जाता है।" } },
          { title: "Fit", body: "The final crown or bridge is checked, adjusted and cemented.", hi: { title: "फ़िटिंग", body: "अंतिम क्राउन या ब्रिज जाँचकर, ठीक करके सीमेंट किया जाता है।" } },
        ],
        duration: "5 to 7 working days", visits: "2 visits", recovery: "The tooth may feel different for a few days while your bite settles.",
        comfort: "Shaping is done under local anaesthesia. The temporary crown keeps the tooth covered in between.",
        faqs: [{ title: "Metal-ceramic or zirconia?", body: "Metal-ceramic is strong and costs less; zirconia has no metal and looks more natural at the front. We suggest one based on where the tooth is.", hi: { title: "मेटल-सिरेमिक या ज़िरकोनिया?", body: "मेटल-सिरेमिक मज़बूत और सस्ता है; ज़िरकोनिया में धातु नहीं होती और सामने ज़्यादा प्राकृतिक दिखता है। दाँत की जगह के हिसाब से हम सुझाव देते हैं।" } }],
        fromPrice: "4,500", priceNote: "per crown, metal-ceramic",
        hi: {
          name: "क्राउन और ब्रिज", category: "दाँत बदलना",
          summary: "कमज़ोर दाँत को बचाने वाली टोपी, या बगल के दाँतों के सहारे ख़ाली जगह भरने वाला ब्रिज।",
          what: "क्राउन टूटे, बहुत भरे या रूट कैनाल हुए दाँत को ढकता है ताकि वह फिर से सुरक्षित चबा सके। ब्रिज एक गायब दाँत की जगह नकली दाँत लगाता है, जो दोनों ओर के दाँतों पर लगे क्राउन से जुड़ा होता है। हम मेटल-सिरेमिक और पूरे सिरेमिक (ज़िरकोनिया) विकल्प देते हैं और बताते हैं कि कहाँ कौन सा ठीक है।",
          symptoms: ["रूट कैनाल के बाद का पीछे का दाँत", "बड़ी, दरार वाली फ़िलिंग वाला दाँत", "एक गायब दाँत, जिसके दोनों ओर स्वस्थ दाँत हों"],
          whoNeedsIt: ["कमज़ोर दाँतों वाले वयस्क", "एक ख़ाली जगह के लिए निकलने वाले डेंचर की जगह फ़िक्स्ड विकल्प चाहने वाले"],
          duration: "5 से 7 कार्य दिवस", visits: "2 विज़िट", recovery: "कुछ दिन दाँत अलग लग सकता है, जब तक काटना सामान्य न हो।",
          comfort: "आकार देना लोकल एनेस्थीसिया में होता है। बीच में अस्थायी क्राउन दाँत को ढके रखता है।", priceNote: "प्रति क्राउन, मेटल-सिरेमिक",
        },
      },
      {
        slug: "tooth-extraction", name: "Tooth extraction", category: "Extractions", icon: "extraction", image: "/demo/img/dental/sterile-instrument-tray-640.webp", reason: "pain",
        summary: "Careful removal of a tooth that cannot be saved, with clear aftercare.",
        what: "We remove a tooth only when it cannot be saved or is in the way of other treatment. After numbing the area, the tooth is gently loosened and lifted out. We talk about replacing it before we start, because a gap can let neighbouring teeth drift.",
        symptoms: ["A tooth broken below the gum", "A very loose tooth from gum disease", "A tooth that repeated root canal cannot save"],
        whoNeedsIt: ["Adults whose tooth cannot be restored", "Children with a milk tooth that blocks the adult tooth"],
        steps: [
          { title: "Check health", body: "Medicines, blood pressure and sugar are checked first.", hi: { title: "सेहत की जाँच", body: "पहले दवाएँ, ब्लड प्रेशर और शुगर देखी जाती है।" } },
          { title: "Numb and remove", body: "Local anaesthesia, then the tooth is eased out.", hi: { title: "सुन्न करके निकालना", body: "लोकल एनेस्थीसिया, फिर दाँत धीरे से निकाला जाता है।" } },
          { title: "Aftercare", body: "Gauze, written instructions and a number to call.", hi: { title: "बाद की देखभाल", body: "गॉज़, लिखित निर्देश और फ़ोन करने के लिए नंबर।" } },
        ],
        duration: "One visit", visits: "1 visit of 20 to 40 minutes", recovery: "Soft food for a day or two. No spitting, straws or smoking for 24 hours.",
        comfort: "You feel pressure, not sharp pain, while the area is numb. We check before we begin.",
        faqs: [{ title: "Can I go to work the next day?", body: "Usually yes after a simple extraction. Plan a quieter day if it was a surgical removal.", hi: { title: "क्या अगले दिन काम पर जा सकते हैं?", body: "सामान्य दाँत निकालने के बाद आमतौर पर हाँ। सर्जरी से निकाला हो तो हल्का दिन रखें।" } }],
        fromPrice: "800", priceNote: "per tooth, simple extraction",
        hi: {
          name: "दाँत निकालना", category: "दाँत निकालना",
          summary: "जो दाँत बच नहीं सकता, उसे सावधानी से निकालना, साफ़ निर्देशों के साथ।",
          what: "हम दाँत तभी निकालते हैं जब वह बच न सके या दूसरे इलाज में रुकावट हो। जगह सुन्न करने के बाद दाँत को धीरे से ढीला करके निकाला जाता है। शुरू करने से पहले हम उसकी जगह भरने की बात करते हैं, क्योंकि ख़ाली जगह से बगल के दाँत खिसक सकते हैं।",
          symptoms: ["मसूड़े के नीचे तक टूटा दाँत", "मसूड़ों की बीमारी से बहुत ढीला दाँत", "जिसे बार-बार रूट कैनाल से भी न बचाया जा सके"],
          whoNeedsIt: ["जिनका दाँत ठीक नहीं हो सकता", "बच्चे, जिनका दूध का दाँत पक्के दाँत का रास्ता रोके"],
          duration: "एक विज़िट", visits: "20 से 40 मिनट की 1 विज़िट", recovery: "एक-दो दिन नरम खाना। 24 घंटे थूकना, स्ट्रॉ और धूम्रपान नहीं।",
          comfort: "सुन्न होने पर दबाव लगता है, तेज़ दर्द नहीं। शुरू करने से पहले हम जाँच लेते हैं।", priceNote: "प्रति दाँत, सामान्य निकासी",
        },
      },
      {
        slug: "wisdom-tooth-removal", name: "Wisdom tooth removal", category: "Extractions", icon: "wisdom", image: "/demo/img/dental/tech-xray-tablet-640.webp", reason: "wisdom",
        summary: "Removal of a stuck or repeatedly infected wisdom tooth, planned on an X-ray.",
        what: "Wisdom teeth often lack room and come in tilted or half-covered by gum, where food collects and the gum swells. If it keeps happening, or the tooth is damaging the one in front, removal is advised. An X-ray shows its position and how close it is to the nerve before we decide.",
        symptoms: ["Swollen, sore gum at the back of the mouth", "Pain on opening wide or swallowing", "A bad taste from the back"],
        whoNeedsIt: ["Adults with repeated wisdom tooth infections", "Teeth pushing against or decaying the tooth in front"],
        steps: [
          { title: "X-ray", body: "To see the roots and the nerve before planning.", hi: { title: "एक्स-रे", body: "योजना से पहले जड़ें और नस देखने के लिए।" } },
          { title: "Remove", body: "Under local anaesthesia; sometimes the tooth is divided to remove it gently.", hi: { title: "निकालना", body: "लोकल एनेस्थीसिया में; कभी-कभी दाँत को टुकड़ों में धीरे से निकाला जाता है।" } },
          { title: "Review", body: "A check after a week, and stitches removed if used.", hi: { title: "फ़ॉलो-अप", body: "एक हफ़्ते बाद जाँच, और टाँके हों तो हटाना।" } },
        ],
        duration: "One visit, plus a review", visits: "1 visit of 30 to 60 minutes", recovery: "Swelling peaks on day two and settles within a week. Ice packs on the first day help.",
        comfort: "Done under local anaesthesia. For complex teeth we refer to an oral surgeon and tell you why.",
        faqs: [{ title: "Should all wisdom teeth come out?", body: "No. A wisdom tooth that is upright, cleanable and not causing trouble can stay.", hi: { title: "क्या सारी अक़्ल दाढ़ें निकालनी चाहिए?", body: "नहीं। जो अक़्ल दाढ़ सीधी हो, साफ़ हो सके और परेशानी न दे, वह रह सकती है।" } }],
        fromPrice: "3,500", priceNote: "per tooth, surgical",
        hi: {
          name: "अक़्ल दाढ़ निकालना", category: "दाँत निकालना",
          summary: "फँसी हुई या बार-बार संक्रमित अक़्ल दाढ़ को एक्स-रे देखकर निकालना।",
          what: "अक़्ल दाढ़ को अक्सर जगह नहीं मिलती और वह टेढ़ी या आधी मसूड़े में ढकी निकलती है, जहाँ खाना जमता है और मसूड़ा सूजता है। यह बार-बार हो, या दाढ़ आगे वाले दाँत को नुकसान दे, तो निकालने की सलाह दी जाती है। फ़ैसले से पहले एक्स-रे से उसकी स्थिति और नस से दूरी देखी जाती है।",
          symptoms: ["मुँह के पीछे सूजा, दुखता मसूड़ा", "मुँह खोलने या निगलने में दर्द", "पीछे से ख़राब स्वाद"],
          whoNeedsIt: ["बार-बार अक़्ल दाढ़ के संक्रमण वाले वयस्क", "आगे के दाँत को धकेलती या सड़ाती दाढ़"],
          duration: "एक विज़िट, और एक फ़ॉलो-अप", visits: "30 से 60 मिनट की 1 विज़िट", recovery: "सूजन दूसरे दिन सबसे ज़्यादा होती है और एक हफ़्ते में घटती है। पहले दिन बर्फ़ की सिकाई मदद करती है।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है। जटिल दाढ़ के लिए हम ओरल सर्जन के पास भेजते हैं और कारण बताते हैं।", priceNote: "प्रति दाँत, सर्जिकल",
        },
      },
      {
        slug: "dentures", name: "Dentures", category: "Replacing teeth", icon: "denture", image: "/demo/img/dental/patient-older-woman-talk-640.webp", featured: true, reason: "not-sure",
        summary: "Complete or partial dentures, made over several fittings so they sit well.",
        what: "A denture is a removable set of teeth on a gum-coloured base. A complete denture replaces all the teeth in a jaw; a partial one fills gaps and clips to the remaining teeth. A good fit takes several short visits, and we take our time with each, because a loose denture is the most common reason people stop wearing one.",
        symptoms: ["Several or all teeth missing", "An old denture that rocks, rubs or clicks", "Difficulty chewing rotis or vegetables"],
        whoNeedsIt: ["Seniors with many missing teeth", "Anyone who is not suited to implants or prefers a removable option"],
        steps: [
          { title: "Impressions", body: "Moulds of your gums and a record of how your jaws meet.", hi: { title: "नाप", body: "मसूड़ों का साँचा और जबड़े कैसे मिलते हैं, इसका रिकॉर्ड।" } },
          { title: "Try-in", body: "The teeth are set in wax so you can see and approve them.", hi: { title: "ट्रायल", body: "दाँत मोम में लगाए जाते हैं ताकि आप देखकर मंज़ूरी दें।" } },
          { title: "Fit and adjust", body: "The finished denture is fitted, then eased at one or two review visits.", hi: { title: "फ़िटिंग और सुधार", body: "तैयार डेंचर लगाकर एक-दो फ़ॉलो-अप में ठीक किया जाता है।" } },
        ],
        duration: "3 to 4 weeks", visits: "4 to 5 short visits", recovery: "A new denture takes a few weeks to get used to. Start with soft food and small bites.",
        comfort: "No injections are needed. Sore spots are adjusted at the review visits.",
        faqs: [{ title: "Can I sleep with my dentures in?", body: "It is better to take them out at night, clean them and keep them in water, so the gums can rest.", hi: { title: "क्या डेंचर पहनकर सो सकते हैं?", body: "रात में निकालकर साफ़ करके पानी में रखना बेहतर है, ताकि मसूड़ों को आराम मिले।" } }],
        fromPrice: "15,000", priceNote: "per complete set, both jaws",
        hi: {
          name: "डेंचर (नकली दाँत)", category: "दाँत बदलना",
          summary: "पूरे या आंशिक डेंचर, कई फ़िटिंग में बनाए जाते हैं ताकि ठीक से बैठें।",
          what: "डेंचर मसूड़े के रंग के बेस पर लगे निकलने वाले दाँतों का सेट है। पूरा डेंचर एक जबड़े के सभी दाँतों की जगह लेता है; आंशिक डेंचर ख़ाली जगह भरता है और बचे दाँतों पर क्लिप होता है। अच्छी फ़िटिंग के लिए कई छोटी विज़िट लगती हैं, और हम हर एक में समय लेते हैं, क्योंकि ढीला डेंचर ही लोगों के उसे छोड़ देने का सबसे आम कारण है।",
          symptoms: ["कई या सभी दाँत गायब", "पुराना डेंचर हिलता, रगड़ता या आवाज़ करता है", "रोटी या सब्ज़ी चबाने में दिक़्क़त"],
          whoNeedsIt: ["कई गायब दाँतों वाले बुज़ुर्ग", "जो इम्प्लांट के लिए उपयुक्त नहीं या निकलने वाला विकल्प चाहते हैं"],
          duration: "3 से 4 हफ़्ते", visits: "4 से 5 छोटी विज़िट", recovery: "नए डेंचर की आदत पड़ने में कुछ हफ़्ते लगते हैं। नरम खाने और छोटे कौर से शुरू करें।",
          comfort: "कोई इंजेक्शन नहीं लगता। दुखने वाली जगहें फ़ॉलो-अप में ठीक की जाती हैं।", priceNote: "पूरा सेट, दोनों जबड़े",
        },
      },
      {
        slug: "childrens-dentistry", name: "Children's dentistry", category: "Children", icon: "kids", image: "/demo/img/dental/kids-boy-checkup-640.webp", featured: true, reason: "kids",
        summary: "Check-ups, fluoride, sealants and fillings in milk teeth, by our visiting children's specialist.",
        what: "Milk teeth hold space for adult teeth and let a child chew and speak well, so decay in them matters. Our visiting paediatric dentist sees children on Saturday mornings: first visits, check-ups, fluoride varnish, sealants on new back teeth, and fillings. We go at the child's pace and a parent stays in the room.",
        symptoms: ["White or brown spots on the teeth", "Your child avoids chewing on one side", "Thumb sucking beyond age four"],
        whoNeedsIt: ["Babies by the first birthday", "Children aged 6 to 12 as the adult teeth arrive"],
        steps: [
          { title: "Meet", body: "The child sits on your lap and meets the dentist and the chair.", hi: { title: "मुलाक़ात", body: "बच्चा आपकी गोद में बैठकर डेंटिस्ट और कुर्सी से मिलता है।" } },
          { title: "Check", body: "A gentle look, counting teeth, with the child's help.", hi: { title: "जाँच", body: "बच्चे की मदद से दाँत गिनते हुए हल्की जाँच।" } },
          { title: "Prevent", body: "Fluoride or sealants if needed, and brushing tips for you.", hi: { title: "बचाव", body: "ज़रूरत हो तो फ़्लोराइड या सीलेंट, और आपके लिए ब्रश करने के सुझाव।" } },
        ],
        duration: "One visit", visits: "1 visit of 20 to 30 minutes", recovery: "None for a check-up. No food for 30 minutes after fluoride.",
        comfort: "We use tell-show-do: explain, show on a finger, then do. A parent can stay throughout.",
        faqs: [{ title: "Do milk teeth need fillings if they will fall out?", body: "Often yes. Back milk teeth stay until about age 11, and untreated decay can cause pain and infection.", hi: { title: "जो दूध के दाँत गिर जाएँगे, क्या उनमें फ़िलिंग ज़रूरी है?", body: "अक्सर हाँ। पीछे के दूध के दाँत लगभग 11 साल तक रहते हैं, और बिना इलाज कीड़ा दर्द और संक्रमण कर सकता है।" } }],
        fromPrice: "800", priceNote: "fluoride application",
        hi: {
          name: "बच्चों के दाँतों का इलाज", category: "बच्चे",
          summary: "चेक-अप, फ़्लोराइड, सीलेंट और दूध के दाँतों की फ़िलिंग, हमारी विज़िटिंग बच्चों की विशेषज्ञ द्वारा।",
          what: "दूध के दाँत पक्के दाँतों के लिए जगह रखते हैं और बच्चे को ठीक से चबाने और बोलने देते हैं, इसलिए उनमें कीड़ा मायने रखता है। हमारी विज़िटिंग बच्चों की डेंटिस्ट शनिवार सुबह बच्चों को देखती हैं: पहली विज़िट, चेक-अप, फ़्लोराइड वार्निश, नए पीछे के दाँतों पर सीलेंट, और फ़िलिंग। हम बच्चे की रफ़्तार से चलते हैं और माता-पिता कमरे में रहते हैं।",
          symptoms: ["दाँतों पर सफ़ेद या भूरे धब्बे", "बच्चा एक तरफ़ से चबाने से बचता है", "चार साल के बाद भी अँगूठा चूसना"],
          whoNeedsIt: ["पहले जन्मदिन तक के शिशु", "6 से 12 साल के बच्चे, जब पक्के दाँत आते हैं"],
          duration: "एक विज़िट", visits: "20 से 30 मिनट की 1 विज़िट", recovery: "चेक-अप के बाद कुछ नहीं। फ़्लोराइड के बाद 30 मिनट कुछ न खाएँ।",
          comfort: "हम बताओ-दिखाओ-करो तरीक़ा अपनाते हैं: समझाना, उँगली पर दिखाना, फिर करना। माता-पिता पूरे समय साथ रह सकते हैं।", priceNote: "फ़्लोराइड लगाना",
        },
      },
      {
        slug: "gum-care", name: "Gum treatment", category: "Everyday care", icon: "gum", image: "/demo/img/dental/patient-woman-chair-640.webp", reason: "cleaning",
        summary: "Deep cleaning below the gums for gum disease, with follow-up checks.",
        what: "When gum inflammation goes deeper, pockets form between the gum and tooth and the bone around the tooth slowly shrinks. Deep cleaning (root planing) cleans those pockets under local anaesthesia. Regular follow-up keeps the disease from coming back; we refer advanced cases to a periodontist.",
        symptoms: ["Gums that bleed easily", "Teeth that look longer or feel loose", "Persistent bad breath"],
        whoNeedsIt: ["Adults with gum pockets deeper than a normal clean can reach", "People with diabetes or who smoke"],
        steps: [
          { title: "Measure", body: "Pocket depths and an X-ray of the bone.", hi: { title: "नाप", body: "जेबों की गहराई और हड्डी का एक्स-रे।" } },
          { title: "Deep clean", body: "One half of the mouth at a time, under local anaesthesia.", hi: { title: "गहरी सफ़ाई", body: "लोकल एनेस्थीसिया में, एक बार में आधा मुँह।" } },
          { title: "Re-check", body: "Pockets measured again after six to eight weeks.", hi: { title: "दोबारा जाँच", body: "छह से आठ हफ़्ते बाद जेबें फिर से नापी जाती हैं।" } },
        ],
        duration: "6 to 8 weeks including the re-check", visits: "2 to 3 visits", recovery: "Gums may be tender for a few days; teeth can feel sensitive to cold.",
        comfort: "Deep cleaning is done under local anaesthesia, one area at a time.",
        faqs: [{ title: "Is gum disease linked to diabetes?", body: "Yes, each can make the other harder to control. Treating the gums is part of looking after diabetes.", hi: { title: "क्या मसूड़ों की बीमारी का डायबिटीज़ से संबंध है?", body: "हाँ, दोनों एक-दूसरे को नियंत्रित करना कठिन बनाते हैं। मसूड़ों का इलाज डायबिटीज़ की देखभाल का हिस्सा है।" } }],
        fromPrice: "2,500", priceNote: "per quarter of the mouth",
        hi: {
          name: "मसूड़ों का इलाज", category: "रोज़ की देखभाल",
          summary: "मसूड़ों की बीमारी में मसूड़ों के नीचे गहरी सफ़ाई, फ़ॉलो-अप जाँच के साथ।",
          what: "जब मसूड़ों की सूजन गहरी हो जाती है, तो मसूड़े और दाँत के बीच जेबें बनती हैं और दाँत के आसपास की हड्डी धीरे-धीरे घटती है। गहरी सफ़ाई (रूट प्लानिंग) लोकल एनेस्थीसिया में इन जेबों को साफ़ करती है। नियमित फ़ॉलो-अप बीमारी को लौटने से रोकता है; गंभीर मामलों में हम पेरियोडॉन्टिस्ट के पास भेजते हैं।",
          symptoms: ["मसूड़ों से आसानी से ख़ून", "दाँत लंबे दिखना या ढीले लगना", "लगातार मुँह की बदबू"],
          whoNeedsIt: ["जिनकी मसूड़ों की जेबें सामान्य सफ़ाई से गहरी हैं", "डायबिटीज़ वाले या धूम्रपान करने वाले"],
          duration: "दोबारा जाँच मिलाकर 6 से 8 हफ़्ते", visits: "2 से 3 विज़िट", recovery: "कुछ दिन मसूड़े नाज़ुक रह सकते हैं; ठंडे से दाँत संवेदनशील लग सकते हैं।",
          comfort: "गहरी सफ़ाई लोकल एनेस्थीसिया में, एक बार में एक हिस्सा।", priceNote: "मुँह के प्रति चौथाई हिस्से",
        },
      },
      {
        slug: "braces-and-aligners", name: "Braces and aligners", category: "Braces", icon: "braces", image: "/demo/img/dental/ortho-braces-model-640.webp", reason: "braces",
        summary: "Metal, ceramic braces and clear aligners, planned by our visiting orthodontist on Thursdays.",
        what: "Crowded, gapped or protruding teeth can be moved gradually with braces or clear aligners. Our visiting orthodontist examines your bite, takes records and explains which option suits you, how long it may take and what it costs, before anything is fitted.",
        symptoms: ["Crowded or overlapping teeth", "Gaps between teeth", "Upper teeth that stick out"],
        whoNeedsIt: ["Children from about age 7 for an early check", "Teenagers and adults of any age with healthy gums"],
        steps: [
          { title: "Orthodontic check", body: "Examination, photos and X-rays on a Thursday evening.", hi: { title: "ऑर्थोडॉन्टिक जाँच", body: "गुरुवार शाम जाँच, फ़ोटो और एक्स-रे।" } },
          { title: "Plan and estimate", body: "Options, time and a written estimate.", hi: { title: "योजना और अनुमान", body: "विकल्प, समय और लिखित अनुमान।" } },
          { title: "Fit and adjust", body: "Braces or aligners fitted, with monthly reviews.", hi: { title: "लगाना और सुधार", body: "ब्रेसेज़ या अलाइनर लगाना, हर महीने जाँच।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "A review every 4 to 6 weeks", recovery: "Teeth feel sore for 2 to 3 days after each adjustment.",
        comfort: "Fitting braces needs no injections. Wax is given for any rubbing.",
        faqs: [{ title: "Am I too old for braces?", body: "No. Adults can have braces or aligners as long as the gums and bone are healthy.", hi: { title: "क्या ब्रेसेज़ के लिए मेरी उम्र ज़्यादा है?", body: "नहीं। मसूड़े और हड्डी स्वस्थ हों तो वयस्क भी ब्रेसेज़ या अलाइनर लगवा सकते हैं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "ब्रेसेज़ और अलाइनर", category: "ब्रेसेज़",
          summary: "मेटल, सिरेमिक ब्रेसेज़ और क्लियर अलाइनर, गुरुवार को आने वाले हमारे ऑर्थोडॉन्टिस्ट की योजना से।",
          what: "भीड़ वाले, गैप वाले या आगे निकले दाँत ब्रेसेज़ या क्लियर अलाइनर से धीरे-धीरे खिसकाए जा सकते हैं। हमारे विज़िटिंग ऑर्थोडॉन्टिस्ट आपके काटने की जाँच करते हैं, रिकॉर्ड लेते हैं और कुछ भी लगाने से पहले बताते हैं कि कौन सा विकल्प सही है, कितना समय लग सकता है और कितना ख़र्च होगा।",
          symptoms: ["भीड़ वाले या एक-दूसरे पर चढ़े दाँत", "दाँतों के बीच गैप", "ऊपर के दाँत आगे निकले हुए"],
          whoNeedsIt: ["लगभग 7 साल से बच्चे, शुरुआती जाँच के लिए", "स्वस्थ मसूड़ों वाले किशोर और किसी भी उम्र के वयस्क"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "हर 4 से 6 हफ़्ते में जाँच", recovery: "हर सुधार के बाद 2 से 3 दिन दाँत दुख सकते हैं।",
          comfort: "ब्रेसेज़ लगाने में इंजेक्शन नहीं लगता। रगड़ के लिए वैक्स दिया जाता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
    ],
    fees: [
      { treatment: "Consultation", slug: "dental-check-up", from: "300", unit: "per visit", group: "Consultation", note: "Includes the examination and a written plan", hi: { treatment: "परामर्श", unit: "प्रति विज़िट", group: "परामर्श", note: "जाँच और लिखित योजना शामिल" } },
      { treatment: "Digital X-ray (single tooth)", from: "200", unit: "per X-ray", group: "Consultation", hi: { treatment: "डिजिटल एक्स-रे (एक दाँत)", unit: "प्रति एक्स-रे", group: "परामर्श" } },
      { treatment: "Scaling and polishing", slug: "scaling-and-cleaning", from: "1,000", unit: "full mouth", group: "Everyday care", hi: { treatment: "स्केलिंग और पॉलिश", unit: "पूरा मुँह", group: "रोज़ की देखभाल" } },
      { treatment: "Tooth-coloured filling", slug: "tooth-coloured-fillings", from: "800", unit: "per tooth", group: "Fillings and root canal", hi: { treatment: "दाँत के रंग की फ़िलिंग", unit: "प्रति दाँत", group: "फ़िलिंग और रूट कैनाल" } },
      { treatment: "Root canal treatment (front tooth)", slug: "root-canal-treatment", from: "3,500", unit: "per tooth", group: "Fillings and root canal", hi: { treatment: "रूट कैनाल (आगे का दाँत)", unit: "प्रति दाँत", group: "फ़िलिंग और रूट कैनाल" } },
      { treatment: "Root canal treatment (molar)", slug: "root-canal-treatment", from: "5,000", unit: "per tooth", group: "Fillings and root canal", note: "Crown charged separately", hi: { treatment: "रूट कैनाल (दाढ़)", unit: "प्रति दाँत", group: "फ़िलिंग और रूट कैनाल", note: "क्राउन का शुल्क अलग" } },
      { treatment: "Crown, metal-ceramic", slug: "crowns-and-bridges", from: "4,500", unit: "per crown", group: "Replacing teeth", hi: { treatment: "क्राउन, मेटल-सिरेमिक", unit: "प्रति क्राउन", group: "दाँत बदलना" } },
      { treatment: "Crown, zirconia", slug: "crowns-and-bridges", from: "9,000", unit: "per crown", group: "Replacing teeth", hi: { treatment: "क्राउन, ज़िरकोनिया", unit: "प्रति क्राउन", group: "दाँत बदलना" } },
      { treatment: "Simple extraction", slug: "tooth-extraction", from: "800", unit: "per tooth", group: "Extractions", hi: { treatment: "सामान्य दाँत निकालना", unit: "प्रति दाँत", group: "दाँत निकालना" } },
      { treatment: "Wisdom tooth removal (surgical)", slug: "wisdom-tooth-removal", from: "3,500", unit: "per tooth", group: "Extractions", hi: { treatment: "अक़्ल दाढ़ निकालना (सर्जिकल)", unit: "प्रति दाँत", group: "दाँत निकालना" } },
      { treatment: "Complete dentures", slug: "dentures", from: "15,000", unit: "both jaws", group: "Replacing teeth", hi: { treatment: "पूरे डेंचर", unit: "दोनों जबड़े", group: "दाँत बदलना" } },
      { treatment: "Fluoride application (child)", slug: "childrens-dentistry", from: "800", unit: "per visit", group: "Children", hi: { treatment: "फ़्लोराइड लगाना (बच्चा)", unit: "प्रति विज़िट", group: "बच्चे" } },
      { treatment: "Braces or aligners", slug: "braces-and-aligners", consult: true, group: "Braces", note: "Plan and estimate at the orthodontic check", hi: { treatment: "ब्रेसेज़ या अलाइनर", group: "ब्रेसेज़", note: "ऑर्थोडॉन्टिक जाँच पर योजना और अनुमान" } },
      { treatment: "Dental implants", consult: true, group: "Replacing teeth", note: "Referred to a partner implant surgeon after X-ray", hi: { treatment: "डेंटल इम्प्लांट", group: "दाँत बदलना", note: "एक्स-रे के बाद साथी इम्प्लांट सर्जन के पास भेजा जाता है" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: a Rs 15,000 denture over 6 months on card EMI is about Rs 2,600 a month, depending on your bank.",
      modes: ["UPI", "Debit and credit cards", "Cash"],
      insurance: "Most health policies do not cover routine dental work. We give an itemised bill for any claim you make.",
      consultFee: "Consultation: Rs 300. Treatment is charged as per the estimate you approve.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: 15,000 रुपये का डेंचर 6 महीने की कार्ड EMI पर लगभग 2,600 रुपये महीना, आपके बैंक पर निर्भर।",
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नक़द"],
        insurance: "ज़्यादातर हेल्थ पॉलिसी सामान्य दाँतों का इलाज कवर नहीं करतीं। किसी भी क्लेम के लिए हम मदवार बिल देते हैं।",
        consultFee: "परामर्श: 300 रुपये। इलाज का शुल्क आपके मंज़ूर किए अनुमान के अनुसार।",
      },
    },
    emergency: {
      headline: "Tooth pain? Same-day emergency appointments",
      intro: "Severe toothache, a swollen face or a broken tooth should not wait for next week. Call or WhatsApp us and we fit you into the next session, including Sunday mornings.",
      phone: "+91 00000 00000",
      whatsapp: "910000000000",
      hours: "Emergency calls answered 9 am to 9 pm, all week",
      urgent: ["Severe toothache that painkillers do not settle", "Swelling of the gum, cheek or jaw", "A knocked-out or badly broken tooth", "Bleeding after an extraction that will not stop with pressure"],
      firstAid: [
        { title: "Knocked-out adult tooth", body: "Hold it by the crown, not the root. Rinse briefly in milk, put it back in the socket if you can, or keep it in milk, and come in within the hour.", hi: { title: "पक्का दाँत निकल गया", body: "दाँत को ऊपर के हिस्से से पकड़ें, जड़ से नहीं। दूध में हल्का धोएँ, हो सके तो वापस जगह पर रखें, नहीं तो दूध में रखें, और एक घंटे के अंदर आएँ।" } },
        { title: "Broken tooth", body: "Rinse with warm water, keep any pieces, and use a cold pack on the cheek for swelling.", hi: { title: "टूटा दाँत", body: "गुनगुने पानी से कुल्ला करें, टुकड़े संभालें, और सूजन के लिए गाल पर ठंडी सिकाई करें।" } },
        { title: "Bleeding after an extraction", body: "Bite firmly on a folded clean gauze or cloth for 30 minutes without checking. Do not spit or rinse.", hi: { title: "दाँत निकलने के बाद ख़ून", body: "साफ़ मुड़ी हुई गॉज़ या कपड़े को 30 मिनट तक बिना देखे कसकर दबाएँ। थूकें या कुल्ला न करें।" } },
        { title: "Toothache at night", body: "Take a painkiller you have used safely before, keep your head raised, and avoid very hot or cold food. Do not put aspirin on the gum.", hi: { title: "रात में दाँत दर्द", body: "पहले सुरक्षित इस्तेमाल की हुई दर्द की दवा लें, सिर ऊँचा रखें, बहुत गरम या ठंडा न खाएँ। मसूड़े पर एस्पिरिन न रखें।" } },
      ],
      canWait: ["A small chip with no pain", "A lost filling with no pain", "Mild sensitivity to cold", "A loose crown that is still in place"],
      hi: {
        headline: "दाँत में दर्द? उसी दिन इमरजेंसी अपॉइंटमेंट",
        intro: "तेज़ दाँत दर्द, सूजा चेहरा या टूटा दाँत अगले हफ़्ते का इंतज़ार नहीं कर सकता। फ़ोन या व्हाट्सऐप करें, हम अगले सेशन में, रविवार सुबह भी, आपको देखेंगे।",
        hours: "इमरजेंसी कॉल सुबह 9 से रात 9 तक, पूरे हफ़्ते",
        urgent: ["तेज़ दाँत दर्द जो दवा से भी न रुके", "मसूड़े, गाल या जबड़े में सूजन", "पूरा निकला या बुरी तरह टूटा दाँत", "दाँत निकालने के बाद ख़ून जो दबाने से भी न रुके"],
        canWait: ["बिना दर्द का छोटा सा टूटा किनारा", "बिना दर्द के निकली फ़िलिंग", "ठंडे से हल्की झनझनाहट", "ढीला क्राउन जो अभी अपनी जगह पर है"],
      },
    },
    booking: {
      reasons: [
        { id: "pain", label: "Tooth pain or swelling", icon: "pain", urgent: true, treatment: "root-canal-treatment", hi: { label: "दाँत में दर्द या सूजन" } },
        { id: "checkup", label: "Check-up", icon: "checkup", treatment: "dental-check-up", hi: { label: "चेक-अप" } },
        { id: "cleaning", label: "Cleaning or bleeding gums", icon: "cleaning", treatment: "scaling-and-cleaning", hi: { label: "सफ़ाई या मसूड़ों से ख़ून" } },
        { id: "root-canal", label: "Root canal", icon: "root-canal", treatment: "root-canal-treatment", hi: { label: "रूट कैनाल" } },
        { id: "kids", label: "For my child", icon: "kids", treatment: "childrens-dentistry", hi: { label: "बच्चे के लिए" } },
        { id: "braces", label: "Braces or aligners", icon: "braces", treatment: "braces-and-aligners", hi: { label: "ब्रेसेज़ या अलाइनर" } },
        { id: "wisdom", label: "Wisdom tooth", icon: "wisdom", treatment: "wisdom-tooth-removal", hi: { label: "अक़्ल दाढ़" } },
        { id: "not-sure", label: "Dentures or not sure", icon: "tooth", treatment: "dentures", hi: { label: "डेंचर या पक्का नहीं पता" } },
      ],
      morning: ["10:00 am", "10:30 am", "11:00 am", "11:30 am", "12:00 pm", "12:30 pm"],
      evening: ["5:00 pm", "5:30 pm", "6:00 pm", "6:30 pm", "7:00 pm", "7:30 pm", "8:00 pm"],
      closedDays: [],
      closedNote: "Sunday: morning session only, 10 am to 1 pm",
      hi: { closedNote: "रविवार: सिर्फ़ सुबह का सेशन, 10 से दोपहर 1" },
    },
    sessions: [
      { days: [1, 2, 3, 4, 5, 6], from: "10:00", to: "13:30" },
      { days: [1, 2, 3, 4, 5, 6], from: "17:00", to: "20:30" },
      { days: [0], from: "10:00", to: "13:00" },
    ],
    reach: {
      transit: "Ten minutes by auto from Patrakarpuram; the nearest bus stop is at the crossing.",
      parking: "Two-wheelers in front of the building; cars in the service lane.",
      access: "First floor with a lift. We can bring a wheelchair down on request.",
      hi: {
        transit: "पत्रकारपुरम से ऑटो से दस मिनट; सबसे पास का बस स्टॉप चौराहे पर है।",
        parking: "दोपहिया इमारत के सामने; कारें सर्विस लेन में।",
        access: "पहली मंज़िल, लिफ़्ट के साथ। कहने पर व्हीलचेयर नीचे ला सकते हैं।",
      },
    },
    sterilisation: [
      { title: "Clean", body: "Instruments are scrubbed and cleaned in an ultrasonic bath after every patient.", hi: { title: "सफ़ाई", body: "हर मरीज़ के बाद औज़ार रगड़कर अल्ट्रासोनिक बाथ में साफ़ किए जाते हैं।" } },
      { title: "Seal", body: "Each set is packed in a dated, sealed pouch.", hi: { title: "सील", body: "हर सेट तारीख़ वाले सील पाउच में पैक होता है।" } },
      { title: "Sterilise", body: "Pouches go through a Class B autoclave cycle, logged every day.", hi: { title: "स्टरलाइज़", body: "पाउच क्लास B ऑटोक्लेव से गुज़रते हैं, जिसका रोज़ रिकॉर्ड रखा जाता है।" } },
      { title: "Open in front of you", body: "The pouch is opened at your chair. Gloves, needles and cups are single use.", hi: { title: "आपके सामने खोलना", body: "पाउच आपकी कुर्सी पर खोला जाता है। दस्ताने, सुई और कप एक बार ही इस्तेमाल होते हैं।" } },
    ],
    trust: [
      { title: "A written estimate first", body: "You see the cost on paper before any treatment starts.", hi: { title: "पहले लिखित अनुमान", body: "किसी भी इलाज से पहले आप ख़र्च काग़ज़ पर देखते हैं।" } },
      { title: "Your X-ray on the screen", body: "We show you what we see, so you can decide.", hi: { title: "स्क्रीन पर आपका एक्स-रे", body: "हमें जो दिखता है, वही आपको दिखाते हैं, ताकि आप फ़ैसला ले सकें।" } },
      { title: "Specialists on fixed days", body: "An orthodontist and a children's dentist visit every week.", hi: { title: "तय दिनों पर विशेषज्ञ", body: "ऑर्थोडॉन्टिस्ट और बच्चों की डेंटिस्ट हर हफ़्ते आते हैं।" } },
      { title: "Registration numbers shown", body: "Every dentist's council registration is on this site and at the desk.", hi: { title: "रजिस्ट्रेशन नंबर सामने", body: "हर डेंटिस्ट का काउंसिल रजिस्ट्रेशन इस साइट पर और काउंटर पर है।" } },
    ],
    comfort: [
      { title: "Local anaesthesia", body: "Used for fillings, root canals and extractions. We wait until you are fully numb.", hi: { title: "लोकल एनेस्थीसिया", body: "फ़िलिंग, रूट कैनाल और दाँत निकालने में। पूरी तरह सुन्न होने तक हम रुकते हैं।" } },
      { title: "Raise a hand to pause", body: "Agree a signal before we begin, and we stop when you use it.", hi: { title: "रुकने के लिए हाथ उठाएँ", body: "शुरू करने से पहले इशारा तय करें, और आप करेंगे तो हम रुक जाएँगे।" } },
      { title: "Nervous patients", body: "Tell us when you book; we give you a longer slot and explain each step first.", hi: { title: "घबराने वाले मरीज़", body: "बुकिंग के समय बता दें; हम लंबा स्लॉट देते हैं और हर क़दम पहले समझाते हैं।" } },
    ],
  },
});
