/**
 * d2-multispeciality: Palash Multispeciality Dental Centre, Kondapur, Hyderabad.
 * A six-chair centre with an MDS team across specialties: implants, root canal,
 * braces, kids, gums and oral surgery; technology by benefit; guides.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md. Everything here is fiction: the centre, the doctors,
 * the reviews, the rating, the cases and the trust figures are SAMPLE content
 * and carry the SampleNote label until the clinic replaces them. Fixed for
 * scripts/measure-gutters.mjs: treatment `root-canal-treatment` and
 * "Dr. Meera Reddy" with a bio. Name forms exactly as in TEMPLATE_NAMES.
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Palash Multispeciality Dental Centre",
  shortName: "Palash Dental",
  tagline: "Implants, root canal, braces, kids dentistry and emergency care in Kondapur, Hyderabad.",
  city: "Hyderabad",
  state: "Telangana",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2015",
  establishedYear: "2015",
  sitePages: [...DENTAL_PAGE_SETS["d2-multispeciality"]],
  heroImage: "/demo/img/dental/hero-white-studio-800.webp",
  sectionPhotos: { about: "/demo/img/dental/interior-teal-operatory-640.webp" },
  photos: [
    { src: "/demo/img/dental/interior-teal-operatory-640.webp", alt: "", category: "Clinic", caption: "Treatment room", hi: { category: "क्लिनिक", caption: "इलाज का कमरा" } },
    { src: "/demo/img/dental/interior-waiting-teal-640.webp", alt: "", category: "Clinic", caption: "Reception and waiting area", hi: { category: "क्लिनिक", caption: "रिसेप्शन और प्रतीक्षा कक्ष" } },
    { src: "/demo/img/dental/tech-3d-imaging-640.webp", alt: "", category: "Diagnosis", caption: "3D imaging room", hi: { category: "जाँच", caption: "3D इमेजिंग कक्ष" } },
    { src: "/demo/img/dental/sterile-sealed-pouches-640.webp", alt: "", category: "Sterilisation", caption: "Sealed instrument pouches", hi: { category: "स्टरलाइज़ेशन", caption: "सील किए औज़ारों के पाउच" } },
  ],
  about:
    "Palash Multispeciality Dental Centre was set up in 2015 by two dentists who wanted patients in Kondapur to find every dental specialty under one roof. It now has six treatment rooms, an in-house X-ray and 3D imaging room, and a team of MDS specialists who plan complex cases together.\n\nMost patients come for one problem, a toothache or a missing tooth, and we treat that first. When a case needs more than one specialist, the endodontist, the prosthodontist and the orthodontist sit down with the same scans and agree one plan and one estimate, so you are not passed from clinic to clinic.",
  mission: "Specialist dental care in one place, planned as a team and explained before it starts.",
  vision: "A centre where a family can bring every dental question, from a first tooth to a full set of implants.",
  hi: {
    instituteName: "पलाश मल्टीस्पेशलिटी डेंटल सेंटर",
    shortName: "पलाश डेंटल",
    tagline: "इम्प्लांट, रूट कैनाल, ब्रेसेज़, बच्चों के दाँत और इमरजेंसी देखभाल, कोंडापुर, हैदराबाद में।",
    city: "हैदराबाद",
    state: "तेलंगाना",
    established: "2015 से",
    establishedYear: "2015",
    about:
      "पलाश मल्टीस्पेशलिटी डेंटल सेंटर 2015 में दो डेंटिस्टों ने शुरू किया, जो चाहते थे कि कोंडापुर के मरीज़ों को दाँतों की हर विशेषज्ञता एक ही जगह मिले। आज यहाँ इलाज के छह कमरे, अपना एक्स-रे और 3D इमेजिंग कक्ष, और MDS विशेषज्ञों की टीम है जो जटिल मामलों की योजना साथ बैठकर बनाती है।\n\nज़्यादातर मरीज़ एक समस्या लेकर आते हैं, दाँत दर्द या गायब दाँत, और हम पहले उसी का इलाज करते हैं। जब एक से ज़्यादा विशेषज्ञ की ज़रूरत हो, तो एंडोडॉन्टिस्ट, प्रोस्थोडॉन्टिस्ट और ऑर्थोडॉन्टिस्ट एक ही स्कैन देखकर एक योजना और एक अनुमान तय करते हैं, ताकि आपको एक क्लिनिक से दूसरे में न भटकना पड़े।",
    mission: "दाँतों की विशेषज्ञ देखभाल एक ही जगह, टीम के साथ योजना बनाकर और शुरू करने से पहले समझाकर।",
    vision: "ऐसा सेंटर जहाँ परिवार दाँतों का हर सवाल ला सके, पहले दाँत से लेकर पूरे इम्प्लांट तक।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "care@example.com",
    addressLines: ["Example Road", "Kondapur, Hyderabad 500000"],
    hours: "Mon to Sat, 10 am to 1:30 pm and 5 to 8:30 pm. Sun, 10 am to 1 pm",
    landmark: "Second floor, opposite a supermarket on the main road",
    mapQuery: "Kondapur, Hyderabad",
    hi: {
      addressLines: ["उदाहरण रोड", "कोंडापुर, हैदराबाद 500000"],
      hours: "सोम से शनि, सुबह 10 से दोपहर 1:30 और शाम 5 से 8:30। रवि, सुबह 10 से दोपहर 1",
      landmark: "दूसरी मंज़िल, मुख्य सड़क पर सुपरमार्केट के सामने",
    },
  },
  stats: [
    { value: "11", label: "Years in Kondapur", basis: "Since 2015", hi: { label: "साल कोंडापुर में", basis: "2015 से" } },
    { value: "6", label: "MDS specialists", basis: "Six recognised specialties on one team", hi: { label: "MDS विशेषज्ञ", basis: "एक टीम में छह मान्य विशेषज्ञताएँ" } },
    { value: "6", label: "Treatment rooms", basis: "Plus a separate imaging room", hi: { label: "इलाज के कमरे", basis: "और एक अलग इमेजिंग कक्ष" } },
    { value: "4", label: "Languages spoken", basis: "Telugu, Hindi, English, Urdu", hi: { label: "भाषाएँ बोली जाती हैं", basis: "तेलुगु, हिंदी, अंग्रेज़ी, उर्दू" } },
  ],
  rating: { value: "4.7", count: "412", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "Two doctors looked at my CBCT together and gave me one plan for the implant and the root canal next to it. The estimate was clear and nothing was added later.", relation: "Patient, implant and root canal", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Implants", hi: { quote: "दो डॉक्टरों ने साथ मिलकर मेरा CBCT देखा और इम्प्लांट और बगल के रूट कैनाल के लिए एक योजना दी। अनुमान साफ़ था और बाद में कुछ नहीं जुड़ा।", relation: "मरीज़, इम्प्लांट और रूट कैनाल", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "इम्प्लांट" } },
    { quote: "My daughter's braces were done here over twenty months. Evening appointments meant she never missed school, and the orthodontist explained every change.", relation: "Parent, braces", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Braces", hi: { quote: "मेरी बेटी के ब्रेसेज़ यहाँ बीस महीने में हुए। शाम की अपॉइंटमेंट से उसका स्कूल कभी नहीं छूटा, और ऑर्थोडॉन्टिस्ट ने हर बदलाव समझाया।", relation: "माता-पिता, ब्रेसेज़", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "ब्रेसेज़" } },
    { quote: "Came in with severe pain on a Saturday evening and was seen within the hour. Root canal finished in one sitting on the Monday.", relation: "Patient, root canal", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Root canal", hi: { quote: "शनिवार शाम तेज़ दर्द के साथ आया और एक घंटे के अंदर देखा गया। सोमवार को एक ही बैठक में रूट कैनाल पूरा हुआ।", relation: "मरीज़, रूट कैनाल", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "रूट कैनाल" } },
    { quote: "The children's dentist let my son hold the mirror and count his own teeth. He asks when he can go back.", relation: "Parent, child's check-up", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Kids", hi: { quote: "बच्चों की डेंटिस्ट ने मेरे बेटे को शीशा पकड़ने दिया और उसके अपने दाँत गिनवाए। अब वह पूछता है कि फिर कब जाएँगे।", relation: "माता-पिता, बच्चे का चेक-अप", source: "गूगल रिव्यू", date: "जून 2026", category: "बच्चे" } },
    { quote: "Whitening was explained honestly: my crowns would not change colour, so they suggested waiting before replacing them. Appreciated that.", relation: "Patient, whitening", rating: "4", source: "Google review", date: "May 2026", consent: true, category: "Whitening", hi: { quote: "व्हाइटनिंग के बारे में ईमानदारी से बताया: मेरे क्राउन का रंग नहीं बदलेगा, इसलिए उन्हें बदलने से पहले रुकने की सलाह दी। यह अच्छा लगा।", relation: "मरीज़, व्हाइटनिंग", source: "गूगल रिव्यू", date: "मई 2026", category: "व्हाइटनिंग" } },
    { quote: "Wisdom tooth removal was quicker than I expected. Swelling for two days, and they called the next morning to check.", relation: "Patient, wisdom tooth", rating: "5", source: "Google review", date: "Apr 2026", consent: true, category: "Oral surgery", hi: { quote: "अक़्ल दाढ़ निकालना मेरी उम्मीद से जल्दी हुआ। दो दिन सूजन रही, और अगली सुबह उन्होंने फ़ोन करके हाल पूछा।", relation: "मरीज़, अक़्ल दाढ़", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "ओरल सर्जरी" } },
    { quote: "Parking is tight at peak hours, but the treatment and the follow-up on WhatsApp were very good.", relation: "Patient, gum treatment", rating: "4", source: "Google review", date: "Mar 2026", consent: true, category: "Gums", hi: { quote: "भीड़ के समय पार्किंग मुश्किल है, पर इलाज और व्हाट्सऐप पर फ़ॉलो-अप बहुत अच्छा रहा।", relation: "मरीज़, मसूड़ों का इलाज", source: "गूगल रिव्यू", date: "मार्च 2026", category: "मसूड़े" } },
  ],
  faq: [
    { title: "How do I know which specialist to see?", body: "You do not need to. Book for your problem, such as pain, a missing tooth or crooked teeth, and the first dentist you meet will involve the right specialist.", group: "Visiting", hi: { title: "मुझे कैसे पता चले कि किस विशेषज्ञ से मिलूँ?", body: "आपको जानने की ज़रूरत नहीं। अपनी समस्या के लिए बुक करें, जैसे दर्द, गायब दाँत या टेढ़े दाँत, और पहले मिलने वाले डेंटिस्ट सही विशेषज्ञ को शामिल करेंगे।", group: "विज़िट" } },
    { title: "What is the consultation fee?", body: "Rs 400 with a general dentist and Rs 700 with a specialist. X-rays are charged separately; a 3D CBCT scan is advised only when planning needs it.", group: "Fees", hi: { title: "परामर्श शुल्क कितना है?", body: "जनरल डेंटिस्ट के साथ 400 रुपये और विशेषज्ञ के साथ 700 रुपये। एक्स-रे का शुल्क अलग है; 3D CBCT स्कैन तभी सुझाया जाता है जब योजना के लिए ज़रूरी हो।", group: "फ़ीस" } },
    { title: "Do you offer EMI?", body: "EMI options may be available through partner lenders, subject to their approval, usually for treatment above Rs 15,000. The desk can check eligibility in a few minutes.", group: "Fees", hi: { title: "क्या EMI मिलती है?", body: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर, आमतौर पर 15,000 रुपये से ज़्यादा के इलाज पर। काउंटर पर कुछ मिनट में पात्रता देखी जा सकती है।", group: "फ़ीस" } },
    { title: "Is my insurance accepted?", body: "Some corporate and health policies cover dental treatment after an accident or as an add-on. We provide itemised bills and reports for reimbursement; ask your insurer what your policy covers.", group: "Fees", hi: { title: "क्या मेरा बीमा मान्य है?", body: "कुछ कॉर्पोरेट और हेल्थ पॉलिसी दुर्घटना के बाद या ऐड-ऑन के रूप में दाँतों का इलाज कवर करती हैं। भरपाई के लिए हम मदवार बिल और रिपोर्ट देते हैं; अपनी पॉलिसी का कवर बीमा कंपनी से पूछें।", group: "फ़ीस" } },
    { title: "How long does an implant take from start to finish?", body: "Usually three to six months: the implant is placed, the bone heals around it, and the crown is fitted. Some cases can have a temporary tooth sooner; your CBCT scan decides.", group: "Treatment", hi: { title: "इम्प्लांट में शुरू से आख़िर तक कितना समय लगता है?", body: "आमतौर पर तीन से छह महीने: इम्प्लांट लगाया जाता है, हड्डी उसके चारों ओर भरती है, फिर क्राउन लगता है। कुछ मामलों में अस्थायी दाँत जल्दी लग सकता है; यह आपके CBCT स्कैन से तय होता है।", group: "इलाज" } },
    { title: "Are X-rays safe for children and during pregnancy?", body: "Digital X-rays use a low dose, and we take them only when they change a decision. In pregnancy we postpone routine X-rays and use a lead apron if one is essential.", group: "Safety", hi: { title: "क्या बच्चों और गर्भावस्था में एक्स-रे सुरक्षित है?", body: "डिजिटल एक्स-रे में कम डोज़ होती है, और हम तभी लेते हैं जब उससे फ़ैसला बदले। गर्भावस्था में सामान्य एक्स-रे टाल देते हैं और ज़रूरी हो तो लेड एप्रन इस्तेमाल करते हैं।", group: "सुरक्षा" } },
    { title: "How do you sterilise instruments?", body: "Every instrument is cleaned, sealed in a pouch and sterilised in a Class B autoclave, with a daily test record. Pouches are opened at your chair.", group: "Safety", hi: { title: "औज़ार कैसे स्टरलाइज़ होते हैं?", body: "हर औज़ार साफ़ होकर पाउच में सील होता है और क्लास B ऑटोक्लेव में स्टरलाइज़ होता है, जिसका रोज़ का टेस्ट रिकॉर्ड रहता है। पाउच आपकी कुर्सी पर खोले जाते हैं।", group: "सुरक्षा" } },
    { title: "Can I get a same-day appointment?", body: "For pain, swelling or a broken tooth we keep slots free in each session. Same-day slots depend on availability, so call or WhatsApp first.", group: "Visiting", hi: { title: "क्या उसी दिन अपॉइंटमेंट मिल सकता है?", body: "दर्द, सूजन या टूटे दाँत के लिए हम हर सेशन में कुछ स्लॉट ख़ाली रखते हैं। उसी दिन के स्लॉट उपलब्धता पर निर्भर हैं, इसलिए पहले फ़ोन या व्हाट्सऐप करें।", group: "विज़िट" } },
    { title: "Do you see patients with diabetes, heart conditions or on blood thinners?", body: "Yes. Bring your medicines list and recent reports. For surgery we plan with your physician's advice and check sugar and blood pressure on the day.", group: "Treatment", hi: { title: "क्या डायबिटीज़, दिल की बीमारी या ख़ून पतला करने वाली दवा लेने वालों का इलाज होता है?", body: "हाँ। दवाओं की सूची और हाल की रिपोर्ट लाएँ। सर्जरी की योजना आपके डॉक्टर की सलाह से बनाते हैं और उस दिन शुगर और ब्लड प्रेशर जाँचते हैं।", group: "इलाज" } },
  ],
  posts: [
    {
      slug: "root-canal-or-extraction", title: "Root canal or extraction: how to decide", date: "12 Sep 2026", category: "Root canal", treatment: "root-canal-treatment",
      author: "Dr. Karthik Rao", reviewedBy: "Medically reviewed by Dr. Karthik Rao, MDS (Conservative Dentistry and Endodontics)",
      excerpt: "Saving a tooth and removing it both have a place. Here is what decides it, and what each costs over time.",
      body: "When a tooth's nerve is infected, there are two ways to stop the pain: clean and seal the canals (root canal treatment), or remove the tooth.\n\nA root canal keeps your own tooth, your bite and the bone around it. It suits a tooth with enough healthy structure left to hold a crown and gums that are firm around it. It usually takes one or two visits, plus a crown on back teeth.\n\nExtraction is quicker and costs less on the day. It suits a tooth that is cracked down the root, very loose from gum disease, or too broken to rebuild. The gap then needs thought: teeth beside it can tilt, and replacing it later with a bridge or an implant costs more than the root canal would have.\n\nAsk your dentist to show you the X-ray, and to write down both options with their cost over the next few years, not only today.",
      hi: {
        title: "रूट कैनाल या दाँत निकलवाना: कैसे तय करें", date: "12 सितंबर 2026", category: "रूट कैनाल", author: "डॉ. कार्तिक राव", reviewedBy: "डॉ. कार्तिक राव, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "दाँत बचाना और निकलवाना, दोनों की अपनी जगह है। यहाँ जानें कि फ़ैसला किस बात पर होता है और समय के साथ किसका कितना ख़र्च है।",
        body: "जब दाँत की नस संक्रमित हो, तो दर्द रोकने के दो रास्ते हैं: नलिकाओं को साफ़ करके सील करना (रूट कैनाल), या दाँत निकालना।\n\nरूट कैनाल आपका अपना दाँत, काटने का तरीक़ा और आसपास की हड्डी बचाता है। यह उस दाँत के लिए ठीक है जिसमें क्राउन सँभालने लायक़ स्वस्थ हिस्सा बचा हो और मसूड़े मज़बूत हों। आमतौर पर एक या दो विज़िट लगती हैं, और पीछे के दाँतों पर क्राउन।\n\nदाँत निकालना उस दिन जल्दी और सस्ता है। यह उस दाँत के लिए ठीक है जो जड़ तक फटा हो, मसूड़ों की बीमारी से बहुत ढीला हो, या इतना टूटा हो कि बन न सके। फिर ख़ाली जगह पर सोचना पड़ता है: बगल के दाँत झुक सकते हैं, और बाद में ब्रिज या इम्प्लांट का ख़र्च रूट कैनाल से ज़्यादा होता है।\n\nअपने डेंटिस्ट से एक्स-रे दिखाने और दोनों विकल्प अगले कुछ सालों के ख़र्च के साथ लिखकर देने को कहें, सिर्फ़ आज के नहीं।",
      },
    },
    {
      slug: "dental-implant-cost-guide", title: "What goes into the cost of a dental implant", date: "28 Aug 2026", category: "Implants", treatment: "dental-implants",
      author: "Dr. Meera Reddy", reviewedBy: "Medically reviewed by Dr. Meera Reddy, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "Why two quotes for 'one implant' can differ, and the questions to ask before you compare.",
      body: "An implant quote is really three things: the implant (a titanium post), the abutment that connects it, and the crown you see. Each has options, and each changes the total.\n\nThe scan comes first. A 3D CBCT scan shows how much bone there is. If there is too little, a bone graft may be needed, which adds cost and healing time.\n\nThe crown can be metal-ceramic or zirconia. Zirconia costs more and looks more natural at the front of the mouth.\n\nWhen you compare quotes, ask: is the scan included, is a graft likely, which crown material is it, how many review visits are included, and what happens if the implant does not integrate. A written estimate should answer all five. The final cost depends on your diagnosis, so be wary of a fixed price given before anyone has seen your scan.",
      hi: {
        title: "डेंटल इम्प्लांट के ख़र्च में क्या-क्या शामिल होता है", date: "28 अगस्त 2026", category: "इम्प्लांट", author: "डॉ. मीरा रेड्डी", reviewedBy: "डॉ. मीरा रेड्डी, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "'एक इम्प्लांट' के दो अनुमान अलग क्यों हो सकते हैं, और तुलना से पहले कौन से सवाल पूछें।",
        body: "इम्प्लांट का अनुमान असल में तीन चीज़ें हैं: इम्प्लांट (टाइटेनियम का पोस्ट), उसे जोड़ने वाला एबटमेंट, और दिखने वाला क्राउन। हर एक के विकल्प हैं, और हर एक कुल ख़र्च बदलता है।\n\nपहले स्कैन होता है। 3D CBCT स्कैन से पता चलता है कि हड्डी कितनी है। कम हो तो बोन ग्राफ़्ट लग सकता है, जिससे ख़र्च और भरने का समय बढ़ता है।\n\nक्राउन मेटल-सिरेमिक या ज़िरकोनिया का हो सकता है। ज़िरकोनिया महँगा है और मुँह के सामने ज़्यादा प्राकृतिक दिखता है।\n\nअनुमानों की तुलना करते समय पूछें: क्या स्कैन शामिल है, क्या ग्राफ़्ट की संभावना है, क्राउन किस सामग्री का है, कितनी फ़ॉलो-अप विज़िट शामिल हैं, और अगर इम्प्लांट न जुड़े तो क्या होगा। लिखित अनुमान में पाँचों के जवाब होने चाहिए। अंतिम ख़र्च आपके निदान पर निर्भर है, इसलिए स्कैन देखे बिना दी गई तय क़ीमत से सावधान रहें।",
      },
    },
    {
      slug: "braces-for-adults", title: "Braces for adults: what is different after 25", date: "10 Aug 2026", category: "Braces", treatment: "braces",
      author: "Dr. Sana Fatima", reviewedBy: "Medically reviewed by Dr. Sana Fatima, MDS (Orthodontics and Dentofacial Orthopaedics)",
      excerpt: "Adults can straighten their teeth at any age. Gum health, not age, decides what is possible.",
      body: "Teeth move at any age, so there is no upper limit for braces or aligners. What changes in adults is the starting point.\n\nGums come first. Any gum disease is treated before teeth are moved, because moving teeth in inflamed gums can loosen them.\n\nTreatment can take a little longer than in teenagers, often 18 to 24 months, and some adults need a small amount of reshaping between teeth to create room.\n\nCeramic braces and clear aligners are popular because they are less visible at work. Aligners must be worn about 22 hours a day to work, so they suit people who will be disciplined about it.\n\nRetainers matter most of all. Teeth tend to drift back, and wearing a retainer at night is what keeps the result.",
      hi: {
        title: "वयस्कों के लिए ब्रेसेज़: 25 के बाद क्या अलग है", date: "10 अगस्त 2026", category: "ब्रेसेज़", author: "डॉ. सना फ़ातिमा", reviewedBy: "डॉ. सना फ़ातिमा, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "वयस्क किसी भी उम्र में दाँत सीधे करवा सकते हैं। क्या संभव है, यह उम्र नहीं, मसूड़ों की सेहत तय करती है।",
        body: "दाँत किसी भी उम्र में खिसकते हैं, इसलिए ब्रेसेज़ या अलाइनर की कोई ऊपरी उम्र नहीं है। वयस्कों में शुरुआत की स्थिति बदलती है।\n\nपहले मसूड़े। दाँत खिसकाने से पहले मसूड़ों की बीमारी का इलाज होता है, क्योंकि सूजे मसूड़ों में दाँत खिसकाने से वे ढीले हो सकते हैं।\n\nइलाज किशोरों से थोड़ा लंबा हो सकता है, अक्सर 18 से 24 महीने, और कुछ वयस्कों में जगह बनाने के लिए दाँतों के बीच थोड़ा आकार बदलना पड़ता है।\n\nसिरेमिक ब्रेसेज़ और क्लियर अलाइनर पसंद किए जाते हैं क्योंकि दफ़्तर में कम दिखते हैं। अलाइनर दिन में लगभग 22 घंटे पहनने पर ही काम करते हैं, इसलिए ये अनुशासित लोगों के लिए ठीक हैं।\n\nसबसे ज़रूरी है रिटेनर। दाँत वापस खिसकने की ओर जाते हैं, और रात में रिटेनर पहनना ही नतीजा बनाए रखता है।",
      },
    },
    {
      slug: "teeth-whitening-myths", title: "Teeth whitening: five common myths", date: "22 Jul 2026", category: "Cosmetic", treatment: "teeth-whitening",
      author: "Dr. Meera Reddy", reviewedBy: "Medically reviewed by Dr. Meera Reddy, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "Whitening is safe when it is supervised, but it does not do everything people expect.",
      body: "Myth 1: whitening damages enamel. Supervised whitening with the right gel strength does not. Sensitivity for a day or two is common and passes.\n\nMyth 2: it whitens crowns and fillings too. It does not. Only natural teeth change shade, so old front fillings may need replacing afterwards to match.\n\nMyth 3: charcoal and lemon work as well. Abrasive powders and acids wear enamel and can make teeth look more yellow over time.\n\nMyth 4: results are permanent. Tea, coffee, paan and smoking restain teeth. A top-up every year or two keeps the shade.\n\nMyth 5: everyone is a candidate. Decay and gum disease are treated first, and whitening is not advised in pregnancy.",
      hi: {
        title: "दाँत सफ़ेद करना: पाँच आम ग़लतफ़हमियाँ", date: "22 जुलाई 2026", category: "कॉस्मेटिक", author: "डॉ. मीरा रेड्डी", reviewedBy: "डॉ. मीरा रेड्डी, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "निगरानी में व्हाइटनिंग सुरक्षित है, पर यह वह सब नहीं करती जिसकी लोग उम्मीद करते हैं।",
        body: "ग़लतफ़हमी 1: व्हाइटनिंग इनेमल ख़राब करती है। सही ताक़त के जेल के साथ निगरानी में की गई व्हाइटनिंग ऐसा नहीं करती। एक-दो दिन झनझनाहट आम है और चली जाती है।\n\nग़लतफ़हमी 2: इससे क्राउन और फ़िलिंग भी सफ़ेद होते हैं। नहीं होते। सिर्फ़ प्राकृतिक दाँतों का रंग बदलता है, इसलिए बाद में मिलान के लिए आगे की पुरानी फ़िलिंग बदलनी पड़ सकती है।\n\nग़लतफ़हमी 3: कोयला और नींबू भी उतना ही काम करते हैं। घिसने वाले पाउडर और एसिड इनेमल घिसते हैं और समय के साथ दाँत ज़्यादा पीले दिख सकते हैं।\n\nग़लतफ़हमी 4: नतीजा हमेशा रहता है। चाय, कॉफ़ी, पान और धूम्रपान से दाग़ लौटते हैं। हर एक-दो साल में टॉप-अप से रंग बना रहता है।\n\nग़लतफ़हमी 5: हर कोई करा सकता है। पहले कीड़े और मसूड़ों की बीमारी का इलाज होता है, और गर्भावस्था में व्हाइटनिंग की सलाह नहीं दी जाती।",
      },
    },
  ],
  dental: {
    legalName: "Palash Dental Care Private Limited (sample)",
    hi: { legalName: "पलाश डेंटल केयर प्राइवेट लिमिटेड (नमूना)" },
    hero: {
      pill: "Multi-speciality dental centre, Kondapur",
      headline: "Dental care *designed around* your smile",
      lead: "Implants, root canal, braces, kids dentistry and emergency care in Kondapur, Hyderabad.",
      nextSlot: "Evening slots from 5 pm, Mon to Sat",
      credential: "Six MDS specialists, one treatment plan",
      hi: {
        pill: "मल्टीस्पेशलिटी डेंटल सेंटर, कोंडापुर",
        headline: "आपकी मुस्कान के *हिसाब से बनी* दाँतों की देखभाल",
        lead: "इम्प्लांट, रूट कैनाल, ब्रेसेज़, बच्चों के दाँत और इमरजेंसी देखभाल, कोंडापुर, हैदराबाद में।",
        nextSlot: "शाम 5 बजे से स्लॉट, सोम से शनि",
        credential: "छह MDS विशेषज्ञ, इलाज की एक योजना",
      },
    },
    doctors: [
      {
        slug: "meera-reddy", name: "Dr. Meera Reddy", photo: "/demo/img/people/dentist-w01-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Prosthodontics and Crown and Bridge)", specialisation: "Prosthodontist",
        focus: "Dental implants, crowns and bridges, full-mouth rehabilitation, smile makeovers", experience: "15 years in practice",
        languages: ["Telugu", "English", "Hindi"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        bio: "Dr. Meera Reddy co-founded the centre in 2015. Her work is replacing and rebuilding teeth: implants, crowns, bridges and dentures, and the full-mouth cases where several of these come together.\n\nShe leads the weekly case meeting where complex plans are agreed by the whole team, and she insists that every patient leaves that meeting's outcome with a written estimate and a timeline they understand.",
        quote: "A good plan is one the patient can explain back to me.",
        training: ["BDS, 2008 (sample)", "MDS, Prosthodontics and Crown and Bridge, 2012 (sample)", "Implant surgery and prosthetics course, 2014 (sample)"],
        memberships: ["Indian Prosthodontic Society (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. मीरा रेड्डी", qualification: "BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज)", specialisation: "प्रोस्थोडॉन्टिस्ट",
          focus: "डेंटल इम्प्लांट, क्राउन और ब्रिज, पूरे मुँह का पुनर्निर्माण, स्माइल मेकओवर", experience: "15 साल का अनुभव",
          languages: ["तेलुगु", "अंग्रेज़ी", "हिंदी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि",
          bio: "डॉ. मीरा रेड्डी ने 2015 में इस सेंटर की सह-स्थापना की। उनका काम दाँत बदलना और फिर से बनाना है: इम्प्लांट, क्राउन, ब्रिज और डेंचर, और पूरे मुँह के वे मामले जहाँ ये सब साथ आते हैं।\n\nवे हर हफ़्ते की केस मीटिंग की अगुवाई करती हैं जहाँ पूरी टीम जटिल योजनाएँ तय करती है, और ज़ोर देती हैं कि हर मरीज़ को उस योजना का लिखित अनुमान और समझ में आने वाली समय-सीमा मिले।",
          quote: "अच्छी योजना वह है जिसे मरीज़ मुझे वापस समझा सके।",
          training: ["BDS, 2008 (नमूना)", "MDS, प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज, 2012 (नमूना)", "इम्प्लांट सर्जरी और प्रोस्थेटिक्स कोर्स, 2014 (नमूना)"],
          memberships: ["इंडियन प्रोस्थोडॉन्टिक सोसाइटी (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "karthik-rao", name: "Dr. Karthik Rao", photo: "/demo/img/people/dentist-m01-240.webp", gender: "male",
        qualification: "BDS, MDS (Conservative Dentistry and Endodontics)", specialisation: "Endodontist",
        focus: "Root canal treatment, re-treatment of failed root canals, cracked teeth", experience: "11 years in practice",
        languages: ["Telugu", "English", "Kannada"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        bio: "Dr. Karthik Rao co-founded the centre and sees most of its root canal cases, including teeth that were treated elsewhere and still hurt. He works with rotary instruments and magnification, and explains each case on the X-ray before and after.\n\nHe also writes the centre's patient guides, because he finds most fear of root canals comes from not knowing what happens.",
        quote: "Saving a tooth is worth the effort when the tooth is worth saving. I will tell you which it is.",
        training: ["BDS, 2010 (sample)", "MDS, Conservative Dentistry and Endodontics, 2014 (sample)"],
        memberships: ["Indian Endodontic Society (sample)"],
        hi: {
          name: "डॉ. कार्तिक राव", qualification: "BDS, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स)", specialisation: "एंडोडॉन्टिस्ट",
          focus: "रूट कैनाल, असफल रूट कैनाल का दोबारा इलाज, दरार वाले दाँत", experience: "11 साल का अनुभव",
          languages: ["तेलुगु", "अंग्रेज़ी", "कन्नड़"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि",
          bio: "डॉ. कार्तिक राव सेंटर के सह-संस्थापक हैं और यहाँ के ज़्यादातर रूट कैनाल देखते हैं, उन दाँतों समेत जिनका इलाज कहीं और हुआ और अब भी दर्द है। वे रोटरी औज़ारों और मैग्निफ़िकेशन से काम करते हैं, और हर केस इलाज से पहले और बाद में एक्स-रे पर समझाते हैं।\n\nसेंटर की मरीज़ गाइड भी वही लिखते हैं, क्योंकि उनके अनुसार रूट कैनाल का ज़्यादातर डर यह न जानने से आता है कि होता क्या है।",
          quote: "दाँत बचाने की मेहनत तब सही है जब दाँत बचाने लायक़ हो। मैं आपको बताऊँगा कि आपका कैसा है।",
          training: ["BDS, 2010 (नमूना)", "MDS, कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स, 2014 (नमूना)"],
          memberships: ["इंडियन एंडोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "sana-fatima", name: "Dr. Sana Fatima", photo: "/demo/img/people/dentist-w02-240.webp", gender: "female",
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist", focus: "Braces, clear aligners, early orthodontic checks for children",
        experience: "9 years in practice", languages: ["Urdu", "Hindi", "English", "Telugu"], regNo: "Reg. no. A-00000 (sample)", days: "Tue, Thu and Sat",
        hi: { name: "डॉ. सना फ़ातिमा", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट", focus: "ब्रेसेज़, क्लियर अलाइनर, बच्चों की शुरुआती ऑर्थोडॉन्टिक जाँच", experience: "9 साल का अनुभव", languages: ["उर्दू", "हिंदी", "अंग्रेज़ी", "तेलुगु"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल, गुरु और शनि" },
      },
      {
        slug: "priya-kulkarni", name: "Dr. Priya Kulkarni", photo: "/demo/img/people/dentist-w03-240.webp", gender: "female",
        qualification: "BDS, MDS (Paediatric and Preventive Dentistry)", specialisation: "Paediatric dentist", focus: "Children's check-ups, fillings and pulp treatment in milk teeth, children with special needs",
        experience: "8 years in practice", languages: ["Telugu", "English", "Marathi", "Hindi"], regNo: "Reg. no. A-00000 (sample)", days: "Mon, Wed, Fri and Sat",
        hi: { name: "डॉ. प्रिया कुलकर्णी", qualification: "BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)", specialisation: "बच्चों की डेंटिस्ट", focus: "बच्चों का चेक-अप, दूध के दाँतों की फ़िलिंग और नस का इलाज, विशेष ज़रूरतों वाले बच्चे", experience: "8 साल का अनुभव", languages: ["तेलुगु", "अंग्रेज़ी", "मराठी", "हिंदी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम, बुध, शुक्र और शनि" },
      },
      {
        slug: "venkat-naidu", name: "Dr. Venkat Naidu", photo: "/demo/img/people/dentist-m03-240.webp", gender: "male", visiting: true,
        qualification: "BDS, MDS (Oral and Maxillofacial Surgery)", specialisation: "Oral and maxillofacial surgeon", focus: "Wisdom tooth surgery, implant surgery, bone grafts",
        experience: "13 years in practice", languages: ["Telugu", "English", "Hindi"], regNo: "Reg. no. A-00000 (sample)", days: "Wednesdays and Saturdays, by appointment",
        hi: { name: "डॉ. वेंकट नायडू", qualification: "BDS, MDS (ओरल एंड मैक्सिलोफ़ेशियल सर्जरी)", specialisation: "ओरल और मैक्सिलोफ़ेशियल सर्जन", focus: "अक़्ल दाढ़ की सर्जरी, इम्प्लांट सर्जरी, बोन ग्राफ़्ट", experience: "13 साल का अनुभव", languages: ["तेलुगु", "अंग्रेज़ी", "हिंदी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "बुधवार और शनिवार, अपॉइंटमेंट पर" },
      },
      {
        slug: "arjun-varma", name: "Dr. Arjun Varma", photo: "/demo/img/people/dentist-m05-240.webp", gender: "male", visiting: true,
        qualification: "BDS, MDS (Periodontology)", specialisation: "Periodontist", focus: "Gum disease, deep cleaning, gum surgery around implants",
        experience: "10 years in practice", languages: ["Telugu", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Tuesdays and Fridays, 5 to 8:30 pm",
        hi: { name: "डॉ. अर्जुन वर्मा", qualification: "BDS, MDS (पेरियोडॉन्टोलॉजी)", specialisation: "पेरियोडॉन्टिस्ट", focus: "मसूड़ों की बीमारी, गहरी सफ़ाई, इम्प्लांट के आसपास मसूड़ों की सर्जरी", experience: "10 साल का अनुभव", languages: ["तेलुगु", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगलवार और शुक्रवार, शाम 5 से 8:30" },
      },
    ],
    treatments: [
      {
        slug: "dental-implants", name: "Dental implants", category: "Implants and replacement", icon: "implant", image: "/demo/img/dental/implant-models-table-640.webp", featured: true, reason: "implants",
        summary: "A fixed replacement for a missing tooth, planned on a 3D CBCT scan.",
        what: "An implant is a small titanium post placed in the jawbone where a tooth is missing. Once the bone has healed around it, a crown is fixed on top. It does not rely on the neighbouring teeth, and it helps keep the bone in that area. Our prosthodontist and oral surgeon plan each implant together on a 3D scan.",
        symptoms: ["A gap from a lost or removed tooth", "A bridge or denture that no longer fits", "Difficulty chewing on one side"],
        whoNeedsIt: ["Adults with enough bone, or who can have a graft", "People with controlled diabetes and healthy gums", "Non-smokers, or those willing to stop around surgery"],
        steps: [
          { title: "Scan and plan", body: "A 3D CBCT scan shows bone height and width; the plan and estimate follow.", hi: { title: "स्कैन और योजना", body: "3D CBCT स्कैन से हड्डी की ऊँचाई-चौड़ाई दिखती है; फिर योजना और अनुमान।" } },
          { title: "Place the implant", body: "Under local anaesthesia, usually in under an hour.", hi: { title: "इम्प्लांट लगाना", body: "लोकल एनेस्थीसिया में, आमतौर पर एक घंटे से कम में।" } },
          { title: "Heal", body: "Two to four months for the bone to bond with the implant.", hi: { title: "भरना", body: "हड्डी को इम्प्लांट से जुड़ने में दो से चार महीने।" } },
          { title: "Fit the crown", body: "An impression or scan, then the final crown is fixed.", hi: { title: "क्राउन लगाना", body: "नाप या स्कैन, फिर अंतिम क्राउन फ़िक्स किया जाता है।" } },
        ],
        duration: "3 to 6 months", visits: "4 to 5 visits", recovery: "Mild swelling for 2 to 3 days after placement. Soft food on that side for a week.",
        comfort: "Placed under local anaesthesia. Most people describe the days after as easier than an extraction.",
        faqs: [
          { title: "How long does an implant last?", body: "With good cleaning and regular reviews, implants can serve for many years. Smoking, gum disease and grinding shorten that; we check the implant at every visit.", hi: { title: "इम्प्लांट कितने समय चलता है?", body: "अच्छी सफ़ाई और नियमित जाँच से इम्प्लांट कई साल चल सकते हैं। धूम्रपान, मसूड़ों की बीमारी और दाँत पीसने से यह समय घटता है; हम हर विज़िट में जाँचते हैं।" } },
          { title: "Can I have an implant if I have diabetes?", body: "Often yes, if your sugar is controlled. We ask for a recent HbA1c report before planning.", hi: { title: "क्या डायबिटीज़ में इम्प्लांट लग सकता है?", body: "अक्सर हाँ, अगर शुगर नियंत्रित है। योजना से पहले हम हाल की HbA1c रिपोर्ट माँगते हैं।" } },
        ],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "डेंटल इम्प्लांट", category: "इम्प्लांट और दाँत बदलना",
          summary: "गायब दाँत की जगह फ़िक्स्ड दाँत, 3D CBCT स्कैन पर योजना के साथ।",
          what: "इम्प्लांट टाइटेनियम का छोटा पोस्ट है जो गायब दाँत की जगह जबड़े की हड्डी में लगाया जाता है। हड्डी के उसके चारों ओर भरने के बाद ऊपर क्राउन लगता है। यह बगल के दाँतों पर निर्भर नहीं करता और उस हिस्से की हड्डी बनाए रखने में मदद करता है। हमारे प्रोस्थोडॉन्टिस्ट और ओरल सर्जन हर इम्प्लांट की योजना 3D स्कैन पर साथ बनाते हैं।",
          symptoms: ["टूटे या निकाले गए दाँत की ख़ाली जगह", "ब्रिज या डेंचर जो अब ठीक नहीं बैठता", "एक तरफ़ से चबाने में दिक़्क़त"],
          whoNeedsIt: ["पर्याप्त हड्डी वाले वयस्क, या जिन्हें ग्राफ़्ट लग सके", "नियंत्रित डायबिटीज़ और स्वस्थ मसूड़ों वाले", "धूम्रपान न करने वाले, या सर्जरी के आसपास छोड़ने को तैयार"],
          duration: "3 से 6 महीने", visits: "4 से 5 विज़िट", recovery: "लगाने के बाद 2 से 3 दिन हल्की सूजन। एक हफ़्ते उस तरफ़ नरम खाना।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है। ज़्यादातर लोग बाद के दिनों को दाँत निकलवाने से आसान बताते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "root-canal-treatment", name: "Root canal treatment", category: "Root canal and fillings", icon: "root-canal", image: "/demo/img/dental/doctor-handpiece-care-640.webp", featured: true, reason: "root-canal",
        summary: "Saves an infected tooth by an endodontist, with rotary files and magnification.",
        what: "Root canal treatment removes infected or inflamed pulp from inside a tooth, disinfects the canals and seals them. Our endodontist uses rotary files, an electronic apex locator to measure canal length and magnification to find every canal, which matters for back teeth with three or four canals.",
        symptoms: ["Lingering pain with hot or cold", "Pain on biting", "Swelling or a gum boil near a tooth", "Night pain that wakes you"],
        whoNeedsIt: ["Teeth with deep decay reaching the nerve", "Teeth with a previous root canal that still hurts", "Cracked teeth that can still be saved"],
        steps: [
          { title: "Diagnose", body: "X-ray, cold test and bite test to confirm the tooth.", hi: { title: "निदान", body: "एक्स-रे, ठंडा टेस्ट और काटने का टेस्ट, दाँत पक्का करने के लिए।" } },
          { title: "Clean and seal", body: "Under local anaesthesia with a rubber dam; one or two visits.", hi: { title: "सफ़ाई और सील", body: "लोकल एनेस्थीसिया और रबर डैम के साथ; एक या दो विज़िट।" } },
          { title: "Protect", body: "A crown on back teeth, fitted a week or two later.", hi: { title: "सुरक्षा", body: "पीछे के दाँतों पर क्राउन, एक-दो हफ़्ते बाद।" } },
        ],
        duration: "1 to 2 visits, plus a crown", visits: "45 to 90 minutes each. Single-visit root canal where clinically suitable.",
        recovery: "Tender to bite for 2 to 3 days. Avoid hard food on that side until the crown is fitted.",
        comfort: "Root canal treatment under local anaesthesia, with comfort breaks when you need them.",
        faqs: [{ title: "Why do I need a crown after a root canal?", body: "A back tooth that has had a root canal is more brittle. A crown spreads the biting force and lowers the risk of it splitting.", hi: { title: "रूट कैनाल के बाद क्राउन क्यों चाहिए?", body: "रूट कैनाल हुआ पीछे का दाँत ज़्यादा भुरभुरा होता है। क्राउन चबाने का ज़ोर बाँटता है और दाँत के फटने का ख़तरा घटाता है।" } }],
        fromPrice: "4,500", priceNote: "per tooth, front teeth",
        hi: {
          name: "रूट कैनाल ट्रीटमेंट", category: "रूट कैनाल और फ़िलिंग",
          summary: "एंडोडॉन्टिस्ट द्वारा रोटरी फ़ाइलों और मैग्निफ़िकेशन से संक्रमित दाँत बचाना।",
          what: "रूट कैनाल में दाँत के अंदर का संक्रमित या सूजा गूदा निकाला जाता है, नलिकाएँ कीटाणुरहित करके सील की जाती हैं। हमारे एंडोडॉन्टिस्ट रोटरी फ़ाइलें, नलिका की लंबाई नापने वाला इलेक्ट्रॉनिक एपेक्स लोकेटर और हर नलिका ढूँढने के लिए मैग्निफ़िकेशन इस्तेमाल करते हैं, जो तीन-चार नलिकाओं वाली दाढ़ों में ज़रूरी है।",
          symptoms: ["गरम या ठंडे से देर तक रहने वाला दर्द", "काटने पर दर्द", "दाँत के पास सूजन या फोड़ा", "रात में दर्द से नींद खुलना"],
          whoNeedsIt: ["नस तक पहुँचे गहरे कीड़े वाले दाँत", "पहले रूट कैनाल के बाद भी दर्द वाले दाँत", "दरार वाले दाँत जो अभी बच सकते हैं"],
          duration: "1 से 2 विज़िट, और क्राउन", visits: "हर विज़िट 45 से 90 मिनट। जहाँ क्लिनिकली सही हो, वहाँ एक विज़िट में रूट कैनाल।",
          recovery: "2 से 3 दिन काटने पर हल्का दर्द। क्राउन लगने तक उस तरफ़ सख़्त खाना नहीं।",
          comfort: "रूट कैनाल लोकल एनेस्थीसिया में, और जब चाहें तब आराम के लिए रुकावट।", priceNote: "प्रति दाँत, आगे के दाँत",
        },
      },
      {
        slug: "braces", name: "Braces", category: "Braces and aligners", icon: "braces", image: "/demo/img/dental/ortho-braces-model-640.webp", featured: true, reason: "braces",
        summary: "Metal and ceramic braces for teenagers and adults, planned by our orthodontist.",
        what: "Braces are small brackets bonded to the teeth and joined by a wire that is adjusted every few weeks to move the teeth into line. Metal braces are the most economical; ceramic braces are tooth-coloured and less visible. Both correct crowding, gaps and bite problems.",
        symptoms: ["Crowded or crooked teeth", "Upper teeth that stick out", "Teeth that do not meet when you bite"],
        whoNeedsIt: ["Children from about 11 once most adult teeth are in", "Adults with healthy gums"],
        steps: [
          { title: "Records", body: "Photos, X-rays and a scan or moulds of the teeth.", hi: { title: "रिकॉर्ड", body: "फ़ोटो, एक्स-रे और दाँतों का स्कैन या साँचा।" } },
          { title: "Fit", body: "Brackets are bonded in one visit of about an hour.", hi: { title: "लगाना", body: "लगभग एक घंटे की एक विज़िट में ब्रैकेट लगाए जाते हैं।" } },
          { title: "Adjust and retain", body: "Reviews every 4 to 6 weeks, then retainers to hold the result.", hi: { title: "सुधार और रिटेनर", body: "हर 4 से 6 हफ़्ते जाँच, फिर नतीजा बनाए रखने के लिए रिटेनर।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "A review every 4 to 6 weeks", recovery: "Sore teeth for 2 to 3 days after fitting and after adjustments.",
        comfort: "No injections are needed. Orthodontic wax helps where brackets rub.",
        faqs: [{ title: "Metal or ceramic?", body: "Both work equally well. Ceramic is less visible but costs more and needs a little more care with staining food.", hi: { title: "मेटल या सिरेमिक?", body: "दोनों बराबर काम करते हैं। सिरेमिक कम दिखता है पर महँगा है और दाग़ वाले खाने से थोड़ा ज़्यादा ध्यान चाहिए।" } }],
        fromPrice: "35,000", priceNote: "metal braces, both jaws",
        hi: {
          name: "ब्रेसेज़", category: "ब्रेसेज़ और अलाइनर",
          summary: "किशोरों और वयस्कों के लिए मेटल और सिरेमिक ब्रेसेज़, हमारे ऑर्थोडॉन्टिस्ट की योजना से।",
          what: "ब्रेसेज़ दाँतों पर चिपके छोटे ब्रैकेट हैं जो एक तार से जुड़े होते हैं, जिसे हर कुछ हफ़्तों में कसकर दाँत सीध में लाए जाते हैं। मेटल ब्रेसेज़ सबसे किफ़ायती हैं; सिरेमिक ब्रेसेज़ दाँत के रंग के और कम दिखने वाले हैं। दोनों भीड़, गैप और काटने की समस्याएँ ठीक करते हैं।",
          symptoms: ["भीड़ वाले या टेढ़े दाँत", "ऊपर के दाँत आगे निकले हुए", "काटते समय दाँत न मिलना"],
          whoNeedsIt: ["लगभग 11 साल से बच्चे, जब ज़्यादातर पक्के दाँत आ जाएँ", "स्वस्थ मसूड़ों वाले वयस्क"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "हर 4 से 6 हफ़्ते में जाँच", recovery: "लगाने और हर सुधार के बाद 2 से 3 दिन दाँत दुखते हैं।",
          comfort: "इंजेक्शन की ज़रूरत नहीं। जहाँ ब्रैकेट रगड़ें, वहाँ ऑर्थोडॉन्टिक वैक्स मदद करता है।", priceNote: "मेटल ब्रेसेज़, दोनों जबड़े",
        },
      },
      {
        slug: "clear-aligners", name: "Clear aligners", category: "Braces and aligners", icon: "aligner", image: "/demo/img/dental/ortho-aligner-fit-640.webp", reason: "aligners",
        summary: "Removable clear trays that straighten teeth in stages, planned on a 3D scan.",
        what: "Aligners are a series of thin, clear trays made from a 3D scan of your teeth. Each set moves the teeth a little; you change to the next set every one or two weeks. You take them out to eat and brush, so they need discipline: about 22 hours a day.",
        symptoms: ["Mild to moderate crowding or gaps", "Teeth that moved after braces years ago"],
        whoNeedsIt: ["Adults and older teenagers who will wear them consistently", "People who want a less visible option at work"],
        steps: [
          { title: "Scan", body: "An intraoral scan instead of moulds.", hi: { title: "स्कैन", body: "साँचे की जगह इंट्राओरल स्कैन।" } },
          { title: "Preview the plan", body: "You see the planned tooth movement on screen before approving.", hi: { title: "योजना देखें", body: "मंज़ूरी से पहले स्क्रीन पर दाँतों की योजनाबद्ध हलचल देखें।" } },
          { title: "Wear and review", body: "New trays every 1 to 2 weeks, checks every 6 to 8 weeks.", hi: { title: "पहनना और जाँच", body: "हर 1 से 2 हफ़्ते नई ट्रे, हर 6 से 8 हफ़्ते जाँच।" } },
        ],
        duration: "Usually 6 to 18 months", visits: "A review every 6 to 8 weeks", recovery: "Pressure for a day or two with each new set.",
        comfort: "No brackets or wires. Small tooth-coloured attachments may be bonded to help grip.",
        faqs: [{ title: "Are aligners faster than braces?", body: "Not usually. They suit simpler cases; complex bite problems are often better treated with braces.", hi: { title: "क्या अलाइनर ब्रेसेज़ से जल्दी काम करते हैं?", body: "आमतौर पर नहीं। ये आसान मामलों के लिए ठीक हैं; जटिल काटने की समस्याएँ अक्सर ब्रेसेज़ से बेहतर ठीक होती हैं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "क्लियर अलाइनर", category: "ब्रेसेज़ और अलाइनर",
          summary: "निकलने वाली पारदर्शी ट्रे जो चरणों में दाँत सीधे करती हैं, 3D स्कैन पर योजना के साथ।",
          what: "अलाइनर पतली, पारदर्शी ट्रे की एक श्रृंखला है जो आपके दाँतों के 3D स्कैन से बनती है। हर सेट दाँतों को थोड़ा खिसकाता है; हर एक-दो हफ़्ते आप अगला सेट पहनते हैं। खाने और ब्रश के लिए इन्हें निकालते हैं, इसलिए अनुशासन चाहिए: दिन में लगभग 22 घंटे।",
          symptoms: ["हल्की से मध्यम भीड़ या गैप", "सालों पहले ब्रेसेज़ के बाद खिसके दाँत"],
          whoNeedsIt: ["वयस्क और बड़े किशोर जो इन्हें लगातार पहनेंगे", "जो दफ़्तर में कम दिखने वाला विकल्प चाहते हैं"],
          duration: "आमतौर पर 6 से 18 महीने", visits: "हर 6 से 8 हफ़्ते में जाँच", recovery: "हर नए सेट के साथ एक-दो दिन दबाव।",
          comfort: "कोई ब्रैकेट या तार नहीं। पकड़ के लिए छोटे दाँत के रंग के अटैचमेंट लग सकते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "teeth-whitening", name: "Teeth whitening", category: "Cosmetic", icon: "whitening", image: "/demo/img/dental/patient-laugh-room-640.webp", reason: "whitening",
        summary: "Supervised in-clinic whitening, after a check that your teeth and gums are healthy.",
        what: "Whitening uses a peroxide gel to lighten the natural colour of the teeth. In the clinic, the gums are protected and the gel is applied in timed rounds. It lightens natural teeth only; crowns and fillings keep their shade.",
        symptoms: ["Yellowing with age", "Staining from tea, coffee or tobacco"],
        whoNeedsIt: ["Adults with healthy teeth and gums", "Not advised in pregnancy or for children"],
        steps: [
          { title: "Check and clean", body: "Decay and gum problems are treated first; a clean removes surface stain.", hi: { title: "जाँच और सफ़ाई", body: "पहले कीड़े और मसूड़ों की समस्या का इलाज; सफ़ाई से ऊपरी दाग़ हटते हैं।" } },
          { title: "Whiten", body: "Gums protected, gel applied in rounds over about an hour.", hi: { title: "व्हाइटनिंग", body: "मसूड़े सुरक्षित करके लगभग एक घंटे में कई बार जेल लगाया जाता है।" } },
          { title: "Aftercare", body: "Avoid strongly coloured food and drink for 48 hours.", hi: { title: "बाद की देखभाल", body: "48 घंटे गहरे रंग वाला खाना-पीना न लें।" } },
        ],
        duration: "One visit", visits: "1 visit of about 90 minutes", recovery: "Sensitivity for a day or two is common.",
        comfort: "No anaesthetic is needed. A desensitising gel is applied afterwards.",
        faqs: [{ title: "How white will my teeth get?", body: "It varies with your starting shade. Results vary from person to person; we record your shade before and after.", hi: { title: "मेरे दाँत कितने सफ़ेद होंगे?", body: "यह आपके शुरुआती रंग पर निर्भर है। नतीजे हर व्यक्ति में अलग होते हैं; हम पहले और बाद का रंग दर्ज करते हैं।" } }],
        fromPrice: "12,000", priceNote: "in-clinic, both jaws",
        hi: {
          name: "दाँत सफ़ेद करना", category: "कॉस्मेटिक",
          summary: "क्लिनिक में निगरानी वाली व्हाइटनिंग, दाँत और मसूड़े स्वस्थ होने की जाँच के बाद।",
          what: "व्हाइटनिंग में पेरॉक्साइड जेल से दाँतों का प्राकृतिक रंग हल्का किया जाता है। क्लिनिक में मसूड़ों को सुरक्षित करके जेल तय समय के कई दौर में लगाया जाता है। यह सिर्फ़ प्राकृतिक दाँतों को हल्का करता है; क्राउन और फ़िलिंग का रंग वही रहता है।",
          symptoms: ["उम्र के साथ पीलापन", "चाय, कॉफ़ी या तंबाकू के दाग़"],
          whoNeedsIt: ["स्वस्थ दाँत और मसूड़ों वाले वयस्क", "गर्भावस्था में या बच्चों के लिए सलाह नहीं"],
          duration: "एक विज़िट", visits: "लगभग 90 मिनट की 1 विज़िट", recovery: "एक-दो दिन झनझनाहट आम है।",
          comfort: "सुन्न करने की ज़रूरत नहीं। बाद में झनझनाहट कम करने वाला जेल लगाया जाता है।", priceNote: "क्लिनिक में, दोनों जबड़े",
        },
      },
      {
        slug: "smile-makeover", name: "Smile makeover", category: "Cosmetic", icon: "smile", image: "/demo/img/dental/tech-3d-scan-screen-640.webp", reason: "veneers",
        summary: "A planned combination of whitening, veneers, crowns or aligners, previewed before we start.",
        what: "A smile makeover combines treatments to change the shape, colour or alignment of the front teeth. We start with photos and a digital plan, then a trial smile in temporary material so you can see and approve the result in your own mouth before any permanent work.",
        symptoms: ["Chipped, worn or uneven front teeth", "Gaps or old discoloured fillings at the front"],
        whoNeedsIt: ["Adults with healthy gums who want a change in their front teeth"],
        steps: [
          { title: "Photos and plan", body: "Photos, a scan and a digital smile design.", hi: { title: "फ़ोटो और योजना", body: "फ़ोटो, स्कैन और डिजिटल स्माइल डिज़ाइन।" } },
          { title: "Trial smile", body: "A temporary mock-up on your teeth to approve.", hi: { title: "ट्रायल स्माइल", body: "मंज़ूरी के लिए आपके दाँतों पर अस्थायी मॉक-अप।" } },
          { title: "Final work", body: "Veneers, crowns or bonding made to the approved design.", hi: { title: "अंतिम काम", body: "मंज़ूर डिज़ाइन के अनुसार वीनियर, क्राउन या बॉन्डिंग।" } },
        ],
        duration: "2 to 6 weeks", visits: "3 to 5 visits", recovery: "A few days to get used to the new shape of your teeth.",
        comfort: "Tooth preparation is done under local anaesthesia. We keep preparation as conservative as the plan allows.",
        faqs: [{ title: "Can I see the result before committing?", body: "Yes. The trial smile shows the planned shape in your mouth, and you can ask for changes before the final work.", hi: { title: "क्या तय करने से पहले नतीजा देख सकते हैं?", body: "हाँ। ट्रायल स्माइल आपके मुँह में योजनाबद्ध आकार दिखाती है, और अंतिम काम से पहले आप बदलाव माँग सकते हैं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "स्माइल मेकओवर", category: "कॉस्मेटिक",
          summary: "व्हाइटनिंग, वीनियर, क्राउन या अलाइनर का योजनाबद्ध मेल, शुरू करने से पहले झलक के साथ।",
          what: "स्माइल मेकओवर में आगे के दाँतों का आकार, रंग या सीध बदलने के लिए कई इलाज मिलाए जाते हैं। हम फ़ोटो और डिजिटल योजना से शुरू करते हैं, फिर अस्थायी सामग्री में ट्रायल स्माइल बनाते हैं ताकि स्थायी काम से पहले आप अपने मुँह में नतीजा देखकर मंज़ूर कर सकें।",
          symptoms: ["टूटे, घिसे या असमान आगे के दाँत", "सामने गैप या पुरानी बदरंग फ़िलिंग"],
          whoNeedsIt: ["स्वस्थ मसूड़ों वाले वयस्क जो आगे के दाँतों में बदलाव चाहते हैं"],
          duration: "2 से 6 हफ़्ते", visits: "3 से 5 विज़िट", recovery: "दाँतों के नए आकार की आदत में कुछ दिन।",
          comfort: "दाँत की तैयारी लोकल एनेस्थीसिया में। योजना जितनी अनुमति दे, उतनी कम घिसाई।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "kids-dentistry", name: "Kids dentistry", category: "Children", icon: "kids", image: "/demo/img/dental/kids-boy-with-dentist-640.webp", featured: true, reason: "kids",
        summary: "Check-ups, fluoride, sealants and milk-teeth care by our paediatric dentist.",
        what: "Our paediatric dentist sees children from the first tooth to their teens. Visits are short and paced for the child: prevention first (fluoride varnish, sealants, diet advice), and fillings or pulp treatment in milk teeth when needed. A parent stays in the room throughout.",
        symptoms: ["White chalky or brown spots on teeth", "Your child complains when eating sweets", "Thumb sucking or mouth breathing"],
        whoNeedsIt: ["Babies by the first birthday", "Children every six months"],
        steps: [
          { title: "Meet", body: "A look around the room and the chair first.", hi: { title: "मुलाक़ात", body: "पहले कमरे और कुर्सी से पहचान।" } },
          { title: "Check", body: "A gentle examination, X-ray only if needed.", hi: { title: "जाँच", body: "हल्की जाँच, ज़रूरत हो तभी एक्स-रे।" } },
          { title: "Prevent or treat", body: "Fluoride, sealants, or a filling at the child's pace.", hi: { title: "बचाव या इलाज", body: "बच्चे की रफ़्तार से फ़्लोराइड, सीलेंट या फ़िलिंग।" } },
        ],
        duration: "One visit for a check-up", visits: "20 to 40 minutes", recovery: "None for a check-up. No food for 30 minutes after fluoride.",
        comfort: "Tell-show-do: we explain, show and then do. Treatment stops if your child needs a break.",
        faqs: [{ title: "Can my child be sedated?", body: "For a few children who cannot manage treatment awake, we discuss conscious sedation or treatment under general anaesthesia at a partner hospital. It is always a joint decision with you.", hi: { title: "क्या बच्चे को सेडेशन दिया जा सकता है?", body: "जो कुछ बच्चे जागते हुए इलाज नहीं करा पाते, उनके लिए हम कॉन्शियस सेडेशन या साथी अस्पताल में जनरल एनेस्थीसिया पर बात करते हैं। फ़ैसला हमेशा आपके साथ मिलकर होता है।" } }],
        fromPrice: "600", priceNote: "per sealant",
        hi: {
          name: "बच्चों के दाँत", category: "बच्चे",
          summary: "हमारी बच्चों की डेंटिस्ट द्वारा चेक-अप, फ़्लोराइड, सीलेंट और दूध के दाँतों की देखभाल।",
          what: "हमारी बच्चों की डेंटिस्ट पहले दाँत से किशोर उम्र तक बच्चों को देखती हैं। विज़िट छोटी और बच्चे की रफ़्तार से होती हैं: पहले बचाव (फ़्लोराइड वार्निश, सीलेंट, खान-पान की सलाह), और ज़रूरत हो तो दूध के दाँतों की फ़िलिंग या नस का इलाज। माता-पिता पूरे समय कमरे में रहते हैं।",
          symptoms: ["दाँतों पर सफ़ेद चॉक जैसे या भूरे धब्बे", "मीठा खाने पर बच्चे को तकलीफ़", "अँगूठा चूसना या मुँह से साँस लेना"],
          whoNeedsIt: ["पहले जन्मदिन तक के शिशु", "बच्चे, हर छह महीने"],
          duration: "चेक-अप के लिए एक विज़िट", visits: "20 से 40 मिनट", recovery: "चेक-अप के बाद कुछ नहीं। फ़्लोराइड के बाद 30 मिनट कुछ न खाएँ।",
          comfort: "बताओ-दिखाओ-करो: हम समझाते हैं, दिखाते हैं, फिर करते हैं। बच्चे को रुकना हो तो इलाज रुक जाता है।", priceNote: "प्रति सीलेंट",
        },
      },
      {
        slug: "wisdom-tooth-surgery", name: "Wisdom tooth surgery", category: "Oral surgery", icon: "wisdom", image: "/demo/img/dental/doctor-xray-review-640.webp", reason: "wisdom",
        summary: "Removal of impacted wisdom teeth by our oral and maxillofacial surgeon.",
        what: "An impacted wisdom tooth is stuck under the gum or bone. When it causes repeated swelling or damages the tooth in front, our oral surgeon removes it under local anaesthesia, after a 3D scan if the roots are close to the nerve.",
        symptoms: ["Recurring swelling at the back of the jaw", "Pain opening the mouth", "Food trapped behind the last molar"],
        whoNeedsIt: ["Adults with symptomatic or damaging wisdom teeth"],
        steps: [
          { title: "Scan", body: "X-ray, and a CBCT scan if the roots lie near the nerve.", hi: { title: "स्कैन", body: "एक्स-रे, और जड़ें नस के पास हों तो CBCT स्कैन।" } },
          { title: "Surgery", body: "Under local anaesthesia, usually 30 to 60 minutes.", hi: { title: "सर्जरी", body: "लोकल एनेस्थीसिया में, आमतौर पर 30 से 60 मिनट।" } },
          { title: "Review", body: "Stitches checked or removed after a week.", hi: { title: "फ़ॉलो-अप", body: "एक हफ़्ते बाद टाँके जाँचे या हटाए जाते हैं।" } },
        ],
        duration: "One visit, plus a review", visits: "1 visit of 30 to 60 minutes", recovery: "Swelling and stiffness for 3 to 5 days. Most people rest for a day.",
        comfort: "Done under local anaesthesia. You will feel pressure and hear sounds, not sharp pain.",
        faqs: [{ title: "Should I remove all four at once?", body: "Only if all four are causing problems. Healthy, upright wisdom teeth can stay.", hi: { title: "क्या चारों एक साथ निकलवाएँ?", body: "सिर्फ़ तब जब चारों परेशानी दे रहे हों। स्वस्थ, सीधी अक़्ल दाढ़ें रह सकती हैं।" } }],
        fromPrice: "5,000", priceNote: "per tooth, surgical",
        hi: {
          name: "अक़्ल दाढ़ की सर्जरी", category: "ओरल सर्जरी",
          summary: "हमारे ओरल और मैक्सिलोफ़ेशियल सर्जन द्वारा फँसी अक़्ल दाढ़ निकालना।",
          what: "फँसी अक़्ल दाढ़ मसूड़े या हड्डी के नीचे अटकी रहती है। जब वह बार-बार सूजन करे या आगे के दाँत को नुकसान दे, तो हमारे ओरल सर्जन उसे लोकल एनेस्थीसिया में निकालते हैं, और जड़ें नस के पास हों तो पहले 3D स्कैन करते हैं।",
          symptoms: ["जबड़े के पीछे बार-बार सूजन", "मुँह खोलने में दर्द", "आख़िरी दाढ़ के पीछे खाना फँसना"],
          whoNeedsIt: ["जिनकी अक़्ल दाढ़ तकलीफ़ या नुकसान दे रही हो"],
          duration: "एक विज़िट, और फ़ॉलो-अप", visits: "30 से 60 मिनट की 1 विज़िट", recovery: "3 से 5 दिन सूजन और जकड़न। ज़्यादातर लोग एक दिन आराम करते हैं।",
          comfort: "लोकल एनेस्थीसिया में। आपको दबाव लगेगा और आवाज़ें सुनाई देंगी, तेज़ दर्द नहीं।", priceNote: "प्रति दाँत, सर्जिकल",
        },
      },
      {
        slug: "teeth-cleaning", name: "Teeth cleaning", category: "Gums", icon: "cleaning", image: "/demo/img/dental/doctor-at-work-blue-640.webp", reason: "cleaning",
        summary: "Scaling and polishing to remove tartar and stains, with brushing advice.",
        what: "Professional cleaning removes hardened tartar and surface stains that brushing cannot. It keeps gums healthy and is the first step for bleeding gums or bad breath.",
        symptoms: ["Bleeding gums", "Tartar near the gum line", "Bad breath"],
        whoNeedsIt: ["Most adults every 6 to 12 months"],
        steps: [
          { title: "Scale", body: "Ultrasonic scaling with a water spray.", hi: { title: "स्केलिंग", body: "पानी की फुहार के साथ अल्ट्रासोनिक स्केलिंग।" } },
          { title: "Polish", body: "Removes surface stain and smooths the teeth.", hi: { title: "पॉलिश", body: "ऊपरी दाग़ हटाकर दाँत चिकने करना।" } },
          { title: "Advise", body: "Brushing and interdental cleaning shown on your teeth.", hi: { title: "सलाह", body: "आपके दाँतों पर ब्रश और दाँतों के बीच सफ़ाई का तरीक़ा।" } },
        ],
        duration: "One visit", visits: "30 to 45 minutes", recovery: "Mild sensitivity for a day.",
        comfort: "Usually no anaesthetic. Tell us if an area is sensitive and we will numb it.",
        faqs: [{ title: "How often should I have a cleaning?", body: "Every six months for most people; every three to four months if you have gum disease.", hi: { title: "सफ़ाई कितनी बार करानी चाहिए?", body: "ज़्यादातर लोगों के लिए हर छह महीने; मसूड़ों की बीमारी हो तो हर तीन-चार महीने।" } }],
        fromPrice: "1,200", priceNote: "full mouth",
        hi: {
          name: "दाँतों की सफ़ाई", category: "मसूड़े",
          summary: "टार्टर और दाग़ हटाने के लिए स्केलिंग और पॉलिश, ब्रश करने की सलाह के साथ।",
          what: "प्रोफ़ेशनल सफ़ाई सख़्त टार्टर और ऊपरी दाग़ हटाती है जो ब्रश से नहीं हटते। इससे मसूड़े स्वस्थ रहते हैं और मसूड़ों से ख़ून या मुँह की बदबू में यह पहला क़दम है।",
          symptoms: ["मसूड़ों से ख़ून", "मसूड़ों के पास टार्टर", "मुँह की बदबू"],
          whoNeedsIt: ["ज़्यादातर वयस्क, हर 6 से 12 महीने"],
          duration: "एक विज़िट", visits: "30 से 45 मिनट", recovery: "एक दिन हल्की झनझनाहट।",
          comfort: "आमतौर पर सुन्न करने की ज़रूरत नहीं। कोई हिस्सा संवेदनशील हो तो बताएँ, हम सुन्न कर देंगे।", priceNote: "पूरा मुँह",
        },
      },
      {
        slug: "gum-treatment", name: "Gum treatment", category: "Gums", icon: "gum", image: "/demo/img/dental/patient-woman-chair-640.webp", reason: "cleaning",
        summary: "Deep cleaning and, where needed, gum surgery by our periodontist.",
        what: "Gum disease loosens the attachment between gum and tooth and slowly destroys the supporting bone. Our periodontist treats it with deep cleaning below the gums and, in advanced cases, minor gum surgery, then sets a maintenance schedule to keep it stable.",
        symptoms: ["Gums that bleed or recede", "Loose or drifting teeth", "Persistent bad taste"],
        whoNeedsIt: ["Adults with gum pockets or bone loss on X-ray", "People with diabetes or who smoke"],
        steps: [
          { title: "Chart", body: "Pocket depths around every tooth, and X-rays.", hi: { title: "चार्ट", body: "हर दाँत के चारों ओर जेबों की गहराई, और एक्स-रे।" } },
          { title: "Deep clean", body: "Root planing under local anaesthesia, in two or four sittings.", hi: { title: "गहरी सफ़ाई", body: "लोकल एनेस्थीसिया में रूट प्लानिंग, दो या चार बैठकों में।" } },
          { title: "Maintain", body: "Re-assessment, then cleaning every 3 to 4 months.", hi: { title: "देखभाल जारी", body: "दोबारा आकलन, फिर हर 3 से 4 महीने सफ़ाई।" } },
        ],
        duration: "6 to 8 weeks for the first phase", visits: "2 to 4 visits", recovery: "Tender gums for a few days; sensitivity to cold may last longer.",
        comfort: "Deep cleaning is done under local anaesthesia.",
        faqs: [{ title: "Will my loose teeth tighten?", body: "Often they become firmer once the inflammation settles, but lost bone does not fully regrow. Early treatment saves the most.", hi: { title: "क्या ढीले दाँत कस जाएँगे?", body: "सूजन घटने पर अक्सर दाँत मज़बूत होते हैं, पर गई हड्डी पूरी तरह वापस नहीं आती। जल्दी इलाज से सबसे ज़्यादा बचता है।" } }],
        fromPrice: "3,000", priceNote: "per quarter of the mouth",
        hi: {
          name: "मसूड़ों का इलाज", category: "मसूड़े",
          summary: "हमारे पेरियोडॉन्टिस्ट द्वारा गहरी सफ़ाई और ज़रूरत हो तो मसूड़ों की सर्जरी।",
          what: "मसूड़ों की बीमारी मसूड़े और दाँत का जुड़ाव ढीला करती है और सहारा देने वाली हड्डी को धीरे-धीरे नष्ट करती है। हमारे पेरियोडॉन्टिस्ट मसूड़ों के नीचे गहरी सफ़ाई से और गंभीर मामलों में छोटी सर्जरी से इलाज करते हैं, फिर इसे स्थिर रखने के लिए नियमित देखभाल तय करते हैं।",
          symptoms: ["मसूड़ों से ख़ून या मसूड़ों का पीछे हटना", "ढीले या खिसकते दाँत", "लगातार ख़राब स्वाद"],
          whoNeedsIt: ["जिनके एक्स-रे में जेबें या हड्डी का नुकसान दिखे", "डायबिटीज़ वाले या धूम्रपान करने वाले"],
          duration: "पहले चरण के लिए 6 से 8 हफ़्ते", visits: "2 से 4 विज़िट", recovery: "कुछ दिन मसूड़े नाज़ुक; ठंडे से झनझनाहट ज़्यादा दिन रह सकती है।",
          comfort: "गहरी सफ़ाई लोकल एनेस्थीसिया में होती है।", priceNote: "मुँह के प्रति चौथाई हिस्से",
        },
      },
      {
        slug: "crowns-and-bridges", name: "Crowns and bridges", category: "Implants and replacement", icon: "crown", image: "/demo/img/dental/implant-ceramic-crowns-640.webp", reason: "not-sure",
        summary: "Metal-ceramic and zirconia crowns and bridges, matched to your teeth.",
        what: "A crown restores a weak or root-canal-treated tooth; a bridge replaces a missing tooth using the teeth on either side. We take a digital scan or impression and match the shade in daylight.",
        symptoms: ["A tooth after root canal treatment", "A large broken filling", "A single missing tooth"],
        whoNeedsIt: ["Adults needing to protect or replace a tooth"],
        steps: [
          { title: "Prepare", body: "The tooth is shaped and a temporary crown fitted.", hi: { title: "तैयारी", body: "दाँत को आकार देकर अस्थायी क्राउन लगाया जाता है।" } },
          { title: "Scan", body: "A digital scan and shade match go to the lab.", hi: { title: "स्कैन", body: "डिजिटल स्कैन और रंग मिलान लैब भेजा जाता है।" } },
          { title: "Fit", body: "The final crown is checked and cemented.", hi: { title: "फ़िटिंग", body: "अंतिम क्राउन जाँचकर सीमेंट किया जाता है।" } },
        ],
        duration: "5 to 7 working days", visits: "2 visits", recovery: "Your bite settles within a few days.",
        comfort: "Shaping is done under local anaesthesia.",
        faqs: [{ title: "Will a crown look natural?", body: "All-ceramic and zirconia crowns are shade-matched and suit front teeth; metal-ceramic is often chosen for back teeth.", hi: { title: "क्या क्राउन प्राकृतिक दिखेगा?", body: "पूरे सिरेमिक और ज़िरकोनिया क्राउन का रंग मिलाया जाता है और ये आगे के दाँतों के लिए ठीक हैं; पीछे के दाँतों के लिए अक्सर मेटल-सिरेमिक चुना जाता है।" } }],
        fromPrice: "5,500", priceNote: "per crown, metal-ceramic",
        hi: {
          name: "क्राउन और ब्रिज", category: "इम्प्लांट और दाँत बदलना",
          summary: "मेटल-सिरेमिक और ज़िरकोनिया क्राउन और ब्रिज, आपके दाँतों से मिलते हुए।",
          what: "क्राउन कमज़ोर या रूट कैनाल हुए दाँत को ठीक करता है; ब्रिज दोनों ओर के दाँतों के सहारे गायब दाँत की जगह लेता है। हम डिजिटल स्कैन या नाप लेते हैं और दिन की रोशनी में रंग मिलाते हैं।",
          symptoms: ["रूट कैनाल के बाद का दाँत", "बड़ी टूटी फ़िलिंग", "एक गायब दाँत"],
          whoNeedsIt: ["जिन्हें दाँत बचाना या बदलना है"],
          duration: "5 से 7 कार्य दिवस", visits: "2 विज़िट", recovery: "कुछ दिनों में काटना सामान्य हो जाता है।",
          comfort: "आकार देना लोकल एनेस्थीसिया में होता है।", priceNote: "प्रति क्राउन, मेटल-सिरेमिक",
        },
      },
      {
        slug: "tooth-coloured-fillings", name: "Tooth-coloured fillings", category: "Root canal and fillings", icon: "filling", image: "/demo/img/dental/doctor-at-work-teal-640.webp", reason: "checkup",
        summary: "Composite fillings for small cavities, done in one visit.",
        what: "Early decay is cleaned out and the space filled with tooth-coloured composite that bonds to the tooth. It is set with a light, so you can eat the same day.",
        symptoms: ["Sensitivity to sweets or cold", "A dark spot or small hole", "A chipped old filling"],
        whoNeedsIt: ["Adults and children with small or medium cavities"],
        steps: [
          { title: "Clean", body: "Decay removed, under local anaesthesia if deep.", hi: { title: "सफ़ाई", body: "कीड़ा हटाना, गहरा हो तो लोकल एनेस्थीसिया में।" } },
          { title: "Fill", body: "Composite placed in layers and light-cured.", hi: { title: "भरना", body: "कम्पोज़िट परतों में भरकर लाइट से सख़्त करना।" } },
          { title: "Polish", body: "Shaped and polished to your bite.", hi: { title: "पॉलिश", body: "आपके काटने के हिसाब से आकार और पॉलिश।" } },
        ],
        duration: "One visit", visits: "30 to 45 minutes per tooth", recovery: "Mild sensitivity for a few days.",
        comfort: "Small fillings often need no anaesthetic; deeper ones are numbed first.",
        faqs: [{ title: "Should I replace my old silver fillings?", body: "Only if they are cracked, leaking or have decay around them. Sound fillings can stay.", hi: { title: "क्या पुरानी चाँदी वाली फ़िलिंग बदलवाऊँ?", body: "सिर्फ़ तब जब वे फटी, रिसती या आसपास कीड़ा हो। ठीक फ़िलिंग रह सकती हैं।" } }],
        fromPrice: "1,000", priceNote: "per tooth",
        hi: {
          name: "दाँत के रंग की फ़िलिंग", category: "रूट कैनाल और फ़िलिंग",
          summary: "छोटे कीड़ों के लिए कम्पोज़िट फ़िलिंग, एक विज़िट में।",
          what: "शुरुआती कीड़ा साफ़ करके जगह दाँत के रंग वाले कम्पोज़िट से भरी जाती है जो दाँत से चिपक जाता है। इसे लाइट से सख़्त किया जाता है, इसलिए उसी दिन खा सकते हैं।",
          symptoms: ["मीठे या ठंडे से झनझनाहट", "काला धब्बा या छोटा छेद", "टूटी पुरानी फ़िलिंग"],
          whoNeedsIt: ["छोटे या मध्यम कीड़े वाले बड़े और बच्चे"],
          duration: "एक विज़िट", visits: "प्रति दाँत 30 से 45 मिनट", recovery: "कुछ दिन हल्की झनझनाहट।",
          comfort: "छोटी फ़िलिंग में अक्सर सुन्न करने की ज़रूरत नहीं; गहरी में पहले सुन्न किया जाता है।", priceNote: "प्रति दाँत",
        },
      },
    ],
    specialties: [
      { title: "Implants and replacement", body: "Implants, crowns, bridges and dentures, led by a prosthodontist.", group: "Implants and replacement", hi: { title: "इम्प्लांट और दाँत बदलना", body: "इम्प्लांट, क्राउन, ब्रिज और डेंचर, प्रोस्थोडॉन्टिस्ट की अगुवाई में।", group: "इम्प्लांट और दाँत बदलना" } },
      { title: "Root canal and fillings", body: "Saving teeth with root canal treatment and fillings, by an endodontist.", group: "Root canal and fillings", hi: { title: "रूट कैनाल और फ़िलिंग", body: "एंडोडॉन्टिस्ट द्वारा रूट कैनाल और फ़िलिंग से दाँत बचाना।", group: "रूट कैनाल और फ़िलिंग" } },
      { title: "Braces and aligners", body: "Metal and ceramic braces and clear aligners, by an orthodontist.", group: "Braces and aligners", hi: { title: "ब्रेसेज़ और अलाइनर", body: "ऑर्थोडॉन्टिस्ट द्वारा मेटल और सिरेमिक ब्रेसेज़ और क्लियर अलाइनर।", group: "ब्रेसेज़ और अलाइनर" } },
      { title: "Cosmetic", body: "Whitening and smile makeovers, planned and previewed first.", group: "Cosmetic", hi: { title: "कॉस्मेटिक", body: "व्हाइटनिंग और स्माइल मेकओवर, पहले योजना और झलक के साथ।", group: "कॉस्मेटिक" } },
      { title: "Children", body: "Prevention and gentle treatment by a paediatric dentist.", group: "Children", hi: { title: "बच्चे", body: "बच्चों की डेंटिस्ट द्वारा बचाव और सहज इलाज।", group: "बच्चे" } },
      { title: "Gums", body: "Cleaning, deep cleaning and gum care, by a periodontist.", group: "Gums", hi: { title: "मसूड़े", body: "पेरियोडॉन्टिस्ट द्वारा सफ़ाई, गहरी सफ़ाई और मसूड़ों की देखभाल।", group: "मसूड़े" } },
      { title: "Oral surgery", body: "Wisdom teeth, surgical extractions and bone grafts, by an oral surgeon.", group: "Oral surgery", hi: { title: "ओरल सर्जरी", body: "ओरल सर्जन द्वारा अक़्ल दाढ़, सर्जिकल निकासी और बोन ग्राफ़्ट।", group: "ओरल सर्जरी" } },
    ],
    technology: [
      { title: "Digital X-rays", benefit: "A lower radiation dose than film, and the image is on screen in seconds so we can show you.", group: "diagnosis", icon: "xray", image: "/demo/img/dental/tech-xray-monitor-640.webp", hi: { title: "डिजिटल एक्स-रे", benefit: "फ़िल्म से कम रेडिएशन, और तस्वीर कुछ सेकंड में स्क्रीन पर, ताकि हम आपको दिखा सकें।" } },
      { title: "3D CBCT imaging", benefit: "Shows bone, nerves and sinuses in three dimensions, so implants and wisdom tooth surgery are planned precisely.", group: "diagnosis", icon: "cbct", image: "/demo/img/dental/tech-3d-imaging-640.webp", hi: { title: "3D CBCT इमेजिंग", benefit: "हड्डी, नसें और साइनस तीन आयामों में दिखते हैं, ताकि इम्प्लांट और अक़्ल दाढ़ की सर्जरी की योजना सटीक बने।" } },
      { title: "Intraoral scanner", benefit: "A digital scan instead of messy impression trays, for crowns, aligners and implants.", group: "precision", icon: "scan", image: "/demo/img/dental/tech-intraoral-scanner-640.webp", hi: { title: "इंट्राओरल स्कैनर", benefit: "क्राउन, अलाइनर और इम्प्लांट के लिए साँचे की ट्रे की जगह डिजिटल स्कैन।" } },
      { title: "Rotary endodontics and apex locator", benefit: "Cleaner, more predictable root canals, often in fewer visits.", group: "comfort", icon: "root-canal", hi: { title: "रोटरी एंडोडॉन्टिक्स और एपेक्स लोकेटर", benefit: "ज़्यादा साफ़ और भरोसेमंद रूट कैनाल, अक्सर कम विज़िट में।" } },
      { title: "Magnification", benefit: "Loupes and a dental microscope help find hidden canals and fine cracks.", group: "precision", icon: "microscope", hi: { title: "मैग्निफ़िकेशन", benefit: "लूप और डेंटल माइक्रोस्कोप छिपी नलिकाएँ और बारीक दरारें ढूँढने में मदद करते हैं।" } },
      { title: "Class B autoclave", benefit: "Sterilises hollow and wrapped instruments reliably, tested and logged every day.", group: "hygiene", icon: "sterile", image: "/demo/img/dental/sterile-autoclave-640.webp", hi: { title: "क्लास B ऑटोक्लेव", benefit: "खोखले और लिपटे औज़ारों को भरोसे से स्टरलाइज़ करता है, रोज़ जाँच और रिकॉर्ड के साथ।" } },
    ],
    fees: [
      { treatment: "Consultation, general dentist", from: "400", unit: "per visit", group: "Consultation", hi: { treatment: "परामर्श, जनरल डेंटिस्ट", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "Consultation, specialist", from: "700", unit: "per visit", group: "Consultation", hi: { treatment: "परामर्श, विशेषज्ञ", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "3D CBCT scan", from: "2,500", unit: "per scan", group: "Consultation", note: "Only when planning needs it", hi: { treatment: "3D CBCT स्कैन", unit: "प्रति स्कैन", group: "परामर्श", note: "सिर्फ़ जब योजना के लिए ज़रूरी हो" } },
      { treatment: "Teeth cleaning", slug: "teeth-cleaning", from: "1,200", unit: "full mouth", group: "General", hi: { treatment: "दाँतों की सफ़ाई", unit: "पूरा मुँह", group: "सामान्य" } },
      { treatment: "Tooth-coloured filling", slug: "tooth-coloured-fillings", from: "1,000", unit: "per tooth", group: "General", hi: { treatment: "दाँत के रंग की फ़िलिंग", unit: "प्रति दाँत", group: "सामान्य" } },
      { treatment: "Root canal treatment (front tooth)", slug: "root-canal-treatment", from: "4,500", unit: "per tooth", group: "Root canal", hi: { treatment: "रूट कैनाल (आगे का दाँत)", unit: "प्रति दाँत", group: "रूट कैनाल" } },
      { treatment: "Root canal treatment (molar)", slug: "root-canal-treatment", from: "6,500", unit: "per tooth", group: "Root canal", note: "Crown charged separately", hi: { treatment: "रूट कैनाल (दाढ़)", unit: "प्रति दाँत", group: "रूट कैनाल", note: "क्राउन का शुल्क अलग" } },
      { treatment: "Crown, metal-ceramic", slug: "crowns-and-bridges", from: "5,500", unit: "per crown", group: "Crowns and implants", hi: { treatment: "क्राउन, मेटल-सिरेमिक", unit: "प्रति क्राउन", group: "क्राउन और इम्प्लांट" } },
      { treatment: "Crown, zirconia", slug: "crowns-and-bridges", from: "11,000", unit: "per crown", group: "Crowns and implants", hi: { treatment: "क्राउन, ज़िरकोनिया", unit: "प्रति क्राउन", group: "क्राउन और इम्प्लांट" } },
      { treatment: "Dental implant with crown", slug: "dental-implants", consult: true, group: "Crowns and implants", hi: { treatment: "क्राउन के साथ डेंटल इम्प्लांट", group: "क्राउन और इम्प्लांट" } },
      { treatment: "Wisdom tooth surgery", slug: "wisdom-tooth-surgery", from: "5,000", unit: "per tooth", group: "Oral surgery", hi: { treatment: "अक़्ल दाढ़ की सर्जरी", unit: "प्रति दाँत", group: "ओरल सर्जरी" } },
      { treatment: "Metal braces", slug: "braces", from: "35,000", unit: "both jaws", group: "Braces and aligners", hi: { treatment: "मेटल ब्रेसेज़", unit: "दोनों जबड़े", group: "ब्रेसेज़ और अलाइनर" } },
      { treatment: "Clear aligners", slug: "clear-aligners", consult: true, group: "Braces and aligners", hi: { treatment: "क्लियर अलाइनर", group: "ब्रेसेज़ और अलाइनर" } },
      { treatment: "In-clinic whitening", slug: "teeth-whitening", from: "12,000", unit: "both jaws", group: "Cosmetic", hi: { treatment: "क्लिनिक में व्हाइटनिंग", unit: "दोनों जबड़े", group: "कॉस्मेटिक" } },
      { treatment: "Smile makeover", slug: "smile-makeover", consult: true, group: "Cosmetic", hi: { treatment: "स्माइल मेकओवर", group: "कॉस्मेटिक" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: Rs 36,000 over 12 months is about Rs 3,000 a month before any lender charges.",
      partners: ["Card EMI through your bank", "A healthcare finance partner (sample)"],
      modes: ["UPI", "Debit and credit cards", "Net banking", "Cash"],
      insurance: "Reimbursement with some insurers where your policy covers dental treatment; ask at the desk. We provide itemised bills and reports.",
      consultFee: "Consultation: Rs 400 with a general dentist, Rs 700 with a specialist.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: 12 महीने में 36,000 रुपये, किसी भी शुल्क से पहले लगभग 3,000 रुपये महीना।",
        partners: ["आपके बैंक के कार्ड पर EMI", "एक हेल्थकेयर फ़ाइनेंस साथी (नमूना)"],
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नेट बैंकिंग", "नक़द"],
        insurance: "जहाँ आपकी पॉलिसी दाँतों का इलाज कवर करे, वहाँ कुछ बीमा कंपनियों से भरपाई; काउंटर पर पूछें। हम मदवार बिल और रिपोर्ट देते हैं।",
        consultFee: "परामर्श: जनरल डेंटिस्ट के साथ 400 रुपये, विशेषज्ञ के साथ 700 रुपये।",
      },
    },
    cases: [
      { category: "Implants", title: "Single missing lower molar replaced with an implant crown", treatment: "dental-implants", duration: "4 months, 4 visits", hi: { category: "इम्प्लांट", title: "नीचे की एक गायब दाढ़ की जगह इम्प्लांट क्राउन", duration: "4 महीने, 4 विज़िट" } },
      { category: "Implants", title: "Two upper teeth replaced with an implant-supported bridge", treatment: "dental-implants", duration: "5 months, 5 visits", hi: { category: "इम्प्लांट", title: "ऊपर के दो दाँतों की जगह इम्प्लांट पर टिका ब्रिज", duration: "5 महीने, 5 विज़िट" } },
      { category: "Braces", title: "Crowded lower front teeth aligned with ceramic braces", treatment: "braces", duration: "16 months", problem: "Crowding", hi: { category: "ब्रेसेज़", title: "नीचे के भीड़ वाले आगे के दाँत सिरेमिक ब्रेसेज़ से सीधे", duration: "16 महीने", problem: "भीड़" } },
      { category: "Braces", title: "Gap between upper front teeth closed with clear aligners", treatment: "clear-aligners", duration: "8 months", problem: "Gaps", hi: { category: "ब्रेसेज़", title: "ऊपर के आगे के दाँतों का गैप क्लियर अलाइनर से बंद", duration: "8 महीने", problem: "गैप" } },
      { category: "Whitening", title: "In-clinic whitening of tea-stained teeth", treatment: "teeth-whitening", duration: "1 visit", hi: { category: "व्हाइटनिंग", title: "चाय के दाग़ वाले दाँतों की क्लिनिक में व्हाइटनिंग", duration: "1 विज़िट" } },
      { category: "Smile design", title: "Chipped front teeth rebuilt after a trial smile", treatment: "smile-makeover", duration: "3 weeks, 4 visits", hi: { category: "स्माइल डिज़ाइन", title: "ट्रायल स्माइल के बाद टूटे आगे के दाँत फिर से बनाए गए", duration: "3 हफ़्ते, 4 विज़िट" } },
    ],
    emergency: {
      headline: "Tooth pain? Same-day emergency appointments",
      intro: "We keep emergency slots in every session for severe pain, swelling, broken teeth and injuries. Call or WhatsApp before you leave home so we can have the right specialist ready.",
      phone: "+91 00000 00000",
      whatsapp: "910000000000",
      hours: "Emergency line answered 8 am to 10 pm, all week",
      urgent: ["Severe or throbbing toothache", "Swelling of the face, gum or jaw", "A knocked-out or broken tooth after a fall or sports injury", "Bleeding after an extraction that pressure does not stop", "A broken brace wire cutting the cheek"],
      firstAid: [
        { title: "Knocked-out adult tooth", body: "Pick it up by the crown. Rinse briefly in milk or saline, place it back in the socket or keep it in milk, and come in within 60 minutes.", hi: { title: "पक्का दाँत निकल गया", body: "दाँत को ऊपर के हिस्से से उठाएँ। दूध या सलाइन में हल्का धोएँ, वापस जगह पर रखें या दूध में रखें, और 60 मिनट के अंदर आएँ।" } },
        { title: "Broken tooth", body: "Rinse with warm water, save the pieces in milk, and hold a cold pack to the cheek.", hi: { title: "टूटा दाँत", body: "गुनगुने पानी से कुल्ला करें, टुकड़े दूध में रखें, और गाल पर ठंडी सिकाई करें।" } },
        { title: "Swelling", body: "Cold pack on the outside, head raised, and call us. Do not apply heat.", hi: { title: "सूजन", body: "बाहर ठंडी सिकाई, सिर ऊँचा, और हमें फ़ोन करें। गरम सिकाई न करें।" } },
        { title: "Broken brace wire", body: "Push the end flat with a pencil eraser or cover it with orthodontic wax, then call to book a repair.", hi: { title: "ब्रेसेज़ का टूटा तार", body: "पेंसिल के रबर से सिरा दबा दें या ऑर्थोडॉन्टिक वैक्स से ढकें, फिर मरम्मत के लिए फ़ोन करें।" } },
      ],
      canWait: ["A lost filling without pain", "A loose bracket that is not cutting the cheek", "Mild sensitivity to cold", "A small chip on a front tooth"],
      hi: {
        headline: "दाँत में दर्द? उसी दिन इमरजेंसी अपॉइंटमेंट",
        intro: "तेज़ दर्द, सूजन, टूटे दाँत और चोट के लिए हम हर सेशन में इमरजेंसी स्लॉट रखते हैं। घर से निकलने से पहले फ़ोन या व्हाट्सऐप करें ताकि सही विशेषज्ञ तैयार रहें।",
        hours: "इमरजेंसी लाइन सुबह 8 से रात 10 तक, पूरे हफ़्ते",
        urgent: ["तेज़ या धड़कता दाँत दर्द", "चेहरे, मसूड़े या जबड़े में सूजन", "गिरने या खेल में चोट से निकला या टूटा दाँत", "दाँत निकालने के बाद ख़ून जो दबाने से न रुके", "ब्रेसेज़ का टूटा तार जो गाल काट रहा हो"],
        canWait: ["बिना दर्द के निकली फ़िलिंग", "ढीला ब्रैकेट जो गाल न काट रहा हो", "ठंडे से हल्की झनझनाहट", "आगे के दाँत का छोटा टूटा किनारा"],
      },
    },
    kids: {
      intro: "Our paediatric dentist sees children from the first tooth to the early teens, on four days a week including Saturday. Visits are short, a parent stays in the room, and prevention comes first.",
      firstVisit: [
        { title: "Book a morning slot", body: "Children are freshest before lunch. Tell us your child's age and any worries.", hi: { title: "सुबह का स्लॉट बुक करें", body: "बच्चे दोपहर से पहले सबसे ताज़ा रहते हैं। बच्चे की उम्र और कोई चिंता बताएँ।" } },
        { title: "Meet the room", body: "Your child rides the chair up and down and meets the mirror and the light.", hi: { title: "कमरे से पहचान", body: "बच्चा कुर्सी को ऊपर-नीचे करता है और शीशे और लाइट से मिलता है।" } },
        { title: "A gentle look", body: "On your lap for toddlers, in the chair for older children.", hi: { title: "हल्की जाँच", body: "छोटे बच्चे आपकी गोद में, बड़े बच्चे कुर्सी पर।" } },
        { title: "A plan for home", body: "Brushing, toothpaste amount and snacks, written down for you.", hi: { title: "घर के लिए योजना", body: "ब्रश, टूथपेस्ट की मात्रा और नाश्ते की बातें, लिखकर दी जाती हैं।" } },
      ],
      ageBands: [
        { title: "Babies (0 to 3)", body: "First visit by the first birthday. Wipe gums, brush the first teeth with a rice-grain smear of fluoride toothpaste, and avoid night-time bottles of milk or juice.", hi: { title: "शिशु (0 से 3)", body: "पहले जन्मदिन तक पहली विज़िट। मसूड़े पोंछें, पहले दाँतों पर चावल के दाने जितना फ़्लोराइड टूथपेस्ट लगाएँ, और रात में दूध या जूस की बोतल से बचें।" } },
        { title: "Children (4 to 8)", body: "Check-ups every six months, fluoride varnish, and sealants when the first adult molars arrive around age six.", hi: { title: "बच्चे (4 से 8)", body: "हर छह महीने चेक-अप, फ़्लोराइड वार्निश, और लगभग छह साल में पहली पक्की दाढ़ आने पर सीलेंट।" } },
        { title: "Pre-teens (9 to 13)", body: "An orthodontic check, sealants on the second molars, and mouthguards for sport.", hi: { title: "किशोरावस्था से पहले (9 से 13)", body: "ऑर्थोडॉन्टिक जाँच, दूसरी दाढ़ों पर सीलेंट, और खेल के लिए माउथगार्ड।" } },
      ],
      prevention: [
        { title: "Fluoride varnish", body: "A quick paint-on coating that strengthens enamel, every six months.", hi: { title: "फ़्लोराइड वार्निश", body: "इनेमल मज़बूत करने वाली जल्दी लगने वाली परत, हर छह महीने।" } },
        { title: "Sealants", body: "A thin coating on the grooves of back teeth, where most cavities start.", hi: { title: "सीलेंट", body: "पीछे के दाँतों की दरारों पर पतली परत, जहाँ ज़्यादातर कीड़े शुरू होते हैं।" } },
        { title: "Snack timing", body: "Sweets with meals rather than between them, and water between meals.", hi: { title: "नाश्ते का समय", body: "मिठाई खाने के साथ, बीच में नहीं, और खाने के बीच पानी।" } },
      ],
      habits: [
        { title: "Thumb sucking", body: "Usually harmless before four. After that we help with gentle reminders and, rarely, an appliance.", hi: { title: "अँगूठा चूसना", body: "चार साल से पहले आमतौर पर नुकसान नहीं। उसके बाद हल्की याद दिलाने से और कभी-कभी एक उपकरण से मदद करते हैं।" } },
        { title: "Night bottle", body: "Milk or juice pooling on teeth overnight causes early decay; switch to water.", hi: { title: "रात की बोतल", body: "रात भर दाँतों पर दूध या जूस रहने से जल्दी कीड़ा लगता है; पानी दें।" } },
        { title: "Mouth breathing", body: "Can affect jaw growth; we check the airway and may refer to an ENT doctor.", hi: { title: "मुँह से साँस लेना", body: "जबड़े के विकास पर असर डाल सकता है; हम जाँच करके ENT डॉक्टर के पास भेज सकते हैं।" } },
      ],
      comfort: [
        { title: "Tell-show-do", body: "We explain in the child's words, show on a finger, then do.", hi: { title: "बताओ-दिखाओ-करो", body: "बच्चे के शब्दों में समझाते हैं, उँगली पर दिखाते हैं, फिर करते हैं।" } },
        { title: "Parent in the room", body: "You can stay close throughout every visit.", hi: { title: "कमरे में माता-पिता", body: "हर विज़िट में आप पूरे समय पास रह सकते हैं।" } },
        { title: "Sedation information", body: "For some children we discuss sedation options with you. We explain the benefits and risks; it is never routine.", hi: { title: "सेडेशन की जानकारी", body: "कुछ बच्चों के लिए हम आपके साथ सेडेशन के विकल्पों पर बात करते हैं। फ़ायदे और जोखिम समझाते हैं; यह कभी सामान्य नहीं होता।" } },
      ],
      specialCare: "Children with autism, ADHD or other special needs are welcome. Tell us when you book and we will plan a quiet, longer slot.",
      parentFaq: [
        { title: "Are dental X-rays safe for my child?", body: "We use low-dose digital X-rays and take them only when they will change what we do.", hi: { title: "क्या डेंटल एक्स-रे मेरे बच्चे के लिए सुरक्षित है?", body: "हम कम डोज़ वाले डिजिटल एक्स-रे इस्तेमाल करते हैं और तभी लेते हैं जब उससे इलाज बदले।" } },
        { title: "My child's adult tooth is coming in behind the milk tooth. Is that a problem?", body: "It is common in lower front teeth. If the milk tooth has not loosened within a few weeks, we remove it.", hi: { title: "पक्का दाँत दूध के दाँत के पीछे आ रहा है। क्या यह समस्या है?", body: "नीचे के आगे के दाँतों में यह आम है। अगर कुछ हफ़्तों में दूध का दाँत ढीला न हो, तो हम निकाल देते हैं।" } },
        { title: "How much toothpaste should I use?", body: "A rice-grain smear under three; a pea-sized amount from three to six.", hi: { title: "कितना टूथपेस्ट लगाएँ?", body: "तीन साल से कम में चावल के दाने जितना; तीन से छह साल में मटर के दाने जितना।" } },
      ],
      hi: {
        intro: "हमारी बच्चों की डेंटिस्ट पहले दाँत से शुरुआती किशोर उम्र तक, शनिवार समेत हफ़्ते में चार दिन बच्चों को देखती हैं। विज़िट छोटी होती हैं, माता-पिता कमरे में रहते हैं, और बचाव पहले आता है।",
        specialCare: "ऑटिज़्म, ADHD या अन्य विशेष ज़रूरतों वाले बच्चों का स्वागत है। बुकिंग के समय बताएँ, हम शांत और लंबा स्लॉट रखेंगे।",
      },
    },
    booking: {
      reasons: [
        { id: "pain", label: "Tooth pain or swelling", icon: "pain", urgent: true, treatment: "root-canal-treatment", hi: { label: "दाँत में दर्द या सूजन" } },
        { id: "checkup", label: "Check-up and cleaning", icon: "checkup", treatment: "teeth-cleaning", hi: { label: "चेक-अप और सफ़ाई" } },
        { id: "implants", label: "Missing tooth or implants", icon: "implant", treatment: "dental-implants", hi: { label: "गायब दाँत या इम्प्लांट" } },
        { id: "root-canal", label: "Root canal", icon: "root-canal", treatment: "root-canal-treatment", hi: { label: "रूट कैनाल" } },
        { id: "braces", label: "Braces", icon: "braces", treatment: "braces", hi: { label: "ब्रेसेज़" } },
        { id: "aligners", label: "Clear aligners", icon: "aligner", treatment: "clear-aligners", hi: { label: "क्लियर अलाइनर" } },
        { id: "whitening", label: "Whitening or smile makeover", icon: "whitening", treatment: "teeth-whitening", hi: { label: "व्हाइटनिंग या स्माइल मेकओवर" } },
        { id: "kids", label: "For my child", icon: "kids", treatment: "kids-dentistry", hi: { label: "बच्चे के लिए" } },
        { id: "wisdom", label: "Wisdom tooth", icon: "wisdom", treatment: "wisdom-tooth-surgery", hi: { label: "अक़्ल दाढ़" } },
        { id: "not-sure", label: "Not sure", icon: "tooth", hi: { label: "पक्का नहीं पता" } },
      ],
      morning: ["10:00 am", "10:30 am", "11:00 am", "11:30 am", "12:00 pm", "12:30 pm", "1:00 pm"],
      evening: ["5:00 pm", "5:30 pm", "6:00 pm", "6:30 pm", "7:00 pm", "7:30 pm", "8:00 pm"],
      closedDays: [],
      closedNote: "Sunday: morning session only, 10 am to 1 pm",
      hi: { closedNote: "रविवार: सिर्फ़ सुबह का सेशन, 10 से दोपहर 1" },
    },
    sessions: [
      { days: [1, 2, 3, 4, 5, 6], from: "10:00", to: "13:30" },
      { days: [1, 2, 3, 4, 5, 6], from: "17:00", to: "20:30" },
      { days: [0], from: "10:00", to: "13:00" },
    ],
    reach: {
      transit: "Five minutes by auto from the nearest metro station; buses stop at the main road junction.",
      parking: "Basement parking for cars; two-wheeler parking at the side entrance.",
      access: "Lift to the second floor; step-free from the basement parking.",
      hi: {
        transit: "सबसे पास के मेट्रो स्टेशन से ऑटो से पाँच मिनट; बसें मुख्य सड़क के चौराहे पर रुकती हैं।",
        parking: "कारों के लिए बेसमेंट पार्किंग; दोपहिया के लिए बगल के गेट पर पार्किंग।",
        access: "दूसरी मंज़िल तक लिफ़्ट; बेसमेंट पार्किंग से बिना सीढ़ी।",
      },
    },
    sterilisation: [
      { title: "Clean", body: "Instruments are scrubbed and run through an ultrasonic cleaner.", hi: { title: "सफ़ाई", body: "औज़ार रगड़कर अल्ट्रासोनिक क्लीनर से साफ़ किए जाते हैं।" } },
      { title: "Pack", body: "Each kit is sealed in a dated pouch with a colour indicator.", hi: { title: "पैक", body: "हर किट रंग बदलने वाले संकेतक के साथ तारीख़ वाले पाउच में सील होती है।" } },
      { title: "Sterilise", body: "Class B autoclave cycles, with a test and a log every day.", hi: { title: "स्टरलाइज़", body: "क्लास B ऑटोक्लेव चक्र, रोज़ जाँच और रिकॉर्ड के साथ।" } },
      { title: "Open at your chair", body: "The pouch is opened in front of you. Gloves, needles and suction tips are single use.", hi: { title: "आपकी कुर्सी पर खोलना", body: "पाउच आपके सामने खोला जाता है। दस्ताने, सुई और सक्शन टिप एक बार ही इस्तेमाल होते हैं।" } },
    ],
    trust: [
      { title: "One plan from the whole team", body: "Complex cases are planned together, with one estimate.", hi: { title: "पूरी टीम की एक योजना", body: "जटिल मामलों की योजना साथ बनती है, एक अनुमान के साथ।" } },
      { title: "Specialists named with their degrees", body: "Every doctor's MDS branch and registration number is listed.", hi: { title: "डिग्री के साथ विशेषज्ञों के नाम", body: "हर डॉक्टर की MDS शाखा और रजिस्ट्रेशन नंबर दिया गया है।" } },
      { title: "Written estimates", body: "You approve the cost before treatment starts.", hi: { title: "लिखित अनुमान", body: "इलाज शुरू होने से पहले आप ख़र्च मंज़ूर करते हैं।" } },
      { title: "Scans shown to you", body: "Your X-ray or 3D scan is explained on screen.", hi: { title: "स्कैन आपको दिखाया जाता है", body: "आपका एक्स-रे या 3D स्कैन स्क्रीन पर समझाया जाता है।" } },
    ],
    comfort: [
      { title: "Local anaesthesia, checked first", body: "We test that the area is numb before we begin.", hi: { title: "लोकल एनेस्थीसिया, पहले जाँच", body: "शुरू करने से पहले जाँचते हैं कि जगह सुन्न है।" } },
      { title: "Breaks when you need them", body: "Raise a hand and we stop.", hi: { title: "जब चाहें तब रुकावट", body: "हाथ उठाएँ और हम रुक जाएँगे।" } },
      { title: "Longer slots for anxious patients", body: "Tell us when you book; we explain each step before doing it.", hi: { title: "घबराने वाले मरीज़ों के लिए लंबा स्लॉट", body: "बुकिंग के समय बताएँ; हम हर क़दम करने से पहले समझाते हैं।" } },
    ],
  },
});
