/**
 * d3-smile-studio: Mogra Smile Studio, Bandra West, Mumbai.
 * A cosmetic smile design studio: veneers, whitening, bonding, aligners and
 * smile makeovers, with a four-step smile journey, a digital preview and a
 * trial smile before any permanent work. International patients welcome.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md. Everything here is fiction: the studio, the doctors,
 * the reviews, the rating, the cases and the trust figures are SAMPLE content
 * and carry the SampleNote label until the clinic replaces them. Cases have
 * no photos: the page draws the illustrative placeholder. Name forms exactly
 * as in TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Mogra Smile Studio",
  shortName: "Mogra",
  tagline: "Veneers, whitening, smile makeovers and clear aligners in Bandra West, Mumbai.",
  city: "Mumbai",
  state: "Maharashtra",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Est. 2011",
  establishedYear: "2011",
  sitePages: [...DENTAL_PAGE_SETS["d3-smile-studio"]],
  heroImage: "/demo/img/dental/hero-sunlit-operatory-800.webp",
  sectionPhotos: { about: "/demo/img/dental/interior-lounge-corridor-640.webp" },
  photos: [
    { src: "/demo/img/dental/hero-reception-lounge-800.webp", alt: "", category: "Studio", caption: "Reception", hi: { category: "स्टूडियो", caption: "रिसेप्शन" } },
    { src: "/demo/img/dental/interior-lounge-corridor-640.webp", alt: "", category: "Studio", caption: "Lounge corridor", hi: { category: "स्टूडियो", caption: "लाउंज गलियारा" } },
    { src: "/demo/img/dental/interior-consult-room-640.webp", alt: "", category: "Studio", caption: "Consultation room", hi: { category: "स्टूडियो", caption: "परामर्श कक्ष" } },
    { src: "/demo/img/dental/interior-garden-operatory-640.webp", alt: "", category: "Studio", caption: "Treatment room with a garden view", hi: { category: "स्टूडियो", caption: "बगीचे की ओर खुलता इलाज का कमरा" } },
  ],
  about:
    "Mogra Smile Studio opened in 2011 in a converted bungalow flat in Bandra West, with one idea: nobody should commit to a new smile without seeing it first. Every cosmetic plan here starts with photographs and a digital design, and moves to a trial smile in your own mouth before a single tooth is prepared.\n\nThe studio is small by choice. Three treatment rooms, one consultation room with a large screen, and a team led by a prosthodontist who plans each smile around the face, the lips and the way you speak, not a catalogue shade. We are just as likely to suggest whitening and bonding as veneers, if that is what your teeth need.",
  mission: "Cosmetic dentistry that is planned, previewed and approved by you before it becomes permanent.",
  vision: "Smiles that look like your own teeth on a good day, not like someone else's.",
  hi: {
    instituteName: "मोगरा स्माइल स्टूडियो",
    shortName: "मोगरा",
    tagline: "वीनियर, व्हाइटनिंग, स्माइल मेकओवर और क्लियर अलाइनर, बांद्रा वेस्ट, मुंबई में।",
    city: "मुंबई",
    state: "महाराष्ट्र",
    established: "स्थापना 2011",
    establishedYear: "2011",
    about:
      "मोगरा स्माइल स्टूडियो 2011 में बांद्रा वेस्ट के एक पुराने बंगले के फ़्लैट में एक सोच के साथ शुरू हुआ: कोई भी नई मुस्कान को पहले देखे बिना उसके लिए हाँ न कहे। यहाँ हर कॉस्मेटिक योजना फ़ोटो और डिजिटल डिज़ाइन से शुरू होती है, और किसी भी दाँत को तैयार करने से पहले आपके अपने मुँह में ट्रायल स्माइल तक जाती है।\n\nस्टूडियो जानबूझकर छोटा है। इलाज के तीन कमरे, बड़ी स्क्रीन वाला एक परामर्श कक्ष, और एक प्रोस्थोडॉन्टिस्ट की अगुवाई वाली टीम जो हर मुस्कान की योजना चेहरे, होंठों और आपके बोलने के तरीक़े के हिसाब से बनाती है, किसी कैटलॉग के रंग से नहीं। अगर आपके दाँतों को यही चाहिए, तो हम वीनियर जितनी ही आसानी से व्हाइटनिंग और बॉन्डिंग भी सुझाते हैं।",
    mission: "ऐसी कॉस्मेटिक डेंटिस्ट्री जिसकी योजना बने, झलक दिखे और स्थायी होने से पहले आप मंज़ूरी दें।",
    vision: "ऐसी मुस्कान जो किसी अच्छे दिन आपके अपने दाँतों जैसी लगे, किसी और की नहीं।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "studio@example.com",
    addressLines: ["Example Road", "Bandra West, Mumbai 400000"],
    hours: "Tue to Sun, 10 am to 7 pm. Closed on Mondays",
    landmark: "Ground floor of a residential bungalow, two lanes from the sea-facing promenade",
    mapQuery: "Bandra West, Mumbai",
    hi: {
      addressLines: ["उदाहरण रोड", "बांद्रा वेस्ट, मुंबई 400000"],
      hours: "मंगल से रवि, सुबह 10 से शाम 7। सोमवार बंद",
      landmark: "एक रिहायशी बंगले का भूतल, समुद्र किनारे के रास्ते से दो गलियाँ दूर",
    },
  },
  stats: [
    { value: "15", label: "Years of smile design", basis: "Since 2011, Bandra West", hi: { label: "साल स्माइल डिज़ाइन के", basis: "2011 से, बांद्रा वेस्ट" } },
    { value: "3", label: "MDS specialists", basis: "Prosthodontics, orthodontics, periodontology", hi: { label: "MDS विशेषज्ञ", basis: "प्रोस्थोडॉन्टिक्स, ऑर्थोडॉन्टिक्स, पेरियोडॉन्टोलॉजी" } },
    { value: "4", label: "Steps to your new smile", basis: "Consult, preview, trial smile, final", hi: { label: "क़दम आपकी नई मुस्कान तक", basis: "परामर्श, झलक, ट्रायल स्माइल, अंतिम" } },
  ],
  rating: { value: "4.9", count: "238", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "I came in asking for veneers on all my front teeth. Dr. Kapadia showed me that whitening and bonding two chipped edges would do what I wanted. It did, for a fraction of the cost.", relation: "Patient, whitening and bonding", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Whitening", hi: { quote: "मैं आगे के सभी दाँतों पर वीनियर माँगने आई थी। डॉ. कपाड़िया ने दिखाया कि व्हाइटनिंग और दो टूटे किनारों की बॉन्डिंग से वही हो जाएगा जो मैं चाहती थी। हुआ भी, बहुत कम ख़र्च में।", relation: "मरीज़, व्हाइटनिंग और बॉन्डिंग", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "व्हाइटनिंग" } },
    { quote: "The trial smile was the reason I went ahead. I wore it for an evening, asked for the canines to be softer, and the final veneers matched that exactly.", relation: "Patient, porcelain veneers", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Veneers", hi: { quote: "ट्रायल स्माइल ही वजह थी कि मैंने आगे बढ़ने का फ़ैसला किया। मैंने उसे एक शाम पहना, कैनाइन थोड़े नरम करने को कहा, और अंतिम वीनियर बिल्कुल वैसे ही बने।", relation: "मरीज़, पोर्सिलेन वीनियर", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "वीनियर" } },
    { quote: "Planned my aligners around my wedding date, with a clear timeline and a check-in every six weeks. Calm studio, never felt rushed.", relation: "Patient, clear aligners", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Aligners", hi: { quote: "मेरी शादी की तारीख़ के हिसाब से अलाइनर की योजना बनी, साफ़ समय-सीमा और हर छह हफ़्ते जाँच के साथ। शांत स्टूडियो, कभी जल्दबाज़ी नहीं लगी।", relation: "मरीज़, क्लियर अलाइनर", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "अलाइनर" } },
    { quote: "Flew in from Dubai for two trips. The video consultation beforehand meant the first visit was already planned to the hour.", relation: "Patient from abroad, smile makeover", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Smile design", hi: { quote: "दुबई से दो बार आया। पहले के वीडियो परामर्श से पहली विज़िट घंटे-घंटे तक पहले से तय थी।", relation: "विदेश से मरीज़, स्माइल मेकओवर", source: "गूगल रिव्यू", date: "जून 2026", category: "स्माइल डिज़ाइन" } },
    { quote: "Honest about what whitening could not do for my crowned tooth. They matched a new crown to the whitened shade afterwards.", relation: "Patient, whitening and crown", rating: "5", source: "Google review", date: "May 2026", consent: true, category: "Whitening", hi: { quote: "उन्होंने ईमानदारी से बताया कि व्हाइटनिंग मेरे क्राउन वाले दाँत के लिए क्या नहीं कर सकती। बाद में सफ़ेद हुए रंग से मिलता नया क्राउन बनाया।", relation: "मरीज़, व्हाइटनिंग और क्राउन", source: "गूगल रिव्यू", date: "मई 2026", category: "व्हाइटनिंग" } },
    { quote: "Beautiful space and a careful team. It is not inexpensive, but every rupee was on the estimate before we began.", relation: "Patient, veneers", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Veneers", hi: { quote: "सुंदर जगह और सावधान टीम। यह सस्ता नहीं है, पर हर रुपया शुरू करने से पहले अनुमान में था।", relation: "मरीज़, वीनियर", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "वीनियर" } },
  ],
  faq: [
    { title: "Do I have to get veneers?", body: "No. Many people get the look they want from whitening, bonding or aligners. We show you each option on your own photos before you decide.", group: "Treatment", hi: { title: "क्या वीनियर ज़रूरी हैं?", body: "नहीं। बहुत से लोगों को मनचाहा रूप व्हाइटनिंग, बॉन्डिंग या अलाइनर से मिल जाता है। फ़ैसले से पहले हम हर विकल्प आपकी अपनी फ़ोटो पर दिखाते हैं।", group: "इलाज" } },
    { title: "What is a trial smile?", body: "A temporary copy of the planned design, placed over your teeth in tooth-coloured material without drilling. You can see it, speak with it and ask for changes before anything is permanent.", group: "Treatment", hi: { title: "ट्रायल स्माइल क्या है?", body: "योजनाबद्ध डिज़ाइन की अस्थायी नक़ल, जो बिना ड्रिल किए दाँत के रंग वाली सामग्री से आपके दाँतों पर लगाई जाती है। स्थायी कुछ भी होने से पहले आप इसे देख सकते हैं, बोलकर परख सकते हैं और बदलाव माँग सकते हैं।", group: "इलाज" } },
    { title: "How much does a smile makeover cost?", body: "It depends on how many teeth are involved and which treatments are used. After the consultation, photos and scan, you get a written estimate for each option. Veneers start from Rs 18,000 per tooth.", group: "Fees", hi: { title: "स्माइल मेकओवर का ख़र्च कितना है?", body: "यह इस पर निर्भर है कि कितने दाँत शामिल हैं और कौन से इलाज होंगे। परामर्श, फ़ोटो और स्कैन के बाद आपको हर विकल्प का लिखित अनुमान मिलता है। वीनियर प्रति दाँत 18,000 रुपये से शुरू।", group: "फ़ीस" } },
    { title: "Is there a consultation fee?", body: "The smile design consultation is Rs 1,500 and includes photographs and a discussion of options. The digital design and trial smile are quoted separately.", group: "Fees", hi: { title: "क्या परामर्श शुल्क है?", body: "स्माइल डिज़ाइन परामर्श 1,500 रुपये का है, जिसमें फ़ोटो और विकल्पों पर चर्चा शामिल है। डिजिटल डिज़ाइन और ट्रायल स्माइल का अनुमान अलग से दिया जाता है।", group: "फ़ीस" } },
    { title: "How long do veneers last?", body: "Porcelain veneers can last many years with good care. Grinding, biting hard objects and gum disease shorten their life. We check them at every hygiene visit.", group: "Treatment", hi: { title: "वीनियर कितने समय चलते हैं?", body: "अच्छी देखभाल से पोर्सिलेन वीनियर कई साल चल सकते हैं। दाँत पीसना, सख़्त चीज़ें काटना और मसूड़ों की बीमारी उनकी उम्र घटाते हैं। हर सफ़ाई विज़िट में हम जाँचते हैं।", group: "इलाज" } },
    { title: "I have a wedding coming up. How early should I start?", body: "Whitening needs about two weeks including a review. Veneers need four to six weeks. Aligners need six months or more. Start with a consultation as early as you can.", group: "Planning", hi: { title: "मेरी शादी आने वाली है। कितना पहले शुरू करूँ?", body: "व्हाइटनिंग में जाँच मिलाकर लगभग दो हफ़्ते लगते हैं। वीनियर में चार से छह हफ़्ते। अलाइनर में छह महीने या ज़्यादा। जितनी जल्दी हो सके, परामर्श से शुरू करें।", group: "योजना" } },
    { title: "Can I pay in instalments?", body: "EMI options may be available through partner lenders, subject to their approval. Larger plans can also be paid in stages as each phase is completed.", group: "Fees", hi: { title: "क्या किस्तों में भुगतान हो सकता है?", body: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर। बड़ी योजनाओं का भुगतान हर चरण पूरा होने पर भी किया जा सकता है।", group: "फ़ीस" } },
    { title: "I live abroad. Can I be treated in one trip?", body: "Whitening and bonding, yes. Veneers usually need two trips or one stay of about ten days. We plan the visits on a video call first.", group: "Planning", hi: { title: "मैं विदेश में रहता हूँ। क्या एक ही यात्रा में इलाज हो सकता है?", body: "व्हाइटनिंग और बॉन्डिंग, हाँ। वीनियर में आमतौर पर दो यात्राएँ या लगभग दस दिन का एक ठहराव लगता है। हम पहले वीडियो कॉल पर विज़िट की योजना बनाते हैं।", group: "योजना" } },
  ],
  posts: [
    {
      slug: "veneers-or-bonding", title: "Veneers or bonding: which suits your teeth", date: "15 Sep 2026", category: "Veneers", treatment: "porcelain-veneers",
      author: "Dr. Rhea Kapadia", reviewedBy: "Medically reviewed by Dr. Rhea Kapadia, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "Both change the shape and colour of front teeth. They differ in how much tooth is prepared, how long they last and what they cost.",
      body: "Composite bonding adds tooth-coloured resin to the tooth by hand, usually with no drilling. It is quick, costs less and can be repaired, but it can stain and chip over the years.\n\nPorcelain veneers are thin ceramic shells made in a lab. The tooth surface is usually reduced by a fraction of a millimetre so the veneer sits flush. They resist staining and keep their polish, but the preparation cannot be undone.\n\nBonding suits small chips, gaps and edges, and younger patients. Veneers suit teeth with deeper discolouration, worn edges or several shape problems at once.\n\nAsk to see both on a digital design of your own face before choosing.",
      hi: {
        title: "वीनियर या बॉन्डिंग: आपके दाँतों के लिए कौन सा ठीक", date: "15 सितंबर 2026", category: "वीनियर", author: "डॉ. रिया कपाड़िया", reviewedBy: "डॉ. रिया कपाड़िया, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "दोनों आगे के दाँतों का आकार और रंग बदलते हैं। फ़र्क़ इसमें है कि दाँत कितना तैयार होता है, ये कितना चलते हैं और कितना ख़र्च होता है।",
        body: "कम्पोज़िट बॉन्डिंग में दाँत पर हाथ से दाँत के रंग का रेज़िन जोड़ा जाता है, आमतौर पर बिना ड्रिल के। यह जल्दी होती है, सस्ती है और मरम्मत हो सकती है, पर सालों में दाग़ लग सकते हैं और टूट सकती है।\n\nपोर्सिलेन वीनियर लैब में बने पतले सिरेमिक खोल हैं। दाँत की सतह आमतौर पर एक मिलीमीटर के अंश जितनी घटाई जाती है ताकि वीनियर बराबर बैठे। इन पर दाग़ कम लगते हैं और चमक बनी रहती है, पर तैयारी वापस नहीं हो सकती।\n\nबॉन्डिंग छोटे टूटे किनारों, गैप और कम उम्र के मरीज़ों के लिए ठीक है। वीनियर गहरे बदरंग, घिसे किनारों या एक साथ कई आकार की समस्याओं वाले दाँतों के लिए ठीक हैं।\n\nचुनने से पहले दोनों को अपने चेहरे के डिजिटल डिज़ाइन पर देखने को कहें।",
      },
    },
    {
      slug: "wedding-smile-timeline", title: "A smile timeline for your wedding", date: "30 Aug 2026", category: "Planning", treatment: "smile-makeover",
      author: "Dr. Rhea Kapadia", reviewedBy: "Medically reviewed by Dr. Rhea Kapadia, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "What to start twelve months, three months and two weeks before the day, and what to leave alone.",
      body: "Twelve months before: a check-up and cleaning, and a consultation if you are thinking of aligners. Straightening takes the longest, so it comes first.\n\nThree to six months before: veneers or crowns, if planned. This leaves time for a trial smile, the final work and any adjustment.\n\nFour to six weeks before: whitening, so the shade has settled and any sensitivity has passed. Replace visible old fillings after whitening, not before, so they match the new shade.\n\nTwo weeks before: a hygiene visit and polish. Nothing new in the final week: this is not the time for a first-ever treatment.",
      hi: {
        title: "शादी के लिए मुस्कान की समय-सारिणी", date: "30 अगस्त 2026", category: "योजना", author: "डॉ. रिया कपाड़िया", reviewedBy: "डॉ. रिया कपाड़िया, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "बारह महीने, तीन महीने और दो हफ़्ते पहले क्या शुरू करें, और किसे न छेड़ें।",
        body: "बारह महीने पहले: चेक-अप और सफ़ाई, और अलाइनर का सोच रहे हों तो परामर्श। दाँत सीधे करने में सबसे ज़्यादा समय लगता है, इसलिए यह पहले आता है।\n\nतीन से छह महीने पहले: योजना हो तो वीनियर या क्राउन। इससे ट्रायल स्माइल, अंतिम काम और किसी भी सुधार का समय मिलता है।\n\nचार से छह हफ़्ते पहले: व्हाइटनिंग, ताकि रंग स्थिर हो जाए और झनझनाहट चली जाए। दिखने वाली पुरानी फ़िलिंग व्हाइटनिंग के बाद बदलें, पहले नहीं, ताकि नए रंग से मिलें।\n\nदो हफ़्ते पहले: सफ़ाई और पॉलिश। आख़िरी हफ़्ते में कुछ नया नहीं: यह पहली बार कोई इलाज कराने का समय नहीं है।",
      },
    },
    {
      slug: "living-with-aligners", title: "Living with clear aligners: the first month", date: "8 Aug 2026", category: "Aligners", treatment: "clear-aligners",
      author: "Dr. Kabir Shetty", reviewedBy: "Medically reviewed by Dr. Kabir Shetty, MDS (Orthodontics and Dentofacial Orthopaedics)",
      excerpt: "The habits that make aligners work, from wearing time to what to drink.",
      body: "Wear time is everything. Aligners move teeth only while they are in, so aim for about 22 hours a day and take them out only to eat and brush.\n\nExpect pressure for a day or two with each new set. It is a sign they are working and it fades.\n\nDrink only plain water with aligners in. Tea, coffee and sugary drinks get trapped against the teeth and stain the trays.\n\nBrush before you put them back in, and rinse the aligners in cool water; hot water can warp them.\n\nKeep the case with you. Most lost aligners are wrapped in a napkin at a restaurant.",
      hi: {
        title: "क्लियर अलाइनर के साथ पहला महीना", date: "8 अगस्त 2026", category: "अलाइनर", author: "डॉ. कबीर शेट्टी", reviewedBy: "डॉ. कबीर शेट्टी, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "वे आदतें जिनसे अलाइनर काम करते हैं, पहनने के समय से लेकर क्या पिएँ तक।",
        body: "पहनने का समय ही सब कुछ है। अलाइनर तभी दाँत खिसकाते हैं जब लगे हों, इसलिए दिन में लगभग 22 घंटे पहनें और सिर्फ़ खाने और ब्रश के लिए निकालें।\n\nहर नए सेट के साथ एक-दो दिन दबाव की उम्मीद रखें। यह इस बात का संकेत है कि वे काम कर रहे हैं, और यह चला जाता है।\n\nअलाइनर लगे हों तो सिर्फ़ सादा पानी पिएँ। चाय, कॉफ़ी और मीठे पेय दाँतों से सटकर फँस जाते हैं और ट्रे पर दाग़ लगाते हैं।\n\nवापस लगाने से पहले ब्रश करें, और अलाइनर ठंडे पानी से धोएँ; गरम पानी से वे टेढ़े हो सकते हैं।\n\nकेस साथ रखें। ज़्यादातर अलाइनर रेस्टोरेंट में नैपकिन में लिपटे खो जाते हैं।",
      },
    },
  ],
  dental: {
    legalName: "Mogra Aesthetic Dentistry LLP (sample)",
    hi: { legalName: "मोगरा एस्थेटिक डेंटिस्ट्री LLP (नमूना)" },
    hero: {
      variant: "luxury-centred",
      pill: "Smile design studio, Bandra West",
      headline: "Your *smile journey* starts here",
      lead: "Veneers, whitening, smile makeovers and clear aligners in Bandra West, Mumbai, previewed on your own face first.",
      credential: "Dr. Rhea Kapadia, BDS, MDS (Prosthodontics and Crown and Bridge)",
      hi: {
        pill: "स्माइल डिज़ाइन स्टूडियो, बांद्रा वेस्ट",
        headline: "आपकी *मुस्कान का सफ़र* यहाँ से शुरू होता है",
        lead: "वीनियर, व्हाइटनिंग, स्माइल मेकओवर और क्लियर अलाइनर, बांद्रा वेस्ट, मुंबई में, पहले आपके अपने चेहरे पर झलक के साथ।",
        credential: "डॉ. रिया कपाड़िया, BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज)",
      },
    },
    doctors: [
      {
        slug: "rhea-kapadia", name: "Dr. Rhea Kapadia", photo: "/demo/img/people/dentist-w04-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Prosthodontics and Crown and Bridge)", specialisation: "Prosthodontist",
        focus: "Smile design, porcelain veneers, all-ceramic crowns, full smile makeovers", experience: "16 years in practice",
        languages: ["English", "Hindi", "Gujarati", "Marathi"], regNo: "Reg. no. A-00000 (sample)", days: "Tue to Sat",
        bio: "Dr. Rhea Kapadia founded the studio in 2011. She trained as a prosthodontist, the specialty that rebuilds and replaces teeth, and spends most of her time on smile design: veneers, ceramic crowns and makeovers that combine several treatments.\n\nShe plans every smile from photographs of the whole face, not only the teeth, and will not prepare a tooth until the patient has worn and approved a trial smile. Patients often hear her suggest the smaller option first.",
        quote: "The compliment I value most is when nobody can tell which teeth we worked on.",
        training: ["BDS, 2006 (sample)", "MDS, Prosthodontics and Crown and Bridge, 2010 (sample)", "Digital smile design course, 2015 (sample)", "Ceramic veneers course, 2018 (sample)"],
        memberships: ["Indian Prosthodontic Society (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. रिया कपाड़िया", qualification: "BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज)", specialisation: "प्रोस्थोडॉन्टिस्ट",
          focus: "स्माइल डिज़ाइन, पोर्सिलेन वीनियर, पूरे सिरेमिक क्राउन, पूरा स्माइल मेकओवर", experience: "16 साल का अनुभव",
          languages: ["अंग्रेज़ी", "हिंदी", "गुजराती", "मराठी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल से शनि",
          bio: "डॉ. रिया कपाड़िया ने 2011 में स्टूडियो शुरू किया। उन्होंने प्रोस्थोडॉन्टिस्ट की पढ़ाई की, जो दाँतों को फिर से बनाने और बदलने की विशेषज्ञता है, और उनका ज़्यादातर समय स्माइल डिज़ाइन में जाता है: वीनियर, सिरेमिक क्राउन और कई इलाजों को मिलाने वाले मेकओवर।\n\nवे हर मुस्कान की योजना सिर्फ़ दाँतों की नहीं, पूरे चेहरे की फ़ोटो से बनाती हैं, और जब तक मरीज़ ट्रायल स्माइल पहनकर मंज़ूरी न दे, कोई दाँत तैयार नहीं करतीं। मरीज़ अक्सर उन्हें पहले छोटा विकल्प सुझाते सुनते हैं।",
          quote: "मुझे सबसे प्यारी तारीफ़ तब लगती है जब कोई बता न सके कि हमने किन दाँतों पर काम किया।",
          training: ["BDS, 2006 (नमूना)", "MDS, प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज, 2010 (नमूना)", "डिजिटल स्माइल डिज़ाइन कोर्स, 2015 (नमूना)", "सिरेमिक वीनियर कोर्स, 2018 (नमूना)"],
          memberships: ["इंडियन प्रोस्थोडॉन्टिक सोसाइटी (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "kabir-shetty", name: "Dr. Kabir Shetty", photo: "/demo/img/people/dentist-m06-240.webp", gender: "male",
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist",
        focus: "Clear aligners, ceramic braces, alignment before veneers", experience: "12 years in practice",
        languages: ["English", "Hindi", "Kannada", "Tulu"], regNo: "Reg. no. A-00000 (sample)", days: "Wed, Fri and Sun",
        bio: "Dr. Kabir Shetty is the studio's orthodontist. Many smile makeovers start with him, because moving a tooth a few millimetres with aligners can mean a veneer is not needed at all, or needs far less preparation.\n\nHe plans aligner cases on a 3D scan and shows patients the predicted movement stage by stage before they commit.",
        quote: "Move the tooth first. Then see if you still want to change it.",
        training: ["BDS, 2009 (sample)", "MDS, Orthodontics and Dentofacial Orthopaedics, 2014 (sample)"],
        memberships: ["Indian Orthodontic Society (sample)"],
        hi: {
          name: "डॉ. कबीर शेट्टी", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट",
          focus: "क्लियर अलाइनर, सिरेमिक ब्रेसेज़, वीनियर से पहले सीध", experience: "12 साल का अनुभव",
          languages: ["अंग्रेज़ी", "हिंदी", "कन्नड़", "तुलु"], regNo: "रजि. नं. A-00000 (नमूना)", days: "बुध, शुक्र और रवि",
          bio: "डॉ. कबीर शेट्टी स्टूडियो के ऑर्थोडॉन्टिस्ट हैं। कई स्माइल मेकओवर उनसे शुरू होते हैं, क्योंकि अलाइनर से दाँत को कुछ मिलीमीटर खिसकाने का मतलब हो सकता है कि वीनियर की ज़रूरत ही न पड़े, या बहुत कम तैयारी लगे।\n\nवे अलाइनर की योजना 3D स्कैन पर बनाते हैं और मरीज़ के फ़ैसले से पहले अनुमानित हलचल चरण-दर-चरण दिखाते हैं।",
          quote: "पहले दाँत खिसकाइए। फिर देखिए कि क्या अब भी उसे बदलना चाहते हैं।",
          training: ["BDS, 2009 (नमूना)", "MDS, ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स, 2014 (नमूना)"],
          memberships: ["इंडियन ऑर्थोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "anaya-fernandes", name: "Dr. Anaya Fernandes", photo: "/demo/img/people/dentist-w03-240.webp", gender: "female",
        qualification: "BDS, MDS (Periodontology)", specialisation: "Periodontist", focus: "Gum contouring, gum health before cosmetic work, hygiene programme",
        experience: "10 years in practice", languages: ["English", "Hindi", "Konkani", "Marathi"], regNo: "Reg. no. A-00000 (sample)", days: "Tue, Thu and Sat",
        hi: { name: "डॉ. अनाया फ़र्नांडिस", qualification: "BDS, MDS (पेरियोडॉन्टोलॉजी)", specialisation: "पेरियोडॉन्टिस्ट", focus: "मसूड़ों का आकार सुधारना, कॉस्मेटिक काम से पहले मसूड़ों की सेहत, सफ़ाई कार्यक्रम", experience: "10 साल का अनुभव", languages: ["अंग्रेज़ी", "हिंदी", "कोंकणी", "मराठी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल, गुरु और शनि" },
      },
      {
        slug: "vivaan-mehra", name: "Dr. Vivaan Mehra", photo: "/demo/img/people/dentist-m04-240.webp", gender: "male",
        qualification: "BDS", specialisation: "General dentist", focus: "Composite bonding, whitening, check-ups and hygiene",
        experience: "6 years in practice", languages: ["English", "Hindi", "Punjabi"], regNo: "Reg. no. A-00000 (sample)", days: "Tue to Sun",
        hi: { name: "डॉ. विवान मेहरा", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "कम्पोज़िट बॉन्डिंग, व्हाइटनिंग, चेक-अप और सफ़ाई", experience: "6 साल का अनुभव", languages: ["अंग्रेज़ी", "हिंदी", "पंजाबी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल से रवि" },
      },
    ],
    journey: [
      { title: "Consultation", body: "We listen to what you would like to change, examine your teeth and gums, and take photographs.", hi: { title: "परामर्श", body: "आप क्या बदलना चाहते हैं, हम सुनते हैं, दाँत और मसूड़ों की जाँच करते हैं, और फ़ोटो लेते हैं।" } },
      { title: "Digital preview", body: "A smile design on your own photographs, with options and a written estimate for each.", hi: { title: "डिजिटल झलक", body: "आपकी अपनी फ़ोटो पर स्माइल डिज़ाइन, विकल्पों और हर एक के लिखित अनुमान के साथ।" } },
      { title: "Trial smile", body: "The design copied onto your teeth in temporary material, without drilling, to see, speak with and adjust.", hi: { title: "ट्रायल स्माइल", body: "बिना ड्रिल किए डिज़ाइन की अस्थायी नक़ल आपके दाँतों पर, देखने, बोलकर परखने और सुधारने के लिए।" } },
      { title: "Final smile", body: "Whitening, bonding, aligners or veneers made to the approved design, then a review after two weeks.", hi: { title: "अंतिम मुस्कान", body: "मंज़ूर डिज़ाइन के अनुसार व्हाइटनिंग, बॉन्डिंग, अलाइनर या वीनियर, फिर दो हफ़्ते बाद जाँच।" } },
    ],
    treatments: [
      {
        slug: "smile-makeover", name: "Smile makeover", category: "Smile design", icon: "smile", image: "/demo/img/dental/patient-older-woman-talk-640.webp", featured: true, reason: "veneers",
        summary: "A plan that combines whitening, bonding, aligners or veneers, designed on your face and tried in before it is made.",
        what: "A smile makeover is not one treatment but a plan. We look at the shape, colour, length and alignment of the front teeth against your lips and face, then combine the fewest treatments that get you there. You see the design on your photographs, then wear it as a trial smile, before anything permanent is done.",
        symptoms: ["Uneven, worn or chipped front teeth", "Gaps, or teeth of different lengths", "Old fillings or crowns that no longer match"],
        whoNeedsIt: ["Adults with healthy gums and a stable bite", "People preparing for a wedding or a public role, with time to plan"],
        steps: [
          { title: "Photos and records", body: "Face and smile photos, a 3D scan and a gum check.", hi: { title: "फ़ोटो और रिकॉर्ड", body: "चेहरे और मुस्कान की फ़ोटो, 3D स्कैन और मसूड़ों की जाँच।" } },
          { title: "Design and estimate", body: "Options drawn on your photos, each with a written estimate.", hi: { title: "डिज़ाइन और अनुमान", body: "आपकी फ़ोटो पर विकल्प, हर एक के लिखित अनुमान के साथ।" } },
          { title: "Trial smile", body: "The design placed over your teeth to approve or change.", hi: { title: "ट्रायल स्माइल", body: "मंज़ूरी या बदलाव के लिए डिज़ाइन आपके दाँतों पर।" } },
          { title: "Treatment and review", body: "The agreed treatments, then a two-week review.", hi: { title: "इलाज और जाँच", body: "तय इलाज, फिर दो हफ़्ते बाद जाँच।" } },
        ],
        duration: "2 weeks to 8 months, depending on the plan", visits: "3 to 6 visits", recovery: "A few days to get used to new tooth shapes. Sensitivity after whitening passes in a day or two.",
        comfort: "Any tooth preparation is done under local anaesthesia. We keep preparation to the least the design needs.",
        faqs: [
          { title: "Will it look natural?", body: "That is the brief for every design. The trial smile lets you judge it in daylight, speaking and smiling, before you commit.", hi: { title: "क्या यह प्राकृतिक दिखेगा?", body: "हर डिज़ाइन का यही लक्ष्य है। ट्रायल स्माइल से आप फ़ैसले से पहले दिन की रोशनी में, बोलते और मुस्कुराते हुए इसे परख सकते हैं।" } },
          { title: "Can I do it in stages?", body: "Yes. Many plans start with aligners or whitening and add bonding or veneers later.", hi: { title: "क्या यह चरणों में हो सकता है?", body: "हाँ। कई योजनाएँ अलाइनर या व्हाइटनिंग से शुरू होकर बाद में बॉन्डिंग या वीनियर जोड़ती हैं।" } },
        ],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "स्माइल मेकओवर", category: "स्माइल डिज़ाइन",
          summary: "व्हाइटनिंग, बॉन्डिंग, अलाइनर या वीनियर को मिलाने वाली योजना, आपके चेहरे पर डिज़ाइन और बनने से पहले ट्रायल के साथ।",
          what: "स्माइल मेकओवर एक इलाज नहीं, एक योजना है। हम आगे के दाँतों का आकार, रंग, लंबाई और सीध आपके होंठों और चेहरे के साथ देखते हैं, फिर सबसे कम इलाज मिलाते हैं जो वहाँ तक पहुँचाएँ। स्थायी कुछ भी होने से पहले आप डिज़ाइन अपनी फ़ोटो पर देखते हैं, फिर उसे ट्रायल स्माइल के रूप में पहनते हैं।",
          symptoms: ["असमान, घिसे या टूटे आगे के दाँत", "गैप, या अलग-अलग लंबाई के दाँत", "पुरानी फ़िलिंग या क्राउन जो अब मेल नहीं खाते"],
          whoNeedsIt: ["स्वस्थ मसूड़ों और स्थिर काटने वाले वयस्क", "शादी या सार्वजनिक भूमिका की तैयारी करने वाले, योजना के समय के साथ"],
          duration: "योजना के अनुसार 2 हफ़्ते से 8 महीने", visits: "3 से 6 विज़िट", recovery: "नए आकार की आदत में कुछ दिन। व्हाइटनिंग के बाद की झनझनाहट एक-दो दिन में जाती है।",
          comfort: "दाँत की कोई भी तैयारी लोकल एनेस्थीसिया में होती है। हम डिज़ाइन की ज़रूरत से ज़्यादा घिसाई नहीं करते।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "porcelain-veneers", name: "Porcelain veneers", category: "Veneers and bonding", icon: "veneer", image: "/demo/img/dental/implant-ceramic-crowns-640.webp", featured: true, reason: "veneers",
        summary: "Thin ceramic shells bonded to the front of the teeth to change their shape and shade.",
        what: "A porcelain veneer is a thin layer of ceramic, made in a lab and bonded to the front of a tooth. It can change colour, shape and length together, and it resists staining. The tooth surface is usually reduced by a fraction of a millimetre, which cannot be reversed, so we plan veneers only after a trial smile.",
        symptoms: ["Deep discolouration that whitening cannot lift", "Worn or chipped edges on several teeth", "Small gaps or uneven shapes"],
        whoNeedsIt: ["Adults with healthy gums and enough enamel", "Not suited to heavy grinders without a night guard"],
        steps: [
          { title: "Trial smile", body: "The planned shape tried on first.", hi: { title: "ट्रायल स्माइल", body: "पहले योजनाबद्ध आकार आज़माया जाता है।" } },
          { title: "Prepare and scan", body: "Minimal preparation under local anaesthesia; temporaries fitted.", hi: { title: "तैयारी और स्कैन", body: "लोकल एनेस्थीसिया में न्यूनतम तैयारी; अस्थायी वीनियर लगाए जाते हैं।" } },
          { title: "Bond", body: "The veneers are checked in daylight, then bonded.", hi: { title: "चिपकाना", body: "वीनियर दिन की रोशनी में जाँचकर चिपकाए जाते हैं।" } },
        ],
        duration: "2 to 3 weeks", visits: "3 visits", recovery: "Mild sensitivity for a few days; you can eat normally from the next day.",
        comfort: "Preparation is done under local anaesthesia. Temporary veneers cover the teeth in between.",
        faqs: [{ title: "Do veneers damage my teeth?", body: "They need a thin layer of enamel removed, which is permanent. Planned conservatively, the tooth underneath stays healthy.", hi: { title: "क्या वीनियर दाँतों को नुकसान करते हैं?", body: "इनके लिए इनेमल की पतली परत हटानी पड़ती है, जो स्थायी है। सावधानी से योजना बने तो नीचे का दाँत स्वस्थ रहता है।" } }],
        fromPrice: "18,000", priceNote: "per tooth",
        hi: {
          name: "पोर्सिलेन वीनियर", category: "वीनियर और बॉन्डिंग",
          summary: "दाँतों के आगे चिपकाए जाने वाले पतले सिरेमिक खोल, आकार और रंग बदलने के लिए।",
          what: "पोर्सिलेन वीनियर सिरेमिक की पतली परत है, जो लैब में बनकर दाँत के आगे चिपकाई जाती है। यह रंग, आकार और लंबाई एक साथ बदल सकता है, और इस पर दाग़ कम लगते हैं। दाँत की सतह आमतौर पर एक मिलीमीटर के अंश जितनी घटाई जाती है, जो वापस नहीं हो सकती, इसलिए हम वीनियर की योजना सिर्फ़ ट्रायल स्माइल के बाद बनाते हैं।",
          symptoms: ["गहरा बदरंगपन जिसे व्हाइटनिंग न हटा सके", "कई दाँतों के घिसे या टूटे किनारे", "छोटे गैप या असमान आकार"],
          whoNeedsIt: ["स्वस्थ मसूड़ों और पर्याप्त इनेमल वाले वयस्क", "बिना नाइट गार्ड के बहुत दाँत पीसने वालों के लिए ठीक नहीं"],
          duration: "2 से 3 हफ़्ते", visits: "3 विज़िट", recovery: "कुछ दिन हल्की झनझनाहट; अगले दिन से सामान्य खाना।",
          comfort: "तैयारी लोकल एनेस्थीसिया में होती है। बीच में अस्थायी वीनियर दाँतों को ढकते हैं।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "teeth-whitening", name: "Teeth whitening", category: "Whitening", icon: "whitening", image: "/demo/img/dental/patient-laugh-room-640.webp", featured: true, reason: "whitening",
        summary: "In-studio whitening with custom take-home trays, after a check and a clean.",
        what: "We combine one in-studio session with custom-fitted trays for a few nights at home, which gives a more even and stable shade than either alone. Your starting shade is recorded, and we tell you honestly if crowns or fillings will need matching afterwards.",
        symptoms: ["Yellowing or dullness", "Stains from tea, coffee or smoking"],
        whoNeedsIt: ["Adults with healthy teeth and gums", "Not in pregnancy or while breastfeeding"],
        steps: [
          { title: "Check, clean and record", body: "Gums checked, teeth polished, shade photographed.", hi: { title: "जाँच, सफ़ाई और रिकॉर्ड", body: "मसूड़ों की जाँच, दाँतों की पॉलिश, रंग की फ़ोटो।" } },
          { title: "In-studio session", body: "Gums protected, gel applied in rounds for about an hour.", hi: { title: "स्टूडियो सेशन", body: "मसूड़े सुरक्षित, लगभग एक घंटे में कई बार जेल।" } },
          { title: "Home trays", body: "Custom trays and gel for 5 to 7 nights, then a review.", hi: { title: "घर की ट्रे", body: "5 से 7 रातों के लिए कस्टम ट्रे और जेल, फिर जाँच।" } },
        ],
        duration: "About 2 weeks", visits: "2 visits", recovery: "Sensitivity for a day or two is common and passes.",
        comfort: "No anaesthetic is needed. A desensitising gel is applied after the session.",
        faqs: [{ title: "How long does whitening last?", body: "Often one to three years, depending on tea, coffee and smoking. A few nights with your trays tops it up.", hi: { title: "व्हाइटनिंग कितने समय चलती है?", body: "अक्सर एक से तीन साल, चाय, कॉफ़ी और धूम्रपान पर निर्भर। ट्रे के साथ कुछ रातें इसे फिर ताज़ा कर देती हैं।" } }],
        fromPrice: "15,000", priceNote: "in-studio plus home trays",
        hi: {
          name: "दाँत सफ़ेद करना", category: "व्हाइटनिंग",
          summary: "जाँच और सफ़ाई के बाद स्टूडियो में व्हाइटनिंग, घर के लिए कस्टम ट्रे के साथ।",
          what: "हम स्टूडियो के एक सेशन को कुछ रातों तक घर पर पहनी जाने वाली कस्टम ट्रे के साथ मिलाते हैं, जिससे अकेले किसी एक से ज़्यादा समान और टिकाऊ रंग मिलता है। आपका शुरुआती रंग दर्ज होता है, और अगर बाद में क्राउन या फ़िलिंग का मिलान करना पड़े तो हम ईमानदारी से बताते हैं।",
          symptoms: ["पीलापन या फीकापन", "चाय, कॉफ़ी या धूम्रपान के दाग़"],
          whoNeedsIt: ["स्वस्थ दाँत और मसूड़ों वाले वयस्क", "गर्भावस्था या स्तनपान के दौरान नहीं"],
          duration: "लगभग 2 हफ़्ते", visits: "2 विज़िट", recovery: "एक-दो दिन झनझनाहट आम है और चली जाती है।",
          comfort: "सुन्न करने की ज़रूरत नहीं। सेशन के बाद झनझनाहट कम करने वाला जेल लगाया जाता है।", priceNote: "स्टूडियो सेशन और घर की ट्रे",
        },
      },
      {
        slug: "clear-aligners", name: "Clear aligners", category: "Aligners", icon: "aligner", image: "/demo/img/dental/doctor-aligner-smile-640.webp", featured: true, reason: "aligners",
        summary: "Nearly invisible trays that straighten teeth, often as the first step of a smile plan.",
        what: "Clear aligners move teeth gradually with a series of custom trays, each worn for one to two weeks. In a cosmetic plan they often come first: straighter teeth may need no veneers at all, or far thinner ones. Our orthodontist shows the predicted movement on a 3D model before you start.",
        symptoms: ["Crowding or rotated front teeth", "Small gaps", "Relapse after braces in the past"],
        whoNeedsIt: ["Adults and older teens who will wear them about 22 hours a day"],
        steps: [
          { title: "Scan and plan", body: "An intraoral scan and a 3D movement plan to review with you.", hi: { title: "स्कैन और योजना", body: "इंट्राओरल स्कैन और आपके साथ देखने के लिए 3D हलचल योजना।" } },
          { title: "Wear", body: "A new set every 1 to 2 weeks; check-ins every 6 to 8 weeks.", hi: { title: "पहनना", body: "हर 1 से 2 हफ़्ते नया सेट; हर 6 से 8 हफ़्ते जाँच।" } },
          { title: "Retain", body: "Retainers at night to hold the result.", hi: { title: "रिटेनर", body: "नतीजा बनाए रखने के लिए रात में रिटेनर।" } },
        ],
        duration: "Usually 6 to 14 months for cosmetic cases", visits: "A review every 6 to 8 weeks", recovery: "Pressure for a day or two with each new set.",
        comfort: "No wires or brackets. Small tooth-coloured attachments may be added for grip.",
        faqs: [{ title: "Can I start aligners before veneers?", body: "Often that is the better order. Aligning first can reduce how much tooth a veneer needs.", hi: { title: "क्या वीनियर से पहले अलाइनर शुरू कर सकते हैं?", body: "अक्सर यही बेहतर क्रम है। पहले सीध से वीनियर के लिए दाँत कम घिसना पड़ सकता है।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "क्लियर अलाइनर", category: "अलाइनर",
          summary: "लगभग न दिखने वाली ट्रे जो दाँत सीधे करती हैं, अक्सर स्माइल योजना का पहला क़दम।",
          what: "क्लियर अलाइनर कस्टम ट्रे की श्रृंखला से दाँत धीरे-धीरे खिसकाते हैं, हर एक एक-दो हफ़्ते पहना जाता है। कॉस्मेटिक योजना में ये अक्सर पहले आते हैं: सीधे दाँतों को वीनियर की ज़रूरत ही न पड़े, या बहुत पतले चाहिए हों। शुरू करने से पहले हमारे ऑर्थोडॉन्टिस्ट 3D मॉडल पर अनुमानित हलचल दिखाते हैं।",
          symptoms: ["भीड़ वाले या घूमे हुए आगे के दाँत", "छोटे गैप", "पहले के ब्रेसेज़ के बाद दाँत वापस खिसकना"],
          whoNeedsIt: ["वयस्क और बड़े किशोर जो इन्हें दिन में लगभग 22 घंटे पहनेंगे"],
          duration: "कॉस्मेटिक मामलों में आमतौर पर 6 से 14 महीने", visits: "हर 6 से 8 हफ़्ते में जाँच", recovery: "हर नए सेट के साथ एक-दो दिन दबाव।",
          comfort: "कोई तार या ब्रैकेट नहीं। पकड़ के लिए छोटे दाँत के रंग के अटैचमेंट लग सकते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "composite-bonding", name: "Composite bonding", category: "Veneers and bonding", icon: "filling", image: "/demo/img/dental/doctor-lamp-adjust-640.webp", reason: "veneers",
        summary: "Tooth-coloured resin sculpted by hand to repair chips, close small gaps and even out edges.",
        what: "Bonding adds composite resin to the tooth and shapes it by hand, usually without drilling or anaesthetic. It is a quick, reversible way to fix small chips, gaps and uneven edges, and it can be polished or repaired later.",
        symptoms: ["A chipped front tooth", "A small gap between front teeth", "Slightly uneven edges"],
        whoNeedsIt: ["People who want a conservative change", "Younger adults not ready for veneers"],
        steps: [
          { title: "Shade match", body: "Layers of composite chosen to match your enamel.", hi: { title: "रंग मिलान", body: "आपके इनेमल से मिलती कम्पोज़िट की परतें चुनी जाती हैं।" } },
          { title: "Sculpt", body: "Resin shaped by hand and set with light.", hi: { title: "आकार देना", body: "रेज़िन को हाथ से आकार देकर लाइट से सख़्त किया जाता है।" } },
          { title: "Polish", body: "Polished to a natural lustre.", hi: { title: "पॉलिश", body: "प्राकृतिक चमक तक पॉलिश।" } },
        ],
        duration: "One visit", visits: "1 visit of 45 to 90 minutes", recovery: "None. Avoid strongly coloured food for 48 hours.",
        comfort: "Usually no drilling and no anaesthetic.",
        faqs: [{ title: "Will bonding stain?", body: "Composite can pick up stain over the years. A polish at your hygiene visits keeps it bright.", hi: { title: "क्या बॉन्डिंग पर दाग़ लगेंगे?", body: "सालों में कम्पोज़िट पर दाग़ लग सकते हैं। सफ़ाई विज़िट की पॉलिश से यह चमकदार रहती है।" } }],
        fromPrice: "6,000", priceNote: "per tooth",
        hi: {
          name: "कम्पोज़िट बॉन्डिंग", category: "वीनियर और बॉन्डिंग",
          summary: "टूटे किनारे, छोटे गैप और असमान किनारों के लिए हाथ से आकार दिया गया दाँत के रंग का रेज़िन।",
          what: "बॉन्डिंग में दाँत पर कम्पोज़िट रेज़िन जोड़कर हाथ से आकार दिया जाता है, आमतौर पर बिना ड्रिल या सुन्न किए। छोटे टूटे किनारे, गैप और असमान किनारे ठीक करने का यह जल्दी और वापस हो सकने वाला तरीक़ा है, और बाद में पॉलिश या मरम्मत हो सकती है।",
          symptoms: ["टूटा आगे का दाँत", "आगे के दाँतों के बीच छोटा गैप", "थोड़े असमान किनारे"],
          whoNeedsIt: ["जो कम से कम बदलाव चाहते हैं", "कम उम्र के वयस्क जो अभी वीनियर के लिए तैयार नहीं"],
          duration: "एक विज़िट", visits: "45 से 90 मिनट की 1 विज़िट", recovery: "कुछ नहीं। 48 घंटे गहरे रंग वाला खाना न लें।",
          comfort: "आमतौर पर न ड्रिल, न सुन्न करना।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "gum-contouring", name: "Gum contouring", category: "Smile design", icon: "gum", image: "/demo/img/dental/interior-garden-operatory-640.webp", reason: "not-sure",
        summary: "Reshaping an uneven or high gum line so teeth look evenly proportioned.",
        what: "When the gum covers too much of some teeth, or sits unevenly, the teeth can look short or crooked. Our periodontist reshapes the gum line under local anaesthesia, often with a soft-tissue laser, and plans it together with any veneers.",
        symptoms: ["A gummy smile", "Teeth that look short", "An uneven gum line"],
        whoNeedsIt: ["Adults with healthy gums and bone levels checked on X-ray"],
        steps: [
          { title: "Measure", body: "Gum and bone levels checked on X-ray and probing.", hi: { title: "नाप", body: "एक्स-रे और जाँच से मसूड़े और हड्डी का स्तर।" } },
          { title: "Reshape", body: "Under local anaesthesia, usually with a laser.", hi: { title: "आकार सुधार", body: "लोकल एनेस्थीसिया में, आमतौर पर लेज़र से।" } },
          { title: "Heal", body: "A review after one to two weeks.", hi: { title: "भरना", body: "एक-दो हफ़्ते बाद जाँच।" } },
        ],
        duration: "One visit, plus a review", visits: "1 visit of about an hour", recovery: "Gums are tender for a few days; they settle fully in a few weeks.",
        comfort: "Done under local anaesthesia.",
        faqs: [{ title: "Will the gum grow back?", body: "Planned to your bone level, the new gum line usually stays stable.", hi: { title: "क्या मसूड़ा वापस बढ़ेगा?", body: "हड्डी के स्तर के हिसाब से योजना बने तो नई मसूड़ा रेखा आमतौर पर स्थिर रहती है।" } }],
        fromPrice: "8,000", priceNote: "per arch segment",
        hi: {
          name: "मसूड़ों का आकार सुधारना", category: "स्माइल डिज़ाइन",
          summary: "असमान या ऊँची मसूड़ा रेखा का आकार सुधारना ताकि दाँत बराबर अनुपात में दिखें।",
          what: "जब मसूड़ा कुछ दाँतों को ज़्यादा ढकता है या असमान होता है, तो दाँत छोटे या टेढ़े दिख सकते हैं। हमारे पेरियोडॉन्टिस्ट लोकल एनेस्थीसिया में, अक्सर सॉफ़्ट-टिश्यू लेज़र से, मसूड़ा रेखा का आकार सुधारते हैं और इसकी योजना किसी भी वीनियर के साथ बनाते हैं।",
          symptoms: ["मुस्कुराने पर ज़्यादा मसूड़ा दिखना", "छोटे दिखते दाँत", "असमान मसूड़ा रेखा"],
          whoNeedsIt: ["स्वस्थ मसूड़ों वाले वयस्क, एक्स-रे पर हड्डी के स्तर की जाँच के बाद"],
          duration: "एक विज़िट, और एक जाँच", visits: "लगभग एक घंटे की 1 विज़िट", recovery: "कुछ दिन मसूड़े नाज़ुक; कुछ हफ़्तों में पूरी तरह ठीक।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है।", priceNote: "प्रति जबड़े के हिस्से",
        },
      },
      {
        slug: "all-ceramic-crowns", name: "All-ceramic crowns", category: "Veneers and bonding", icon: "crown", image: "/demo/img/dental/implant-crown-640.webp", reason: "not-sure",
        summary: "Metal-free crowns shade-matched in daylight, for broken or darkened front teeth.",
        what: "When a front tooth is heavily filled, root-canal treated or broken, a veneer is not enough and a full crown is needed. All-ceramic crowns have no metal, so they let light through like enamel and show no grey line at the gum.",
        symptoms: ["A darkened root-canal-treated front tooth", "A large failing filling", "An old crown with a dark edge at the gum"],
        whoNeedsIt: ["Adults needing a front tooth rebuilt to match its neighbours"],
        steps: [
          { title: "Prepare", body: "Tooth shaped under local anaesthesia; temporary crown fitted.", hi: { title: "तैयारी", body: "लोकल एनेस्थीसिया में दाँत को आकार; अस्थायी क्राउन।" } },
          { title: "Match", body: "Scan and shade photos for the ceramist.", hi: { title: "मिलान", body: "सिरेमिस्ट के लिए स्कैन और रंग की फ़ोटो।" } },
          { title: "Fit", body: "Checked in daylight, then bonded.", hi: { title: "फ़िटिंग", body: "दिन की रोशनी में जाँच, फिर चिपकाना।" } },
        ],
        duration: "7 to 10 days", visits: "2 to 3 visits", recovery: "Your bite settles within a few days.",
        comfort: "Preparation is done under local anaesthesia.",
        faqs: [{ title: "Crown or veneer?", body: "A veneer covers the front; a crown covers the whole tooth. We choose by how much healthy tooth is left.", hi: { title: "क्राउन या वीनियर?", body: "वीनियर आगे का हिस्सा ढकता है; क्राउन पूरा दाँत। कितना स्वस्थ दाँत बचा है, उससे चुनते हैं।" } }],
        fromPrice: "14,000", priceNote: "per crown",
        hi: {
          name: "पूरे सिरेमिक क्राउन", category: "वीनियर और बॉन्डिंग",
          summary: "टूटे या काले पड़े आगे के दाँतों के लिए बिना धातु के क्राउन, दिन की रोशनी में रंग मिलाकर।",
          what: "जब आगे का दाँत बहुत भरा, रूट कैनाल हुआ या टूटा हो, तो वीनियर काफ़ी नहीं होता और पूरा क्राउन चाहिए। पूरे सिरेमिक क्राउन में धातु नहीं होती, इसलिए ये इनेमल की तरह रोशनी गुज़रने देते हैं और मसूड़े पर धूसर रेखा नहीं दिखती।",
          symptoms: ["रूट कैनाल के बाद काला पड़ा आगे का दाँत", "बड़ी ख़राब होती फ़िलिंग", "मसूड़े पर काले किनारे वाला पुराना क्राउन"],
          whoNeedsIt: ["जिन्हें आगे का दाँत पड़ोसी दाँतों से मिलता हुआ फिर से बनवाना है"],
          duration: "7 से 10 दिन", visits: "2 से 3 विज़िट", recovery: "कुछ दिनों में काटना सामान्य हो जाता है।",
          comfort: "तैयारी लोकल एनेस्थीसिया में होती है।", priceNote: "प्रति क्राउन",
        },
      },
      {
        slug: "hygiene-and-polish", name: "Hygiene and polish", category: "Care", icon: "cleaning", image: "/demo/img/dental/patient-man-checkup-640.webp", reason: "cleaning",
        summary: "A thorough clean, stain removal and a check of any cosmetic work, every six months.",
        what: "Cosmetic work lasts longest on healthy gums. A hygiene visit removes tartar and surface stain, polishes veneers and bonding with the right pastes, and checks the edges of every restoration.",
        symptoms: ["Surface stain from tea or coffee", "Bleeding gums", "Six months since your last clean"],
        whoNeedsIt: ["Everyone, and especially patients with veneers, crowns or bonding"],
        steps: [
          { title: "Check", body: "Gums and restorations examined.", hi: { title: "जाँच", body: "मसूड़ों और रेस्टोरेशन की जाँच।" } },
          { title: "Clean", body: "Gentle scaling and air polishing.", hi: { title: "सफ़ाई", body: "हल्की स्केलिंग और एयर पॉलिशिंग।" } },
          { title: "Polish", body: "Restoration-safe polish and home-care advice.", hi: { title: "पॉलिश", body: "रेस्टोरेशन के लिए सुरक्षित पॉलिश और घर की देखभाल की सलाह।" } },
        ],
        duration: "One visit", visits: "45 minutes", recovery: "None.",
        comfort: "Usually no anaesthetic. Sensitive areas can be numbed.",
        faqs: [{ title: "Is air polishing safe for veneers?", body: "Yes, with the right powder. We choose pastes and powders that do not scratch ceramic or composite.", hi: { title: "क्या एयर पॉलिशिंग वीनियर के लिए सुरक्षित है?", body: "हाँ, सही पाउडर के साथ। हम ऐसे पेस्ट और पाउडर चुनते हैं जो सिरेमिक या कम्पोज़िट पर खरोंच न डालें।" } }],
        fromPrice: "2,500", priceNote: "per visit",
        hi: {
          name: "सफ़ाई और पॉलिश", category: "देखभाल",
          summary: "हर छह महीने पूरी सफ़ाई, दाग़ हटाना और हर कॉस्मेटिक काम की जाँच।",
          what: "कॉस्मेटिक काम स्वस्थ मसूड़ों पर सबसे ज़्यादा टिकता है। सफ़ाई विज़िट में टार्टर और ऊपरी दाग़ हटते हैं, वीनियर और बॉन्डिंग सही पेस्ट से पॉलिश होते हैं, और हर रेस्टोरेशन के किनारे जाँचे जाते हैं।",
          symptoms: ["चाय या कॉफ़ी के ऊपरी दाग़", "मसूड़ों से ख़ून", "पिछली सफ़ाई को छह महीने"],
          whoNeedsIt: ["सभी, और ख़ासकर वीनियर, क्राउन या बॉन्डिंग वाले मरीज़"],
          duration: "एक विज़िट", visits: "45 मिनट", recovery: "कुछ नहीं।",
          comfort: "आमतौर पर सुन्न करने की ज़रूरत नहीं। संवेदनशील जगह सुन्न की जा सकती है।", priceNote: "प्रति विज़िट",
        },
      },
      {
        slug: "dental-implants", name: "Dental implants", category: "Care", icon: "implant", image: "/demo/img/dental/implant-models-table-640.webp", reason: "implants",
        summary: "A missing front or back tooth replaced with an implant and a ceramic crown, planned with the smile design.",
        what: "In the smile zone, an implant has to look right as well as work. We plan it on a 3D scan together with the smile design, so the crown's shape and gum line match the teeth beside it. Surgery is by a visiting oral surgeon; the crown is made and fitted here.",
        symptoms: ["A missing front tooth", "A failing old bridge", "A tooth that cannot be saved"],
        whoNeedsIt: ["Adults with enough bone and healthy gums"],
        steps: [
          { title: "Scan", body: "3D CBCT scan and a design of the final crown.", hi: { title: "स्कैन", body: "3D CBCT स्कैन और अंतिम क्राउन का डिज़ाइन।" } },
          { title: "Place", body: "Implant placed under local anaesthesia; a temporary tooth where possible.", hi: { title: "लगाना", body: "लोकल एनेस्थीसिया में इम्प्लांट; जहाँ संभव हो, अस्थायी दाँत।" } },
          { title: "Crown", body: "A ceramic crown fitted after healing.", hi: { title: "क्राउन", body: "भरने के बाद सिरेमिक क्राउन।" } },
        ],
        duration: "3 to 6 months", visits: "4 to 5 visits", recovery: "Mild swelling for a few days after placement.",
        comfort: "Placed under local anaesthesia.",
        faqs: [{ title: "Will I be without a tooth while it heals?", body: "Not in the front. A temporary tooth or a removable replacement fills the gap until the crown is fitted.", hi: { title: "क्या भरने तक बिना दाँत के रहना होगा?", body: "सामने नहीं। क्राउन लगने तक अस्थायी दाँत या निकलने वाला विकल्प जगह भरता है।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "डेंटल इम्प्लांट", category: "देखभाल",
          summary: "गायब आगे या पीछे का दाँत इम्प्लांट और सिरेमिक क्राउन से, स्माइल डिज़ाइन के साथ योजना।",
          what: "मुस्कान वाले हिस्से में इम्प्लांट को काम करने के साथ सही दिखना भी चाहिए। हम इसकी योजना 3D स्कैन पर स्माइल डिज़ाइन के साथ बनाते हैं, ताकि क्राउन का आकार और मसूड़ा रेखा बगल के दाँतों से मिले। सर्जरी विज़िटिंग ओरल सर्जन करते हैं; क्राउन यहीं बनता और लगता है।",
          symptoms: ["गायब आगे का दाँत", "ख़राब होता पुराना ब्रिज", "जो दाँत बच न सके"],
          whoNeedsIt: ["पर्याप्त हड्डी और स्वस्थ मसूड़ों वाले वयस्क"],
          duration: "3 से 6 महीने", visits: "4 से 5 विज़िट", recovery: "लगाने के बाद कुछ दिन हल्की सूजन।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
    ],
    technology: [
      { title: "Digital smile design", benefit: "Your new smile drawn on your own photographs, so you can compare options before choosing one.", group: "preview", icon: "smile", image: "/demo/img/dental/tech-3d-scan-screen-640.webp", hi: { title: "डिजिटल स्माइल डिज़ाइन", benefit: "आपकी अपनी फ़ोटो पर नई मुस्कान, ताकि चुनने से पहले विकल्पों की तुलना कर सकें।" } },
      { title: "Trial smile mock-up", benefit: "The design worn in your mouth for an evening, without any drilling.", group: "preview", icon: "veneer", hi: { title: "ट्रायल स्माइल मॉक-अप", benefit: "बिना किसी ड्रिल के डिज़ाइन को एक शाम अपने मुँह में पहनना।" } },
      { title: "Intraoral scanner", benefit: "A quick 3D scan in place of impression trays, for aligners, veneers and crowns.", group: "precision", icon: "scan", image: "/demo/img/dental/tech-intraoral-scanner-640.webp", hi: { title: "इंट्राओरल स्कैनर", benefit: "अलाइनर, वीनियर और क्राउन के लिए साँचे की ट्रे की जगह जल्दी 3D स्कैन।" } },
      { title: "Shade photography", benefit: "Calibrated photos in daylight so the ceramist matches your teeth, not a shade tab under a lamp.", group: "precision", icon: "checkup", hi: { title: "रंग की फ़ोटोग्राफ़ी", benefit: "दिन की रोशनी में कैलिब्रेटेड फ़ोटो, ताकि सिरेमिस्ट आपके दाँतों से मिलान करे, लैंप के नीचे रंग की पट्टी से नहीं।" } },
      { title: "Soft-tissue laser", benefit: "Precise gum reshaping with less bleeding and quicker healing than a blade.", group: "comfort", icon: "laser", hi: { title: "सॉफ़्ट-टिश्यू लेज़र", benefit: "ब्लेड से कम ख़ून और जल्दी भरने के साथ मसूड़ों का सटीक आकार सुधार।" } },
    ],
    fees: [
      { treatment: "Smile design consultation", from: "1,500", unit: "per visit", group: "Consultation", note: "Includes photographs and a discussion of options", hi: { treatment: "स्माइल डिज़ाइन परामर्श", unit: "प्रति विज़िट", group: "परामर्श", note: "फ़ोटो और विकल्पों पर चर्चा शामिल" } },
      { treatment: "Digital smile design and trial smile", from: "8,000", unit: "per plan", group: "Consultation", note: "Adjusted against treatment if you go ahead", hi: { treatment: "डिजिटल स्माइल डिज़ाइन और ट्रायल स्माइल", unit: "प्रति योजना", group: "परामर्श", note: "इलाज कराने पर उसमें समायोजित" } },
      { treatment: "Hygiene and polish", slug: "hygiene-and-polish", from: "2,500", unit: "per visit", group: "Care", hi: { treatment: "सफ़ाई और पॉलिश", unit: "प्रति विज़िट", group: "देखभाल" } },
      { treatment: "Teeth whitening, in-studio plus home trays", slug: "teeth-whitening", from: "15,000", unit: "both jaws", group: "Whitening", hi: { treatment: "व्हाइटनिंग, स्टूडियो और घर की ट्रे", unit: "दोनों जबड़े", group: "व्हाइटनिंग" } },
      { treatment: "Composite bonding", slug: "composite-bonding", from: "6,000", unit: "per tooth", group: "Veneers and bonding", hi: { treatment: "कम्पोज़िट बॉन्डिंग", unit: "प्रति दाँत", group: "वीनियर और बॉन्डिंग" } },
      { treatment: "Porcelain veneer", slug: "porcelain-veneers", from: "18,000", unit: "per tooth", group: "Veneers and bonding", hi: { treatment: "पोर्सिलेन वीनियर", unit: "प्रति दाँत", group: "वीनियर और बॉन्डिंग" } },
      { treatment: "All-ceramic crown", slug: "all-ceramic-crowns", from: "14,000", unit: "per crown", group: "Veneers and bonding", hi: { treatment: "पूरा सिरेमिक क्राउन", unit: "प्रति क्राउन", group: "वीनियर और बॉन्डिंग" } },
      { treatment: "Gum contouring", slug: "gum-contouring", from: "8,000", unit: "per arch segment", group: "Smile design", hi: { treatment: "मसूड़ों का आकार सुधारना", unit: "प्रति जबड़े का हिस्सा", group: "स्माइल डिज़ाइन" } },
      { treatment: "Smile makeover", slug: "smile-makeover", consult: true, group: "Smile design", note: "An estimate for each option after the design", hi: { treatment: "स्माइल मेकओवर", group: "स्माइल डिज़ाइन", note: "डिज़ाइन के बाद हर विकल्प का अनुमान" } },
      { treatment: "Clear aligners", slug: "clear-aligners", consult: true, group: "Aligners", hi: { treatment: "क्लियर अलाइनर", group: "अलाइनर" } },
      { treatment: "Dental implant with ceramic crown", slug: "dental-implants", consult: true, group: "Care", hi: { treatment: "सिरेमिक क्राउन के साथ डेंटल इम्प्लांट", group: "देखभाल" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: Rs 72,000 for four veneers over 12 months is about Rs 6,000 a month before any lender charges.",
      partners: ["Card EMI through your bank", "A healthcare finance partner (sample)"],
      modes: ["UPI", "Debit and credit cards", "Bank transfer", "International cards"],
      insurance: "Cosmetic treatment is not usually covered by health insurance.",
      consultFee: "Smile design consultation: Rs 1,500. Treatment is charged as per the estimate you approve.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: चार वीनियर के 72,000 रुपये 12 महीने में, किसी भी शुल्क से पहले लगभग 6,000 रुपये महीना।",
        partners: ["आपके बैंक के कार्ड पर EMI", "एक हेल्थकेयर फ़ाइनेंस साथी (नमूना)"],
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "बैंक ट्रांसफ़र", "अंतरराष्ट्रीय कार्ड"],
        insurance: "कॉस्मेटिक इलाज आमतौर पर हेल्थ इंश्योरेंस में कवर नहीं होता।",
        consultFee: "स्माइल डिज़ाइन परामर्श: 1,500 रुपये। इलाज का शुल्क आपके मंज़ूर किए अनुमान के अनुसार।",
      },
    },
    cases: [
      { category: "Veneers", title: "Six upper porcelain veneers for worn, uneven edges", treatment: "porcelain-veneers", duration: "3 weeks, 3 visits", hi: { category: "वीनियर", title: "घिसे, असमान किनारों के लिए ऊपर के छह पोर्सिलेन वीनियर", duration: "3 हफ़्ते, 3 विज़िट" } },
      { category: "Veneers", title: "Two central veneers to match a darkened front tooth", treatment: "porcelain-veneers", duration: "2 weeks, 3 visits", hi: { category: "वीनियर", title: "काले पड़े आगे के दाँत से मिलान के लिए बीच के दो वीनियर", duration: "2 हफ़्ते, 3 विज़िट" } },
      { category: "Whitening", title: "In-studio and home whitening of tea-stained teeth", treatment: "teeth-whitening", duration: "2 weeks, 2 visits", hi: { category: "व्हाइटनिंग", title: "चाय के दाग़ वाले दाँतों की स्टूडियो और घर पर व्हाइटनिंग", duration: "2 हफ़्ते, 2 विज़िट" } },
      { category: "Aligners", title: "Crowded lower front teeth aligned before a wedding", treatment: "clear-aligners", duration: "9 months", problem: "Crowding", hi: { category: "अलाइनर", title: "शादी से पहले नीचे के भीड़ वाले आगे के दाँत सीधे", duration: "9 महीने", problem: "भीड़" } },
      { category: "Smile design", title: "Aligners, whitening and bonding combined for a gap and chips", treatment: "smile-makeover", duration: "7 months", hi: { category: "स्माइल डिज़ाइन", title: "गैप और टूटे किनारों के लिए अलाइनर, व्हाइटनिंग और बॉन्डिंग साथ", duration: "7 महीने" } },
      { category: "Smile design", title: "Gum contouring and four veneers for short-looking teeth", treatment: "smile-makeover", duration: "5 weeks, 4 visits", hi: { category: "स्माइल डिज़ाइन", title: "छोटे दिखते दाँतों के लिए मसूड़ों का आकार सुधार और चार वीनियर", duration: "5 हफ़्ते, 4 विज़िट" } },
      { category: "Bonding", title: "Chipped front tooth rebuilt with composite bonding", treatment: "composite-bonding", duration: "1 visit", hi: { category: "बॉन्डिंग", title: "टूटा आगे का दाँत कम्पोज़िट बॉन्डिंग से फिर से बना", duration: "1 विज़िट" } },
    ],
    international: {
      intro: "Many of our patients live abroad and visit Mumbai for family or work. We plan your treatment on a video call first, so your time in the studio is used well, and we send you home with your records.",
      steps: [
        { title: "Send photos and X-rays", body: "Smile photos from your phone and any recent X-rays, by email or WhatsApp.", hi: { title: "फ़ोटो और एक्स-रे भेजें", body: "फ़ोन से मुस्कान की फ़ोटो और हाल के एक्स-रे, ईमेल या व्हाट्सऐप पर।" } },
        { title: "Video consultation", body: "A 30-minute call to discuss options and a provisional estimate.", hi: { title: "वीडियो परामर्श", body: "विकल्पों और अस्थायी अनुमान पर 30 मिनट की कॉल।" } },
        { title: "Plan your trip", body: "We book your visits back to back and tell you how many days to allow.", hi: { title: "यात्रा की योजना", body: "हम आपकी विज़िट लगातार बुक करते हैं और बताते हैं कितने दिन रखें।" } },
        { title: "Treatment in the studio", body: "Examination, confirmed estimate, then treatment as planned.", hi: { title: "स्टूडियो में इलाज", body: "जाँच, पक्का अनुमान, फिर योजना के अनुसार इलाज।" } },
        { title: "Records and follow-up", body: "Your scans, photos and a treatment summary, and a video review after you return.", hi: { title: "रिकॉर्ड और फ़ॉलो-अप", body: "आपके स्कैन, फ़ोटो और इलाज का सारांश, और लौटने के बाद वीडियो जाँच।" } },
      ],
      stays: [
        { title: "Whitening or bonding", body: "Plan for 3 to 4 days.", hi: { title: "व्हाइटनिंग या बॉन्डिंग", body: "3 से 4 दिन की योजना रखें।" } },
        { title: "Veneers or ceramic crowns", body: "Plan for 10 to 14 days, or two shorter trips.", hi: { title: "वीनियर या सिरेमिक क्राउन", body: "10 से 14 दिन, या दो छोटी यात्राओं की योजना रखें।" } },
        { title: "Implants", body: "Plan for two trips, 3 to 4 months apart.", hi: { title: "इम्प्लांट", body: "3 से 4 महीने के अंतर पर दो यात्राओं की योजना रखें।" } },
        { title: "Clear aligners", body: "One visit to start, then remote check-ins with in-person reviews on your trips home.", hi: { title: "क्लियर अलाइनर", body: "शुरुआत के लिए एक विज़िट, फिर दूर से जाँच और घर आने पर आमने-सामने समीक्षा।" } },
      ],
      hi: { intro: "हमारे कई मरीज़ विदेश में रहते हैं और परिवार या काम से मुंबई आते हैं। हम पहले वीडियो कॉल पर आपके इलाज की योजना बनाते हैं, ताकि स्टूडियो में आपका समय सही इस्तेमाल हो, और आपके रिकॉर्ड के साथ घर भेजते हैं।" },
    },
    booking: {
      reasons: [
        { id: "veneers", label: "Veneers or smile makeover", icon: "veneer", treatment: "smile-makeover", hi: { label: "वीनियर या स्माइल मेकओवर" } },
        { id: "whitening", label: "Whitening", icon: "whitening", treatment: "teeth-whitening", hi: { label: "व्हाइटनिंग" } },
        { id: "aligners", label: "Clear aligners", icon: "aligner", treatment: "clear-aligners", hi: { label: "क्लियर अलाइनर" } },
        { id: "cleaning", label: "Hygiene and polish", icon: "cleaning", treatment: "hygiene-and-polish", hi: { label: "सफ़ाई और पॉलिश" } },
        { id: "implants", label: "Missing tooth", icon: "implant", treatment: "dental-implants", hi: { label: "गायब दाँत" } },
        { id: "pain", label: "Tooth pain or a broken tooth", icon: "pain", urgent: true, hi: { label: "दाँत दर्द या टूटा दाँत" } },
        { id: "not-sure", label: "Not sure yet", icon: "tooth", hi: { label: "अभी पक्का नहीं" } },
      ],
      morning: ["10:00 am", "11:00 am", "12:00 pm"],
      evening: ["2:30 pm", "3:30 pm", "4:30 pm", "5:30 pm"],
      closedDays: [1],
      closedNote: "Closed on Mondays",
      hi: { closedNote: "सोमवार बंद" },
    },
    sessions: [{ days: [0, 2, 3, 4, 5, 6], from: "10:00", to: "19:00" }],
    reach: {
      transit: "Fifteen minutes by auto or taxi from Bandra station (West).",
      parking: "Two visitor spaces in the bungalow compound; valet on request.",
      access: "Ground floor, step-free from the gate.",
      hi: {
        transit: "बांद्रा स्टेशन (वेस्ट) से ऑटो या टैक्सी से पंद्रह मिनट।",
        parking: "बंगले के परिसर में दो विज़िटर पार्किंग; कहने पर वैले।",
        access: "भूतल, गेट से बिना सीढ़ी।",
      },
    },
    sterilisation: [
      { title: "Clean", body: "Every instrument is cleaned in an ultrasonic bath after use.", hi: { title: "सफ़ाई", body: "हर इस्तेमाल के बाद औज़ार अल्ट्रासोनिक बाथ में साफ़ होते हैं।" } },
      { title: "Seal", body: "Instruments are packed in dated, sealed pouches.", hi: { title: "सील", body: "औज़ार तारीख़ वाले सील पाउच में पैक होते हैं।" } },
      { title: "Sterilise", body: "Class B autoclave cycles, tested and logged daily.", hi: { title: "स्टरलाइज़", body: "क्लास B ऑटोक्लेव चक्र, रोज़ जाँच और रिकॉर्ड।" } },
      { title: "Open at your chair", body: "Pouches are opened in front of you; disposables are single use.", hi: { title: "आपकी कुर्सी पर खोलना", body: "पाउच आपके सामने खोले जाते हैं; डिस्पोज़ेबल चीज़ें एक बार ही।" } },
    ],
    trust: [
      { title: "You see it before we make it", body: "A digital design and a trial smile come before any permanent work.", hi: { title: "बनने से पहले आप देखते हैं", body: "किसी भी स्थायी काम से पहले डिजिटल डिज़ाइन और ट्रायल स्माइल।" } },
      { title: "The smaller option first", body: "Whitening and bonding are offered where they will do.", hi: { title: "पहले छोटा विकल्प", body: "जहाँ काम चल जाए, वहाँ व्हाइटनिंग और बॉन्डिंग सुझाई जाती है।" } },
      { title: "Estimates in writing", body: "Each option is costed before you choose.", hi: { title: "लिखित अनुमान", body: "चुनने से पहले हर विकल्प का ख़र्च बताया जाता है।" } },
    ],
    comfort: [
      { title: "Unhurried appointments", body: "Longer slots, and a consultation room away from the treatment chair.", hi: { title: "बिना जल्दबाज़ी की अपॉइंटमेंट", body: "लंबे स्लॉट, और इलाज की कुर्सी से अलग परामर्श कक्ष।" } },
      { title: "Local anaesthesia when needed", body: "Used for any tooth preparation, and checked before we begin.", hi: { title: "ज़रूरत पर लोकल एनेस्थीसिया", body: "दाँत की किसी भी तैयारी में, और शुरू करने से पहले जाँच।" } },
      { title: "Pause whenever you like", body: "Agree a hand signal and we stop.", hi: { title: "जब चाहें रुकें", body: "हाथ का इशारा तय करें और हम रुक जाएँगे।" } },
    ],
  },
});
