/**
 * d4-implant-centre: Deodar Dental Implant Centre, Baner, Pune.
 * An implant and full-mouth centre led by an oral surgeon and a
 * prosthodontist: single implants, implant bridges, full-arch fixed teeth,
 * implant dentures and grafting, each planned on a 3D CBCT scan. Written for
 * patients over 45 and the sons and daughters researching for them.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md. Everything here is fiction: the centre, the doctors,
 * the reviews, the rating, the cases and the trust figures are SAMPLE content
 * and carry the SampleNote label until the clinic replaces them. No success
 * rates, no warranties, no fixed implant prices. Name forms exactly as in
 * TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Deodar Dental Implant Centre",
  shortName: "Deodar Implant Centre",
  tagline: "Single implants, full-arch fixed teeth and implant dentures, planned with 3D CBCT imaging.",
  city: "Pune",
  state: "Maharashtra",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2014",
  establishedYear: "2014",
  sitePages: [...DENTAL_PAGE_SETS["d4-implant-centre"]],
  heroImage: "/demo/img/dental/hero-white-operatory-800.webp",
  sectionPhotos: { about: "/demo/img/dental/patient-older-woman-talk-640.webp" },
  photos: [
    { src: "/demo/img/dental/tech-3d-imaging-640.webp", alt: "", category: "Diagnosis", caption: "CBCT scanning room", hi: { category: "जाँच", caption: "CBCT स्कैन कक्ष" } },
    { src: "/demo/img/dental/interior-consult-room-640.webp", alt: "", category: "Centre", caption: "Planning room", hi: { category: "सेंटर", caption: "योजना कक्ष" } },
    { src: "/demo/img/dental/implant-models-table-640.webp", alt: "", category: "Lab", caption: "Models in the dental lab", hi: { category: "लैब", caption: "डेंटल लैब में मॉडल" } },
    { src: "/demo/img/dental/sterile-sealed-pouches-640.webp", alt: "", category: "Sterilisation", caption: "Sealed surgical kits", hi: { category: "स्टरलाइज़ेशन", caption: "सील किए सर्जिकल किट" } },
  ],
  about:
    "Deodar Dental Implant Centre was founded in 2014 by an oral surgeon and a prosthodontist who had worked together on implant cases for years. The surgeon places the implant; the prosthodontist designs the teeth that go on it. Planning both at the start, on the same 3D scan, is the idea the centre is built on.\n\nMost of our patients are over 45. Many arrive with a son or daughter who has done the research, and with a loose denture, a failing bridge or several teeth that cannot be saved. We take time over the first consultation, put every option and its cost on paper, and are plain about who is and is not a good candidate for implants.",
  mission: "Fixed, comfortable teeth, planned in 3D and explained to the whole family before treatment begins.",
  vision: "That nobody in Pune has to give up chewing the food they like because of missing teeth.",
  hi: {
    instituteName: "देवदार डेंटल इम्प्लांट सेंटर",
    shortName: "देवदार",
    tagline: "एक इम्प्लांट, पूरे जबड़े के फ़िक्स्ड दाँत और इम्प्लांट डेंचर, 3D CBCT इमेजिंग से योजना के साथ।",
    city: "पुणे",
    state: "महाराष्ट्र",
    established: "2014 से",
    establishedYear: "2014",
    about:
      "देवदार डेंटल इम्प्लांट सेंटर 2014 में एक ओरल सर्जन और एक प्रोस्थोडॉन्टिस्ट ने शुरू किया, जो सालों से इम्प्लांट के मामलों पर साथ काम कर रहे थे। सर्जन इम्प्लांट लगाते हैं; प्रोस्थोडॉन्टिस्ट उस पर लगने वाले दाँत डिज़ाइन करते हैं। शुरुआत में ही एक ही 3D स्कैन पर दोनों की योजना बनाना, यही इस सेंटर की नींव है।\n\nहमारे ज़्यादातर मरीज़ 45 से ऊपर हैं। कई अपने बेटे या बेटी के साथ आते हैं जिन्होंने जानकारी जुटाई है, और साथ में ढीला डेंचर, ख़राब होता ब्रिज या कई दाँत होते हैं जो बच नहीं सकते। हम पहले परामर्श में समय लेते हैं, हर विकल्प और उसका ख़र्च काग़ज़ पर देते हैं, और साफ़ बताते हैं कि कौन इम्प्लांट के लिए उपयुक्त है और कौन नहीं।",
    mission: "फ़िक्स्ड, आरामदायक दाँत, 3D में योजना बनाकर और इलाज से पहले पूरे परिवार को समझाकर।",
    vision: "कि पुणे में किसी को भी गायब दाँतों की वजह से अपना पसंदीदा खाना छोड़ना न पड़े।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "implants@example.com",
    addressLines: ["Example Road", "Baner, Pune 411000"],
    hours: "Mon to Sat, 9:30 am to 1:30 pm and 4:30 to 7:30 pm. Closed on Sundays",
    landmark: "First floor of a commercial building on the main Baner road, lift from the lobby",
    mapQuery: "Baner, Pune",
    hi: {
      addressLines: ["उदाहरण रोड", "बाणेर, पुणे 411000"],
      hours: "सोम से शनि, सुबह 9:30 से दोपहर 1:30 और शाम 4:30 से 7:30। रविवार बंद",
      landmark: "बाणेर मुख्य सड़क पर एक व्यावसायिक इमारत की पहली मंज़िल, लॉबी से लिफ़्ट",
    },
  },
  stats: [
    { value: "12", label: "Years in Baner", basis: "Since 2014", hi: { label: "साल बाणेर में", basis: "2014 से" } },
    { value: "3", label: "MDS specialists", basis: "Oral surgery, prosthodontics, periodontology", hi: { label: "MDS विशेषज्ञ", basis: "ओरल सर्जरी, प्रोस्थोडॉन्टिक्स, पेरियोडॉन्टोलॉजी" } },
    { value: "3D", label: "CBCT scan before every implant", basis: "Taken on site, reviewed with you", hi: { label: "हर इम्प्लांट से पहले CBCT स्कैन", basis: "यहीं लिया जाता है, आपके साथ देखा जाता है" } },
  ],
  rating: { value: "4.8", count: "164", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "My father is 71 and had struggled with a loose lower denture for years. Two implants now hold it firmly. Dr. Joshi explained the CBCT scan to both of us and answered every question about his diabetes.", relation: "Daughter of a patient, implant denture", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Implant dentures", hi: { quote: "मेरे पिता 71 साल के हैं और सालों से ढीले निचले डेंचर से परेशान थे। अब दो इम्प्लांट उसे मज़बूती से पकड़ते हैं। डॉ. जोशी ने हम दोनों को CBCT स्कैन समझाया और उनकी डायबिटीज़ के हर सवाल का जवाब दिया।", relation: "मरीज़ की बेटी, इम्प्लांट डेंचर", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "इम्प्लांट डेंचर" } },
    { quote: "Single implant for a lower molar. The estimate listed the implant, abutment, crown and scan separately, and the final bill was the same.", relation: "Patient, single implant", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Implants", hi: { quote: "नीचे की दाढ़ के लिए एक इम्प्लांट। अनुमान में इम्प्लांट, एबटमेंट, क्राउन और स्कैन अलग-अलग लिखे थे, और अंतिम बिल भी उतना ही आया।", relation: "मरीज़, एक इम्प्लांट", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "इम्प्लांट" } },
    { quote: "They told me honestly that I needed a bone graft first and that it would add three months. I appreciated not being rushed.", relation: "Patient, bone graft and implant", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Bone grafting", hi: { quote: "उन्होंने ईमानदारी से बताया कि पहले बोन ग्राफ़्ट चाहिए और इससे तीन महीने बढ़ेंगे। जल्दबाज़ी न करना अच्छा लगा।", relation: "मरीज़, बोन ग्राफ़्ट और इम्प्लांट", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "बोन ग्राफ़्ट" } },
    { quote: "Full upper arch on implants for my mother. It took several visits over five months, but she has fixed teeth again and speaks clearly.", relation: "Son of a patient, full-arch fixed teeth", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Full arch", hi: { quote: "मेरी माँ के लिए ऊपर का पूरा जबड़ा इम्प्लांट पर। पाँच महीनों में कई विज़िट लगीं, पर अब उनके फ़िक्स्ड दाँत हैं और वह साफ़ बोलती हैं।", relation: "मरीज़ का बेटा, पूरे जबड़े के फ़िक्स्ड दाँत", source: "गूगल रिव्यू", date: "जून 2026", category: "पूरा जबड़ा" } },
    { quote: "Came from Dubai for two short trips. The planning on video beforehand meant no wasted days.", relation: "Patient from abroad, implant bridge", rating: "5", source: "Google review", date: "May 2026", consent: true, category: "Implants", hi: { quote: "दुबई से दो छोटी यात्राओं में आया। पहले वीडियो पर योजना से कोई दिन बर्बाद नहीं हुआ।", relation: "विदेश से मरीज़, इम्प्लांट ब्रिज", source: "गूगल रिव्यू", date: "मई 2026", category: "इम्प्लांट" } },
    { quote: "Swelling for three days after surgery, as they said there would be. The follow-up calls were reassuring. Waiting area gets busy in the evening.", relation: "Patient, two implants", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Implants", hi: { quote: "सर्जरी के बाद तीन दिन सूजन रही, जैसा उन्होंने बताया था। फ़ॉलो-अप कॉल से भरोसा मिला। शाम को प्रतीक्षा कक्ष में भीड़ हो जाती है।", relation: "मरीज़, दो इम्प्लांट", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "इम्प्लांट" } },
  ],
  posts: [
    {
      slug: "implant-bridge-or-denture", title: "Implant, bridge or denture: comparing the options for a missing tooth", date: "18 Sep 2026", category: "Implants", treatment: "single-tooth-implant",
      author: "Dr. Neha Deshpande", reviewedBy: "Medically reviewed by Dr. Neha Deshpande, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "Each option has a place. What decides it is the teeth beside the gap, the bone under it and how long you want it to last.",
      body: "An implant replaces the root with a titanium post in the bone, then a crown on top. It does not touch the neighbouring teeth, and it keeps the bone under the gap in use. It needs enough bone and healthy gums, and takes about three to six months from start to finish.\n\nA bridge uses the teeth on either side as supports. It is quicker, often two or three weeks, but those teeth are trimmed for crowns. It suits a gap whose neighbours already need crowns.\n\nA removable denture costs the least and needs no surgery. It can feel bulky, and it has to come out for cleaning.\n\nThe cost on the day is only part of the comparison. Ask how long each option usually lasts, what care it needs, and what it would cost to redo. The final choice and cost depend on your examination and scan.",
      hi: {
        title: "इम्प्लांट, ब्रिज या डेन्चर: गायब दाँत के विकल्पों की तुलना", date: "18 सितंबर 2026", category: "इम्प्लांट", author: "डॉ. नेहा देशपांडे", reviewedBy: "डॉ. नेहा देशपांडे, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "हर विकल्प की अपनी जगह है। फ़ैसला ख़ाली जगह के बगल के दाँत, नीचे की हड्डी और आप इसे कितना लंबा चलाना चाहते हैं, इस पर होता है।",
        body: "इम्प्लांट जड़ की जगह हड्डी में टाइटेनियम का पोस्ट लगाता है, फिर ऊपर क्राउन। यह बगल के दाँतों को नहीं छूता, और ख़ाली जगह के नीचे की हड्डी को काम में रखता है। इसके लिए पर्याप्त हड्डी और स्वस्थ मसूड़े चाहिए, और शुरू से अंत तक लगभग तीन से छह महीने लगते हैं।\n\nब्रिज दोनों तरफ़ के दाँतों को सहारे की तरह इस्तेमाल करता है। यह जल्दी होता है, अक्सर दो-तीन हफ़्ते, पर उन दाँतों को क्राउन के लिए घिसा जाता है। यह तब ठीक है जब बगल के दाँतों को पहले से क्राउन की ज़रूरत हो।\n\nनिकालने वाला डेन्चर सबसे सस्ता है और इसमें सर्जरी नहीं होती। यह भारी लग सकता है, और सफ़ाई के लिए निकालना पड़ता है।\n\nउस दिन का ख़र्च तुलना का सिर्फ़ एक हिस्सा है। पूछें कि हर विकल्प आमतौर पर कितना चलता है, कैसी देखभाल चाहिए, और दोबारा बनवाने में कितना लगेगा। अंतिम विकल्प और ख़र्च आपकी जाँच और स्कैन पर निर्भर है।",
      },
    },
    {
      slug: "bone-graft-and-sinus-lift", title: "Not enough bone for an implant? Bone grafts and sinus lifts explained", date: "4 Sep 2026", category: "Surgery", treatment: "bone-grafting",
      author: "Dr. Sameer Joshi", reviewedBy: "Medically reviewed by Dr. Sameer Joshi, MDS (Oral and Maxillofacial Surgery)",
      excerpt: "Bone shrinks after a tooth is lost. A 3D scan shows how much is left, and whether it needs building up first.",
      body: "After a tooth is removed, the bone that held it slowly shrinks, most in the first year. An implant needs enough bone around it, in height and in width, to stay firm.\n\nA CBCT scan measures this in 3D before anything is planned. If there is too little, a bone graft adds bone-like material to the area, covered by a thin membrane. It usually heals for three to six months before the implant goes in, and sometimes both are done together.\n\nIn the upper back jaw, the sinus sits just above the roots. A sinus lift gently raises the sinus floor and places graft material under it, to make room for the implant.\n\nBoth are done under local anaesthesia. Expect swelling for a few days. They add time and cost, so they should appear in your written estimate from the start, not as a surprise later.",
      hi: {
        title: "इम्प्लांट के लिए हड्डी कम है? बोन ग्राफ़्ट और साइनस लिफ़्ट की जानकारी", date: "4 सितंबर 2026", category: "सर्जरी", author: "डॉ. समीर जोशी", reviewedBy: "डॉ. समीर जोशी, MDS (ओरल एंड मैक्सिलोफ़ेशियल सर्जरी) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "दाँत जाने के बाद हड्डी घटती है। 3D स्कैन से पता चलता है कि कितनी बची है, और क्या पहले उसे बढ़ाना होगा।",
        body: "दाँत निकलने के बाद उसे पकड़ने वाली हड्डी धीरे-धीरे घटती है, सबसे ज़्यादा पहले साल में। इम्प्लांट को मज़बूत रहने के लिए चारों ओर ऊँचाई और चौड़ाई में पर्याप्त हड्डी चाहिए।\n\nकुछ भी तय करने से पहले CBCT स्कैन इसे 3D में नापता है। कम हो तो बोन ग्राफ़्ट में उस जगह हड्डी जैसी सामग्री भरकर पतली झिल्ली से ढका जाता है। आमतौर पर इम्प्लांट से पहले तीन से छह महीने भरने दिया जाता है, और कभी दोनों एक साथ होते हैं।\n\nऊपर के पीछे के जबड़े में साइनस जड़ों के ठीक ऊपर होता है। साइनस लिफ़्ट में साइनस के तल को हल्के से ऊपर उठाकर नीचे ग्राफ़्ट सामग्री रखी जाती है, ताकि इम्प्लांट के लिए जगह बने।\n\nदोनों लोकल एनेस्थीसिया में होते हैं। कुछ दिन सूजन रह सकती है। इनसे समय और ख़र्च बढ़ता है, इसलिए ये शुरू से आपके लिखित अनुमान में होने चाहिए, बाद में अचानक नहीं।",
      },
    },
    {
      slug: "looking-after-an-implant", title: "Looking after an implant so it lasts", date: "21 Aug 2026", category: "Aftercare", treatment: "implant-maintenance",
      author: "Dr. Amol Patil", reviewedBy: "Medically reviewed by Dr. Amol Patil, MDS (Periodontology)",
      excerpt: "An implant cannot decay, but the gum and bone around it can still become inflamed. Daily cleaning and reviews keep it healthy.",
      body: "The crown on an implant cannot get a cavity. The gum and bone around it can still become inflamed if plaque is left there, a condition called peri-implantitis. It is the most common reason implants fail years later.\n\nBrush around the implant twice a day, and clean the sides every day with an interdental brush or a water flosser. Under a full-arch bridge, a water flosser or special floss reaches where a brush cannot.\n\nCome in for a review and professional cleaning every six months in the first years. X-rays taken once a year check the bone level around the implant.\n\nSmoking and uncontrolled diabetes raise the risk of problems. Bleeding, swelling or a loose feeling around an implant needs a check soon, not at the next routine visit.",
      hi: {
        title: "इम्प्लांट की देखभाल, ताकि वह लंबा चले", date: "21 अगस्त 2026", category: "देखभाल", author: "डॉ. अमोल पाटिल", reviewedBy: "डॉ. अमोल पाटिल, MDS (पेरियोडॉन्टोलॉजी) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "इम्प्लांट में कीड़ा नहीं लगता, पर उसके आसपास के मसूड़े और हड्डी में सूजन हो सकती है। रोज़ की सफ़ाई और जाँच उसे स्वस्थ रखती है।",
        body: "इम्प्लांट के क्राउन में कैविटी नहीं होती। पर अगर वहाँ प्लाक रह जाए तो आसपास के मसूड़े और हड्डी में सूजन हो सकती है, जिसे पेरी-इम्प्लांटाइटिस कहते हैं। सालों बाद इम्प्लांट के ख़राब होने की यही सबसे आम वजह है।\n\nदिन में दो बार इम्प्लांट के चारों ओर ब्रश करें, और हर दिन इंटरडेंटल ब्रश या वॉटर फ़्लॉसर से किनारे साफ़ करें। पूरे जबड़े के ब्रिज के नीचे वॉटर फ़्लॉसर या ख़ास फ़्लॉस वहाँ पहुँचता है जहाँ ब्रश नहीं पहुँचता।\n\nशुरुआती सालों में हर छह महीने जाँच और प्रोफ़ेशनल सफ़ाई के लिए आएँ। साल में एक बार एक्स-रे से इम्प्लांट के आसपास हड्डी का स्तर देखा जाता है।\n\nधूम्रपान और बिना नियंत्रण की डायबिटीज़ से परेशानी का ख़तरा बढ़ता है। इम्प्लांट के आसपास ख़ून, सूजन या ढीलापन लगे तो जल्दी जाँच करवाएँ, अगली नियमित विज़िट का इंतज़ार न करें।",
      },
    },
  ],
  faq: [
    { title: "Am I too old for implants?", body: "Age alone is rarely the limit. What matters is general health, bone, gums and whether you can keep the area clean. Many of our patients are in their seventies.", group: "Suitability", hi: { title: "क्या इम्प्लांट के लिए मेरी उम्र ज़्यादा है?", body: "सिर्फ़ उम्र शायद ही कभी रुकावट होती है। मायने रखते हैं सामान्य सेहत, हड्डी, मसूड़े और यह कि आप उस जगह को साफ़ रख पाएँ। हमारे कई मरीज़ सत्तर पार हैं।", group: "उपयुक्तता" } },
    { title: "Can I have implants if I have diabetes?", body: "Often yes, when blood sugar is well controlled. We ask for a recent HbA1c report and plan with your physician. Healing can take a little longer.", group: "Suitability", hi: { title: "क्या डायबिटीज़ में इम्प्लांट लग सकते हैं?", body: "अक्सर हाँ, जब शुगर अच्छी तरह नियंत्रित हो। हम हाल की HbA1c रिपोर्ट माँगते हैं और आपके डॉक्टर के साथ योजना बनाते हैं। भरने में थोड़ा ज़्यादा समय लग सकता है।", group: "उपयुक्तता" } },
    { title: "Does implant surgery hurt?", body: "It is done under local anaesthesia, so you feel pressure rather than pain. Afterwards most people have swelling and soreness for two to four days, managed with ordinary painkillers.", group: "Treatment", hi: { title: "क्या इम्प्लांट सर्जरी में दर्द होता है?", body: "यह लोकल एनेस्थीसिया में होती है, इसलिए दर्द नहीं, दबाव महसूस होता है। बाद में ज़्यादातर लोगों को दो से चार दिन सूजन और दर्द रहता है, जो आम दर्द निवारक दवा से संभलता है।", group: "इलाज" } },
    { title: "How much does an implant cost?", body: "It depends on the scan, whether a graft is needed, the implant system and the crown material. After the consultation and CBCT scan you get a written, itemised estimate. We do not quote a fixed price before seeing the scan.", group: "Fees", hi: { title: "इम्प्लांट का ख़र्च कितना है?", body: "यह स्कैन, ग्राफ़्ट की ज़रूरत, इम्प्लांट सिस्टम और क्राउन की सामग्री पर निर्भर है। परामर्श और CBCT स्कैन के बाद आपको लिखित, मदवार अनुमान मिलता है। स्कैन देखे बिना हम तय क़ीमत नहीं बताते।", group: "फ़ीस" } },
    { title: "Will I be without teeth during treatment?", body: "Rarely. For front teeth and full arches we plan a temporary tooth, bridge or denture so you are never without teeth in public.", group: "Treatment", hi: { title: "क्या इलाज के दौरान बिना दाँतों के रहना होगा?", body: "शायद ही कभी। आगे के दाँतों और पूरे जबड़े के लिए हम अस्थायी दाँत, ब्रिज या डेंचर की योजना बनाते हैं ताकि आप सबके सामने कभी बिना दाँत के न हों।", group: "इलाज" } },
    { title: "What if I take blood thinners?", body: "Do not stop any medicine on your own. We coordinate with your cardiologist or physician and plan surgery around their advice.", group: "Suitability", hi: { title: "अगर मैं ख़ून पतला करने वाली दवा लेता हूँ तो?", body: "कोई भी दवा अपने आप बंद न करें। हम आपके कार्डियोलॉजिस्ट या डॉक्टर से तालमेल करते हैं और उनकी सलाह से सर्जरी की योजना बनाते हैं।", group: "उपयुक्तता" } },
    { title: "How long do implants last?", body: "With good cleaning, no smoking and regular reviews, implants can last many years. No one can promise a fixed number of years; we check every implant at your maintenance visits.", group: "Aftercare", hi: { title: "इम्प्लांट कितने समय चलते हैं?", body: "अच्छी सफ़ाई, धूम्रपान न करने और नियमित जाँच से इम्प्लांट कई साल चल सकते हैं। कोई तय सालों का वादा नहीं कर सकता; देखभाल विज़िट में हम हर इम्प्लांट की जाँच करते हैं।", group: "देखभाल" } },
    { title: "Can my son or daughter join the consultation by video?", body: "Yes. Many families do. Tell us when you book and we will send a link for the planning discussion.", group: "Visiting", hi: { title: "क्या मेरा बेटा या बेटी वीडियो से परामर्श में जुड़ सकते हैं?", body: "हाँ। कई परिवार ऐसा करते हैं। बुकिंग के समय बताएँ, हम योजना की चर्चा के लिए लिंक भेज देंगे।", group: "विज़िट" } },
    { title: "What should I bring to the first visit?", body: "Any old X-rays or scans, a list of your medicines, recent blood reports if you have diabetes, and your current denture if you wear one.", group: "Visiting", hi: { title: "पहली विज़िट में क्या लाएँ?", body: "पुराने एक्स-रे या स्कैन, दवाओं की सूची, डायबिटीज़ हो तो हाल की ख़ून की रिपोर्ट, और अगर पहनते हैं तो अपना मौजूदा डेंचर।", group: "विज़िट" } },
  ],
  dental: {
    legalName: "Deodar Dental Implant Centre LLP (sample)",
    hi: { legalName: "देवदार डेंटल इम्प्लांट सेंटर LLP (नमूना)" },
    hero: {
      variant: "calm-full",
      pill: "Dental implant centre, Baner, Pune",
      headline: "Fixed teeth, *planned in 3D*.",
      lead: "Single implants, implant bridges, full-arch fixed teeth and implant dentures, each planned on a CBCT scan and explained to your family first.",
      credential: "Dr. Sameer Joshi, BDS, MDS (Oral and Maxillofacial Surgery). Reg. no. A-00000 (sample)",
      hi: {
        pill: "डेंटल इम्प्लांट सेंटर, बाणेर, पुणे",
        headline: "फ़िक्स्ड दाँत, *3D में योजना के साथ*।",
        lead: "एक इम्प्लांट, इम्प्लांट ब्रिज, पूरे जबड़े के फ़िक्स्ड दाँत और इम्प्लांट डेंचर, हर एक CBCT स्कैन पर योजना के साथ और पहले आपके परिवार को समझाकर।",
        credential: "डॉ. समीर जोशी, BDS, MDS (ओरल एंड मैक्सिलोफ़ेशियल सर्जरी)। रजि. नं. A-00000 (नमूना)",
      },
    },
    doctors: [
      {
        slug: "sameer-joshi", name: "Dr. Sameer Joshi", photo: "/demo/img/people/dentist-m01-240.webp", gender: "male", lead: true,
        qualification: "BDS, MDS (Oral and Maxillofacial Surgery)", specialisation: "Oral and maxillofacial surgeon",
        focus: "Implant surgery, bone grafting, sinus lifts, full-arch implant treatment", experience: "18 years in practice",
        languages: ["Marathi", "Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        bio: "Dr. Sameer Joshi co-founded the centre in 2014 after twelve years of oral surgery in hospital and private practice in Pune. He places the implants, performs bone grafts and sinus lifts, and plans every surgery on a CBCT scan with the prosthodontist before the patient is booked.\n\nHe is known for long first consultations. Many of his patients are over sixty with diabetes or heart conditions, and he would rather spend an extra half hour explaining the plan to the family than rush a decision.",
        quote: "If you understand the scan, you will understand the plan. I will not ask you to agree to anything before that.",
        training: ["BDS, 2004 (sample)", "MDS, Oral and Maxillofacial Surgery, 2008 (sample)", "Advanced implant surgery course, 2012 (sample)", "Guided implant surgery course, 2019 (sample)"],
        memberships: ["Association of Oral and Maxillofacial Surgeons of India (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. समीर जोशी", qualification: "BDS, MDS (ओरल एंड मैक्सिलोफ़ेशियल सर्जरी)", specialisation: "ओरल और मैक्सिलोफ़ेशियल सर्जन",
          focus: "इम्प्लांट सर्जरी, बोन ग्राफ़्टिंग, साइनस लिफ़्ट, पूरे जबड़े का इम्प्लांट इलाज", experience: "18 साल का अनुभव",
          languages: ["मराठी", "हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि",
          bio: "डॉ. समीर जोशी ने पुणे के अस्पताल और निजी प्रैक्टिस में बारह साल ओरल सर्जरी के बाद 2014 में इस सेंटर की सह-स्थापना की। वे इम्प्लांट लगाते हैं, बोन ग्राफ़्ट और साइनस लिफ़्ट करते हैं, और मरीज़ की बुकिंग से पहले हर सर्जरी की योजना प्रोस्थोडॉन्टिस्ट के साथ CBCT स्कैन पर बनाते हैं।\n\nवे लंबे पहले परामर्श के लिए जाने जाते हैं। उनके कई मरीज़ साठ पार हैं जिन्हें डायबिटीज़ या दिल की बीमारी है, और वे जल्दबाज़ी में फ़ैसला कराने से बेहतर परिवार को योजना समझाने में आधा घंटा ज़्यादा लगाना मानते हैं।",
          quote: "अगर आप स्कैन समझ लेंगे, तो योजना भी समझ जाएँगे। उससे पहले मैं आपसे किसी बात पर हाँ नहीं कहलवाऊँगा।",
          training: ["BDS, 2004 (नमूना)", "MDS, ओरल एंड मैक्सिलोफ़ेशियल सर्जरी, 2008 (नमूना)", "एडवांस्ड इम्प्लांट सर्जरी कोर्स, 2012 (नमूना)", "गाइडेड इम्प्लांट सर्जरी कोर्स, 2019 (नमूना)"],
          memberships: ["एसोसिएशन ऑफ़ ओरल एंड मैक्सिलोफ़ेशियल सर्जन्स ऑफ़ इंडिया (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "neha-deshpande", name: "Dr. Neha Deshpande", photo: "/demo/img/people/dentist-w04-240.webp", gender: "female",
        qualification: "BDS, MDS (Prosthodontics and Crown and Bridge)", specialisation: "Prosthodontist",
        focus: "Implant crowns and bridges, full-arch fixed teeth, implant dentures", experience: "14 years in practice",
        languages: ["Marathi", "Hindi", "English", "Kannada"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        bio: "Dr. Neha Deshpande co-founded the centre and designs the teeth that sit on every implant: single crowns, bridges, full-arch fixed teeth and implant-retained dentures. She starts from the final teeth and works backwards, so the surgeon places each implant where the tooth needs it.\n\nShe also runs the centre's maintenance programme, because implant teeth need the same regular care as natural ones.",
        quote: "We design the teeth first, then decide where the implants go.",
        training: ["BDS, 2008 (sample)", "MDS, Prosthodontics and Crown and Bridge, 2012 (sample)", "Full-arch implant prosthetics course, 2016 (sample)"],
        memberships: ["Indian Prosthodontic Society (sample)"],
        hi: {
          name: "डॉ. नेहा देशपांडे", qualification: "BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज)", specialisation: "प्रोस्थोडॉन्टिस्ट",
          focus: "इम्प्लांट क्राउन और ब्रिज, पूरे जबड़े के फ़िक्स्ड दाँत, इम्प्लांट डेंचर", experience: "14 साल का अनुभव",
          languages: ["मराठी", "हिंदी", "अंग्रेज़ी", "कन्नड़"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि",
          bio: "डॉ. नेहा देशपांडे सेंटर की सह-संस्थापक हैं और हर इम्प्लांट पर लगने वाले दाँत डिज़ाइन करती हैं: एक क्राउन, ब्रिज, पूरे जबड़े के फ़िक्स्ड दाँत और इम्प्लांट पर टिके डेंचर। वे अंतिम दाँतों से शुरू करके पीछे की ओर काम करती हैं, ताकि सर्जन हर इम्प्लांट वहीं लगाएँ जहाँ दाँत को उसकी ज़रूरत है।\n\nसेंटर का देखभाल कार्यक्रम भी वही चलाती हैं, क्योंकि इम्प्लांट के दाँतों को भी प्राकृतिक दाँतों जैसी नियमित देखभाल चाहिए।",
          quote: "हम पहले दाँत डिज़ाइन करते हैं, फिर तय करते हैं कि इम्प्लांट कहाँ लगें।",
          training: ["BDS, 2008 (नमूना)", "MDS, प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज, 2012 (नमूना)", "पूरे जबड़े के इम्प्लांट प्रोस्थेटिक्स कोर्स, 2016 (नमूना)"],
          memberships: ["इंडियन प्रोस्थोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "amol-patil", name: "Dr. Amol Patil", photo: "/demo/img/people/dentist-m03-240.webp", gender: "male", visiting: true,
        qualification: "BDS, MDS (Periodontology)", specialisation: "Periodontist", focus: "Gum health before implants, soft-tissue grafts, treating inflamed gums around implants",
        experience: "11 years in practice", languages: ["Marathi", "Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Tuesdays and Thursdays, 4:30 to 7:30 pm",
        hi: { name: "डॉ. अमोल पाटिल", qualification: "BDS, MDS (पेरियोडॉन्टोलॉजी)", specialisation: "पेरियोडॉन्टिस्ट", focus: "इम्प्लांट से पहले मसूड़ों की सेहत, सॉफ़्ट-टिश्यू ग्राफ़्ट, इम्प्लांट के आसपास सूजे मसूड़ों का इलाज", experience: "11 साल का अनुभव", languages: ["मराठी", "हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगलवार और गुरुवार, शाम 4:30 से 7:30" },
      },
      {
        slug: "farah-sheikh", name: "Dr. Farah Sheikh", photo: "/demo/img/people/dentist-w02-240.webp", gender: "female",
        qualification: "BDS", specialisation: "General dentist", focus: "First consultations, extractions, dentures, implant maintenance visits",
        experience: "8 years in practice", languages: ["Hindi", "Urdu", "Marathi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        hi: { name: "डॉ. फ़रह शेख़", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "पहला परामर्श, दाँत निकालना, डेंचर, इम्प्लांट देखभाल विज़िट", experience: "8 साल का अनुभव", languages: ["हिंदी", "उर्दू", "मराठी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि" },
      },
    ],
    audience: [
      { title: "One missing tooth", body: "A single implant and crown, without cutting down the healthy teeth beside the gap.", hi: { title: "एक गायब दाँत", body: "एक इम्प्लांट और क्राउन, ख़ाली जगह के बगल के स्वस्थ दाँतों को घिसे बिना।" } },
      { title: "A loose denture", body: "Two to four implants can hold a lower denture firmly so it no longer lifts when you eat or speak.", hi: { title: "ढीला डेंचर", body: "दो से चार इम्प्लांट निचले डेंचर को मज़बूती से पकड़ सकते हैं, ताकि खाते या बोलते समय वह न उठे।" } },
      { title: "Many teeth missing or failing", body: "A fixed full-arch bridge on four to six implants, in place of a removable denture.", hi: { title: "कई दाँत गायब या ख़राब", body: "निकलने वाले डेंचर की जगह चार से छह इम्प्लांट पर पूरे जबड़े का फ़िक्स्ड ब्रिज।" } },
    ],
    candidate: [
      { title: "Enough bone, or a graft", body: "The CBCT scan shows whether there is enough bone. If not, a graft can often rebuild it first.", hi: { title: "पर्याप्त हड्डी, या ग्राफ़्ट", body: "CBCT स्कैन बताता है कि हड्डी पर्याप्त है या नहीं। न हो, तो अक्सर पहले ग्राफ़्ट से बनाई जा सकती है।" } },
      { title: "Diabetes under control", body: "A recent HbA1c report helps us plan; well-controlled diabetes is usually not a barrier.", hi: { title: "नियंत्रित डायबिटीज़", body: "हाल की HbA1c रिपोर्ट योजना में मदद करती है; अच्छी तरह नियंत्रित डायबिटीज़ आमतौर पर रुकावट नहीं।" } },
      { title: "Smoking", body: "Smoking slows healing and raises the risk of problems. Stopping around surgery makes a real difference.", hi: { title: "धूम्रपान", body: "धूम्रपान भरने की रफ़्तार धीमी करता है और समस्याओं का ख़तरा बढ़ाता है। सर्जरी के आसपास छोड़ने से असली फ़र्क़ पड़ता है।" } },
      { title: "Healthy gums", body: "Gum disease is treated before implants, and kept under control afterwards.", hi: { title: "स्वस्थ मसूड़े", body: "इम्प्लांट से पहले मसूड़ों की बीमारी का इलाज होता है, और बाद में उसे नियंत्रण में रखा जाता है।" } },
      { title: "Medicines", body: "Blood thinners, bone medicines and some cancer treatments change the plan. Bring your list.", hi: { title: "दवाएँ", body: "ख़ून पतला करने वाली, हड्डी की और कुछ कैंसर की दवाएँ योजना बदलती हैं। अपनी सूची लाएँ।" } },
    ],
    comparison: {
      title: "Ways to replace missing teeth",
      columns: ["Implant", "Bridge", "Removable denture"],
      rows: [
        { label: "What it involves", values: ["A titanium post in the bone, a crown on top", "Crowns on the teeth either side hold a false tooth", "A plate with teeth that you take out"], hi: { label: "इसमें क्या होता है", values: ["हड्डी में टाइटेनियम पोस्ट, ऊपर क्राउन", "दोनों ओर के दाँतों के क्राउन नकली दाँत पकड़ते हैं", "दाँतों वाली प्लेट जिसे आप निकालते हैं"] } },
        { label: "Neighbouring teeth", values: ["Left untouched", "Shaped for crowns", "Clasps may rest on them"], hi: { label: "बगल के दाँत", values: ["छुए नहीं जाते", "क्राउन के लिए घिसे जाते हैं", "उन पर क्लिप टिक सकती है"] } },
        { label: "Time to finish", values: ["3 to 6 months", "1 to 2 weeks", "3 to 4 weeks"], hi: { label: "पूरा होने में समय", values: ["3 से 6 महीने", "1 से 2 हफ़्ते", "3 से 4 हफ़्ते"] } },
        { label: "Visits", values: ["4 to 6", "2 to 3", "4 to 5"], hi: { label: "विज़िट", values: ["4 से 6", "2 से 3", "4 से 5"] } },
        { label: "Surgery", values: ["Yes, under local anaesthesia", "No", "No"], hi: { label: "सर्जरी", values: ["हाँ, लोकल एनेस्थीसिया में", "नहीं", "नहीं"] } },
        { label: "Bone in the gap", values: ["Helps keep it", "Shrinks slowly", "Shrinks slowly"], hi: { label: "ख़ाली जगह की हड्डी", values: ["बनाए रखने में मदद", "धीरे-धीरे घटती है", "धीरे-धीरे घटती है"] } },
        { label: "Cost", values: ["Highest", "Middle", "Lowest"], hi: { label: "ख़र्च", values: ["सबसे ज़्यादा", "बीच का", "सबसे कम"] } },
      ],
      note: "A general comparison. Which option suits you depends on your scan, gums and health; we explain it at the consultation.",
      hi: { title: "गायब दाँत बदलने के तरीक़े", columns: ["इम्प्लांट", "ब्रिज", "निकलने वाला डेंचर"], note: "एक सामान्य तुलना। आपके लिए कौन सा ठीक है, यह आपके स्कैन, मसूड़ों और सेहत पर निर्भर है; परामर्श में हम समझाते हैं।" },
    },
    journey: [
      { title: "Consultation and CBCT scan", body: "Examination, a 3D scan on site and a first talk about options, with family on video if you like.", hi: { title: "परामर्श और CBCT स्कैन", body: "जाँच, यहीं 3D स्कैन और विकल्पों पर पहली बात, चाहें तो वीडियो पर परिवार के साथ।" } },
      { title: "Plan and written estimate", body: "The surgeon and prosthodontist agree one plan; you get an itemised estimate and a timeline.", hi: { title: "योजना और लिखित अनुमान", body: "सर्जन और प्रोस्थोडॉन्टिस्ट एक योजना तय करते हैं; आपको मदवार अनुमान और समय-सीमा मिलती है।" } },
      { title: "Implant placement", body: "Under local anaesthesia, often with a printed surgical guide. A temporary tooth where possible.", hi: { title: "इम्प्लांट लगाना", body: "लोकल एनेस्थीसिया में, अक्सर प्रिंटेड सर्जिकल गाइड के साथ। जहाँ संभव हो, अस्थायी दाँत।" } },
      { title: "Healing", body: "Two to four months for the bone to bond. A check at one week and one month.", hi: { title: "भरना", body: "हड्डी को जुड़ने में दो से चार महीने। एक हफ़्ते और एक महीने पर जाँच।" } },
      { title: "Final teeth and maintenance", body: "Crowns, bridge or denture fitted, then a maintenance visit every six months.", hi: { title: "अंतिम दाँत और देखभाल", body: "क्राउन, ब्रिज या डेंचर लगाना, फिर हर छह महीने देखभाल विज़िट।" } },
    ],
    treatments: [
      {
        slug: "single-tooth-implant", name: "Single tooth implant", category: "Implants", icon: "implant", image: "/demo/img/dental/implant-crown-640.webp", featured: true, reason: "implants",
        summary: "One missing tooth replaced with an implant and a crown, without touching the teeth beside it.",
        what: "A single implant replaces one tooth from the root up. A titanium post is placed in the jawbone, the bone heals around it over a few months, and a crown is fixed on top. Unlike a bridge, the neighbouring teeth are not shaped, and the implant helps keep the bone in that spot.",
        symptoms: ["A gap from a tooth lost or removed", "A tooth that cannot be saved", "An old bridge that has failed"],
        whoNeedsIt: ["Adults with enough bone, or who can have a graft first", "People whose general health allows minor surgery"],
        steps: [
          { title: "Scan and plan", body: "CBCT scan, crown design and surgical plan.", hi: { title: "स्कैन और योजना", body: "CBCT स्कैन, क्राउन का डिज़ाइन और सर्जरी की योजना।" } },
          { title: "Place", body: "Under local anaesthesia, usually 45 to 60 minutes.", hi: { title: "लगाना", body: "लोकल एनेस्थीसिया में, आमतौर पर 45 से 60 मिनट।" } },
          { title: "Crown", body: "After two to four months of healing, the crown is fitted.", hi: { title: "क्राउन", body: "दो से चार महीने भरने के बाद क्राउन लगाया जाता है।" } },
        ],
        duration: "3 to 5 months", visits: "4 to 5 visits", recovery: "Swelling and soreness for 2 to 4 days. Soft food on that side for a week.",
        comfort: "Placed under local anaesthesia. Most people take the next day easy and are back to routine after that.",
        faqs: [
          { title: "Is a bridge not simpler?", body: "It is quicker, but it needs the teeth either side to be shaped for crowns. If those teeth are healthy, an implant spares them.", hi: { title: "क्या ब्रिज आसान नहीं है?", body: "यह जल्दी होता है, पर इसके लिए दोनों ओर के दाँत क्राउन के लिए घिसने पड़ते हैं। अगर वे दाँत स्वस्थ हैं, तो इम्प्लांट उन्हें बचाता है।" } },
          { title: "Can the implant be done the day the tooth is removed?", body: "Sometimes, if the bone and gum are healthy. The CBCT scan tells us whether an immediate implant is suitable.", hi: { title: "क्या दाँत निकालने के दिन ही इम्प्लांट लग सकता है?", body: "कभी-कभी, अगर हड्डी और मसूड़े स्वस्थ हों। CBCT स्कैन बताता है कि तुरंत इम्प्लांट ठीक है या नहीं।" } },
        ],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "एक दाँत का इम्प्लांट", category: "इम्प्लांट",
          summary: "एक गायब दाँत इम्प्लांट और क्राउन से, बगल के दाँतों को छुए बिना।",
          what: "एक इम्प्लांट एक दाँत को जड़ से बदलता है। जबड़े की हड्डी में टाइटेनियम पोस्ट लगाया जाता है, कुछ महीनों में हड्डी उसके चारों ओर भरती है, और ऊपर क्राउन लगता है। ब्रिज की तरह बगल के दाँत घिसे नहीं जाते, और इम्प्लांट उस जगह की हड्डी बनाए रखने में मदद करता है।",
          symptoms: ["गिरे या निकाले गए दाँत की ख़ाली जगह", "जो दाँत बच न सके", "पुराना ख़राब हुआ ब्रिज"],
          whoNeedsIt: ["पर्याप्त हड्डी वाले वयस्क, या जिन्हें पहले ग्राफ़्ट लग सके", "जिनकी सामान्य सेहत छोटी सर्जरी की अनुमति दे"],
          duration: "3 से 5 महीने", visits: "4 से 5 विज़िट", recovery: "2 से 4 दिन सूजन और दर्द। एक हफ़्ते उस तरफ़ नरम खाना।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है। ज़्यादातर लोग अगले दिन आराम करते हैं और उसके बाद सामान्य दिनचर्या में लौटते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "implant-bridge", name: "Implant bridge", category: "Implants", icon: "bridge", image: "/demo/img/dental/implant-bridge-model-640.webp", reason: "implants",
        summary: "Several missing teeth in a row replaced by a fixed bridge on two or three implants.",
        what: "When three or four teeth are missing next to each other, an implant for every tooth is rarely needed. Two or three implants can carry a fixed bridge that fills the whole gap, with fewer surgical sites and a lower cost than one implant per tooth.",
        symptoms: ["Several missing back teeth on one side", "A partial denture you would rather not wear"],
        whoNeedsIt: ["Adults with a gap of three or more teeth and enough bone at the ends"],
        steps: [
          { title: "Plan", body: "CBCT scan and bridge design decide the implant positions.", hi: { title: "योजना", body: "CBCT स्कैन और ब्रिज का डिज़ाइन इम्प्लांट की जगह तय करते हैं।" } },
          { title: "Place implants", body: "Two or three implants in one visit, under local anaesthesia.", hi: { title: "इम्प्लांट लगाना", body: "लोकल एनेस्थीसिया में एक विज़िट में दो या तीन इम्प्लांट।" } },
          { title: "Fix the bridge", body: "The bridge is screwed or cemented onto the implants after healing.", hi: { title: "ब्रिज लगाना", body: "भरने के बाद ब्रिज इम्प्लांट पर पेंच या सीमेंट से लगाया जाता है।" } },
        ],
        duration: "3 to 6 months", visits: "5 to 6 visits", recovery: "Swelling for 3 to 4 days; a soft diet for the first week.",
        comfort: "Placed under local anaesthesia. A temporary denture can fill the gap during healing.",
        faqs: [{ title: "Can I clean under an implant bridge?", body: "Yes, with interdental brushes or a water flosser. We show you how at the fitting.", hi: { title: "क्या इम्प्लांट ब्रिज के नीचे सफ़ाई हो सकती है?", body: "हाँ, इंटरडेंटल ब्रश या वॉटर फ़्लॉसर से। फ़िटिंग के समय हम तरीक़ा दिखाते हैं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "इम्प्लांट ब्रिज", category: "इम्प्लांट",
          summary: "एक कतार में कई गायब दाँत, दो या तीन इम्प्लांट पर फ़िक्स्ड ब्रिज से।",
          what: "जब तीन-चार दाँत साथ-साथ गायब हों, तो हर दाँत के लिए इम्प्लांट की ज़रूरत शायद ही होती है। दो या तीन इम्प्लांट पूरी ख़ाली जगह भरने वाला फ़िक्स्ड ब्रिज सँभाल सकते हैं, कम सर्जरी वाली जगहों और हर दाँत के एक इम्प्लांट से कम ख़र्च के साथ।",
          symptoms: ["एक तरफ़ पीछे के कई गायब दाँत", "आंशिक डेंचर जिसे आप पहनना नहीं चाहते"],
          whoNeedsIt: ["तीन या ज़्यादा दाँतों की ख़ाली जगह वाले वयस्क, जिनके सिरों पर पर्याप्त हड्डी हो"],
          duration: "3 से 6 महीने", visits: "5 से 6 विज़िट", recovery: "3 से 4 दिन सूजन; पहले हफ़्ते नरम खाना।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है। भरने के दौरान अस्थायी डेंचर जगह भर सकता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "full-arch-fixed-teeth", name: "Full-arch fixed teeth", category: "Full mouth", icon: "implant", image: "/demo/img/dental/implant-models-table-640.webp", featured: true, reason: "implants",
        summary: "A complete fixed set of teeth on four to six implants, in place of a removable denture.",
        what: "For a jaw with no teeth, or with teeth that cannot be saved, a full arch of fixed teeth can be screwed onto four to six implants. It does not come out at night and does not cover the palate. Where the bone allows, a fixed temporary set is fitted within days of surgery, and the final set a few months later.",
        symptoms: ["All teeth missing in a jaw", "Many loose or failing teeth", "A full denture that moves when you eat"],
        whoNeedsIt: ["Adults in reasonable health who want fixed teeth", "Those who can keep up cleaning and six-monthly reviews"],
        steps: [
          { title: "Records and design", body: "CBCT scan, photos and a trial set of teeth to approve.", hi: { title: "रिकॉर्ड और डिज़ाइन", body: "CBCT स्कैन, फ़ोटो और मंज़ूरी के लिए दाँतों का ट्रायल सेट।" } },
          { title: "Surgery day", body: "Remaining teeth removed if needed and implants placed, under local anaesthesia with sedation available.", hi: { title: "सर्जरी का दिन", body: "ज़रूरत हो तो बचे दाँत निकालना और इम्प्लांट लगाना, लोकल एनेस्थीसिया में, सेडेशन के विकल्प के साथ।" } },
          { title: "Temporary, then final teeth", body: "A fixed temporary set where suitable; the final set after 3 to 6 months.", hi: { title: "अस्थायी, फिर अंतिम दाँत", body: "जहाँ ठीक हो, फ़िक्स्ड अस्थायी सेट; 3 से 6 महीने बाद अंतिम सेट।" } },
        ],
        duration: "4 to 6 months", visits: "6 to 8 visits", recovery: "A soft diet for 6 to 8 weeks on the temporary teeth. Swelling for about a week.",
        comfort: "Done under local anaesthesia; conscious sedation can be arranged for longer surgery. We explain both at the planning visit.",
        faqs: [{ title: "Do I get teeth on the same day?", body: "Often a fixed temporary set within a few days, if the implants are stable enough. The scan and the surgery decide; we do not promise it in advance.", hi: { title: "क्या उसी दिन दाँत मिलते हैं?", body: "अगर इम्प्लांट पर्याप्त स्थिर हों तो अक्सर कुछ दिनों में फ़िक्स्ड अस्थायी सेट। यह स्कैन और सर्जरी से तय होता है; हम पहले से वादा नहीं करते।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "पूरे जबड़े के फ़िक्स्ड दाँत", category: "पूरा मुँह",
          summary: "निकलने वाले डेंचर की जगह चार से छह इम्प्लांट पर दाँतों का पूरा फ़िक्स्ड सेट।",
          what: "जिस जबड़े में दाँत न हों, या जिसके दाँत बच न सकें, उसके लिए चार से छह इम्प्लांट पर दाँतों का पूरा फ़िक्स्ड सेट पेंच से लगाया जा सकता है। यह रात में नहीं निकलता और तालू नहीं ढकता। जहाँ हड्डी अनुमति दे, सर्जरी के कुछ दिनों में फ़िक्स्ड अस्थायी सेट लगता है, और अंतिम सेट कुछ महीने बाद।",
          symptoms: ["एक जबड़े के सभी दाँत गायब", "कई ढीले या ख़राब दाँत", "पूरा डेंचर जो खाते समय हिलता है"],
          whoNeedsIt: ["ठीक-ठाक सेहत वाले वयस्क जो फ़िक्स्ड दाँत चाहते हैं", "जो सफ़ाई और हर छह महीने जाँच बनाए रख सकें"],
          duration: "4 से 6 महीने", visits: "6 से 8 विज़िट", recovery: "अस्थायी दाँतों पर 6 से 8 हफ़्ते नरम खाना। लगभग एक हफ़्ता सूजन।",
          comfort: "लोकल एनेस्थीसिया में; लंबी सर्जरी के लिए कॉन्शियस सेडेशन की व्यवस्था हो सकती है। योजना विज़िट में हम दोनों समझाते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "implant-dentures", name: "Implant-supported dentures", category: "Full mouth", icon: "denture", image: "/demo/img/dental/patient-older-woman-mirror-640.webp", featured: true, reason: "implants",
        summary: "A removable denture that clips onto two to four implants so it stays put.",
        what: "A lower denture often floats because there is little to hold it. Two to four implants with small attachments let the denture clip into place. It still comes out for cleaning, but it no longer lifts when you eat or speak. It costs less than a full fixed arch and suits people with less bone.",
        symptoms: ["A lower denture that lifts or rocks", "Sore spots from a moving denture", "Avoiding certain foods because of the denture"],
        whoNeedsIt: ["Denture wearers, especially for the lower jaw", "People who cannot have or do not want a fixed arch"],
        steps: [
          { title: "Check the denture", body: "A new denture is made if the current one does not fit well.", hi: { title: "डेंचर की जाँच", body: "मौजूदा डेंचर ठीक न बैठे तो नया बनाया जाता है।" } },
          { title: "Place implants", body: "Two to four implants under local anaesthesia.", hi: { title: "इम्प्लांट लगाना", body: "लोकल एनेस्थीसिया में दो से चार इम्प्लांट।" } },
          { title: "Connect", body: "After healing, attachments are fitted into the denture.", hi: { title: "जोड़ना", body: "भरने के बाद डेंचर में अटैचमेंट लगाए जाते हैं।" } },
        ],
        duration: "3 to 4 months", visits: "4 to 6 visits", recovery: "Soreness for a few days. The old denture is softened and relined to wear meanwhile.",
        comfort: "Placed under local anaesthesia; the surgery is usually shorter than for a fixed arch.",
        faqs: [{ title: "Do the attachments wear out?", body: "The small nylon inserts wear with use and are replaced at maintenance visits, usually every year or two.", hi: { title: "क्या अटैचमेंट घिसते हैं?", body: "छोटे नायलॉन इन्सर्ट इस्तेमाल से घिसते हैं और देखभाल विज़िट में बदले जाते हैं, आमतौर पर हर एक-दो साल।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "इम्प्लांट पर टिके डेंचर", category: "पूरा मुँह",
          summary: "निकलने वाला डेंचर जो दो से चार इम्प्लांट पर क्लिप होकर अपनी जगह टिका रहता है।",
          what: "निचला डेंचर अक्सर तैरता है क्योंकि उसे पकड़ने को कुछ नहीं होता। छोटे अटैचमेंट वाले दो से चार इम्प्लांट डेंचर को अपनी जगह क्लिप होने देते हैं। सफ़ाई के लिए यह अब भी निकलता है, पर खाते या बोलते समय नहीं उठता। यह पूरे फ़िक्स्ड जबड़े से सस्ता है और कम हड्डी वालों के लिए ठीक है।",
          symptoms: ["निचला डेंचर जो उठता या हिलता है", "हिलते डेंचर से दुखने वाली जगहें", "डेंचर की वजह से कुछ खाना छोड़ना"],
          whoNeedsIt: ["डेंचर पहनने वाले, ख़ासकर निचले जबड़े के लिए", "जो पूरा फ़िक्स्ड जबड़ा नहीं करा सकते या नहीं चाहते"],
          duration: "3 से 4 महीने", visits: "4 से 6 विज़िट", recovery: "कुछ दिन दर्द। इस बीच पहनने के लिए पुराने डेंचर को नरम परत से ठीक किया जाता है।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है; सर्जरी आमतौर पर फ़िक्स्ड जबड़े से छोटी होती है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "bone-grafting", name: "Bone grafting", category: "Grafting", icon: "shield", image: "/demo/img/dental/tech-3d-imaging-640.webp", reason: "implants",
        summary: "Rebuilding bone where it has shrunk, so an implant has enough support.",
        what: "After a tooth is lost, the bone in that area slowly shrinks. If the CBCT scan shows too little width or height for an implant, graft material can be added to rebuild it. Sometimes this is done at the same visit as the implant; sometimes it needs a few months to mature first.",
        symptoms: ["A tooth lost years ago", "A thin ridge seen on the scan", "Gum that has sunk in at a gap"],
        whoNeedsIt: ["Implant patients whose scan shows insufficient bone"],
        steps: [
          { title: "Measure", body: "Bone width and height measured on the CBCT scan.", hi: { title: "नाप", body: "CBCT स्कैन पर हड्डी की चौड़ाई और ऊँचाई नापी जाती है।" } },
          { title: "Graft", body: "Graft material placed and covered with a membrane, under local anaesthesia.", hi: { title: "ग्राफ़्ट", body: "लोकल एनेस्थीसिया में ग्राफ़्ट सामग्री रखकर झिल्ली से ढकी जाती है।" } },
          { title: "Mature", body: "Three to six months before the implant, if it was not placed at the same time.", hi: { title: "पकना", body: "अगर इम्प्लांट साथ न लगा हो, तो उससे पहले तीन से छह महीने।" } },
        ],
        duration: "Adds 3 to 6 months to treatment", visits: "1 surgical visit plus reviews", recovery: "Swelling for 3 to 5 days; avoid chewing on the area.",
        comfort: "Done under local anaesthesia.",
        faqs: [{ title: "Where does the graft come from?", body: "Usually a processed, sterile graft material, so no second surgical site is needed. We explain the options at planning.", hi: { title: "ग्राफ़्ट कहाँ से आता है?", body: "आमतौर पर प्रोसेस की हुई, स्टराइल ग्राफ़्ट सामग्री, ताकि दूसरी सर्जरी की जगह न चाहिए। योजना में हम विकल्प समझाते हैं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "बोन ग्राफ़्टिंग", category: "ग्राफ़्टिंग",
          summary: "जहाँ हड्डी घट गई हो, वहाँ फिर से बनाना ताकि इम्प्लांट को पर्याप्त सहारा मिले।",
          what: "दाँत गिरने के बाद उस जगह की हड्डी धीरे-धीरे घटती है। अगर CBCT स्कैन इम्प्लांट के लिए कम चौड़ाई या ऊँचाई दिखाए, तो ग्राफ़्ट सामग्री जोड़कर उसे फिर से बनाया जा सकता है। कभी यह इम्प्लांट वाली विज़िट में ही होता है; कभी पहले कुछ महीने पकने देना पड़ता है।",
          symptoms: ["सालों पहले गिरा दाँत", "स्कैन पर पतली हड्डी", "ख़ाली जगह पर धँसा मसूड़ा"],
          whoNeedsIt: ["इम्प्लांट मरीज़ जिनके स्कैन में हड्डी कम दिखे"],
          duration: "इलाज में 3 से 6 महीने जुड़ते हैं", visits: "1 सर्जिकल विज़िट और जाँच", recovery: "3 से 5 दिन सूजन; उस जगह से न चबाएँ।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "sinus-lift", name: "Sinus lift", category: "Grafting", icon: "cbct", image: "/demo/img/dental/doctor-desk-models-640.webp", reason: "implants",
        summary: "Adding bone under the sinus floor so implants can replace upper back teeth.",
        what: "Above the upper back teeth sits the sinus. When those teeth are lost, the bone below the sinus can be too thin for an implant. A sinus lift raises the sinus lining gently and adds graft beneath it. The CBCT scan decides whether it is needed and which approach suits.",
        symptoms: ["Missing upper molars", "A scan showing thin bone under the sinus"],
        whoNeedsIt: ["Patients wanting implants for upper back teeth with limited bone height"],
        steps: [
          { title: "Scan", body: "The sinus and bone height assessed in 3D.", hi: { title: "स्कैन", body: "साइनस और हड्डी की ऊँचाई 3D में देखी जाती है।" } },
          { title: "Lift and graft", body: "Under local anaesthesia, often with the implant at the same visit.", hi: { title: "लिफ़्ट और ग्राफ़्ट", body: "लोकल एनेस्थीसिया में, अक्सर उसी विज़िट में इम्प्लांट के साथ।" } },
          { title: "Heal", body: "Four to six months before the crown.", hi: { title: "भरना", body: "क्राउन से पहले चार से छह महीने।" } },
        ],
        duration: "Adds 4 to 6 months", visits: "1 surgical visit plus reviews", recovery: "Avoid blowing your nose hard and flying for about two weeks. Mild swelling is common.",
        comfort: "Done under local anaesthesia. We give written aftercare for the sinus.",
        faqs: [{ title: "Will it affect my breathing?", body: "No. The graft sits below the sinus lining, not in the airway.", hi: { title: "क्या इससे साँस पर असर पड़ेगा?", body: "नहीं। ग्राफ़्ट साइनस की झिल्ली के नीचे रहता है, साँस के रास्ते में नहीं।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "साइनस लिफ़्ट", category: "ग्राफ़्टिंग",
          summary: "साइनस के नीचे हड्डी जोड़ना ताकि ऊपर के पीछे के दाँत इम्प्लांट से बदले जा सकें।",
          what: "ऊपर के पीछे के दाँतों के ऊपर साइनस होता है। जब वे दाँत गिर जाते हैं, तो साइनस के नीचे की हड्डी इम्प्लांट के लिए बहुत पतली हो सकती है। साइनस लिफ़्ट में साइनस की झिल्ली धीरे से उठाकर नीचे ग्राफ़्ट डाला जाता है। CBCT स्कैन तय करता है कि इसकी ज़रूरत है या नहीं और कौन सा तरीक़ा ठीक है।",
          symptoms: ["ऊपर की गायब दाढ़ें", "स्कैन पर साइनस के नीचे पतली हड्डी"],
          whoNeedsIt: ["ऊपर के पीछे के दाँतों के लिए इम्प्लांट चाहने वाले, जिनकी हड्डी की ऊँचाई कम हो"],
          duration: "4 से 6 महीने जुड़ते हैं", visits: "1 सर्जिकल विज़िट और जाँच", recovery: "लगभग दो हफ़्ते ज़ोर से नाक न छिनकें और हवाई यात्रा न करें। हल्की सूजन आम है।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है। साइनस के लिए लिखित देखभाल निर्देश देते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "extraction-and-socket-preservation", name: "Extraction and socket preservation", category: "Grafting", icon: "extraction", image: "/demo/img/dental/sterile-instrument-tray-640.webp", reason: "not-sure",
        summary: "Removing a failing tooth gently and protecting the bone for a future implant.",
        what: "When a tooth has to come out and an implant may follow, how it is removed matters. We take it out as gently as possible to keep the surrounding bone, and may fill the socket with graft material so the ridge does not collapse while it heals.",
        symptoms: ["A cracked or badly broken tooth", "A tooth loose from gum disease", "A failed root canal"],
        whoNeedsIt: ["Anyone planning an implant after an extraction"],
        steps: [
          { title: "Plan", body: "X-ray or CBCT to decide on immediate or delayed implant.", hi: { title: "योजना", body: "तुरंत या बाद में इम्प्लांट तय करने के लिए एक्स-रे या CBCT।" } },
          { title: "Gentle removal", body: "Under local anaesthesia, protecting the bone walls.", hi: { title: "सावधानी से निकालना", body: "लोकल एनेस्थीसिया में, हड्डी की दीवारें बचाते हुए।" } },
          { title: "Preserve", body: "Graft and membrane placed if needed; stitches for a week.", hi: { title: "सुरक्षा", body: "ज़रूरत हो तो ग्राफ़्ट और झिल्ली; एक हफ़्ते टाँके।" } },
        ],
        duration: "One visit, plus a review", visits: "1 visit of 30 to 60 minutes", recovery: "Soft food for a few days; no smoking or straws for 72 hours.",
        comfort: "Done under local anaesthesia.",
        faqs: [{ title: "How soon can the implant go in?", body: "Sometimes the same day; otherwise usually after three to four months of healing.", hi: { title: "इम्प्लांट कितनी जल्दी लग सकता है?", body: "कभी उसी दिन; नहीं तो आमतौर पर तीन से चार महीने भरने के बाद।" } }],
        fromPrice: "1,500", priceNote: "per tooth, extraction only; graft after consultation",
        hi: {
          name: "दाँत निकालना और सॉकेट सुरक्षा", category: "ग्राफ़्टिंग",
          summary: "ख़राब दाँत को सावधानी से निकालना और भविष्य के इम्प्लांट के लिए हड्डी बचाना।",
          what: "जब दाँत निकालना हो और बाद में इम्प्लांट लग सकता हो, तो उसे निकालने का तरीक़ा मायने रखता है। हम आसपास की हड्डी बचाने के लिए उसे जितना हो सके सावधानी से निकालते हैं, और सॉकेट में ग्राफ़्ट भर सकते हैं ताकि भरने के दौरान हड्डी न धँसे।",
          symptoms: ["फटा या बुरी तरह टूटा दाँत", "मसूड़ों की बीमारी से ढीला दाँत", "असफल रूट कैनाल"],
          whoNeedsIt: ["दाँत निकालने के बाद इम्प्लांट की योजना बनाने वाले"],
          duration: "एक विज़िट, और एक जाँच", visits: "30 से 60 मिनट की 1 विज़िट", recovery: "कुछ दिन नरम खाना; 72 घंटे धूम्रपान या स्ट्रॉ नहीं।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है।", priceNote: "प्रति दाँत, सिर्फ़ निकालना; ग्राफ़्ट परामर्श के बाद",
        },
      },
      {
        slug: "complete-dentures", name: "Complete dentures", category: "Dentures", icon: "denture", image: "/demo/img/dental/patient-older-woman-talk-640.webp", reason: "not-sure",
        summary: "Well-fitted conventional dentures, designed by a prosthodontist, for those not choosing implants.",
        what: "Implants are not for everyone. A carefully made complete denture, with accurate impressions, a try-in and adjustment visits, can still give good function. It can also be converted to an implant denture later.",
        symptoms: ["No teeth in one or both jaws", "An old denture that no longer fits"],
        whoNeedsIt: ["People whose health or budget does not suit implants now"],
        steps: [
          { title: "Impressions", body: "Detailed moulds and bite records.", hi: { title: "नाप", body: "बारीक साँचे और काटने का रिकॉर्ड।" } },
          { title: "Try-in", body: "Teeth set in wax to check look and bite.", hi: { title: "ट्रायल", body: "रूप और काटने की जाँच के लिए मोम में दाँत।" } },
          { title: "Fit and adjust", body: "Final denture fitted and eased at reviews.", hi: { title: "फ़िटिंग और सुधार", body: "अंतिम डेंचर लगाकर जाँच में ठीक करना।" } },
        ],
        duration: "3 to 4 weeks", visits: "4 to 5 visits", recovery: "A few weeks to get used to eating and speaking with it.",
        comfort: "No injections are needed.",
        faqs: [{ title: "Can I add implants later?", body: "Yes. A well-made denture can often be adapted to clip onto implants in future.", hi: { title: "क्या बाद में इम्प्लांट जोड़ सकते हैं?", body: "हाँ। अच्छी तरह बना डेंचर अक्सर भविष्य में इम्प्लांट पर क्लिप होने लायक़ बदला जा सकता है।" } }],
        fromPrice: "18,000", priceNote: "per set, both jaws",
        hi: {
          name: "पूरे डेंचर", category: "डेंचर",
          summary: "इम्प्लांट न चुनने वालों के लिए प्रोस्थोडॉन्टिस्ट द्वारा डिज़ाइन किए, अच्छी तरह बैठने वाले सामान्य डेंचर।",
          what: "इम्प्लांट हर किसी के लिए नहीं होते। सही नाप, ट्रायल और सुधार विज़िट के साथ ध्यान से बना पूरा डेंचर भी अच्छा काम दे सकता है। इसे बाद में इम्प्लांट डेंचर में भी बदला जा सकता है।",
          symptoms: ["एक या दोनों जबड़ों में दाँत नहीं", "पुराना डेंचर जो अब ठीक नहीं बैठता"],
          whoNeedsIt: ["जिनकी सेहत या बजट अभी इम्प्लांट के लिए ठीक नहीं"],
          duration: "3 से 4 हफ़्ते", visits: "4 से 5 विज़िट", recovery: "इसके साथ खाने और बोलने की आदत में कुछ हफ़्ते।",
          comfort: "कोई इंजेक्शन नहीं लगता।", priceNote: "प्रति सेट, दोनों जबड़े",
        },
      },
      {
        slug: "implant-maintenance", name: "Implant maintenance", category: "Aftercare", icon: "cleaning", image: "/demo/img/dental/doctor-handpiece-care-640.webp", reason: "cleaning",
        summary: "A six-monthly check and professional clean of implants, bridges and dentures.",
        what: "Implants do not decay, but the gum and bone around them can become inflamed if plaque builds up. A maintenance visit checks the gum, the bite and the screws, cleans around each implant with instruments that do not scratch it, and takes an X-ray once a year.",
        symptoms: ["Bleeding around an implant", "A loose crown or bridge", "Six months since your last check"],
        whoNeedsIt: ["Everyone with implants, including those placed elsewhere"],
        steps: [
          { title: "Check", body: "Gums, bite and components examined.", hi: { title: "जाँच", body: "मसूड़े, काटना और पुर्ज़ों की जाँच।" } },
          { title: "Clean", body: "Implant-safe instruments and polishing.", hi: { title: "सफ़ाई", body: "इम्प्लांट के लिए सुरक्षित औज़ार और पॉलिश।" } },
          { title: "X-ray yearly", body: "To confirm the bone level is stable.", hi: { title: "सालाना एक्स-रे", body: "हड्डी का स्तर स्थिर होने की पुष्टि के लिए।" } },
        ],
        duration: "One visit", visits: "45 minutes", recovery: "None.",
        comfort: "Usually no anaesthetic.",
        faqs: [{ title: "Do you see implants placed at other clinics?", body: "Yes. Bring any records you have about the implant system; it helps us source parts if needed.", hi: { title: "क्या दूसरे क्लिनिक में लगे इम्प्लांट भी देखते हैं?", body: "हाँ। इम्प्लांट सिस्टम के जो भी रिकॉर्ड हों, लाएँ; ज़रूरत पड़ने पर पुर्ज़े मँगाने में मदद मिलती है।" } }],
        fromPrice: "2,000", priceNote: "per visit",
        hi: {
          name: "इम्प्लांट की देखभाल", category: "बाद की देखभाल",
          summary: "इम्प्लांट, ब्रिज और डेंचर की हर छह महीने जाँच और प्रोफ़ेशनल सफ़ाई।",
          what: "इम्प्लांट में कीड़ा नहीं लगता, पर प्लाक जमने से आसपास के मसूड़े और हड्डी में सूजन हो सकती है। देखभाल विज़िट में मसूड़े, काटना और पेंच जाँचे जाते हैं, हर इम्प्लांट के आसपास ऐसे औज़ारों से सफ़ाई होती है जो खरोंच न डालें, और साल में एक बार एक्स-रे लिया जाता है।",
          symptoms: ["इम्प्लांट के आसपास ख़ून", "ढीला क्राउन या ब्रिज", "पिछली जाँच को छह महीने"],
          whoNeedsIt: ["इम्प्लांट वाले सभी, कहीं और लगे इम्प्लांट समेत"],
          duration: "एक विज़िट", visits: "45 मिनट", recovery: "कुछ नहीं।",
          comfort: "आमतौर पर सुन्न करने की ज़रूरत नहीं।", priceNote: "प्रति विज़िट",
        },
      },
    ],
    technology: [
      { title: "3D CBCT imaging", benefit: "Shows the height and width of bone and the position of nerves and sinuses, so each implant is planned before surgery, not during it.", group: "diagnosis", icon: "cbct", image: "/demo/img/dental/tech-3d-imaging-640.webp", hi: { title: "3D CBCT इमेजिंग", benefit: "हड्डी की ऊँचाई-चौड़ाई और नसों व साइनस की जगह दिखाता है, ताकि हर इम्प्लांट की योजना सर्जरी से पहले बने, उसके दौरान नहीं।" } },
      { title: "Guided implant surgery", benefit: "A surgical guide printed from your plan helps place implants at the planned angle and depth, often through smaller openings.", group: "precision", icon: "implant", hi: { title: "गाइडेड इम्प्लांट सर्जरी", benefit: "आपकी योजना से प्रिंट की गई सर्जिकल गाइड इम्प्लांट को तय कोण और गहराई पर लगाने में मदद करती है, अक्सर छोटे चीरे से।" } },
      { title: "Intraoral scanner", benefit: "Digital impressions of implants and teeth, without trays of impression paste.", group: "precision", icon: "scan", image: "/demo/img/dental/tech-intraoral-scanner-640.webp", hi: { title: "इंट्राओरल स्कैनर", benefit: "इम्प्लांट और दाँतों का डिजिटल नाप, साँचे के पेस्ट वाली ट्रे के बिना।" } },
      { title: "In-house dental lab", benefit: "Temporary teeth, adjustments and repairs done on site, which saves visits and days.", group: "speed", icon: "crown", image: "/demo/img/dental/implant-models-table-640.webp", hi: { title: "अपनी डेंटल लैब", benefit: "अस्थायी दाँत, सुधार और मरम्मत यहीं, जिससे विज़िट और दिन बचते हैं।" } },
      { title: "Digital X-rays", benefit: "Low-dose check X-rays at each stage, shown to you on screen.", group: "diagnosis", icon: "xray", image: "/demo/img/dental/tech-xray-tablet-640.webp", hi: { title: "डिजिटल एक्स-रे", benefit: "हर चरण पर कम डोज़ वाले जाँच एक्स-रे, स्क्रीन पर आपको दिखाए जाते हैं।" } },
    ],
    fees: [
      { treatment: "Implant consultation", from: "800", unit: "per visit", group: "Consultation", note: "Examination and discussion of options", hi: { treatment: "इम्प्लांट परामर्श", unit: "प्रति विज़िट", group: "परामर्श", note: "जाँच और विकल्पों पर चर्चा" } },
      { treatment: "3D CBCT scan, one jaw", from: "3,000", unit: "per scan", group: "Consultation", hi: { treatment: "3D CBCT स्कैन, एक जबड़ा", unit: "प्रति स्कैन", group: "परामर्श" } },
      { treatment: "Single tooth implant with crown", slug: "single-tooth-implant", consult: true, group: "Implants", note: "Itemised estimate: implant, abutment, crown", hi: { treatment: "क्राउन के साथ एक दाँत का इम्प्लांट", group: "इम्प्लांट", note: "मदवार अनुमान: इम्प्लांट, एबटमेंट, क्राउन" } },
      { treatment: "Implant bridge", slug: "implant-bridge", consult: true, group: "Implants", hi: { treatment: "इम्प्लांट ब्रिज", group: "इम्प्लांट" } },
      { treatment: "Full-arch fixed teeth", slug: "full-arch-fixed-teeth", consult: true, group: "Full mouth", note: "Temporary and final sets itemised", hi: { treatment: "पूरे जबड़े के फ़िक्स्ड दाँत", group: "पूरा मुँह", note: "अस्थायी और अंतिम सेट अलग-अलग" } },
      { treatment: "Implant-supported denture", slug: "implant-dentures", consult: true, group: "Full mouth", hi: { treatment: "इम्प्लांट पर टिका डेंचर", group: "पूरा मुँह" } },
      { treatment: "Bone graft", slug: "bone-grafting", consult: true, group: "Grafting", hi: { treatment: "बोन ग्राफ़्ट", group: "ग्राफ़्टिंग" } },
      { treatment: "Sinus lift", slug: "sinus-lift", consult: true, group: "Grafting", hi: { treatment: "साइनस लिफ़्ट", group: "ग्राफ़्टिंग" } },
      { treatment: "Extraction", slug: "extraction-and-socket-preservation", from: "1,500", unit: "per tooth", group: "Grafting", hi: { treatment: "दाँत निकालना", unit: "प्रति दाँत", group: "ग्राफ़्टिंग" } },
      { treatment: "Complete dentures", slug: "complete-dentures", from: "18,000", unit: "both jaws", group: "Dentures", hi: { treatment: "पूरे डेंचर", unit: "दोनों जबड़े", group: "डेंचर" } },
      { treatment: "Implant maintenance visit", slug: "implant-maintenance", from: "2,000", unit: "per visit", group: "Aftercare", hi: { treatment: "इम्प्लांट देखभाल विज़िट", unit: "प्रति विज़िट", group: "बाद की देखभाल" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: Rs 60,000 over 12 months is about Rs 5,000 a month before any lender charges. Your estimate decides the amount.",
      partners: ["Card EMI through your bank", "A healthcare finance partner (sample)"],
      modes: ["UPI", "Debit and credit cards", "Net banking", "Cash"],
      insurance: "Most health policies do not cover implants. Where treatment follows an accident, we provide reports for your claim.",
      consultFee: "Implant consultation: Rs 800. The CBCT scan is charged separately. Treatment is charged as per the estimate you approve, in stages.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: 12 महीने में 60,000 रुपये, किसी भी शुल्क से पहले लगभग 5,000 रुपये महीना। राशि आपका अनुमान तय करता है।",
        partners: ["आपके बैंक के कार्ड पर EMI", "एक हेल्थकेयर फ़ाइनेंस साथी (नमूना)"],
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नेट बैंकिंग", "नक़द"],
        insurance: "ज़्यादातर हेल्थ पॉलिसी इम्प्लांट कवर नहीं करतीं। दुर्घटना के बाद के इलाज में हम आपके क्लेम के लिए रिपोर्ट देते हैं।",
        consultFee: "इम्प्लांट परामर्श: 800 रुपये। CBCT स्कैन का शुल्क अलग। इलाज का शुल्क आपके मंज़ूर किए अनुमान के अनुसार, चरणों में।",
      },
    },
    cases: [
      { category: "Implants", title: "Single lower molar replaced with an implant crown", treatment: "single-tooth-implant", duration: "4 months, 4 visits", hi: { category: "इम्प्लांट", title: "नीचे की एक दाढ़ की जगह इम्प्लांट क्राउन", duration: "4 महीने, 4 विज़िट" } },
      { category: "Implants", title: "Missing upper front tooth replaced, with a temporary tooth during healing", treatment: "single-tooth-implant", duration: "5 months, 5 visits", hi: { category: "इम्प्लांट", title: "ऊपर का गायब आगे का दाँत बदला, भरने के दौरान अस्थायी दाँत के साथ", duration: "5 महीने, 5 विज़िट" } },
      { category: "Implants", title: "Three missing lower back teeth replaced with a bridge on two implants", treatment: "implant-bridge", duration: "5 months, 6 visits", hi: { category: "इम्प्लांट", title: "नीचे के पीछे के तीन गायब दाँत दो इम्प्लांट पर ब्रिज से", duration: "5 महीने, 6 विज़िट" } },
      { category: "Full arch", title: "Upper jaw restored with fixed teeth on six implants", treatment: "full-arch-fixed-teeth", duration: "6 months, 8 visits", hi: { category: "पूरा जबड़ा", title: "छह इम्प्लांट पर फ़िक्स्ड दाँतों से ऊपर का जबड़ा", duration: "6 महीने, 8 विज़िट" } },
      { category: "Implant dentures", title: "Loose lower denture stabilised on two implants", treatment: "implant-dentures", duration: "3 months, 5 visits", hi: { category: "इम्प्लांट डेंचर", title: "ढीला निचला डेंचर दो इम्प्लांट पर स्थिर", duration: "3 महीने, 5 विज़िट" } },
      { category: "Bone graft", title: "Thin ridge rebuilt with a graft before an implant", treatment: "bone-grafting", duration: "8 months, 6 visits", hi: { category: "बोन ग्राफ़्ट", title: "इम्प्लांट से पहले पतली हड्डी ग्राफ़्ट से बनाई गई", duration: "8 महीने, 6 विज़िट" } },
    ],
    international: {
      intro: "Patients from other cities and from abroad, often visiting parents in Pune, plan implant treatment with us around their trips. Implants need at least two visits a few months apart, so we plan the dates with you before you book tickets.",
      steps: [
        { title: "Send your scans", body: "Recent X-rays or a CBCT scan and photos, by email or WhatsApp.", hi: { title: "स्कैन भेजें", body: "हाल के एक्स-रे या CBCT स्कैन और फ़ोटो, ईमेल या व्हाट्सऐप पर।" } },
        { title: "Video consultation", body: "Options, a provisional estimate and a suggested trip plan.", hi: { title: "वीडियो परामर्श", body: "विकल्प, अस्थायी अनुमान और सुझाई गई यात्रा योजना।" } },
        { title: "First trip: surgery", body: "Scan, confirmed estimate and implant placement, with a review before you fly.", hi: { title: "पहली यात्रा: सर्जरी", body: "स्कैन, पक्का अनुमान और इम्प्लांट, उड़ान से पहले जाँच के साथ।" } },
        { title: "Healing at home", body: "Video check-ins while the bone heals.", hi: { title: "घर पर भरना", body: "हड्डी भरने के दौरान वीडियो पर जाँच।" } },
        { title: "Second trip: teeth", body: "Final crowns, bridge or arch fitted, with your records to take home.", hi: { title: "दूसरी यात्रा: दाँत", body: "अंतिम क्राउन, ब्रिज या जबड़ा, साथ ले जाने के लिए आपके रिकॉर्ड के साथ।" } },
      ],
      stays: [
        { title: "Single implant", body: "Two trips of 3 to 5 days, 3 to 4 months apart.", hi: { title: "एक इम्प्लांट", body: "3 से 4 महीने के अंतर पर 3 से 5 दिन की दो यात्राएँ।" } },
        { title: "Full-arch fixed teeth", body: "First trip of about 10 days; second of about a week, 4 to 6 months later.", hi: { title: "पूरे जबड़े के फ़िक्स्ड दाँत", body: "पहली यात्रा लगभग 10 दिन; दूसरी लगभग एक हफ़्ता, 4 से 6 महीने बाद।" } },
        { title: "With a bone graft or sinus lift", body: "Allow an extra trip, or a longer gap between trips.", hi: { title: "बोन ग्राफ़्ट या साइनस लिफ़्ट के साथ", body: "एक अतिरिक्त यात्रा, या यात्राओं के बीच लंबा अंतर रखें।" } },
      ],
      hi: { intro: "दूसरे शहरों और विदेश से आने वाले मरीज़, अक्सर पुणे में माता-पिता से मिलने आए लोग, अपनी यात्राओं के हिसाब से हमारे साथ इम्प्लांट की योजना बनाते हैं। इम्प्लांट में कुछ महीनों के अंतर पर कम से कम दो विज़िट लगती हैं, इसलिए टिकट बुक करने से पहले हम आपके साथ तारीख़ें तय करते हैं।" },
    },
    booking: {
      reasons: [
        { id: "implants", label: "Missing tooth or implants", icon: "implant", treatment: "single-tooth-implant", hi: { label: "गायब दाँत या इम्प्लांट" } },
        { id: "dentures", label: "Loose denture", icon: "denture", treatment: "implant-dentures", hi: { label: "ढीला डेंचर" } },
        { id: "checkup", label: "Second opinion on a plan", icon: "checkup", hi: { label: "किसी योजना पर दूसरी राय" } },
        { id: "cleaning", label: "Implant check or cleaning", icon: "cleaning", treatment: "implant-maintenance", hi: { label: "इम्प्लांट जाँच या सफ़ाई" } },
        { id: "pain", label: "Pain or a broken tooth", icon: "pain", urgent: true, treatment: "extraction-and-socket-preservation", hi: { label: "दर्द या टूटा दाँत" } },
      ],
      morning: ["9:30 am", "10:30 am", "11:30 am", "12:30 pm"],
      evening: ["4:30 pm", "5:30 pm", "6:30 pm"],
      closedDays: [0],
      closedNote: "Closed on Sundays",
      hi: { closedNote: "रविवार बंद" },
    },
    sessions: [
      { days: [1, 2, 3, 4, 5, 6], from: "09:30", to: "13:30" },
      { days: [1, 2, 3, 4, 5, 6], from: "16:30", to: "19:30" },
    ],
    reach: {
      transit: "Ten minutes by auto from the Baner bus stops on the main road.",
      parking: "Covered parking in the building basement; drop-off at the lobby door.",
      access: "Lift from the lobby, step-free throughout. Wheelchair available at reception.",
      hi: {
        transit: "मुख्य सड़क पर बाणेर बस स्टॉप से ऑटो से दस मिनट।",
        parking: "इमारत के बेसमेंट में ढकी पार्किंग; लॉबी के दरवाज़े पर उतरने की जगह।",
        access: "लॉबी से लिफ़्ट, हर जगह बिना सीढ़ी। रिसेप्शन पर व्हीलचेयर उपलब्ध।",
      },
    },
    sterilisation: [
      { title: "Clean", body: "Surgical instruments are cleaned in an ultrasonic bath and inspected.", hi: { title: "सफ़ाई", body: "सर्जिकल औज़ार अल्ट्रासोनिक बाथ में साफ़ करके जाँचे जाते हैं।" } },
      { title: "Pack", body: "Each surgical kit is sealed in a dated pouch with an indicator strip.", hi: { title: "पैक", body: "हर सर्जिकल किट संकेतक पट्टी के साथ तारीख़ वाले पाउच में सील होती है।" } },
      { title: "Sterilise", body: "Class B autoclave cycles, tested and logged every day.", hi: { title: "स्टरलाइज़", body: "क्लास B ऑटोक्लेव चक्र, रोज़ जाँच और रिकॉर्ड।" } },
      { title: "Sterile field", body: "Surgery under sterile drapes; implants are opened from sealed packs in front of you.", hi: { title: "स्टराइल क्षेत्र", body: "स्टराइल चादरों के नीचे सर्जरी; इम्प्लांट आपके सामने सील पैक से खोले जाते हैं।" } },
    ],
    trust: [
      { title: "Surgeon and prosthodontist plan together", body: "One plan, agreed on one scan, before surgery is booked.", hi: { title: "सर्जन और प्रोस्थोडॉन्टिस्ट साथ योजना बनाते हैं", body: "सर्जरी बुक होने से पहले एक स्कैन पर तय एक योजना।" } },
      { title: "Itemised estimates", body: "Scan, implant, abutment, graft and crown listed separately.", hi: { title: "मदवार अनुमान", body: "स्कैन, इम्प्लांट, एबटमेंट, ग्राफ़्ट और क्राउन अलग-अलग।" } },
      { title: "Honest about suitability", body: "We tell you if implants are not the right choice, and why.", hi: { title: "उपयुक्तता पर ईमानदारी", body: "अगर इम्प्लांट सही विकल्प नहीं है तो हम बताते हैं, और क्यों।" } },
      { title: "Records you keep", body: "Implant system, batch and size recorded and given to you.", hi: { title: "आपके पास रहने वाले रिकॉर्ड", body: "इम्प्लांट सिस्टम, बैच और आकार दर्ज करके आपको दिया जाता है।" } },
    ],
    comfort: [
      { title: "Local anaesthesia, and sedation on request", body: "Longer surgeries can be done with conscious sedation, discussed at planning.", hi: { title: "लोकल एनेस्थीसिया, और कहने पर सेडेशन", body: "लंबी सर्जरी कॉन्शियस सेडेशन के साथ हो सकती है, योजना में चर्चा होती है।" } },
      { title: "A calm first visit", body: "The first consultation is long and unhurried, with family welcome.", hi: { title: "शांत पहली विज़िट", body: "पहला परामर्श लंबा और बिना जल्दबाज़ी का, परिवार का स्वागत।" } },
      { title: "Follow-up calls", body: "We call the day after surgery to check how you are.", hi: { title: "फ़ॉलो-अप कॉल", body: "सर्जरी के अगले दिन हम हाल पूछने के लिए फ़ोन करते हैं।" } },
    ],
  },
});
