/**
 * d5-ortho-aligners: Bakul Orthodontic Clinic, Malviya Nagar, Jaipur.
 * An orthodontist-led clinic: metal, ceramic, self-ligating and lingual
 * braces, clear aligners, early checks at seven and retainers, with a
 * problem picker, a braces-versus-aligners table and evening hours.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md. Everything here is fiction: the clinic, the doctors,
 * the reviews, the rating, the cases and the trust figures are SAMPLE content
 * and carry the SampleNote label until the clinic replaces them. Cases have
 * no photos. Name forms exactly as in TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Bakul Orthodontic Clinic",
  shortName: "Bakul Ortho",
  tagline: "Metal and ceramic braces, clear aligners and early checks for children in Malviya Nagar, Jaipur.",
  city: "Jaipur",
  state: "Rajasthan",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2016",
  establishedYear: "2016",
  sitePages: [...DENTAL_PAGE_SETS["d5-ortho-aligners"]],
  heroImage: "/demo/img/dental/hero-aligner-smile-800.webp",
  sectionPhotos: { about: "/demo/img/dental/interior-open-shelves-640.webp" },
  photos: [
    { src: "/demo/img/dental/interior-open-shelves-640.webp", alt: "", category: "Clinic", caption: "Treatment area", hi: { category: "क्लिनिक", caption: "इलाज का हिस्सा" } },
    { src: "/demo/img/dental/interior-consult-room-640.webp", alt: "", category: "Clinic", caption: "Consultation room", hi: { category: "क्लिनिक", caption: "परामर्श कक्ष" } },
    { src: "/demo/img/dental/tech-intraoral-scanner-640.webp", alt: "", category: "Technology", caption: "Intraoral scanner", hi: { category: "तकनीक", caption: "इंट्राओरल स्कैनर" } },
    { src: "/demo/img/dental/ortho-aligners-vs-braces-640.webp", alt: "", category: "Treatment", caption: "Aligners and braces models", hi: { category: "इलाज", caption: "अलाइनर और ब्रेसेज़ के मॉडल" } },
  ],
  about:
    "Bakul Orthodontic Clinic opened in 2016 as a clinic that does one thing: straightening teeth and correcting bites. Every patient is examined and planned by an orthodontist with an MDS in the specialty, from a seven-year-old's first check to an adult's aligners.\n\nWe see most patients after school and work, so the clinic is open until 9 pm on weekdays and on Sunday mornings. Before any braces or aligners are fitted, you see your plan on a 3D model, the likely time it will take and a written estimate with the monthly payment option spelled out.",
  mission: "Orthodontic care planned by specialists, explained on a 3D model, at hours that suit school and work.",
  vision: "A healthy bite and a confident smile for every child and adult who asks, at a pace that fits their life.",
  hi: {
    instituteName: "बकुल ऑर्थोडॉन्टिक क्लिनिक",
    shortName: "बकुल",
    tagline: "मेटल और सिरेमिक ब्रेसेज़, क्लियर अलाइनर और बच्चों की शुरुआती जाँच, मालवीय नगर, जयपुर में।",
    city: "जयपुर",
    state: "राजस्थान",
    established: "2016 से",
    establishedYear: "2016",
    about:
      "बकुल ऑर्थोडॉन्टिक क्लिनिक 2016 में एक ही काम करने वाले क्लिनिक के रूप में शुरू हुआ: दाँत सीधे करना और काटने का तरीक़ा ठीक करना। हर मरीज़ की जाँच और योजना इसी विशेषज्ञता में MDS वाले ऑर्थोडॉन्टिस्ट करते हैं, सात साल के बच्चे की पहली जाँच से लेकर वयस्क के अलाइनर तक।\n\nज़्यादातर मरीज़ स्कूल और काम के बाद आते हैं, इसलिए क्लिनिक हफ़्ते के दिनों में रात 9 बजे तक और रविवार सुबह खुला रहता है। कोई भी ब्रेसेज़ या अलाइनर लगाने से पहले आप 3D मॉडल पर अपनी योजना, लगने वाला संभावित समय और मासिक भुगतान के विकल्प के साथ लिखित अनुमान देखते हैं।",
    mission: "विशेषज्ञों द्वारा योजनाबद्ध ऑर्थोडॉन्टिक देखभाल, 3D मॉडल पर समझाई हुई, स्कूल और काम के हिसाब से समय पर।",
    vision: "हर बच्चे और वयस्क के लिए स्वस्थ काटना और आत्मविश्वास भरी मुस्कान, उनकी ज़िंदगी की रफ़्तार से।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "smile@example.com",
    addressLines: ["Example Road", "Malviya Nagar, Jaipur 302000"],
    hours: "Mon to Sat, 11 am to 2 pm and 5 to 9 pm. Sun, 10 am to 1 pm",
    landmark: "Ground floor, near the Malviya Nagar main market",
    mapQuery: "Malviya Nagar, Jaipur",
    hi: {
      addressLines: ["उदाहरण रोड", "मालवीय नगर, जयपुर 302000"],
      hours: "सोम से शनि, सुबह 11 से दोपहर 2 और शाम 5 से रात 9। रवि, सुबह 10 से दोपहर 1",
      landmark: "भूतल, मालवीय नगर मुख्य बाज़ार के पास",
    },
  },
  stats: [
    { value: "10", label: "Years in Malviya Nagar", basis: "Since 2016", hi: { label: "साल मालवीय नगर में", basis: "2016 से" } },
    { value: "2", label: "MDS orthodontists", basis: "Every plan made by a specialist", hi: { label: "MDS ऑर्थोडॉन्टिस्ट", basis: "हर योजना विशेषज्ञ द्वारा" } },
    { value: "9 pm", label: "Open until, Monday to Saturday", basis: "Evening slots after school and work", hi: { label: "तक खुला, सोमवार से शनिवार", basis: "स्कूल और काम के बाद शाम के स्लॉट" } },
  ],
  rating: { value: "4.9", count: "297", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "Dr. Agarwal showed my son the 3D model of how his teeth would move before we said yes. Evening appointments after tuition made the two years manageable.", relation: "Parent, metal braces", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Braces", hi: { quote: "डॉ. अग्रवाल ने हाँ कहने से पहले मेरे बेटे को 3D मॉडल पर दिखाया कि उसके दाँत कैसे खिसकेंगे। ट्यूशन के बाद शाम की अपॉइंटमेंट से दो साल आसानी से निकल गए।", relation: "माता-पिता, मेटल ब्रेसेज़", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "ब्रेसेज़" } },
    { quote: "I wanted aligners but was told honestly that my bite needed braces. Ceramic braces were a good middle ground and nobody at work noticed much.", relation: "Patient, ceramic braces", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Braces", hi: { quote: "मैं अलाइनर चाहती थी पर ईमानदारी से बताया गया कि मेरे काटने के लिए ब्रेसेज़ चाहिए। सिरेमिक ब्रेसेज़ अच्छा बीच का रास्ता रहे और दफ़्तर में किसी ने ख़ास ध्यान नहीं दिया।", relation: "मरीज़, सिरेमिक ब्रेसेज़", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "ब्रेसेज़" } },
    { quote: "Clear aligners for crowding. The monthly payment option was explained on paper, and the check-ins every six weeks were quick.", relation: "Patient, clear aligners", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Aligners", hi: { quote: "भीड़ वाले दाँतों के लिए क्लियर अलाइनर। मासिक भुगतान का विकल्प काग़ज़ पर समझाया गया, और हर छह हफ़्ते की जाँच जल्दी हो जाती थी।", relation: "मरीज़, क्लियर अलाइनर", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "अलाइनर" } },
    { quote: "Brought my seven-year-old for an early check as our family dentist suggested. They said no treatment yet and to come back in a year. Appreciated the honesty.", relation: "Parent, early check", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Kids", hi: { quote: "हमारे फ़ैमिली डेंटिस्ट के कहने पर अपनी सात साल की बेटी को शुरुआती जाँच के लिए लाई। उन्होंने कहा अभी इलाज नहीं, एक साल बाद आएँ। ईमानदारी अच्छी लगी।", relation: "माता-पिता, शुरुआती जाँच", source: "गूगल रिव्यू", date: "जून 2026", category: "बच्चे" } },
    { quote: "A wire broke on a Sunday and they fixed it the same morning. Wearing my retainer every night now as told.", relation: "Patient, self-ligating braces", rating: "5", source: "Google review", date: "May 2026", consent: true, category: "Braces", hi: { quote: "रविवार को एक तार टूट गया और उन्होंने उसी सुबह ठीक कर दिया। अब बताए अनुसार हर रात रिटेनर पहनता हूँ।", relation: "मरीज़, सेल्फ़-लिगेटिंग ब्रेसेज़", source: "गूगल रिव्यू", date: "मई 2026", category: "ब्रेसेज़" } },
    { quote: "Good treatment, but the evening slots fill up quickly, so book your next visit before you leave.", relation: "Parent, jaw growth appliance", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Kids", hi: { quote: "इलाज अच्छा है, पर शाम के स्लॉट जल्दी भर जाते हैं, इसलिए जाने से पहले अगली विज़िट बुक कर लें।", relation: "माता-पिता, जबड़े की ग्रोथ का उपकरण", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "बच्चे" } },
  ],
  posts: [
    {
      slug: "braces-or-clear-aligners", title: "Braces or clear aligners: how to choose", date: "17 Sep 2026", category: "Aligners", treatment: "clear-aligners",
      author: "Dr. Pooja Agarwal", reviewedBy: "Medically reviewed by Dr. Pooja Agarwal, MDS (Orthodontics and Dentofacial Orthopaedics)",
      excerpt: "Both move teeth well in the right case. The deciding questions are the kind of movement you need and whether you will wear aligners 22 hours a day.",
      body: "Braces are fixed to the teeth, so they work all the time without you having to remember anything. They handle almost every kind of case, including large rotations and bite corrections. Metal braces cost the least; ceramic braces are tooth-coloured and less visible.\n\nClear aligners are a series of thin, removable trays. They are nearly invisible and come out for meals and brushing. They only move teeth while they are worn, so they need about 22 hours a day. Some movements are harder with aligners and may need small tooth-coloured attachments.\n\nThe right choice starts with an examination, X-rays and a scan, not with a price list. Your orthodontist should tell you which option suits your teeth, how long each would take, and the cost of each as a starting-from figure, with the final cost depending on your diagnosis.",
      hi: {
        title: "ब्रेसेज़ या क्लियर अलाइनर: कैसे चुनें", date: "17 सितंबर 2026", category: "अलाइनर", author: "डॉ. पूजा अग्रवाल", reviewedBy: "डॉ. पूजा अग्रवाल, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "सही केस में दोनों दाँत अच्छी तरह खिसकाते हैं। फ़ैसला इस पर है कि किस तरह की हलचल चाहिए और क्या आप दिन में 22 घंटे अलाइनर पहनेंगे।",
        body: "ब्रेसेज़ दाँतों पर लगे रहते हैं, इसलिए कुछ याद रखे बिना हर समय काम करते हैं। ये लगभग हर तरह के केस सँभालते हैं, बड़े घुमाव और काटने के सुधार समेत। मेटल ब्रेसेज़ सबसे सस्ते हैं; सिरेमिक ब्रेसेज़ दाँत के रंग के होते हैं और कम दिखते हैं।\n\nक्लियर अलाइनर पतली, निकालने वाली ट्रे की एक सीरीज़ हैं। ये लगभग दिखते नहीं और खाने व ब्रश के समय निकल जाते हैं। ये सिर्फ़ पहनने पर दाँत खिसकाते हैं, इसलिए दिन में लगभग 22 घंटे पहनने होते हैं। कुछ हलचल अलाइनर से मुश्किल होती है और छोटे दाँत के रंग के अटैचमेंट लग सकते हैं।\n\nसही चुनाव जाँच, एक्स-रे और स्कैन से शुरू होता है, क़ीमत की सूची से नहीं। आपके ऑर्थोडॉन्टिस्ट को बताना चाहिए कि कौन सा विकल्प आपके दाँतों के लिए ठीक है, हर एक में कितना समय लगेगा, और हर एक का शुरुआती ख़र्च, जहाँ अंतिम ख़र्च आपके निदान पर निर्भर है।",
      },
    },
    {
      slug: "when-should-a-child-see-an-orthodontist", title: "When should a child first see an orthodontist?", date: "3 Sep 2026", category: "Kids", treatment: "early-orthodontic-check",
      author: "Dr. Rahul Khandelwal", reviewedBy: "Medically reviewed by Dr. Rahul Khandelwal, MDS (Orthodontics and Dentofacial Orthopaedics)",
      excerpt: "Around age seven. Most children will not need treatment then, but some jaw problems are easier to guide while the child is still growing.",
      body: "By about seven, the first adult molars and front teeth are in, and an orthodontist can see how the jaws and bite are developing. That is the right time for a first check.\n\nMost children are simply reviewed once a year until more adult teeth arrive. A few benefit from early treatment: a crossbite, where upper teeth bite inside the lower ones; a narrow upper jaw; front teeth that stick out and are easily injured; or habits such as thumb sucking that are changing the bite.\n\nEarly treatment uses simple appliances to guide jaw growth. It can make later braces shorter or simpler, though many of these children still need braces in their teens.\n\nSigns worth an earlier visit: milk teeth lost very early or very late, mouth breathing, trouble biting, or teeth that meet unevenly.",
      hi: {
        title: "बच्चे को पहली बार ऑर्थोडॉन्टिस्ट को कब दिखाएँ?", date: "3 सितंबर 2026", category: "बच्चे", author: "डॉ. राहुल खंडेलवाल", reviewedBy: "डॉ. राहुल खंडेलवाल, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "लगभग सात साल की उम्र में। ज़्यादातर बच्चों को तब इलाज की ज़रूरत नहीं होती, पर जबड़े की कुछ समस्याएँ बढ़ती उम्र में आसानी से सुधारी जा सकती हैं।",
        body: "लगभग सात साल तक पहली पक्की दाढ़ें और आगे के दाँत आ जाते हैं, और ऑर्थोडॉन्टिस्ट देख सकते हैं कि जबड़े और काटने का तरीक़ा कैसे बन रहा है। पहली जाँच का यही सही समय है।\n\nज़्यादातर बच्चों को बस साल में एक बार देखा जाता है, जब तक और पक्के दाँत न आ जाएँ। कुछ को जल्दी इलाज से फ़ायदा होता है: क्रॉसबाइट, जहाँ ऊपर के दाँत नीचे वालों के अंदर काटते हैं; संकरा ऊपरी जबड़ा; बाहर निकले आगे के दाँत जिन्हें आसानी से चोट लगती है; या अँगूठा चूसने जैसी आदतें जो काटने का तरीक़ा बदल रही हैं।\n\nजल्दी इलाज में सरल उपकरणों से जबड़े की बढ़त को दिशा दी जाती है। इससे बाद के ब्रेसेज़ छोटे या आसान हो सकते हैं, हालाँकि इनमें से कई बच्चों को किशोर उम्र में फिर भी ब्रेसेज़ लगते हैं।\n\nजल्दी दिखाने के संकेत: दूध के दाँत बहुत जल्दी या बहुत देर से गिरना, मुँह से साँस लेना, काटने में दिक़्क़त, या दाँतों का असमान मिलना।",
      },
    },
    {
      slug: "why-retainers-matter", title: "Why retainers matter after braces", date: "20 Aug 2026", category: "Aftercare", treatment: "retainers-and-aftercare",
      author: "Dr. Tanvi Mehrotra", reviewedBy: "Medically reviewed by Dr. Pooja Agarwal, MDS (Orthodontics and Dentofacial Orthopaedics)",
      excerpt: "Teeth tend to drift back after braces come off. The retainer is what keeps the result, and for most people it is for years.",
      body: "When braces or aligners finish, the fibres around each tooth still remember the old position. Without a retainer, teeth tend to drift back, often within months.\n\nThere are two kinds. A fixed retainer is a thin wire bonded behind the front teeth; you cannot forget it, but it needs careful cleaning around it. A removable retainer is a clear tray or a wire plate, usually worn every night.\n\nMost orthodontists now advise wearing a retainer at night for the long term. Teeth keep moving slightly throughout life, whether or not you had braces.\n\nBring your retainer to every review. If it cracks, feels tight or stops fitting, call the clinic soon; a retainer made quickly costs far less than a second course of braces.",
      hi: {
        title: "ब्रेसेज़ के बाद रिटेनर क्यों ज़रूरी है", date: "20 अगस्त 2026", category: "देखभाल", author: "डॉ. तन्वी मेहरोत्रा", reviewedBy: "डॉ. पूजा अग्रवाल, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "ब्रेसेज़ हटने के बाद दाँत वापस खिसकने लगते हैं। रिटेनर ही नतीजा बनाए रखता है, और ज़्यादातर लोगों के लिए सालों तक।",
        body: "ब्रेसेज़ या अलाइनर पूरे होने पर भी हर दाँत के आसपास के रेशे पुरानी जगह को याद रखते हैं। रिटेनर के बिना दाँत वापस खिसकने लगते हैं, अक्सर कुछ महीनों में।\n\nये दो तरह के होते हैं। फ़िक्स्ड रिटेनर आगे के दाँतों के पीछे चिपका एक पतला तार है; इसे भूल नहीं सकते, पर इसके आसपास सावधानी से सफ़ाई करनी होती है। निकालने वाला रिटेनर एक पारदर्शी ट्रे या तार वाली प्लेट है, जो आमतौर पर हर रात पहनी जाती है।\n\nज़्यादातर ऑर्थोडॉन्टिस्ट अब लंबे समय तक रात में रिटेनर पहनने की सलाह देते हैं। ब्रेसेज़ लगे हों या नहीं, दाँत पूरी ज़िंदगी थोड़ा खिसकते रहते हैं।\n\nहर जाँच पर रिटेनर साथ लाएँ। अगर वह टूटे, टाइट लगे या ठीक से न बैठे, तो जल्दी क्लिनिक को कॉल करें; जल्दी बना रिटेनर दोबारा ब्रेसेज़ से बहुत कम ख़र्च का होता है।",
      },
    },
  ],
  faq: [
    { title: "At what age should my child have an orthodontic check?", body: "Around age seven. Most children need no treatment then, but some bite and jaw problems are easier to guide while the child is growing.", group: "Children", hi: { title: "बच्चे की ऑर्थोडॉन्टिक जाँच किस उम्र में करानी चाहिए?", body: "लगभग सात साल की उम्र में। ज़्यादातर बच्चों को तब इलाज नहीं चाहिए, पर काटने और जबड़े की कुछ समस्याएँ बढ़ती उम्र में आसानी से दिशा दी जा सकती हैं।", group: "बच्चे" } },
    { title: "Braces or aligners: which is better?", body: "Neither is better for everyone. Aligners suit mild to moderate crowding and gaps in people who will wear them all day. Braces handle complex bites more predictably. The comparison table above sets out the differences.", group: "Choosing", hi: { title: "ब्रेसेज़ या अलाइनर: कौन बेहतर है?", body: "सबके लिए कोई एक बेहतर नहीं। अलाइनर उन लोगों में हल्की से मध्यम भीड़ और गैप के लिए ठीक हैं जो इन्हें पूरे दिन पहनेंगे। ब्रेसेज़ जटिल काटने को ज़्यादा भरोसे से ठीक करते हैं। ऊपर की तुलना तालिका अंतर बताती है।", group: "चुनाव" } },
    { title: "How long will treatment take?", body: "Most cases take 12 to 24 months. Your orthodontist gives you an estimate for your case after the records visit. Missed appointments and broken brackets add time.", group: "Choosing", hi: { title: "इलाज में कितना समय लगेगा?", body: "ज़्यादातर मामलों में 12 से 24 महीने। रिकॉर्ड विज़िट के बाद आपके ऑर्थोडॉन्टिस्ट आपके मामले का अनुमान देते हैं। छूटी अपॉइंटमेंट और टूटे ब्रैकेट समय बढ़ाते हैं।", group: "चुनाव" } },
    { title: "Can I pay monthly?", body: "Yes. For braces, the fee is usually split into a first payment and monthly instalments across treatment. EMI options may be available through partner lenders, subject to their approval.", group: "Fees", hi: { title: "क्या हर महीने भुगतान कर सकते हैं?", body: "हाँ। ब्रेसेज़ में शुल्क आमतौर पर पहली राशि और पूरे इलाज में मासिक किस्तों में बँटता है। साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।", group: "फ़ीस" } },
    { title: "Do braces hurt?", body: "Teeth feel sore and pressured for two to three days after fitting and after each adjustment. Soft food and an ordinary painkiller help. Wax covers anything that rubs.", group: "Living with braces", hi: { title: "क्या ब्रेसेज़ में दर्द होता है?", body: "लगाने और हर सुधार के बाद दो-तीन दिन दाँतों में दर्द और दबाव लगता है। नरम खाना और आम दर्द निवारक दवा मदद करते हैं। रगड़ने वाली जगह वैक्स से ढकी जाती है।", group: "ब्रेसेज़ के साथ" } },
    { title: "Will I need teeth removed?", body: "Sometimes, when there is not enough space. Many cases now avoid it with expansion or slight reshaping between teeth. We explain why if it is suggested.", group: "Choosing", hi: { title: "क्या दाँत निकालने पड़ेंगे?", body: "कभी-कभी, जब जगह काफ़ी न हो। अब कई मामलों में जबड़ा चौड़ा करके या दाँतों के बीच हल्का आकार बदलकर इससे बचा जाता है। सुझाव दिया जाए तो हम कारण समझाते हैं।", group: "चुनाव" } },
    { title: "What can I eat with braces?", body: "Most normal food, cut small. Avoid hard and sticky things: whole nuts, hard sweets, chewing gum, corn on the cob, and biting into apples.", group: "Living with braces", hi: { title: "ब्रेसेज़ के साथ क्या खा सकते हैं?", body: "ज़्यादातर सामान्य खाना, छोटे टुकड़ों में। सख़्त और चिपचिपी चीज़ों से बचें: साबुत मेवे, सख़्त टॉफ़ी, च्युइंग गम, भुट्टा, और सेब को सीधे काटना।", group: "ब्रेसेज़ के साथ" } },
    { title: "Why do I need a retainer?", body: "Teeth tend to drift back after braces or aligners. A retainer worn at night, for as long as you want the result, keeps them in place.", group: "Aftercare", hi: { title: "रिटेनर क्यों चाहिए?", body: "ब्रेसेज़ या अलाइनर के बाद दाँत वापस खिसकने की ओर जाते हैं। रात में पहना रिटेनर, जब तक आप नतीजा चाहें, उन्हें अपनी जगह रखता है।", group: "बाद की देखभाल" } },
  ],
  dental: {
    legalName: "Bakul Orthodontics LLP (sample)",
    hi: { legalName: "बकुल ऑर्थोडॉन्टिक्स LLP (नमूना)" },
    hero: {
      variant: "clinical-reason",
      pill: "Orthodontic clinic, Malviya Nagar, Jaipur",
      headline: "Straighter teeth, *planned with you*",
      lead: "Metal, ceramic and self-ligating braces, clear aligners and early checks for children, with evening hours until 9 pm.",
      nextSlot: "Evening slots until 9 pm, Mon to Sat",
      credential: "Dr. Pooja Agarwal, BDS, MDS (Orthodontics and Dentofacial Orthopaedics)",
      hi: {
        pill: "ऑर्थोडॉन्टिक क्लिनिक, मालवीय नगर, जयपुर",
        headline: "सीधे दाँत, *आपके साथ बनी योजना से*",
        lead: "मेटल, सिरेमिक और सेल्फ़-लिगेटिंग ब्रेसेज़, क्लियर अलाइनर और बच्चों की शुरुआती जाँच, रात 9 बजे तक शाम के समय के साथ।",
        nextSlot: "रात 9 बजे तक स्लॉट, सोम से शनि",
        credential: "डॉ. पूजा अग्रवाल, BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)",
      },
    },
    doctors: [
      {
        slug: "pooja-agarwal", name: "Dr. Pooja Agarwal", photo: "/demo/img/people/dentist-w01-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist",
        focus: "Braces and aligners for teenagers and adults, early treatment for children", experience: "13 years in practice",
        languages: ["Hindi", "English", "Rajasthani"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat, evenings; Sun morning",
        bio: "Dr. Pooja Agarwal founded the clinic in 2016 after seven years as an orthodontist in Jaipur and Delhi. She sees children for their first check at seven, teenagers through braces, and a growing number of adults who always wanted straighter teeth.\n\nShe plans every case on a 3D model and shows families the expected movement before treatment starts. When a child does not yet need braces, she says so and books a review instead.",
        quote: "Sometimes the right plan for a seven-year-old is to wait a year. I would rather say that than start early.",
        training: ["BDS, 2007 (sample)", "MDS, Orthodontics and Dentofacial Orthopaedics, 2012 (sample)", "Clear aligner planning course, 2019 (sample)"],
        memberships: ["Indian Orthodontic Society (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. पूजा अग्रवाल", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट",
          focus: "किशोरों और वयस्कों के लिए ब्रेसेज़ और अलाइनर, बच्चों का शुरुआती इलाज", experience: "13 साल का अनुभव",
          languages: ["हिंदी", "अंग्रेज़ी", "राजस्थानी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि, शाम; रवि सुबह",
          bio: "डॉ. पूजा अग्रवाल ने जयपुर और दिल्ली में सात साल ऑर्थोडॉन्टिस्ट के रूप में काम करने के बाद 2016 में यह क्लिनिक शुरू किया। वे सात साल के बच्चों की पहली जाँच, किशोरों के ब्रेसेज़, और उन वयस्कों को देखती हैं जो हमेशा से सीधे दाँत चाहते थे, जिनकी संख्या बढ़ रही है।\n\nवे हर मामले की योजना 3D मॉडल पर बनाती हैं और इलाज शुरू होने से पहले परिवारों को संभावित हलचल दिखाती हैं। जब बच्चे को अभी ब्रेसेज़ की ज़रूरत नहीं होती, तो वे साफ़ कहती हैं और इलाज की जगह जाँच बुक करती हैं।",
          quote: "कभी-कभी सात साल के बच्चे के लिए सही योजना एक साल रुकना होती है। जल्दी शुरू करने से बेहतर है मैं यही कहूँ।",
          training: ["BDS, 2007 (नमूना)", "MDS, ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स, 2012 (नमूना)", "क्लियर अलाइनर योजना कोर्स, 2019 (नमूना)"],
          memberships: ["इंडियन ऑर्थोडॉन्टिक सोसाइटी (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "rahul-khandelwal", name: "Dr. Rahul Khandelwal", photo: "/demo/img/people/dentist-m05-240.webp", gender: "male",
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist",
        focus: "Self-ligating and lingual braces, adult orthodontics, jaw growth appliances", experience: "8 years in practice",
        languages: ["Hindi", "English", "Marwari"], regNo: "Reg. no. A-00000 (sample)", days: "Tue, Thu, Sat and Sun",
        hi: { name: "डॉ. राहुल खंडेलवाल", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट", focus: "सेल्फ़-लिगेटिंग और लिंग्वल ब्रेसेज़, वयस्क ऑर्थोडॉन्टिक्स, जबड़े की ग्रोथ के उपकरण", experience: "8 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "मारवाड़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल, गुरु, शनि और रवि" },
      },
      {
        slug: "tanvi-mehrotra", name: "Dr. Tanvi Mehrotra", photo: "/demo/img/people/dentist-w06-240.webp", gender: "female",
        qualification: "BDS", specialisation: "General dentist", focus: "Cleaning and fillings before braces, brace repairs, retainer checks",
        experience: "5 years in practice", languages: ["Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        hi: { name: "डॉ. तन्वी मेहरोत्रा", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "ब्रेसेज़ से पहले सफ़ाई और फ़िलिंग, ब्रेसेज़ की मरम्मत, रिटेनर जाँच", experience: "5 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि" },
      },
    ],
    journey: [
      { title: "Scan", body: "An examination, photos, X-rays and a 3D scan of your teeth, with no impression trays.", hi: { title: "स्कैन", body: "जाँच, फ़ोटो, एक्स-रे और दाँतों का 3D स्कैन, बिना साँचे की ट्रे के।" } },
      { title: "Plan preview", body: "Your orthodontist shows the planned movement on a 3D model, the options, the time and a written estimate.", hi: { title: "योजना की झलक", body: "आपके ऑर्थोडॉन्टिस्ट 3D मॉडल पर योजनाबद्ध हलचल, विकल्प, समय और लिखित अनुमान दिखाते हैं।" } },
      { title: "Wear", body: "Braces are fitted in about an hour, or your first aligners are handed over with instructions.", hi: { title: "पहनना", body: "लगभग एक घंटे में ब्रेसेज़ लगते हैं, या निर्देशों के साथ पहले अलाइनर दिए जाते हैं।" } },
      { title: "Check-ins", body: "A visit every 4 to 8 weeks to adjust and track progress, in the evening if you prefer.", hi: { title: "जाँच", body: "सुधार और प्रगति देखने के लिए हर 4 से 8 हफ़्ते एक विज़िट, चाहें तो शाम को।" } },
      { title: "Retainers", body: "When the teeth are in place, retainers hold them there. Reviews continue for a year.", hi: { title: "रिटेनर", body: "दाँत जगह पर आने के बाद रिटेनर उन्हें वहीं रखते हैं। एक साल तक जाँच जारी रहती है।" } },
    ],
    comparison: {
      title: "Braces or aligners?",
      columns: ["Metal braces", "Ceramic braces", "Clear aligners"],
      rows: [
        { label: "How it looks", values: ["Visible metal brackets", "Tooth-coloured brackets, less visible", "Nearly invisible trays"], hi: { label: "कैसा दिखता है", values: ["दिखने वाले धातु के ब्रैकेट", "दाँत के रंग के ब्रैकेट, कम दिखते", "लगभग न दिखने वाली ट्रे"] } },
        { label: "Suits", values: ["Simple to complex cases", "Simple to complex cases", "Mild to moderate crowding and gaps"], hi: { label: "किसके लिए", values: ["आसान से जटिल मामले", "आसान से जटिल मामले", "हल्की से मध्यम भीड़ और गैप"] } },
        { label: "Removable", values: ["No", "No", "Yes, to eat and brush"], hi: { label: "निकल सकता है", values: ["नहीं", "नहीं", "हाँ, खाने और ब्रश के लिए"] } },
        { label: "Daily effort", values: ["Careful brushing, avoid hard food", "Careful brushing, avoid staining food", "Wear about 22 hours a day"], hi: { label: "रोज़ की मेहनत", values: ["ध्यान से ब्रश, सख़्त खाना नहीं", "ध्यान से ब्रश, दाग़ वाला खाना नहीं", "दिन में लगभग 22 घंटे पहनना"] } },
        { label: "Check-ins", values: ["Every 4 to 6 weeks", "Every 4 to 6 weeks", "Every 6 to 8 weeks"], hi: { label: "जाँच", values: ["हर 4 से 6 हफ़्ते", "हर 4 से 6 हफ़्ते", "हर 6 से 8 हफ़्ते"] } },
        { label: "Starting from", values: ["Rs 30,000", "Rs 45,000", "After consultation"], hi: { label: "शुरुआती शुल्क", values: ["30,000 रुपये", "45,000 रुपये", "परामर्श के बाद"] } },
      ],
      note: "A general comparison. Prices are starting prices for a simple case; your final cost depends on your diagnosis and treatment plan. Your orthodontist will tell you which options suit your teeth and bite.",
      hi: { title: "ब्रेसेज़ या अलाइनर?", columns: ["मेटल ब्रेसेज़", "सिरेमिक ब्रेसेज़", "क्लियर अलाइनर"], note: "एक सामान्य तुलना। क़ीमतें आसान मामले की शुरुआती क़ीमतें हैं; आपका अंतिम ख़र्च आपके निदान और इलाज की योजना पर निर्भर है। आपके दाँतों और काटने के लिए कौन से विकल्प ठीक हैं, यह आपके ऑर्थोडॉन्टिस्ट बताएँगे।" },
    },
    treatments: [
      {
        slug: "metal-braces", name: "Metal braces", category: "Braces", icon: "braces", image: "/demo/img/dental/ortho-braces-model-640.webp", featured: true, reason: "braces",
        summary: "Stainless steel brackets and wires: the most economical way to correct crowding, gaps and bite problems.",
        what: "Metal braces are small steel brackets bonded to each tooth and linked by a wire. Every few weeks the wire is adjusted or changed to move the teeth gradually. They handle everything from mild crowding to complex bite problems, and are the most economical option.",
        symptoms: ["Crowded or overlapping teeth", "Upper teeth that stick out", "A deep bite, underbite or crossbite"],
        whoNeedsIt: ["Children from about 11, once most adult teeth are in", "Adults with healthy gums"],
        steps: [
          { title: "Records", body: "Photos, X-rays and a 3D scan; cleaning and any fillings first.", hi: { title: "रिकॉर्ड", body: "फ़ोटो, एक्स-रे और 3D स्कैन; पहले सफ़ाई और ज़रूरी फ़िलिंग।" } },
          { title: "Bond", body: "Brackets are fixed in one visit of about an hour.", hi: { title: "लगाना", body: "लगभग एक घंटे की एक विज़िट में ब्रैकेट लगाए जाते हैं।" } },
          { title: "Adjust", body: "Wire changes every 4 to 6 weeks until the teeth are in place.", hi: { title: "सुधार", body: "दाँत जगह पर आने तक हर 4 से 6 हफ़्ते तार बदलना।" } },
          { title: "Retain", body: "Braces removed and retainers fitted the same day.", hi: { title: "रिटेनर", body: "उसी दिन ब्रेसेज़ हटाकर रिटेनर लगाए जाते हैं।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "A check-in every 4 to 6 weeks", recovery: "Sore teeth for 2 to 3 days after fitting and after each adjustment.",
        comfort: "No injections are needed. Orthodontic wax is given for any bracket that rubs.",
        faqs: [
          { title: "Can I play sports with braces?", body: "Yes, with a mouthguard for contact sports. We can make one that fits over the braces.", hi: { title: "क्या ब्रेसेज़ के साथ खेल सकते हैं?", body: "हाँ, संपर्क वाले खेलों में माउथगार्ड के साथ। हम ब्रेसेज़ के ऊपर फ़िट होने वाला बना सकते हैं।" } },
          { title: "What if a bracket comes loose?", body: "Call or WhatsApp us. If it is not hurting, it can usually wait for your next visit or a short repair slot.", hi: { title: "अगर ब्रैकेट ढीला हो जाए तो?", body: "फ़ोन या व्हाट्सऐप करें। दर्द न हो तो आमतौर पर अगली विज़िट या छोटे मरम्मत स्लॉट तक रुक सकता है।" } },
        ],
        fromPrice: "30,000", priceNote: "both jaws, payable monthly",
        hi: {
          name: "मेटल ब्रेसेज़", category: "ब्रेसेज़",
          summary: "स्टेनलेस स्टील के ब्रैकेट और तार: भीड़, गैप और काटने की समस्याएँ ठीक करने का सबसे किफ़ायती तरीक़ा।",
          what: "मेटल ब्रेसेज़ हर दाँत पर लगे छोटे स्टील ब्रैकेट हैं जो एक तार से जुड़े होते हैं। हर कुछ हफ़्ते तार कसा या बदला जाता है ताकि दाँत धीरे-धीरे खिसकें। ये हल्की भीड़ से लेकर जटिल काटने की समस्याओं तक सब ठीक करते हैं, और सबसे किफ़ायती विकल्प हैं।",
          symptoms: ["भीड़ वाले या एक-दूसरे पर चढ़े दाँत", "ऊपर के दाँत आगे निकले", "गहरा काटना, नीचे का जबड़ा आगे, या क्रॉसबाइट"],
          whoNeedsIt: ["लगभग 11 साल से बच्चे, जब ज़्यादातर पक्के दाँत आ जाएँ", "स्वस्थ मसूड़ों वाले वयस्क"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "हर 4 से 6 हफ़्ते जाँच", recovery: "लगाने और हर सुधार के बाद 2 से 3 दिन दाँत दुखते हैं।",
          comfort: "इंजेक्शन की ज़रूरत नहीं। रगड़ने वाले ब्रैकेट के लिए ऑर्थोडॉन्टिक वैक्स दिया जाता है।", priceNote: "दोनों जबड़े, हर महीने भुगतान",
        },
      },
      {
        slug: "ceramic-braces", name: "Ceramic braces", category: "Braces", icon: "braces", image: "/demo/img/dental/ortho-aligners-vs-braces-640.webp", reason: "braces",
        summary: "Tooth-coloured brackets that work like metal braces but are far less visible.",
        what: "Ceramic braces work exactly like metal braces, but the brackets are tooth-coloured, so they blend in. They suit teenagers and adults who want fixed braces without the metal look. They need a little more care with strongly coloured food.",
        symptoms: ["Crowding, gaps or bite problems", "Wanting braces that are less noticeable"],
        whoNeedsIt: ["Teenagers and adults, especially for college or work"],
        steps: [
          { title: "Records", body: "Scan, photos and X-rays.", hi: { title: "रिकॉर्ड", body: "स्कैन, फ़ोटो और एक्स-रे।" } },
          { title: "Bond", body: "Ceramic brackets fixed in one visit.", hi: { title: "लगाना", body: "एक विज़िट में सिरेमिक ब्रैकेट लगाना।" } },
          { title: "Adjust and retain", body: "Check-ins every 4 to 6 weeks, then retainers.", hi: { title: "सुधार और रिटेनर", body: "हर 4 से 6 हफ़्ते जाँच, फिर रिटेनर।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "A check-in every 4 to 6 weeks", recovery: "Soreness for 2 to 3 days after adjustments.",
        comfort: "No injections are needed.",
        faqs: [{ title: "Do ceramic braces stain?", body: "The brackets resist staining; the small elastic ties can discolour with turmeric, tea and coffee and are changed at every visit.", hi: { title: "क्या सिरेमिक ब्रेसेज़ पर दाग़ लगते हैं?", body: "ब्रैकेट पर दाग़ कम लगते हैं; छोटे इलास्टिक टाई हल्दी, चाय और कॉफ़ी से रंग बदल सकते हैं और हर विज़िट में बदले जाते हैं।" } }],
        fromPrice: "45,000", priceNote: "both jaws, payable monthly",
        hi: {
          name: "सिरेमिक ब्रेसेज़", category: "ब्रेसेज़",
          summary: "दाँत के रंग के ब्रैकेट जो मेटल ब्रेसेज़ की तरह काम करते हैं पर बहुत कम दिखते हैं।",
          what: "सिरेमिक ब्रेसेज़ बिल्कुल मेटल ब्रेसेज़ की तरह काम करते हैं, पर ब्रैकेट दाँत के रंग के होते हैं, इसलिए घुल-मिल जाते हैं। ये उन किशोरों और वयस्कों के लिए ठीक हैं जो धातु के रूप के बिना फ़िक्स्ड ब्रेसेज़ चाहते हैं। गहरे रंग वाले खाने में थोड़ा ज़्यादा ध्यान चाहिए।",
          symptoms: ["भीड़, गैप या काटने की समस्याएँ", "कम दिखने वाले ब्रेसेज़ की चाह"],
          whoNeedsIt: ["किशोर और वयस्क, ख़ासकर कॉलेज या काम के लिए"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "हर 4 से 6 हफ़्ते जाँच", recovery: "सुधार के बाद 2 से 3 दिन दर्द।",
          comfort: "इंजेक्शन की ज़रूरत नहीं।", priceNote: "दोनों जबड़े, हर महीने भुगतान",
        },
      },
      {
        slug: "self-ligating-braces", name: "Self-ligating braces", category: "Braces", icon: "braces", image: "/demo/img/dental/doctor-at-work-teal-640.webp", reason: "braces",
        summary: "Braces with built-in clips instead of elastic ties, so check-ins can be spaced out.",
        what: "Self-ligating brackets hold the wire with a small built-in door rather than elastic ties. There are fewer places for food to catch, and appointments can often be spaced a little further apart. They are available in metal and ceramic.",
        symptoms: ["Crowding, gaps or bite problems", "Difficulty coming in every four weeks"],
        whoNeedsIt: ["Teenagers and adults who want fewer visits and easier cleaning"],
        steps: [
          { title: "Records", body: "Scan, photos and X-rays.", hi: { title: "रिकॉर्ड", body: "स्कैन, फ़ोटो और एक्स-रे।" } },
          { title: "Bond", body: "Brackets fixed in one visit.", hi: { title: "लगाना", body: "एक विज़िट में ब्रैकेट लगाना।" } },
          { title: "Adjust and retain", body: "Check-ins every 6 to 8 weeks, then retainers.", hi: { title: "सुधार और रिटेनर", body: "हर 6 से 8 हफ़्ते जाँच, फिर रिटेनर।" } },
        ],
        duration: "Usually 12 to 22 months", visits: "A check-in every 6 to 8 weeks", recovery: "Soreness for a day or two after adjustments.",
        comfort: "No injections are needed.",
        faqs: [{ title: "Are they faster?", body: "Not reliably. Their main advantages are easier cleaning and fewer visits, not a shorter treatment.", hi: { title: "क्या ये जल्दी काम करते हैं?", body: "भरोसे से नहीं कहा जा सकता। इनके मुख्य फ़ायदे आसान सफ़ाई और कम विज़िट हैं, छोटा इलाज नहीं।" } }],
        fromPrice: "55,000", priceNote: "both jaws, metal",
        hi: {
          name: "सेल्फ़-लिगेटिंग ब्रेसेज़", category: "ब्रेसेज़",
          summary: "इलास्टिक टाई की जगह अंदर बने क्लिप वाले ब्रेसेज़, ताकि जाँच में ज़्यादा अंतर रखा जा सके।",
          what: "सेल्फ़-लिगेटिंग ब्रैकेट तार को इलास्टिक टाई की जगह एक छोटे अंदर बने दरवाज़े से पकड़ते हैं। खाना फँसने की जगहें कम होती हैं, और अपॉइंटमेंट अक्सर थोड़े ज़्यादा अंतर पर रखी जा सकती हैं। ये मेटल और सिरेमिक दोनों में मिलते हैं।",
          symptoms: ["भीड़, गैप या काटने की समस्याएँ", "हर चार हफ़्ते आने में दिक़्क़त"],
          whoNeedsIt: ["किशोर और वयस्क जो कम विज़िट और आसान सफ़ाई चाहते हैं"],
          duration: "आमतौर पर 12 से 22 महीने", visits: "हर 6 से 8 हफ़्ते जाँच", recovery: "सुधार के बाद एक-दो दिन दर्द।",
          comfort: "इंजेक्शन की ज़रूरत नहीं।", priceNote: "दोनों जबड़े, मेटल",
        },
      },
      {
        slug: "lingual-braces", name: "Lingual braces", category: "Braces", icon: "braces", image: "/demo/img/dental/doctor-desk-models-640.webp", reason: "braces",
        summary: "Braces fixed to the inside surface of the teeth, hidden from view.",
        what: "Lingual braces are custom brackets bonded behind the teeth, so they cannot be seen when you smile. They take some getting used to for speech and the tongue, and cost more because each bracket is made for your teeth.",
        symptoms: ["Needing fixed braces with nothing visible", "A bite that aligners cannot correct"],
        whoNeedsIt: ["Adults in public-facing work", "Suitable teeth, confirmed on the 3D scan"],
        steps: [
          { title: "Scan and design", body: "Custom brackets designed from a 3D scan.", hi: { title: "स्कैन और डिज़ाइन", body: "3D स्कैन से कस्टम ब्रैकेट डिज़ाइन।" } },
          { title: "Bond", body: "Brackets fixed behind the teeth using a transfer tray.", hi: { title: "लगाना", body: "ट्रांसफ़र ट्रे से दाँतों के पीछे ब्रैकेट लगाना।" } },
          { title: "Adjust and retain", body: "Check-ins every 6 weeks, then retainers.", hi: { title: "सुधार और रिटेनर", body: "हर 6 हफ़्ते जाँच, फिर रिटेनर।" } },
        ],
        duration: "Usually 18 to 24 months", visits: "A check-in every 6 weeks", recovery: "Tongue soreness and a slight lisp for 2 to 3 weeks, which settle.",
        comfort: "No injections are needed. Wax helps while the tongue adapts.",
        faqs: [{ title: "Will I speak normally?", body: "Most people notice a change for the first few weeks. It usually settles as the tongue adapts.", hi: { title: "क्या मैं सामान्य बोल पाऊँगा?", body: "ज़्यादातर लोग पहले कुछ हफ़्ते बदलाव महसूस करते हैं। जीभ के ढलने पर यह आमतौर पर ठीक हो जाता है।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "लिंग्वल ब्रेसेज़", category: "ब्रेसेज़",
          summary: "दाँतों की अंदर की सतह पर लगे ब्रेसेज़, जो नज़र नहीं आते।",
          what: "लिंग्वल ब्रेसेज़ दाँतों के पीछे लगे कस्टम ब्रैकेट हैं, इसलिए मुस्कुराने पर नहीं दिखते। बोलने और जीभ के लिए इनकी आदत पड़ने में समय लगता है, और हर ब्रैकेट आपके दाँतों के लिए बनने से ये महँगे होते हैं।",
          symptoms: ["कुछ भी न दिखने वाले फ़िक्स्ड ब्रेसेज़ की ज़रूरत", "ऐसा काटना जिसे अलाइनर ठीक न कर सकें"],
          whoNeedsIt: ["लोगों के सामने काम करने वाले वयस्क", "3D स्कैन पर उपयुक्त पाए गए दाँत"],
          duration: "आमतौर पर 18 से 24 महीने", visits: "हर 6 हफ़्ते जाँच", recovery: "2 से 3 हफ़्ते जीभ में दर्द और हल्की तुतलाहट, जो ठीक हो जाती है।",
          comfort: "इंजेक्शन की ज़रूरत नहीं। जीभ के ढलने तक वैक्स मदद करता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "clear-aligners", name: "Clear aligners", category: "Aligners", icon: "aligner", image: "/demo/img/dental/ortho-clear-aligner-640.webp", featured: true, reason: "aligners",
        summary: "Removable clear trays, planned by an orthodontist on a 3D scan, for mild to moderate crowding and gaps.",
        what: "Aligners are a series of clear trays, each moving the teeth a little. You wear each set for one to two weeks and take them out only to eat and brush. Because they are planned and supervised by an orthodontist, not ordered by post, we can add attachments, elastics or a switch to braces if your teeth need it.",
        symptoms: ["Mild to moderate crowding", "Gaps between teeth", "Teeth that moved back after braces"],
        whoNeedsIt: ["Teenagers and adults who will wear them about 22 hours a day"],
        steps: [
          { title: "3D scan", body: "An intraoral scan and photos.", hi: { title: "3D स्कैन", body: "इंट्राओरल स्कैन और फ़ोटो।" } },
          { title: "Preview", body: "The planned movement shown stage by stage before you commit.", hi: { title: "झलक", body: "फ़ैसले से पहले चरण-दर-चरण योजनाबद्ध हलचल।" } },
          { title: "Wear and check in", body: "New trays every 1 to 2 weeks; a check every 6 to 8 weeks.", hi: { title: "पहनना और जाँच", body: "हर 1 से 2 हफ़्ते नई ट्रे; हर 6 से 8 हफ़्ते जाँच।" } },
        ],
        duration: "Usually 6 to 18 months", visits: "A check-in every 6 to 8 weeks", recovery: "Pressure for a day or two with each new set.",
        comfort: "No brackets or wires. Small tooth-coloured attachments may be bonded for grip.",
        faqs: [{ title: "What if I do not wear them enough?", body: "The teeth fall behind the plan and the trays stop fitting. We may need a new scan and extra trays, which adds time and cost.", hi: { title: "अगर पर्याप्त नहीं पहने तो?", body: "दाँत योजना से पीछे रह जाते हैं और ट्रे फ़िट होना बंद कर देती हैं। नया स्कैन और अतिरिक्त ट्रे लग सकती हैं, जिससे समय और ख़र्च बढ़ता है।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "क्लियर अलाइनर", category: "अलाइनर",
          summary: "निकलने वाली पारदर्शी ट्रे, ऑर्थोडॉन्टिस्ट द्वारा 3D स्कैन पर योजना, हल्की से मध्यम भीड़ और गैप के लिए।",
          what: "अलाइनर पारदर्शी ट्रे की श्रृंखला है, हर एक दाँतों को थोड़ा खिसकाती है। हर सेट एक-दो हफ़्ते पहनते हैं और सिर्फ़ खाने और ब्रश के लिए निकालते हैं। क्योंकि इनकी योजना और निगरानी ऑर्थोडॉन्टिस्ट करते हैं, डाक से मँगाए नहीं जाते, इसलिए ज़रूरत पड़ने पर हम अटैचमेंट, इलास्टिक या ब्रेसेज़ पर बदलाव कर सकते हैं।",
          symptoms: ["हल्की से मध्यम भीड़", "दाँतों के बीच गैप", "ब्रेसेज़ के बाद वापस खिसके दाँत"],
          whoNeedsIt: ["किशोर और वयस्क जो इन्हें दिन में लगभग 22 घंटे पहनेंगे"],
          duration: "आमतौर पर 6 से 18 महीने", visits: "हर 6 से 8 हफ़्ते जाँच", recovery: "हर नए सेट के साथ एक-दो दिन दबाव।",
          comfort: "कोई ब्रैकेट या तार नहीं। पकड़ के लिए छोटे दाँत के रंग के अटैचमेंट लग सकते हैं।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "early-orthodontic-check", name: "Early orthodontic check", category: "Children", icon: "kids", image: "/demo/img/dental/kids-girl-mirror-640.webp", featured: true, reason: "kids",
        summary: "A check at about age seven to spot jaw and bite problems while they are easier to guide.",
        what: "By seven, a child has a mix of milk and adult teeth and the jaws are still growing. A short check with the orthodontist can spot a crossbite, a narrow upper jaw, crowding or habits that affect growth. Most children need nothing yet; a few benefit from a simple appliance now.",
        symptoms: ["Upper teeth that bite inside the lower teeth", "Very crowded new front teeth", "Thumb sucking or mouth breathing"],
        whoNeedsIt: ["All children around age seven", "Younger children with an obvious bite problem"],
        steps: [
          { title: "Look and listen", body: "A gentle look at teeth, jaws and habits, with your child in the chair.", hi: { title: "देखना और सुनना", body: "बच्चे को कुर्सी पर बिठाकर दाँतों, जबड़ों और आदतों की हल्की जाँच।" } },
          { title: "X-ray if needed", body: "Only when it will change the advice.", hi: { title: "ज़रूरत हो तो एक्स-रे", body: "सिर्फ़ जब उससे सलाह बदले।" } },
          { title: "Advice", body: "Usually a review in 6 to 12 months; sometimes an appliance.", hi: { title: "सलाह", body: "आमतौर पर 6 से 12 महीने में जाँच; कभी-कभी एक उपकरण।" } },
        ],
        duration: "One visit", visits: "About 20 minutes", recovery: "None.",
        comfort: "No treatment is done at the first check. A parent stays with the child.",
        faqs: [{ title: "Will early treatment avoid braces later?", body: "Sometimes it makes later braces shorter or simpler. It does not always avoid them, and we say so.", hi: { title: "क्या जल्दी इलाज से बाद में ब्रेसेज़ से बचा जा सकता है?", body: "कभी-कभी इससे बाद के ब्रेसेज़ छोटे या आसान हो जाते हैं। हमेशा बचाव नहीं होता, और हम यह साफ़ कहते हैं।" } }],
        fromPrice: "500", priceNote: "per check",
        hi: {
          name: "शुरुआती ऑर्थोडॉन्टिक जाँच", category: "बच्चे",
          summary: "लगभग सात साल की उम्र में जाँच, ताकि जबड़े और काटने की समस्याएँ तब दिखें जब उन्हें दिशा देना आसान हो।",
          what: "सात साल तक बच्चे के दूध और पक्के दाँत मिले-जुले होते हैं और जबड़े अभी बढ़ रहे होते हैं। ऑर्थोडॉन्टिस्ट की छोटी जाँच क्रॉसबाइट, संकरा ऊपरी जबड़ा, भीड़ या विकास पर असर डालने वाली आदतें पकड़ सकती है। ज़्यादातर बच्चों को अभी कुछ नहीं चाहिए; कुछ को अभी एक आसान उपकरण से फ़ायदा होता है।",
          symptoms: ["ऊपर के दाँत नीचे के दाँतों के अंदर बंद होना", "बहुत भीड़ वाले नए आगे के दाँत", "अँगूठा चूसना या मुँह से साँस लेना"],
          whoNeedsIt: ["लगभग सात साल के सभी बच्चे", "साफ़ दिखने वाली काटने की समस्या वाले छोटे बच्चे"],
          duration: "एक विज़िट", visits: "लगभग 20 मिनट", recovery: "कुछ नहीं।",
          comfort: "पहली जाँच में कोई इलाज नहीं होता। माता-पिता बच्चे के साथ रहते हैं।", priceNote: "प्रति जाँच",
        },
      },
      {
        slug: "jaw-growth-appliances", name: "Jaw growth appliances", category: "Children", icon: "retainer", image: "/demo/img/dental/kids-boy-checkup-640.webp", reason: "kids",
        summary: "Expanders and functional appliances that guide a growing child's jaws.",
        what: "In growing children, some problems come from the jaws rather than the teeth: a narrow upper jaw, or a lower jaw that sits too far back. An expander widens the upper jaw; a functional appliance encourages the lower jaw forward. Timing matters, so we plan these around growth.",
        symptoms: ["A crossbite", "A lower jaw that sits well back", "Severe crowding in a young child"],
        whoNeedsIt: ["Children roughly 7 to 12, while the jaws are still growing"],
        steps: [
          { title: "Records", body: "Photos, X-rays and a scan.", hi: { title: "रिकॉर्ड", body: "फ़ोटो, एक्स-रे और स्कैन।" } },
          { title: "Fit", body: "The appliance is fitted and your child shown how to wear or turn it.", hi: { title: "लगाना", body: "उपकरण लगाकर बच्चे को पहनना या घुमाना सिखाया जाता है।" } },
          { title: "Review", body: "Checks every 4 to 6 weeks; braces may follow later.", hi: { title: "जाँच", body: "हर 4 से 6 हफ़्ते जाँच; बाद में ब्रेसेज़ लग सकते हैं।" } },
        ],
        duration: "Usually 6 to 12 months", visits: "A check every 4 to 6 weeks", recovery: "A few days to get used to speaking and eating with it.",
        comfort: "No injections are needed. Speech usually adapts within a week.",
        faqs: [{ title: "Does an expander hurt?", body: "Children feel pressure for a few minutes after each turn. It fades quickly.", hi: { title: "क्या एक्सपैंडर में दर्द होता है?", body: "हर बार घुमाने के बाद बच्चों को कुछ मिनट दबाव लगता है। यह जल्दी चला जाता है।" } }],
        fromPrice: "15,000", priceNote: "per appliance",
        hi: {
          name: "जबड़े की ग्रोथ के उपकरण", category: "बच्चे",
          summary: "एक्सपैंडर और फ़ंक्शनल उपकरण जो बढ़ते बच्चे के जबड़ों को दिशा देते हैं।",
          what: "बढ़ते बच्चों में कुछ समस्याएँ दाँतों से नहीं, जबड़ों से होती हैं: संकरा ऊपरी जबड़ा, या बहुत पीछे बैठा निचला जबड़ा। एक्सपैंडर ऊपरी जबड़ा चौड़ा करता है; फ़ंक्शनल उपकरण निचले जबड़े को आगे बढ़ने में मदद करता है। समय मायने रखता है, इसलिए हम इनकी योजना विकास के हिसाब से बनाते हैं।",
          symptoms: ["क्रॉसबाइट", "बहुत पीछे बैठा निचला जबड़ा", "छोटे बच्चे में बहुत ज़्यादा भीड़"],
          whoNeedsIt: ["लगभग 7 से 12 साल के बच्चे, जब जबड़े बढ़ रहे हों"],
          duration: "आमतौर पर 6 से 12 महीने", visits: "हर 4 से 6 हफ़्ते जाँच", recovery: "इसके साथ बोलने और खाने की आदत में कुछ दिन।",
          comfort: "इंजेक्शन की ज़रूरत नहीं। बोलना आमतौर पर एक हफ़्ते में ढल जाता है।", priceNote: "प्रति उपकरण",
        },
      },
      {
        slug: "adult-orthodontics", name: "Adult orthodontics", category: "Aligners", icon: "smile", image: "/demo/img/dental/doctor-aligner-smile-640.webp", reason: "aligners",
        summary: "Braces or aligners for adults, planned around gum health, work and existing dental work.",
        what: "There is no upper age limit for moving teeth. Adults often have fillings, crowns or gum changes that need planning around, and some need straightening before a crown or implant. We check the gums first and choose the least visible option that will do the job.",
        symptoms: ["Crowding that has worsened over the years", "Teeth tilted into a gap", "Wanting straighter teeth before other dental work"],
        whoNeedsIt: ["Adults of any age with healthy or treated gums"],
        steps: [
          { title: "Gum check", body: "Gums and bone assessed; any gum treatment first.", hi: { title: "मसूड़ों की जाँच", body: "मसूड़े और हड्डी की जाँच; पहले ज़रूरी मसूड़ों का इलाज।" } },
          { title: "Choose", body: "Aligners, ceramic, self-ligating or lingual braces, compared for your case.", hi: { title: "चुनाव", body: "आपके मामले के लिए अलाइनर, सिरेमिक, सेल्फ़-लिगेटिंग या लिंग्वल ब्रेसेज़ की तुलना।" } },
          { title: "Treat and retain", body: "Treatment, then retainers for the long term.", hi: { title: "इलाज और रिटेनर", body: "इलाज, फिर लंबे समय के लिए रिटेनर।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "Evening and Sunday check-ins available", recovery: "Soreness for a few days after adjustments.",
        comfort: "No injections are needed for braces or aligners.",
        faqs: [{ title: "Is it worth it at 40?", body: "Many adults say yes. Straighter teeth are easier to clean, and aligning teeth can make later crowns or implants simpler.", hi: { title: "क्या 40 की उम्र में यह सही है?", body: "कई वयस्क हाँ कहते हैं। सीधे दाँत साफ़ करना आसान है, और दाँत सीधे करने से बाद के क्राउन या इम्प्लांट आसान हो सकते हैं।" } }],
        fromPrice: "45,000", priceNote: "ceramic braces, both jaws",
        hi: {
          name: "वयस्क ऑर्थोडॉन्टिक्स", category: "अलाइनर",
          summary: "वयस्कों के लिए ब्रेसेज़ या अलाइनर, मसूड़ों की सेहत, काम और पहले के दाँतों के काम को ध्यान में रखकर।",
          what: "दाँत खिसकाने की कोई ऊपरी उम्र नहीं है। वयस्कों में अक्सर फ़िलिंग, क्राउन या मसूड़ों के बदलाव होते हैं जिनके हिसाब से योजना बनानी पड़ती है, और कुछ को क्राउन या इम्प्लांट से पहले दाँत सीधे करने होते हैं। हम पहले मसूड़े जाँचते हैं और सबसे कम दिखने वाला विकल्प चुनते हैं जो काम कर दे।",
          symptoms: ["सालों में बढ़ी भीड़", "ख़ाली जगह की ओर झुके दाँत", "दूसरे इलाज से पहले सीधे दाँत की चाह"],
          whoNeedsIt: ["स्वस्थ या इलाज हुए मसूड़ों वाले किसी भी उम्र के वयस्क"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "शाम और रविवार को जाँच उपलब्ध", recovery: "सुधार के बाद कुछ दिन दर्द।",
          comfort: "ब्रेसेज़ या अलाइनर में इंजेक्शन की ज़रूरत नहीं।", priceNote: "सिरेमिक ब्रेसेज़, दोनों जबड़े",
        },
      },
      {
        slug: "retainers-and-aftercare", name: "Retainers and aftercare", category: "Aftercare", icon: "retainer", image: "/demo/img/dental/ortho-aligner-fit-640.webp", reason: "checkup",
        summary: "Fixed and removable retainers that keep teeth where treatment put them.",
        what: "Teeth tend to drift back after braces or aligners. A thin wire bonded behind the front teeth, a clear removable retainer, or both, hold them in place. We review retainers for a year after treatment and replace them when they wear.",
        symptoms: ["Just finished braces or aligners", "A lost or cracked retainer", "Teeth starting to move again"],
        whoNeedsIt: ["Everyone after orthodontic treatment, including treatment done elsewhere"],
        steps: [
          { title: "Fit", body: "Retainers fitted the day braces come off.", hi: { title: "लगाना", body: "ब्रेसेज़ हटने के दिन रिटेनर लगाना।" } },
          { title: "Wear", body: "Full time at first as advised, then nights.", hi: { title: "पहनना", body: "पहले सलाह के अनुसार पूरे समय, फिर रात में।" } },
          { title: "Review", body: "Checks at 3, 6 and 12 months.", hi: { title: "जाँच", body: "3, 6 और 12 महीने पर जाँच।" } },
        ],
        duration: "Long term", visits: "3 reviews in the first year", recovery: "None.",
        comfort: "No injections are needed.",
        faqs: [{ title: "How long do I wear a retainer?", body: "At night for as long as you want the teeth to stay straight. Teeth move throughout life.", hi: { title: "रिटेनर कब तक पहनना होगा?", body: "जब तक आप दाँत सीधे रखना चाहें, रात में। दाँत पूरी ज़िंदगी खिसकते रहते हैं।" } }],
        fromPrice: "4,000", priceNote: "per jaw, clear retainer",
        hi: {
          name: "रिटेनर और बाद की देखभाल", category: "बाद की देखभाल",
          summary: "फ़िक्स्ड और निकलने वाले रिटेनर जो दाँतों को इलाज के बाद की जगह पर रखते हैं।",
          what: "ब्रेसेज़ या अलाइनर के बाद दाँत वापस खिसकने की ओर जाते हैं। आगे के दाँतों के पीछे लगा पतला तार, पारदर्शी निकलने वाला रिटेनर, या दोनों उन्हें अपनी जगह रखते हैं। इलाज के बाद एक साल हम रिटेनर की जाँच करते हैं और घिसने पर बदलते हैं।",
          symptoms: ["अभी ब्रेसेज़ या अलाइनर पूरे हुए", "खोया या टूटा रिटेनर", "दाँत फिर से खिसकने लगे"],
          whoNeedsIt: ["ऑर्थोडॉन्टिक इलाज के बाद सभी, कहीं और हुए इलाज समेत"],
          duration: "लंबे समय तक", visits: "पहले साल में 3 जाँच", recovery: "कुछ नहीं।",
          comfort: "इंजेक्शन की ज़रूरत नहीं।", priceNote: "प्रति जबड़ा, पारदर्शी रिटेनर",
        },
      },
    ],
    fees: [
      { treatment: "Orthodontic consultation", from: "500", unit: "per visit", group: "Consultation", hi: { treatment: "ऑर्थोडॉन्टिक परामर्श", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "Early check for children", slug: "early-orthodontic-check", from: "500", unit: "per check", group: "Consultation", hi: { treatment: "बच्चों की शुरुआती जाँच", unit: "प्रति जाँच", group: "परामर्श" } },
      { treatment: "Records: 3D scan, photos and X-rays", from: "2,500", unit: "one time", group: "Consultation", note: "Adjusted against treatment if you go ahead", hi: { treatment: "रिकॉर्ड: 3D स्कैन, फ़ोटो और एक्स-रे", unit: "एक बार", group: "परामर्श", note: "इलाज कराने पर उसमें समायोजित" } },
      { treatment: "Metal braces", slug: "metal-braces", from: "30,000", unit: "both jaws", group: "Braces", hi: { treatment: "मेटल ब्रेसेज़", unit: "दोनों जबड़े", group: "ब्रेसेज़" } },
      { treatment: "Ceramic braces", slug: "ceramic-braces", from: "45,000", unit: "both jaws", group: "Braces", hi: { treatment: "सिरेमिक ब्रेसेज़", unit: "दोनों जबड़े", group: "ब्रेसेज़" } },
      { treatment: "Self-ligating braces", slug: "self-ligating-braces", from: "55,000", unit: "both jaws", group: "Braces", hi: { treatment: "सेल्फ़-लिगेटिंग ब्रेसेज़", unit: "दोनों जबड़े", group: "ब्रेसेज़" } },
      { treatment: "Lingual braces", slug: "lingual-braces", consult: true, group: "Braces", hi: { treatment: "लिंग्वल ब्रेसेज़", group: "ब्रेसेज़" } },
      { treatment: "Clear aligners", slug: "clear-aligners", consult: true, group: "Aligners", note: "Depends on the number of stages in your plan", hi: { treatment: "क्लियर अलाइनर", group: "अलाइनर", note: "आपकी योजना के चरणों की संख्या पर निर्भर" } },
      { treatment: "Jaw growth appliance", slug: "jaw-growth-appliances", from: "15,000", unit: "per appliance", group: "Children", hi: { treatment: "जबड़े की ग्रोथ का उपकरण", unit: "प्रति उपकरण", group: "बच्चे" } },
      { treatment: "Clear retainer", slug: "retainers-and-aftercare", from: "4,000", unit: "per jaw", group: "Aftercare", hi: { treatment: "पारदर्शी रिटेनर", unit: "प्रति जबड़ा", group: "बाद की देखभाल" } },
      { treatment: "Bonded wire retainer", slug: "retainers-and-aftercare", from: "3,000", unit: "per jaw", group: "Aftercare", hi: { treatment: "चिपका तार रिटेनर", unit: "प्रति जबड़ा", group: "बाद की देखभाल" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: metal braces from Rs 30,000 can be paid as Rs 8,000 at fitting and about Rs 1,850 a month over 12 months.",
      partners: ["Monthly instalments paid to the clinic", "Card EMI through your bank"],
      modes: ["UPI", "Debit and credit cards", "Cash"],
      insurance: "Orthodontic treatment is not usually covered by health insurance.",
      consultFee: "Consultation: Rs 500. Treatment is charged as per the estimate you approve.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: 30,000 रुपये से शुरू मेटल ब्रेसेज़ का भुगतान लगाने पर 8,000 रुपये और 12 महीने तक लगभग 1,850 रुपये महीना के रूप में हो सकता है।",
        partners: ["क्लिनिक को मासिक किस्तें", "आपके बैंक के कार्ड पर EMI"],
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नक़द"],
        insurance: "ऑर्थोडॉन्टिक इलाज आमतौर पर हेल्थ इंश्योरेंस में कवर नहीं होता।",
        consultFee: "परामर्श: 500 रुपये। इलाज का शुल्क आपके मंज़ूर किए अनुमान के अनुसार।",
      },
    },
    cases: [
      { category: "Braces", title: "Severe crowding of upper and lower teeth corrected with metal braces", treatment: "metal-braces", duration: "22 months", problem: "Crowding", hi: { category: "ब्रेसेज़", title: "ऊपर और नीचे के दाँतों की बहुत ज़्यादा भीड़ मेटल ब्रेसेज़ से ठीक", duration: "22 महीने", problem: "भीड़" } },
      { category: "Aligners", title: "Mild lower crowding aligned with clear aligners", treatment: "clear-aligners", duration: "8 months", problem: "Crowding", hi: { category: "अलाइनर", title: "नीचे की हल्की भीड़ क्लियर अलाइनर से सीधी", duration: "8 महीने", problem: "भीड़" } },
      { category: "Aligners", title: "Gaps between upper front teeth closed with aligners", treatment: "clear-aligners", duration: "7 months", problem: "Gaps", hi: { category: "अलाइनर", title: "ऊपर के आगे के दाँतों के गैप अलाइनर से बंद", duration: "7 महीने", problem: "गैप" } },
      { category: "Braces", title: "Protruding upper teeth and deep bite reduced with ceramic braces", treatment: "ceramic-braces", duration: "20 months", problem: "Overbite", hi: { category: "ब्रेसेज़", title: "आगे निकले ऊपर के दाँत और गहरा काटना सिरेमिक ब्रेसेज़ से कम", duration: "20 महीने", problem: "ओवरबाइट" } },
      { category: "Children", title: "Crossbite in a nine-year-old corrected with an upper expander", treatment: "jaw-growth-appliances", duration: "9 months", problem: "Crossbite", hi: { category: "बच्चे", title: "नौ साल के बच्चे का क्रॉसबाइट ऊपरी एक्सपैंडर से ठीक", duration: "9 महीने", problem: "क्रॉसबाइट" } },
      { category: "Braces", title: "Mild underbite in an adult improved with self-ligating braces", treatment: "self-ligating-braces", duration: "18 months", problem: "Underbite", hi: { category: "ब्रेसेज़", title: "वयस्क का हल्का अंडरबाइट सेल्फ़-लिगेटिंग ब्रेसेज़ से बेहतर", duration: "18 महीने", problem: "अंडरबाइट" } },
      { category: "Braces", title: "Open bite from a thumb habit closed with braces after habit breaking", treatment: "metal-braces", duration: "16 months", problem: "Open bite", hi: { category: "ब्रेसेज़", title: "अँगूठा चूसने से हुआ ओपन बाइट आदत छुड़ाने के बाद ब्रेसेज़ से बंद", duration: "16 महीने", problem: "ओपन बाइट" } },
    ],
    kids: {
      intro: "Orthodontic problems are easiest to guide while a child is still growing. We recommend a first check at about seven. Most children need nothing then; we simply watch how the teeth and jaws develop and tell you when the right time comes.",
      firstVisit: [
        { title: "Book an after-school slot", body: "Evening slots run until 9 pm; Sunday mornings are open too.", hi: { title: "स्कूल के बाद का स्लॉट बुक करें", body: "शाम के स्लॉट रात 9 बजे तक; रविवार सुबह भी खुला है।" } },
        { title: "A relaxed look", body: "The orthodontist checks teeth, jaws, breathing and habits. Nothing is fitted at this visit.", hi: { title: "आराम से जाँच", body: "ऑर्थोडॉन्टिस्ट दाँत, जबड़े, साँस और आदतें देखते हैं। इस विज़िट में कुछ नहीं लगाया जाता।" } },
        { title: "Photos, and an X-ray only if needed", body: "So we can compare at the next review.", hi: { title: "फ़ोटो, और ज़रूरत हो तभी एक्स-रे", body: "ताकि अगली जाँच में तुलना कर सकें।" } },
        { title: "A clear answer", body: "Wait and review, or a simple plan now, with the reasons and cost in writing.", hi: { title: "साफ़ जवाब", body: "रुकें और जाँच कराएँ, या अभी आसान योजना, कारण और ख़र्च लिखकर।" } },
      ],
      ageBands: [
        { title: "Ages 7 to 9", body: "First check. We look for crossbites, narrow jaws, crowding of the new front teeth and habits such as thumb sucking.", hi: { title: "7 से 9 साल", body: "पहली जाँच। हम क्रॉसबाइट, संकरे जबड़े, नए आगे के दाँतों की भीड़ और अँगूठा चूसने जैसी आदतें देखते हैं।" } },
        { title: "Ages 10 to 12", body: "The usual time for jaw growth appliances, if needed, while the last milk teeth are being lost.", hi: { title: "10 से 12 साल", body: "ज़रूरत हो तो जबड़े की ग्रोथ के उपकरणों का आम समय, जब आख़िरी दूध के दाँत गिर रहे हों।" } },
        { title: "Ages 12 and up", body: "Most adult teeth are in, and braces or aligners can start.", hi: { title: "12 साल और ऊपर", body: "ज़्यादातर पक्के दाँत आ चुके हैं, और ब्रेसेज़ या अलाइनर शुरू हो सकते हैं।" } },
      ],
      habits: [
        { title: "Thumb or finger sucking", body: "After about age five it can push the front teeth forward and open the bite. We help with gentle reminders first.", hi: { title: "अँगूठा या उँगली चूसना", body: "लगभग पाँच साल के बाद यह आगे के दाँतों को आगे धकेल सकता है और काटने में गैप बना सकता है। हम पहले हल्की याद दिलाने से मदद करते हैं।" } },
        { title: "Mouth breathing", body: "Can affect how the upper jaw grows. We may suggest an ENT check.", hi: { title: "मुँह से साँस लेना", body: "ऊपरी जबड़े के बढ़ने पर असर डाल सकता है। हम ENT जाँच की सलाह दे सकते हैं।" } },
        { title: "Tongue thrusting", body: "Pushing the tongue between the teeth when swallowing; exercises often help.", hi: { title: "जीभ धकेलना", body: "निगलते समय जीभ को दाँतों के बीच धकेलना; अक्सर व्यायाम मदद करते हैं।" } },
      ],
      comfort: [
        { title: "Parent in the room", body: "You stay with your child throughout.", hi: { title: "कमरे में माता-पिता", body: "आप पूरे समय बच्चे के साथ रहते हैं।" } },
        { title: "Shown before it is done", body: "We show each step on a model first.", hi: { title: "करने से पहले दिखाना", body: "हम हर क़दम पहले मॉडल पर दिखाते हैं।" } },
        { title: "No treatment at the first visit", body: "The first visit is a check and a conversation only.", hi: { title: "पहली विज़िट में कोई इलाज नहीं", body: "पहली विज़िट सिर्फ़ जाँच और बातचीत है।" } },
      ],
      parentFaq: [
        { title: "Is seven too early for braces?", body: "Usually yes for full braces. The check at seven is about timing: spotting the few problems that are better treated early.", hi: { title: "क्या सात साल ब्रेसेज़ के लिए बहुत जल्दी है?", body: "पूरे ब्रेसेज़ के लिए आमतौर पर हाँ। सात साल की जाँच समय के बारे में है: उन कुछ समस्याओं को पहचानना जिनका जल्दी इलाज बेहतर है।" } },
        { title: "Will my child need two phases of treatment?", body: "Only some children. If we suggest early treatment, we tell you whether braces are still likely later.", hi: { title: "क्या बच्चे को दो चरणों में इलाज चाहिए होगा?", body: "सिर्फ़ कुछ बच्चों को। अगर हम जल्दी इलाज सुझाते हैं, तो बताते हैं कि बाद में ब्रेसेज़ की संभावना है या नहीं।" } },
        { title: "Can my teenager have aligners?", body: "Often yes, if they will wear them about 22 hours a day. Braces may be the better choice if that is unlikely.", hi: { title: "क्या मेरे किशोर बच्चे को अलाइनर लग सकते हैं?", body: "अक्सर हाँ, अगर वे इन्हें दिन में लगभग 22 घंटे पहनेंगे। अगर यह मुश्किल लगे, तो ब्रेसेज़ बेहतर विकल्प हो सकते हैं।" } },
      ],
      hi: { intro: "ऑर्थोडॉन्टिक समस्याओं को तब दिशा देना सबसे आसान है जब बच्चा बढ़ रहा हो। हम लगभग सात साल की उम्र में पहली जाँच की सलाह देते हैं। ज़्यादातर बच्चों को तब कुछ नहीं चाहिए; हम बस देखते हैं कि दाँत और जबड़े कैसे बढ़ रहे हैं और सही समय आने पर बताते हैं।" },
    },
    booking: {
      reasons: [
        { id: "braces", label: "Braces", icon: "braces", treatment: "metal-braces", hi: { label: "ब्रेसेज़" } },
        { id: "aligners", label: "Clear aligners", icon: "aligner", treatment: "clear-aligners", hi: { label: "क्लियर अलाइनर" } },
        { id: "kids", label: "Early check for my child", icon: "kids", treatment: "early-orthodontic-check", hi: { label: "बच्चे की शुरुआती जाँच" } },
        { id: "checkup", label: "Retainer check or replacement", icon: "retainer", treatment: "retainers-and-aftercare", hi: { label: "रिटेनर जाँच या बदलना" } },
        { id: "pain", label: "Broken wire or bracket", icon: "broken", urgent: true, hi: { label: "टूटा तार या ब्रैकेट" } },
        { id: "not-sure", label: "Not sure yet", icon: "tooth", hi: { label: "अभी पक्का नहीं" } },
      ],
      morning: ["11:00 am", "11:30 am", "12:00 pm", "12:30 pm", "1:00 pm"],
      evening: ["5:00 pm", "5:30 pm", "6:00 pm", "6:30 pm", "7:00 pm", "7:30 pm", "8:00 pm", "8:30 pm"],
      closedDays: [],
      closedNote: "Sunday: morning session only, 10 am to 1 pm",
      hi: { closedNote: "रविवार: सिर्फ़ सुबह का सेशन, 10 से दोपहर 1" },
    },
    sessions: [
      { days: [1, 2, 3, 4, 5, 6], from: "11:00", to: "14:00" },
      { days: [1, 2, 3, 4, 5, 6], from: "17:00", to: "21:00" },
      { days: [0], from: "10:00", to: "13:00" },
    ],
    reach: {
      transit: "A short auto ride from the Malviya Nagar main market; city buses stop on the main road.",
      parking: "Street parking in front; a paid lot at the market.",
      access: "Ground floor, step-free entrance.",
      hi: { transit: "मालवीय नगर मुख्य बाज़ार से ऑटो से थोड़ी दूरी; सिटी बसें मुख्य सड़क पर रुकती हैं।", parking: "सामने सड़क किनारे पार्किंग; बाज़ार में पेड पार्किंग।", access: "भूतल, बिना सीढ़ी का प्रवेश।" },
    },
    sterilisation: [
      { title: "Clean", body: "Pliers and instruments are cleaned in an ultrasonic bath after every patient.", hi: { title: "सफ़ाई", body: "हर मरीज़ के बाद प्लायर और औज़ार अल्ट्रासोनिक बाथ में साफ़ होते हैं।" } },
      { title: "Seal", body: "Each set is packed in a dated, sealed pouch.", hi: { title: "सील", body: "हर सेट तारीख़ वाले सील पाउच में पैक होता है।" } },
      { title: "Sterilise", body: "Class B autoclave, tested and logged daily.", hi: { title: "स्टरलाइज़", body: "क्लास B ऑटोक्लेव, रोज़ जाँच और रिकॉर्ड।" } },
      { title: "Open in front of you", body: "Pouches opened at the chair; brackets and elastics come from sealed packs.", hi: { title: "आपके सामने खोलना", body: "पाउच कुर्सी पर खोले जाते हैं; ब्रैकेट और इलास्टिक सील पैक से आते हैं।" } },
    ],
    trust: [
      { title: "Every plan by an MDS orthodontist", body: "Not by a technician or an app.", hi: { title: "हर योजना MDS ऑर्थोडॉन्टिस्ट द्वारा", body: "किसी तकनीशियन या ऐप द्वारा नहीं।" } },
      { title: "The plan shown in 3D", body: "You see the expected movement before you commit.", hi: { title: "3D में योजना", body: "फ़ैसले से पहले आप संभावित हलचल देखते हैं।" } },
      { title: "Monthly payments in writing", body: "The total, the first payment and the monthly amount on one sheet.", hi: { title: "मासिक भुगतान लिखित में", body: "कुल राशि, पहली राशि और मासिक राशि एक काग़ज़ पर।" } },
    ],
    comfort: [
      { title: "No injections for braces or aligners", body: "Fitting and adjustments are done without anaesthetic.", hi: { title: "ब्रेसेज़ या अलाइनर में इंजेक्शन नहीं", body: "लगाना और सुधार बिना सुन्न किए होते हैं।" } },
      { title: "Wax and advice for the first week", body: "We give you wax and a soft-food list at fitting.", hi: { title: "पहले हफ़्ते के लिए वैक्स और सलाह", body: "लगाते समय हम वैक्स और नरम खाने की सूची देते हैं।" } },
      { title: "Repair slots", body: "Short slots in every session for broken wires and loose brackets.", hi: { title: "मरम्मत के स्लॉट", body: "टूटे तार और ढीले ब्रैकेट के लिए हर सेशन में छोटे स्लॉट।" } },
    ],
  },
});
