/**
 * d6-kids-dental: Tesu Children's Dental Clinic, Sector 35, Chandigarh.
 * A paediatric-dentist-led clinic for children from the first tooth to
 * fourteen: first visits, prevention, milk-teeth treatment, dental injuries,
 * habits and special care, written to the parent. Weekend hours.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md (kids: speak to the parent, no prizes or gifts to lure
 * children, no school-camp promotion). Everything here is fiction: the
 * clinic, the doctors, the reviews, the rating and the trust figures are
 * SAMPLE content and carry the SampleNote label until the clinic replaces
 * them. Name forms exactly as in TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Tesu Children's Dental Clinic",
  shortName: "Tesu Kids Dental",
  tagline: "Check-ups, fluoride, sealants and gentle fillings for children up to 14, in Sector 35, Chandigarh.",
  city: "Chandigarh",
  state: "Chandigarh",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2017",
  establishedYear: "2017",
  sitePages: [...DENTAL_PAGE_SETS["d6-kids-dental"]],
  heroImage: "/demo/img/dental/hero-kids-thumbs-up-800.webp",
  sectionPhotos: { about: "/demo/img/dental/kids-colourful-room-640.webp" },
  photos: [
    { src: "/demo/img/dental/kids-colourful-room-640.webp", alt: "", category: "Clinic", caption: "Children's treatment room", hi: { category: "क्लिनिक", caption: "बच्चों का इलाज कक्ष" } },
    { src: "/demo/img/dental/interior-waiting-lounge-640.webp", alt: "", category: "Clinic", caption: "Waiting area", hi: { category: "क्लिनिक", caption: "प्रतीक्षा कक्ष" } },
    { src: "/demo/img/dental/interior-consult-room-640.webp", alt: "", category: "Clinic", caption: "Parents' talk room", hi: { category: "क्लिनिक", caption: "माता-पिता से बातचीत का कमरा" } },
    { src: "/demo/img/dental/kids-brushing-brothers-640.webp", alt: "", category: "At home", caption: "Brushing at home", hi: { category: "घर पर", caption: "घर पर ब्रश करना" } },
    { src: "/demo/img/dental/sterile-instrument-tray-640.webp", alt: "", category: "Safety", caption: "Child-sized instruments, sterilised", hi: { category: "सुरक्षा", caption: "बच्चों के आकार के स्टरलाइज़ किए औज़ार" } },
  ],
  about:
    "Tesu Children's Dental Clinic opened in 2017 with two paediatric dentists and a simple rule: the child sets the pace. Everything here, from the height of the chair to the length of the appointment, is planned for children and the parents who bring them.\n\nWe see babies from the first tooth, children through the years of milk teeth and new adult teeth, and children with special needs who find ordinary clinics hard. Prevention comes first. When treatment is needed, we explain it to you in plain words, and to your child in theirs, before we begin.",
  mission: "Dental care that children do not dread, and that parents understand.",
  vision: "Children who grow up seeing the dentist as a normal, calm part of life.",
  hi: {
    instituteName: "टेसू चिल्ड्रन्स डेंटल क्लिनिक",
    shortName: "टेसू",
    tagline: "14 साल तक के बच्चों के लिए चेक-अप, फ़्लोराइड, सीलेंट और सहज फ़िलिंग, सेक्टर 35, चंडीगढ़ में।",
    city: "चंडीगढ़",
    state: "चंडीगढ़",
    established: "2017 से",
    establishedYear: "2017",
    about:
      "टेसू चिल्ड्रन्स डेंटल क्लिनिक 2017 में दो बच्चों की डेंटिस्टों और एक सीधे नियम के साथ शुरू हुआ: रफ़्तार बच्चा तय करता है। यहाँ सब कुछ, कुर्सी की ऊँचाई से लेकर अपॉइंटमेंट की लंबाई तक, बच्चों और उन्हें लाने वाले माता-पिता के लिए योजना से बना है।\n\nहम पहले दाँत से शिशुओं को, दूध के दाँतों और नए पक्के दाँतों के सालों में बच्चों को, और विशेष ज़रूरतों वाले उन बच्चों को देखते हैं जिन्हें आम क्लिनिक मुश्किल लगते हैं। बचाव पहले आता है। जब इलाज ज़रूरी हो, तो शुरू करने से पहले हम आपको सीधे शब्दों में और बच्चे को उसके शब्दों में समझाते हैं।",
    mission: "दाँतों की ऐसी देखभाल जिससे बच्चे न डरें, और जिसे माता-पिता समझें।",
    vision: "ऐसे बच्चे जो बड़े होकर डेंटिस्ट के पास जाना ज़िंदगी का आम, शांत हिस्सा समझें।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "hello@example.com",
    addressLines: ["Example Road", "Sector 35, Chandigarh 160000"],
    hours: "Tue to Sun, 10 am to 1:30 pm and 4 to 7:30 pm. Closed on Mondays",
    landmark: "Ground floor of a corner building, near the Sector 35 market",
    mapQuery: "Sector 35, Chandigarh",
    hi: {
      addressLines: ["उदाहरण रोड", "सेक्टर 35, चंडीगढ़ 160000"],
      hours: "मंगल से रवि, सुबह 10 से दोपहर 1:30 और शाम 4 से 7:30। सोमवार बंद",
      landmark: "एक कोने की इमारत का भूतल, सेक्टर 35 मार्केट के पास",
    },
  },
  stats: [
    { value: "9", label: "Years caring for children", basis: "Since 2017, Sector 35", hi: { label: "साल बच्चों की देखभाल में", basis: "2017 से, सेक्टर 35" } },
    { value: "2", label: "MDS paediatric dentists", basis: "Paediatric and Preventive Dentistry", hi: { label: "MDS बच्चों की डेंटिस्ट", basis: "पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री" } },
    { value: "0 to 14", label: "Ages we see", basis: "From the first tooth to the early teens", hi: { label: "उम्र जिन्हें हम देखते हैं", basis: "पहले दाँत से शुरुआती किशोर उम्र तक" } },
  ],
  rating: { value: "4.9", count: "221", source: "Google reviews, checked Sep 2026", hi: { source: "गूगल रिव्यू, सितंबर 2026 में देखा गया" } },
  reviews: [
    { quote: "Our daughter's first visit at fourteen months was mostly play and a look on my lap. The doctor spent more time teaching us to brush than examining her.", relation: "Parent of a toddler, first visit", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "First visit", hi: { quote: "चौदह महीने की उम्र में बेटी की पहली विज़िट ज़्यादातर खेल और मेरी गोद में एक नज़र थी। डॉक्टर ने उसकी जाँच से ज़्यादा समय हमें ब्रश करना सिखाने में लगाया।", relation: "छोटे बच्चे के माता-पिता, पहली विज़िट", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "पहली विज़िट" } },
    { quote: "My son had been frightened by a previous dentist. Dr. Bedi took three short visits to get him comfortable before doing his fillings. No rush at all.", relation: "Parent, fillings", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Fillings", hi: { quote: "मेरा बेटा पिछले डेंटिस्ट से डर गया था। डॉ. बेदी ने फ़िलिंग से पहले उसे सहज करने में तीन छोटी विज़िट लगाईं। बिल्कुल जल्दबाज़ी नहीं।", relation: "माता-पिता, फ़िलिंग", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "फ़िलिंग" } },
    { quote: "Knocked out a front tooth at the park on a Sunday. We called, kept it in milk as they said, and were seen within the hour.", relation: "Parent, dental injury", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Injury", hi: { quote: "रविवार को पार्क में आगे का दाँत निकल गया। हमने फ़ोन किया, उनके कहने पर दूध में रखा, और एक घंटे के अंदर दिखा दिया।", relation: "माता-पिता, दाँत की चोट", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "चोट" } },
    { quote: "Our son is autistic. They gave us the first slot of the day, dimmed the light and let him bring his headphones. It made all the difference.", relation: "Parent, special care", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Special care", hi: { quote: "हमारा बेटा ऑटिस्टिक है। उन्होंने दिन का पहला स्लॉट दिया, रोशनी कम की और उसे हेडफ़ोन लाने दिए। इससे पूरा फ़र्क़ पड़ा।", relation: "माता-पिता, विशेष देखभाल", source: "गूगल रिव्यू", date: "जून 2026", category: "विशेष देखभाल" } },
    { quote: "Sealants for both kids, explained clearly with a model. Sunday appointments are a big help for working parents.", relation: "Parent of two, sealants", rating: "5", source: "Google review", date: "May 2026", consent: true, category: "Prevention", hi: { quote: "दोनों बच्चों के सीलेंट, मॉडल के साथ साफ़ समझाए गए। कामकाजी माता-पिता के लिए रविवार की अपॉइंटमेंट बड़ी मदद है।", relation: "दो बच्चों के माता-पिता, सीलेंट", source: "गूगल रिव्यू", date: "मई 2026", category: "बचाव" } },
    { quote: "Very good with children. Weekend slots book up days ahead, so plan early.", relation: "Parent, check-up", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Check-up", hi: { quote: "बच्चों के साथ बहुत अच्छे हैं। वीकेंड के स्लॉट कई दिन पहले भर जाते हैं, इसलिए पहले से योजना बनाएँ।", relation: "माता-पिता, चेक-अप", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "चेक-अप" } },
  ],
  faq: [
    { title: "When should my child first see a dentist?", body: "By the first birthday, or within six months of the first tooth appearing. Early visits are short and mostly about prevention and advice for you.", group: "First visit", hi: { title: "बच्चे को पहली बार डेंटिस्ट के पास कब ले जाएँ?", body: "पहले जन्मदिन तक, या पहला दाँत आने के छह महीने के अंदर। शुरुआती विज़िट छोटी होती हैं और ज़्यादातर बचाव और आपके लिए सलाह के बारे में होती हैं।", group: "पहली विज़िट" } },
    { title: "Can I stay with my child?", body: "Yes, always. Young children often sit on your lap for the check. For older children, you can sit beside the chair.", group: "First visit", hi: { title: "क्या मैं बच्चे के साथ रह सकता हूँ?", body: "हाँ, हमेशा। छोटे बच्चे जाँच के लिए अक्सर आपकी गोद में बैठते हैं। बड़े बच्चों के लिए आप कुर्सी के पास बैठ सकते हैं।", group: "पहली विज़िट" } },
    { title: "How do I prepare my child for the visit?", body: "Keep it simple and positive. Say the dentist will count their teeth. Avoid words like 'hurt' or 'injection'; we explain things in child-friendly words.", group: "First visit", hi: { title: "विज़िट के लिए बच्चे को कैसे तैयार करूँ?", body: "बात सीधी और सकारात्मक रखें। कहें कि डेंटिस्ट उसके दाँत गिनेंगे। 'दर्द' या 'इंजेक्शन' जैसे शब्दों से बचें; हम बच्चों के शब्दों में समझाते हैं।", group: "पहली विज़िट" } },
    { title: "What does a check-up cost?", body: "A children's consultation is Rs 500, including advice and a written plan. Treatment, if any, is estimated in writing before we start.", group: "Fees", hi: { title: "चेक-अप का ख़र्च कितना है?", body: "बच्चों का परामर्श 500 रुपये का है, जिसमें सलाह और लिखित योजना शामिल है। कोई इलाज हो तो शुरू करने से पहले उसका लिखित अनुमान दिया जाता है।", group: "फ़ीस" } },
    { title: "Are dental X-rays safe for children?", body: "We use low-dose digital X-rays and take them only when they will change what we do, with a protective collar.", group: "Safety", hi: { title: "क्या बच्चों के लिए डेंटल एक्स-रे सुरक्षित है?", body: "हम कम डोज़ वाले डिजिटल एक्स-रे इस्तेमाल करते हैं और सुरक्षा कॉलर के साथ तभी लेते हैं जब उससे इलाज बदले।", group: "सुरक्षा" } },
    { title: "Is sedation or general anaesthesia ever used?", body: "Only for a few children who cannot manage treatment awake, or who need a lot of treatment at once. We explain the options, benefits and risks, and it is always your decision. General anaesthesia is given by an anaesthetist at a partner hospital.", group: "Treatment", hi: { title: "क्या कभी सेडेशन या जनरल एनेस्थीसिया इस्तेमाल होता है?", body: "सिर्फ़ उन कुछ बच्चों के लिए जो जागते हुए इलाज नहीं करा पाते, या जिन्हें एक साथ बहुत इलाज चाहिए। हम विकल्प, फ़ायदे और जोखिम समझाते हैं, और फ़ैसला हमेशा आपका होता है। जनरल एनेस्थीसिया साथी अस्पताल में एनेस्थेटिस्ट देते हैं।", group: "इलाज" } },
    { title: "Why treat milk teeth if they fall out anyway?", body: "Back milk teeth stay until about age 10 to 12. Decay in them can cause pain, infection and early loss, which can crowd the adult teeth.", group: "Treatment", hi: { title: "जब दूध के दाँत गिर ही जाएँगे, तो उनका इलाज क्यों?", body: "पीछे के दूध के दाँत लगभग 10 से 12 साल तक रहते हैं। उनमें कीड़ा दर्द, संक्रमण और जल्दी गिरने का कारण बन सकता है, जिससे पक्के दाँतों में भीड़ हो सकती है।", group: "इलाज" } },
    { title: "My child has special needs. Can you help?", body: "Yes. Tell us when you book. We plan a quiet slot, allow extra time and can do visits in short steps over several days.", group: "Special care", hi: { title: "मेरे बच्चे की विशेष ज़रूरतें हैं। क्या आप मदद कर सकते हैं?", body: "हाँ। बुकिंग के समय बताएँ। हम शांत स्लॉट रखते हैं, ज़्यादा समय देते हैं और कई दिनों में छोटे क़दमों में विज़िट कर सकते हैं।", group: "विशेष देखभाल" } },
  ],
  posts: [
    {
      slug: "first-dental-visit", title: "Your child's first dental visit: what happens", date: "14 Sep 2026", category: "First visit", treatment: "first-dental-visit",
      author: "Dr. Simran Bedi", reviewedBy: "Medically reviewed by Dr. Simran Bedi, MDS (Paediatric and Preventive Dentistry)",
      excerpt: "Why the first visit comes by the first birthday, and why it is mostly a conversation with you.",
      body: "The first visit is due by the first birthday, or within six months of the first tooth. At that age there is rarely anything to treat. The visit is about spotting early signs of decay and giving you the habits that prevent it.\n\nYour child sits on your lap, facing you, and leans back into the dentist's lap for a quick look. It takes a minute or two. Crying is normal and does no harm; it even lets us see the teeth.\n\nThe rest is for you: how to brush, how much toothpaste to use (a smear the size of a grain of rice under three), night feeds, sippy cups and snacks.\n\nBring questions. Most parents leave with fewer worries than they came with.",
      hi: {
        title: "बच्चे की पहली डेंटल विज़िट: क्या होता है", date: "14 सितंबर 2026", category: "पहली विज़िट", author: "डॉ. सिमरन बेदी", reviewedBy: "डॉ. सिमरन बेदी, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "पहली विज़िट पहले जन्मदिन तक क्यों, और यह ज़्यादातर आपसे बातचीत क्यों होती है।",
        body: "पहली विज़िट पहले जन्मदिन तक, या पहला दाँत आने के छह महीने के अंदर होनी चाहिए। उस उम्र में इलाज की ज़रूरत शायद ही होती है। विज़िट का मक़सद कीड़े के शुरुआती संकेत पहचानना और आपको उससे बचाने वाली आदतें देना है।\n\nबच्चा आपकी ओर मुँह करके आपकी गोद में बैठता है और जल्दी देखने के लिए डेंटिस्ट की गोद की ओर पीछे झुकता है। इसमें एक-दो मिनट लगते हैं। रोना सामान्य है और नुकसान नहीं करता; इससे दाँत देखना भी आसान होता है।\n\nबाक़ी आपके लिए है: ब्रश कैसे करें, कितना टूथपेस्ट लगाएँ (तीन साल से कम में चावल के दाने जितना), रात का दूध, सिपर कप और नाश्ता।\n\nसवाल लेकर आएँ। ज़्यादातर माता-पिता जितनी चिंता लेकर आते हैं, उससे कम लेकर जाते हैं।",
      },
    },
    {
      slug: "knocked-out-tooth", title: "Knocked-out tooth: what to do in the first hour", date: "30 Aug 2026", category: "Injuries", treatment: "dental-injuries",
      author: "Dr. Harpreet Sandhu", reviewedBy: "Medically reviewed by Dr. Harpreet Sandhu, MDS (Paediatric and Preventive Dentistry)",
      excerpt: "Milk tooth or adult tooth makes all the difference. Here is how to tell, and what to do.",
      body: "First, check your child for any head injury, and go to a hospital emergency department if they were knocked unconscious, are vomiting or seem confused.\n\nIf it is a milk tooth (usually under age six or seven): do not put it back. Pushing it back can damage the adult tooth growing underneath. Press a clean cloth on the gum and call us.\n\nIf it is an adult tooth: every minute counts. Hold it by the crown, not the root. If it is dirty, rinse it briefly in milk. Put it back in the socket if you can and have your child bite gently on a cloth. If not, keep it in milk and come straight to the clinic, ideally within 60 minutes.\n\nDo not scrub the tooth, wrap it in tissue or let it dry out.",
      hi: {
        title: "दाँत निकल गया: पहले घंटे में क्या करें", date: "30 अगस्त 2026", category: "चोट", author: "डॉ. हरप्रीत संधू", reviewedBy: "डॉ. हरप्रीत संधू, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "दूध का दाँत है या पक्का, इससे पूरा फ़र्क़ पड़ता है। पहचानें कैसे, और क्या करें।",
        body: "पहले देखें कि बच्चे के सिर में चोट तो नहीं, और अगर वह बेहोश हुआ, उल्टी कर रहा है या उलझन में लगे, तो अस्पताल के इमरजेंसी विभाग जाएँ।\n\nअगर दूध का दाँत है (आमतौर पर छह-सात साल से कम): उसे वापस न लगाएँ। वापस दबाने से नीचे बढ़ रहे पक्के दाँत को नुकसान हो सकता है। मसूड़े पर साफ़ कपड़ा दबाएँ और हमें फ़ोन करें।\n\nअगर पक्का दाँत है: हर मिनट मायने रखता है। उसे ऊपर के हिस्से से पकड़ें, जड़ से नहीं। गंदा हो तो दूध में हल्का धोएँ। हो सके तो वापस जगह पर लगाएँ और बच्चे को कपड़े पर धीरे से दबाने दें। न हो सके तो दूध में रखें और सीधे क्लिनिक आएँ, बेहतर है 60 मिनट के अंदर।\n\nदाँत को रगड़ें नहीं, टिशू में न लपेटें और सूखने न दें।",
      },
    },
    {
      slug: "bottle-and-night-feeds", title: "Night feeds and early tooth decay", date: "9 Aug 2026", category: "Prevention", treatment: "fluoride-varnish",
      author: "Dr. Simran Bedi", reviewedBy: "Medically reviewed by Dr. Simran Bedi, MDS (Paediatric and Preventive Dentistry)",
      excerpt: "Why a bottle of milk at bedtime is the most common cause of decay in toddlers, and what to do instead.",
      body: "When a child falls asleep with milk, formula or juice in the mouth, it pools around the upper front teeth all night. Saliva flow drops during sleep, so the sugars are not washed away. The result is decay that starts as white chalky lines near the gums and can progress quickly.\n\nWhat helps: finish the feed before sleep, then wipe or brush the teeth. If your child needs a bottle to settle, fill it with water. Start using an open cup from around the first birthday.\n\nLift your child's upper lip once a month and look at the teeth near the gum. White lines or brown spots are a reason to book a visit. Caught early, they can often be treated with fluoride alone.",
      hi: {
        title: "रात का दूध और जल्दी लगने वाला कीड़ा", date: "9 अगस्त 2026", category: "बचाव", author: "डॉ. सिमरन बेदी", reviewedBy: "डॉ. सिमरन बेदी, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "सोते समय दूध की बोतल छोटे बच्चों में कीड़े का सबसे आम कारण क्यों है, और इसकी जगह क्या करें।",
        body: "जब बच्चा मुँह में दूध, फ़ॉर्मूला या जूस के साथ सो जाता है, तो वह पूरी रात ऊपर के आगे के दाँतों के आसपास जमा रहता है। नींद में लार कम बनती है, इसलिए शक्कर धुलती नहीं। नतीजा ऐसा कीड़ा है जो मसूड़ों के पास सफ़ेद चॉक जैसी रेखाओं से शुरू होकर तेज़ी से बढ़ सकता है।\n\nक्या मदद करता है: सोने से पहले दूध ख़त्म कराएँ, फिर दाँत पोंछें या ब्रश करें। अगर बच्चे को सुलाने के लिए बोतल चाहिए, तो उसमें पानी भरें। लगभग पहले जन्मदिन से खुले कप का इस्तेमाल शुरू करें।\n\nमहीने में एक बार बच्चे का ऊपरी होंठ उठाकर मसूड़ों के पास दाँत देखें। सफ़ेद रेखाएँ या भूरे धब्बे विज़िट बुक करने का कारण हैं। जल्दी पकड़ में आएँ तो अक्सर सिर्फ़ फ़्लोराइड से इलाज हो जाता है।",
      },
    },
  ],
  dental: {
    legalName: "Tesu Paediatric Dental Care LLP (sample)",
    hi: { legalName: "टेसू पीडियाट्रिक डेंटल केयर LLP (नमूना)" },
    hero: {
      variant: "kids-arch",
      pill: "Children's dentist, open on weekends",
      headline: "Happy visits from the *first tooth*",
      lead: "Check-ups, fluoride, sealants and gentle fillings for children up to 14, in Sector 35, Chandigarh.",
      nextSlot: "Weekend morning slots from 10 am",
      credential: "Dr. Simran Bedi, BDS, MDS (Paediatric and Preventive Dentistry)",
      hi: {
        pill: "बच्चों की डेंटिस्ट, वीकेंड पर भी खुला",
        headline: "*पहले दाँत* से ख़ुशनुमा विज़िट",
        lead: "14 साल तक के बच्चों के लिए चेक-अप, फ़्लोराइड, सीलेंट और सहज फ़िलिंग, सेक्टर 35, चंडीगढ़ में।",
        nextSlot: "वीकेंड पर सुबह 10 बजे से स्लॉट",
        credential: "डॉ. सिमरन बेदी, BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)",
      },
    },
    doctors: [
      {
        slug: "simran-bedi", name: "Dr. Simran Bedi", photo: "/demo/img/people/dentist-w04-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Paediatric and Preventive Dentistry)", specialisation: "Paediatric dentist",
        focus: "First visits, prevention, anxious children, children with special needs", experience: "14 years in practice",
        languages: ["Punjabi", "Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Tue to Sun",
        bio: "Dr. Simran Bedi founded the clinic in 2017 after eight years in paediatric dentistry at a teaching hospital. She sees babies for their first visit, anxious children who have had a bad experience elsewhere, and children with autism and other special needs.\n\nShe believes most children can be treated calmly if they are given time, and she will split a treatment over several short visits rather than push a child who is not ready.",
        quote: "A child who leaves calm will come back calm. That matters more than finishing today.",
        training: ["BDS, 2008 (sample)", "MDS, Paediatric and Preventive Dentistry, 2012 (sample)", "Special care dentistry course, 2016 (sample)"],
        memberships: ["Indian Society of Pedodontics and Preventive Dentistry (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. सिमरन बेदी", qualification: "BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)", specialisation: "बच्चों की डेंटिस्ट",
          focus: "पहली विज़िट, बचाव, घबराने वाले बच्चे, विशेष ज़रूरतों वाले बच्चे", experience: "14 साल का अनुभव",
          languages: ["पंजाबी", "हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल से रवि",
          bio: "डॉ. सिमरन बेदी ने एक टीचिंग अस्पताल में आठ साल बच्चों की डेंटिस्ट्री के बाद 2017 में यह क्लिनिक शुरू किया। वे पहली विज़िट वाले शिशुओं, कहीं और बुरे अनुभव के बाद घबराए बच्चों, और ऑटिज़्म व अन्य विशेष ज़रूरतों वाले बच्चों को देखती हैं।\n\nउनका मानना है कि समय मिले तो ज़्यादातर बच्चों का इलाज शांति से हो सकता है, और तैयार न होने वाले बच्चे पर ज़ोर डालने की जगह वे इलाज को कई छोटी विज़िट में बाँट देती हैं।",
          quote: "जो बच्चा शांत होकर जाता है, वह शांत होकर लौटता है। यह आज काम पूरा करने से ज़्यादा ज़रूरी है।",
          training: ["BDS, 2008 (नमूना)", "MDS, पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री, 2012 (नमूना)", "स्पेशल केयर डेंटिस्ट्री कोर्स, 2016 (नमूना)"],
          memberships: ["इंडियन सोसाइटी ऑफ़ पेडोडॉन्टिक्स एंड प्रिवेंटिव डेंटिस्ट्री (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "harpreet-sandhu", name: "Dr. Harpreet Sandhu", photo: "/demo/img/people/dentist-m04-240.webp", gender: "male",
        qualification: "BDS, MDS (Paediatric and Preventive Dentistry)", specialisation: "Paediatric dentist",
        focus: "Dental injuries, pulp treatment and crowns for milk teeth, space maintainers", experience: "9 years in practice",
        languages: ["Punjabi", "Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Wed to Sun",
        hi: { name: "डॉ. हरप्रीत संधू", qualification: "BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)", specialisation: "बच्चों के डेंटिस्ट", focus: "दाँतों की चोट, दूध के दाँतों की नस का इलाज और क्राउन, स्पेस मेंटेनर", experience: "9 साल का अनुभव", languages: ["पंजाबी", "हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "बुध से रवि" },
      },
      {
        slug: "nandini-chawla", name: "Dr. Nandini Chawla", photo: "/demo/img/people/dentist-w03-240.webp", gender: "female", visiting: true,
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist", focus: "Early orthodontic checks, habit-breaking and jaw growth appliances",
        experience: "11 years in practice", languages: ["Hindi", "English", "Punjabi"], regNo: "Reg. no. A-00000 (sample)", days: "Saturdays, 4 to 7:30 pm",
        hi: { name: "डॉ. नंदिनी चावला", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट", focus: "शुरुआती ऑर्थोडॉन्टिक जाँच, आदत छुड़ाना और जबड़े की ग्रोथ के उपकरण", experience: "11 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "पंजाबी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "शनिवार, शाम 4 से 7:30" },
      },
      {
        slug: "kavya-goyal", name: "Dr. Kavya Goyal", photo: "/demo/img/people/dentist-w01-240.webp", gender: "female",
        qualification: "BDS", specialisation: "General dentist", focus: "Check-ups, cleaning, fluoride and brushing advice for families",
        experience: "4 years in practice", languages: ["Hindi", "English", "Punjabi"], regNo: "Reg. no. A-00000 (sample)", days: "Tue to Sat",
        hi: { name: "डॉ. काव्या गोयल", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "चेक-अप, सफ़ाई, फ़्लोराइड और परिवारों के लिए ब्रश करने की सलाह", experience: "4 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "पंजाबी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "मंगल से शनि" },
      },
    ],
    treatments: [
      {
        slug: "first-dental-visit", name: "First dental visit", category: "Prevention", icon: "kids", image: "/demo/img/dental/kids-colourful-room-640.webp", featured: true, reason: "kids",
        summary: "A short, gentle first meeting by the first birthday, with advice for you.",
        what: "The first visit is a chance for your child to meet the dentist while nothing is wrong. We look at the teeth and gums, check for early signs of decay, and talk you through brushing, toothpaste, feeding and teething. Your child sits on your lap throughout.",
        symptoms: ["The first tooth has appeared", "Your child is about to turn one", "White spots near the gums"],
        whoNeedsIt: ["Every baby by the first birthday", "Older children who have never been to a dentist"],
        steps: [
          { title: "Settle in", body: "Your child explores the room with you.", hi: { title: "सहज होना", body: "बच्चा आपके साथ कमरा देखता है।" } },
          { title: "Knee-to-knee look", body: "A quick look with your child on your lap.", hi: { title: "गोद में जाँच", body: "बच्चा आपकी गोद में, जल्दी सी जाँच।" } },
          { title: "Advice for home", body: "Brushing, toothpaste and feeding tips, written down.", hi: { title: "घर के लिए सलाह", body: "ब्रश, टूथपेस्ट और खिलाने की सलाह, लिखकर।" } },
        ],
        duration: "One visit", visits: "About 20 minutes", recovery: "None.",
        comfort: "Nothing is done that needs an injection. Crying is normal and we go at your child's pace.",
        faqs: [{ title: "What if my child cries?", body: "That is fine and very common. It does not harm the visit, and it gets easier with each visit.", hi: { title: "अगर बच्चा रोए तो?", body: "यह ठीक और बहुत आम है। इससे विज़िट पर असर नहीं पड़ता, और हर विज़िट के साथ आसान होता जाता है।" } }],
        fromPrice: "500", priceNote: "consultation",
        hi: {
          name: "पहली डेंटल विज़िट", category: "बचाव",
          summary: "पहले जन्मदिन तक एक छोटी, सहज पहली मुलाक़ात, आपके लिए सलाह के साथ।",
          what: "पहली विज़िट बच्चे के लिए डेंटिस्ट से तब मिलने का मौक़ा है जब कुछ ग़लत न हो। हम दाँत और मसूड़े देखते हैं, कीड़े के शुरुआती संकेत जाँचते हैं, और आपको ब्रश, टूथपेस्ट, खिलाने और दाँत निकलने के बारे में बताते हैं। बच्चा पूरे समय आपकी गोद में रहता है।",
          symptoms: ["पहला दाँत आ गया", "बच्चा एक साल का होने वाला है", "मसूड़ों के पास सफ़ेद धब्बे"],
          whoNeedsIt: ["हर शिशु, पहले जन्मदिन तक", "बड़े बच्चे जो कभी डेंटिस्ट के पास नहीं गए"],
          duration: "एक विज़िट", visits: "लगभग 20 मिनट", recovery: "कुछ नहीं।",
          comfort: "ऐसा कुछ नहीं किया जाता जिसमें इंजेक्शन लगे। रोना सामान्य है और हम बच्चे की रफ़्तार से चलते हैं।", priceNote: "परामर्श",
        },
      },
      {
        slug: "check-ups-and-cleaning", name: "Check-ups and cleaning", category: "Prevention", icon: "checkup", image: "/demo/img/dental/kids-dentist-boy-smile-640.webp", reason: "checkup",
        summary: "A six-monthly check, a gentle clean and brushing practice for your child.",
        what: "Regular check-ups catch decay while it is small, when a fluoride application or a tiny filling is enough. We clean the teeth gently, check how the adult teeth are coming in, and practise brushing with your child using a mirror.",
        symptoms: ["Six months since the last check", "Plaque or staining on the teeth", "Bleeding gums when brushing"],
        whoNeedsIt: ["Every child, every six months"],
        steps: [
          { title: "Check", body: "Teeth, gums and bite, counted with your child.", hi: { title: "जाँच", body: "बच्चे के साथ गिनते हुए दाँत, मसूड़े और काटना।" } },
          { title: "Clean", body: "A soft polish, and scaling for older children if needed.", hi: { title: "सफ़ाई", body: "नरम पॉलिश, और बड़े बच्चों में ज़रूरत हो तो स्केलिंग।" } },
          { title: "Practise", body: "Brushing shown in a mirror; a chart for home.", hi: { title: "अभ्यास", body: "शीशे में ब्रश करना दिखाना; घर के लिए चार्ट।" } },
        ],
        duration: "One visit", visits: "20 to 30 minutes", recovery: "None.",
        comfort: "Tell-show-do throughout. No injections for a check-up or clean.",
        faqs: [{ title: "Does my child need X-rays at every check-up?", body: "No. Only when we cannot see between the back teeth or suspect a problem, usually every year or two at most.", hi: { title: "क्या हर चेक-अप में एक्स-रे ज़रूरी है?", body: "नहीं। सिर्फ़ तब जब पीछे के दाँतों के बीच न दिखे या समस्या का शक हो, आमतौर पर ज़्यादा से ज़्यादा हर एक-दो साल।" } }],
        fromPrice: "800", priceNote: "check-up with cleaning",
        hi: {
          name: "चेक-अप और सफ़ाई", category: "बचाव",
          summary: "हर छह महीने जाँच, हल्की सफ़ाई और बच्चे के साथ ब्रश का अभ्यास।",
          what: "नियमित चेक-अप कीड़े को तब पकड़ते हैं जब वह छोटा हो, जब फ़्लोराइड या बहुत छोटी फ़िलिंग काफ़ी हो। हम दाँत हल्के से साफ़ करते हैं, देखते हैं कि पक्के दाँत कैसे आ रहे हैं, और शीशे के सामने बच्चे के साथ ब्रश का अभ्यास करते हैं।",
          symptoms: ["पिछली जाँच को छह महीने", "दाँतों पर प्लाक या दाग़", "ब्रश करते समय मसूड़ों से ख़ून"],
          whoNeedsIt: ["हर बच्चा, हर छह महीने"],
          duration: "एक विज़िट", visits: "20 से 30 मिनट", recovery: "कुछ नहीं।",
          comfort: "पूरे समय बताओ-दिखाओ-करो। चेक-अप या सफ़ाई में इंजेक्शन नहीं।", priceNote: "सफ़ाई के साथ चेक-अप",
        },
      },
      {
        slug: "fluoride-varnish", name: "Fluoride varnish", category: "Prevention", icon: "fluoride", image: "/demo/img/dental/kids-brushing-brothers-640.webp", reason: "checkup",
        summary: "A quick paint-on coating that strengthens enamel and can reverse the earliest decay.",
        what: "Fluoride varnish is painted on the teeth in under a minute. It sets on contact with saliva and releases fluoride over the following hours, making the enamel harder for acids to dissolve. Applied every three to six months, it lowers the risk of decay and can harden early white spots.",
        symptoms: ["White chalky spots", "A history of cavities", "Braces, or difficulty brushing"],
        whoNeedsIt: ["Children with a higher risk of decay", "Most children from the first tooth"],
        steps: [
          { title: "Dry", body: "Teeth are wiped dry with gauze.", hi: { title: "सुखाना", body: "गॉज़ से दाँत सुखाए जाते हैं।" } },
          { title: "Paint", body: "A thin layer of varnish is painted on.", hi: { title: "लगाना", body: "वार्निश की पतली परत लगाई जाती है।" } },
          { title: "Wait", body: "No eating or drinking for 30 minutes; no brushing until night.", hi: { title: "इंतज़ार", body: "30 मिनट कुछ न खाएँ-पिएँ; रात तक ब्रश नहीं।" } },
        ],
        duration: "One visit", visits: "5 minutes, often with a check-up", recovery: "None. The teeth may look slightly yellow until brushed.",
        comfort: "It tastes sweet and takes less than a minute.",
        faqs: [{ title: "Is fluoride safe for young children?", body: "Yes, in the small amounts used in varnish. It is applied by the dentist and very little is swallowed.", hi: { title: "क्या छोटे बच्चों के लिए फ़्लोराइड सुरक्षित है?", body: "हाँ, वार्निश में इस्तेमाल होने वाली थोड़ी मात्रा में। इसे डेंटिस्ट लगाते हैं और बहुत कम निगला जाता है।" } }],
        fromPrice: "700", priceNote: "per application",
        hi: {
          name: "फ़्लोराइड वार्निश", category: "बचाव",
          summary: "जल्दी लगने वाली परत जो इनेमल मज़बूत करती है और सबसे शुरुआती कीड़े को पलट सकती है।",
          what: "फ़्लोराइड वार्निश एक मिनट से कम में दाँतों पर लगाया जाता है। यह लार के संपर्क में आते ही जम जाता है और अगले घंटों में फ़्लोराइड छोड़ता है, जिससे इनेमल पर एसिड का असर कम होता है। हर तीन से छह महीने लगाने पर कीड़े का ख़तरा घटता है और शुरुआती सफ़ेद धब्बे सख़्त हो सकते हैं।",
          symptoms: ["सफ़ेद चॉक जैसे धब्बे", "पहले भी कीड़े लगे हों", "ब्रेसेज़, या ब्रश करने में दिक़्क़त"],
          whoNeedsIt: ["कीड़े के ज़्यादा ख़तरे वाले बच्चे", "पहले दाँत से ज़्यादातर बच्चे"],
          duration: "एक विज़िट", visits: "5 मिनट, अक्सर चेक-अप के साथ", recovery: "कुछ नहीं। ब्रश होने तक दाँत थोड़े पीले दिख सकते हैं।",
          comfort: "इसका स्वाद मीठा होता है और एक मिनट से कम लगता है।", priceNote: "प्रति बार",
        },
      },
      {
        slug: "sealants", name: "Pit and fissure sealants", category: "Prevention", icon: "sealant", image: "/demo/img/dental/kids-boy-with-dentist-640.webp", featured: true, reason: "checkup",
        summary: "A thin protective coating on the grooves of back teeth, where most cavities start.",
        what: "The chewing surfaces of back teeth have deep grooves that trap food and are hard to brush. A sealant is a thin, flowable resin painted into these grooves and set with a light. It needs no drilling and no injection, and it is ideally done soon after the adult molars appear, around ages six and twelve.",
        symptoms: ["New adult molars coming in", "Deep grooves on the back teeth", "Cavities in other teeth"],
        whoNeedsIt: ["Children aged about 6 to 14", "Some milk molars in children at higher risk"],
        steps: [
          { title: "Clean", body: "The groove is cleaned and dried.", hi: { title: "सफ़ाई", body: "दरार साफ़ करके सुखाई जाती है।" } },
          { title: "Seal", body: "Sealant painted on and set with a blue light.", hi: { title: "सील", body: "सीलेंट लगाकर नीली लाइट से सख़्त किया जाता है।" } },
          { title: "Check", body: "Checked at every six-monthly visit.", hi: { title: "जाँच", body: "हर छह महीने की विज़िट में जाँच।" } },
        ],
        duration: "One visit", visits: "About 10 minutes per tooth", recovery: "None. Your child can eat straight away.",
        comfort: "No drilling and no injection.",
        faqs: [{ title: "How long do sealants last?", body: "Often several years. We check them at each visit and top them up if a part has worn.", hi: { title: "सीलेंट कितने समय चलते हैं?", body: "अक्सर कई साल। हर विज़िट में जाँचते हैं और कोई हिस्सा घिसा हो तो फिर से लगाते हैं।" } }],
        fromPrice: "600", priceNote: "per tooth",
        hi: {
          name: "पिट और फ़िशर सीलेंट", category: "बचाव",
          summary: "पीछे के दाँतों की दरारों पर पतली सुरक्षा परत, जहाँ ज़्यादातर कीड़े शुरू होते हैं।",
          what: "पीछे के दाँतों की चबाने वाली सतह पर गहरी दरारें होती हैं जिनमें खाना फँसता है और ब्रश मुश्किल से पहुँचता है। सीलेंट पतला, बहने वाला रेज़िन है जो इन दरारों में लगाकर लाइट से सख़्त किया जाता है। इसमें न ड्रिल, न इंजेक्शन लगता है, और पक्की दाढ़ें आने के तुरंत बाद, लगभग छह और बारह साल में, सबसे अच्छा रहता है।",
          symptoms: ["नई पक्की दाढ़ें आ रही हैं", "पीछे के दाँतों पर गहरी दरारें", "दूसरे दाँतों में कीड़ा"],
          whoNeedsIt: ["लगभग 6 से 14 साल के बच्चे", "ज़्यादा ख़तरे वाले बच्चों की कुछ दूध की दाढ़ें"],
          duration: "एक विज़िट", visits: "हर दाँत के लिए लगभग 10 मिनट", recovery: "कुछ नहीं। बच्चा तुरंत खा सकता है।",
          comfort: "न ड्रिल, न इंजेक्शन।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "fillings-for-milk-teeth", name: "Fillings for milk teeth", category: "Treatment", icon: "filling", image: "/demo/img/dental/kids-boy-checkup-640.webp", reason: "kids",
        summary: "Small cavities treated gently with tooth-coloured fillings, at your child's pace.",
        what: "When decay has made a hole, it needs a filling so it does not reach the nerve and cause pain. For small cavities we often use gentle hand instruments and tooth-coloured materials that release fluoride. Deeper cavities are numbed first, using a numbing gel before any injection.",
        symptoms: ["A visible hole or dark spot", "Food sticking in a tooth", "Complaints with sweets or cold"],
        whoNeedsIt: ["Children with cavities in milk or new adult teeth"],
        steps: [
          { title: "Explain", body: "Tell-show-do: the child sees and feels each instrument first.", hi: { title: "समझाना", body: "बताओ-दिखाओ-करो: बच्चा हर औज़ार पहले देखता और छूता है।" } },
          { title: "Clean and fill", body: "Decay removed and the tooth filled.", hi: { title: "सफ़ाई और भरना", body: "कीड़ा हटाकर दाँत भरा जाता है।" } },
          { title: "Check the bite", body: "The filling is shaped so the teeth meet evenly.", hi: { title: "काटने की जाँच", body: "फ़िलिंग को आकार दिया जाता है ताकि दाँत बराबर मिलें।" } },
        ],
        duration: "One visit", visits: "20 to 40 minutes", recovery: "If the area was numbed, watch that your child does not bite the lip for 2 hours.",
        comfort: "Numbing gel before any injection; treatment pauses whenever your child needs.",
        faqs: [{ title: "My child is very anxious. What then?", body: "We may split treatment over short visits, or discuss other options with you. We never hold a child down for routine treatment.", hi: { title: "मेरा बच्चा बहुत घबराता है। तब क्या?", body: "हम इलाज को छोटी विज़िट में बाँट सकते हैं, या आपके साथ दूसरे विकल्पों पर बात कर सकते हैं। सामान्य इलाज के लिए हम किसी बच्चे को कभी ज़बरदस्ती नहीं पकड़ते।" } }],
        fromPrice: "900", priceNote: "per tooth",
        hi: {
          name: "दूध के दाँतों की फ़िलिंग", category: "इलाज",
          summary: "छोटे कीड़ों का दाँत के रंग की फ़िलिंग से सहज इलाज, बच्चे की रफ़्तार से।",
          what: "जब कीड़े ने छेद कर दिया हो, तो फ़िलिंग ज़रूरी है ताकि वह नस तक न पहुँचे और दर्द न हो। छोटे कीड़ों के लिए हम अक्सर हाथ के हल्के औज़ार और फ़्लोराइड छोड़ने वाली दाँत के रंग की सामग्री इस्तेमाल करते हैं। गहरे कीड़ों में पहले सुन्न किया जाता है, किसी भी इंजेक्शन से पहले सुन्न करने वाला जेल।",
          symptoms: ["दिखने वाला छेद या काला धब्बा", "दाँत में खाना फँसना", "मीठे या ठंडे पर शिकायत"],
          whoNeedsIt: ["दूध या नए पक्के दाँतों में कीड़े वाले बच्चे"],
          duration: "एक विज़िट", visits: "20 से 40 मिनट", recovery: "अगर सुन्न किया गया हो, तो 2 घंटे ध्यान रखें कि बच्चा होंठ न काटे।",
          comfort: "किसी भी इंजेक्शन से पहले सुन्न करने वाला जेल; बच्चे को ज़रूरत हो तो इलाज रुकता है।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "pulp-treatment", name: "Pulp treatment for milk teeth", category: "Treatment", icon: "root-canal", image: "/demo/img/dental/tech-xray-monitor-640.webp", reason: "pain",
        summary: "Treating an infected nerve in a milk tooth so it can stay until it falls out naturally.",
        what: "When decay reaches the nerve of a milk tooth, it can cause pain and infection. Pulp treatment (pulpotomy or pulpectomy) removes the infected nerve tissue and fills the space, and the tooth is then usually covered with a crown. It keeps the tooth in place to hold space for the adult tooth.",
        symptoms: ["Toothache, especially at night", "A swelling or boil on the gum", "A deep cavity seen on X-ray"],
        whoNeedsIt: ["Children with a deep cavity in a milk molar that can still be saved"],
        steps: [
          { title: "Numb", body: "Numbing gel, then local anaesthesia given slowly.", hi: { title: "सुन्न करना", body: "सुन्न करने वाला जेल, फिर धीरे से लोकल एनेस्थीसिया।" } },
          { title: "Treat the nerve", body: "Infected tissue removed and medicated.", hi: { title: "नस का इलाज", body: "संक्रमित ऊतक हटाकर दवा रखी जाती है।" } },
          { title: "Cap", body: "Usually a crown in the same visit.", hi: { title: "टोपी", body: "आमतौर पर उसी विज़िट में क्राउन।" } },
        ],
        duration: "One visit, usually", visits: "45 to 60 minutes", recovery: "Mild soreness for a day; soft food that evening.",
        comfort: "Done under local anaesthesia with breaks whenever your child needs them.",
        faqs: [{ title: "Would it be simpler to remove the tooth?", body: "Removing a back milk tooth early can let other teeth drift and crowd the adult teeth. Saving it is usually better when possible.", hi: { title: "क्या दाँत निकालना आसान नहीं होगा?", body: "पीछे का दूध का दाँत जल्दी निकालने से दूसरे दाँत खिसक सकते हैं और पक्के दाँतों में भीड़ हो सकती है। संभव हो तो बचाना आमतौर पर बेहतर है।" } }],
        fromPrice: "3,000", priceNote: "per tooth, crown separate",
        hi: {
          name: "दूध के दाँतों की नस का इलाज", category: "इलाज",
          summary: "दूध के दाँत की संक्रमित नस का इलाज, ताकि वह अपने आप गिरने तक रह सके।",
          what: "जब कीड़ा दूध के दाँत की नस तक पहुँच जाए, तो दर्द और संक्रमण हो सकता है। पल्प ट्रीटमेंट (पल्पोटॉमी या पल्पेक्टॉमी) में संक्रमित नस का ऊतक हटाकर जगह भरी जाती है, और फिर दाँत पर आमतौर पर क्राउन लगता है। इससे दाँत अपनी जगह रहता है और पक्के दाँत के लिए जगह बनी रहती है।",
          symptoms: ["दाँत दर्द, ख़ासकर रात में", "मसूड़े पर सूजन या फोड़ा", "एक्स-रे पर गहरा कीड़ा"],
          whoNeedsIt: ["दूध की दाढ़ में गहरे कीड़े वाले बच्चे, जिसे अभी बचाया जा सके"],
          duration: "आमतौर पर एक विज़िट", visits: "45 से 60 मिनट", recovery: "एक दिन हल्का दर्द; उस शाम नरम खाना।",
          comfort: "लोकल एनेस्थीसिया में, बच्चे को ज़रूरत हो तब रुकावट के साथ।", priceNote: "प्रति दाँत, क्राउन अलग",
        },
      },
      {
        slug: "crowns-for-milk-teeth", name: "Crowns for milk teeth", category: "Treatment", icon: "crown", image: "/demo/img/dental/sterile-sealed-pouches-640.webp", reason: "kids",
        summary: "Pre-formed steel or tooth-coloured zirconia caps for badly decayed milk molars.",
        what: "A milk molar with a large cavity or after pulp treatment is weak and likely to break. A pre-formed crown covers it until it falls out naturally. Stainless steel crowns are durable and economical; zirconia crowns are tooth-coloured and cost more.",
        symptoms: ["A large cavity in a back milk tooth", "After pulp treatment", "A broken milk molar"],
        whoNeedsIt: ["Children with badly damaged milk molars"],
        steps: [
          { title: "Prepare", body: "The tooth is gently shaped, usually under local anaesthesia.", hi: { title: "तैयारी", body: "दाँत को हल्के से आकार दिया जाता है, आमतौर पर लोकल एनेस्थीसिया में।" } },
          { title: "Fit", body: "A pre-formed crown is sized and cemented in the same visit.", hi: { title: "फ़िटिंग", body: "उसी विज़िट में तैयार क्राउन का नाप लेकर सीमेंट किया जाता है।" } },
        ],
        duration: "One visit", visits: "30 to 45 minutes", recovery: "The bite may feel high for a day or two and settles.",
        comfort: "Numbing gel, then local anaesthesia; breaks as needed.",
        faqs: [{ title: "Will the crown affect the adult tooth?", body: "No. It falls out with the milk tooth when the adult tooth comes through.", hi: { title: "क्या क्राउन से पक्के दाँत पर असर पड़ेगा?", body: "नहीं। पक्का दाँत आने पर यह दूध के दाँत के साथ गिर जाता है।" } }],
        fromPrice: "2,500", priceNote: "per tooth, stainless steel",
        hi: {
          name: "दूध के दाँतों के क्राउन", category: "इलाज",
          summary: "बुरी तरह सड़ी दूध की दाढ़ों के लिए तैयार स्टील या दाँत के रंग की ज़िरकोनिया टोपी।",
          what: "बड़े कीड़े वाली या नस के इलाज के बाद की दूध की दाढ़ कमज़ोर होती है और टूट सकती है। तैयार क्राउन उसे अपने आप गिरने तक ढके रखता है। स्टेनलेस स्टील क्राउन टिकाऊ और किफ़ायती हैं; ज़िरकोनिया क्राउन दाँत के रंग के और महँगे होते हैं।",
          symptoms: ["पीछे के दूध के दाँत में बड़ा कीड़ा", "नस के इलाज के बाद", "टूटी दूध की दाढ़"],
          whoNeedsIt: ["बुरी तरह ख़राब दूध की दाढ़ों वाले बच्चे"],
          duration: "एक विज़िट", visits: "30 से 45 मिनट", recovery: "एक-दो दिन काटना ऊँचा लग सकता है, फिर ठीक हो जाता है।",
          comfort: "सुन्न करने वाला जेल, फिर लोकल एनेस्थीसिया; ज़रूरत पर रुकावट।", priceNote: "प्रति दाँत, स्टेनलेस स्टील",
        },
      },
      {
        slug: "space-maintainers", name: "Space maintainers", category: "Treatment", icon: "retainer", image: "/demo/img/dental/doctor-desk-models-640.webp", reason: "kids",
        summary: "A small appliance that holds the gap when a milk tooth is lost early.",
        what: "If a back milk tooth is lost years before its time, neighbouring teeth can drift into the gap and block the adult tooth. A space maintainer, usually a small band and wire, keeps the space open until the adult tooth arrives.",
        symptoms: ["A back milk tooth removed or lost early", "Neighbouring teeth tilting into a gap"],
        whoNeedsIt: ["Children who lose a milk molar early"],
        steps: [
          { title: "Measure", body: "A quick scan or impression.", hi: { title: "नाप", body: "जल्दी स्कैन या साँचा।" } },
          { title: "Fit", body: "The maintainer is cemented; no injection is needed.", hi: { title: "लगाना", body: "मेंटेनर सीमेंट किया जाता है; इंजेक्शन की ज़रूरत नहीं।" } },
          { title: "Review", body: "Checked every six months and removed when the adult tooth appears.", hi: { title: "जाँच", body: "हर छह महीने जाँच और पक्का दाँत आने पर हटाना।" } },
        ],
        duration: "1 to 2 visits", visits: "Two short visits", recovery: "A day or two to get used to it.",
        comfort: "No injection is needed to fit it.",
        faqs: [{ title: "What should my child avoid?", body: "Sticky sweets and chewing gum, which can loosen it.", hi: { title: "बच्चे को किससे बचना चाहिए?", body: "चिपचिपी मिठाई और च्युइंग गम, जिससे यह ढीला हो सकता है।" } }],
        fromPrice: "3,500", priceNote: "per appliance",
        hi: {
          name: "स्पेस मेंटेनर", category: "इलाज",
          summary: "दूध का दाँत जल्दी गिरने पर जगह बनाए रखने वाला छोटा उपकरण।",
          what: "अगर पीछे का दूध का दाँत समय से सालों पहले गिर जाए, तो बगल के दाँत ख़ाली जगह में खिसक सकते हैं और पक्के दाँत का रास्ता रोक सकते हैं। स्पेस मेंटेनर, आमतौर पर एक छोटा बैंड और तार, पक्का दाँत आने तक जगह खुली रखता है।",
          symptoms: ["पीछे का दूध का दाँत जल्दी निकला या गिरा", "बगल के दाँत ख़ाली जगह की ओर झुक रहे हैं"],
          whoNeedsIt: ["जिन बच्चों की दूध की दाढ़ जल्दी गिर जाए"],
          duration: "1 से 2 विज़िट", visits: "दो छोटी विज़िट", recovery: "आदत पड़ने में एक-दो दिन।",
          comfort: "लगाने में इंजेक्शन की ज़रूरत नहीं।", priceNote: "प्रति उपकरण",
        },
      },
      {
        slug: "dental-injuries", name: "Dental injuries", category: "Emergency", icon: "broken", image: "/demo/img/dental/hero-dentist-boy-checkup-800.webp", featured: true, reason: "pain",
        summary: "Prompt care for chipped, loose or knocked-out teeth after falls and sports. Call us first.",
        what: "Falls, cycling and sport are common causes of injured front teeth. Quick care matters, especially for a knocked-out adult tooth. We check for damage to the tooth, the root and the bone, repair chips, splint loose teeth and follow the tooth up over the next months.",
        symptoms: ["A chipped or broken tooth", "A tooth pushed out of place or loose", "A knocked-out tooth", "A cut lip or gum"],
        whoNeedsIt: ["Any child after a knock to the mouth"],
        steps: [
          { title: "Call us", body: "We guide you by phone and keep an emergency slot free.", hi: { title: "फ़ोन करें", body: "हम फ़ोन पर बताते हैं और इमरजेंसी स्लॉट ख़ाली रखते हैं।" } },
          { title: "Assess", body: "Examination and an X-ray of the injured area.", hi: { title: "जाँच", body: "चोट वाली जगह की जाँच और एक्स-रे।" } },
          { title: "Treat and follow up", body: "Repair or splint, then reviews over the next year.", hi: { title: "इलाज और फ़ॉलो-अप", body: "मरम्मत या स्प्लिंट, फिर अगले साल भर जाँच।" } },
        ],
        duration: "Same day, then follow-up", visits: "Depends on the injury", recovery: "Soft food for a few days; the tooth may change colour and needs watching.",
        comfort: "Local anaesthesia where needed; a parent stays throughout.",
        faqs: [{ title: "The injured milk tooth turned grey. Is that serious?", body: "It can mean the nerve was bruised. Many settle; we take an X-ray and watch it at follow-up visits.", hi: { title: "चोट लगा दूध का दाँत धूसर हो गया। क्या यह गंभीर है?", body: "इसका मतलब हो सकता है कि नस को चोट लगी। कई ठीक हो जाते हैं; हम एक्स-रे लेकर फ़ॉलो-अप में देखते रहते हैं।" } }],
        fromPrice: "800", priceNote: "emergency examination",
        hi: {
          name: "दाँतों की चोट", category: "इमरजेंसी",
          summary: "गिरने और खेल के बाद टूटे, ढीले या निकले दाँतों की जल्दी देखभाल। पहले हमें फ़ोन करें।",
          what: "गिरना, साइकिल चलाना और खेल आगे के दाँतों की चोट के आम कारण हैं। जल्दी देखभाल ज़रूरी है, ख़ासकर निकले हुए पक्के दाँत के लिए। हम दाँत, जड़ और हड्डी की चोट जाँचते हैं, टूटे किनारे ठीक करते हैं, ढीले दाँतों को स्प्लिंट करते हैं और अगले महीनों में दाँत पर नज़र रखते हैं।",
          symptoms: ["टूटा या चटका दाँत", "जगह से हटा या ढीला दाँत", "पूरा निकला दाँत", "कटा होंठ या मसूड़ा"],
          whoNeedsIt: ["मुँह पर चोट के बाद हर बच्चा"],
          duration: "उसी दिन, फिर फ़ॉलो-अप", visits: "चोट पर निर्भर", recovery: "कुछ दिन नरम खाना; दाँत का रंग बदल सकता है और नज़र रखनी होती है।",
          comfort: "ज़रूरत पर लोकल एनेस्थीसिया; माता-पिता पूरे समय साथ।", priceNote: "इमरजेंसी जाँच",
        },
      },
    ],
    fees: [
      { treatment: "Children's consultation", slug: "first-dental-visit", from: "500", unit: "per visit", group: "Consultation", hi: { treatment: "बच्चों का परामर्श", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "Check-up with cleaning", slug: "check-ups-and-cleaning", from: "800", unit: "per visit", group: "Prevention", hi: { treatment: "सफ़ाई के साथ चेक-अप", unit: "प्रति विज़िट", group: "बचाव" } },
      { treatment: "Fluoride varnish", slug: "fluoride-varnish", from: "700", unit: "per application", group: "Prevention", hi: { treatment: "फ़्लोराइड वार्निश", unit: "प्रति बार", group: "बचाव" } },
      { treatment: "Sealant", slug: "sealants", from: "600", unit: "per tooth", group: "Prevention", hi: { treatment: "सीलेंट", unit: "प्रति दाँत", group: "बचाव" } },
      { treatment: "Filling, milk tooth", slug: "fillings-for-milk-teeth", from: "900", unit: "per tooth", group: "Treatment", hi: { treatment: "फ़िलिंग, दूध का दाँत", unit: "प्रति दाँत", group: "इलाज" } },
      { treatment: "Pulp treatment, milk tooth", slug: "pulp-treatment", from: "3,000", unit: "per tooth", group: "Treatment", hi: { treatment: "नस का इलाज, दूध का दाँत", unit: "प्रति दाँत", group: "इलाज" } },
      { treatment: "Stainless steel crown", slug: "crowns-for-milk-teeth", from: "2,500", unit: "per tooth", group: "Treatment", hi: { treatment: "स्टेनलेस स्टील क्राउन", unit: "प्रति दाँत", group: "इलाज" } },
      { treatment: "Zirconia crown for a milk tooth", slug: "crowns-for-milk-teeth", from: "7,000", unit: "per tooth", group: "Treatment", hi: { treatment: "दूध के दाँत के लिए ज़िरकोनिया क्राउन", unit: "प्रति दाँत", group: "इलाज" } },
      { treatment: "Space maintainer", slug: "space-maintainers", from: "3,500", unit: "per appliance", group: "Treatment", hi: { treatment: "स्पेस मेंटेनर", unit: "प्रति उपकरण", group: "इलाज" } },
      { treatment: "Treatment under general anaesthesia", consult: true, group: "Special care", note: "At a partner hospital; hospital charges are separate", hi: { treatment: "जनरल एनेस्थीसिया में इलाज", group: "विशेष देखभाल", note: "साथी अस्पताल में; अस्पताल का शुल्क अलग" } },
    ],
    payment: {
      modes: ["UPI", "Debit and credit cards", "Cash"],
      insurance: "Children's dental treatment is not usually covered by health insurance, except after an accident. We provide reports for any claim.",
      consultFee: "Children's consultation: Rs 500. Treatment is charged as per the estimate you approve.",
      hi: {
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नक़द"],
        insurance: "बच्चों के दाँतों का इलाज आमतौर पर हेल्थ इंश्योरेंस में कवर नहीं होता, दुर्घटना के बाद को छोड़कर। किसी भी क्लेम के लिए हम रिपोर्ट देते हैं।",
        consultFee: "बच्चों का परामर्श: 500 रुपये। इलाज का शुल्क आपके मंज़ूर किए अनुमान के अनुसार।",
      },
    },
    emergency: {
      headline: "Toothache or a knock to the teeth? Same-day appointments",
      intro: "Children's dental emergencies often happen at weekends. Call or WhatsApp us first: we will tell you what to do on the way and keep a slot free.",
      phone: "+91 00000 00000",
      whatsapp: "910000000000",
      hours: "Emergency calls answered 9 am to 9 pm, Tuesday to Sunday",
      urgent: ["A knocked-out adult tooth", "Toothache that keeps your child awake", "Swelling of the face or gum", "A tooth pushed out of place after a fall"],
      firstAid: [
        { title: "Knocked-out adult tooth", body: "Hold it by the crown, rinse briefly in milk, put it back if you can or keep it in milk, and come in within the hour.", hi: { title: "पक्का दाँत निकल गया", body: "ऊपर के हिस्से से पकड़ें, दूध में हल्का धोएँ, हो सके तो वापस लगाएँ या दूध में रखें, और एक घंटे के अंदर आएँ।" } },
        { title: "Knocked-out milk tooth", body: "Do not put it back. Press a clean cloth on the gum to stop bleeding and call us.", hi: { title: "दूध का दाँत निकल गया", body: "वापस न लगाएँ। ख़ून रोकने के लिए मसूड़े पर साफ़ कपड़ा दबाएँ और हमें फ़ोन करें।" } },
        { title: "Chipped tooth", body: "Keep the piece in milk or water and bring it with you.", hi: { title: "टूटा किनारा", body: "टुकड़ा दूध या पानी में रखें और साथ लाएँ।" } },
        { title: "Toothache", body: "Give a child's dose of paracetamol as on the pack and a cold pack on the cheek. Do not put medicine on the gum.", hi: { title: "दाँत दर्द", body: "पैक के अनुसार बच्चे की ख़ुराक में पैरासिटामोल और गाल पर ठंडी सिकाई। मसूड़े पर दवा न रखें।" } },
      ],
      canWait: ["A wobbly milk tooth that is ready to come out", "A small chip without pain", "A lost filling without pain"],
      hi: {
        headline: "दाँत दर्द या दाँतों पर चोट? उसी दिन अपॉइंटमेंट",
        intro: "बच्चों की दाँतों की इमरजेंसी अक्सर वीकेंड पर होती है। पहले फ़ोन या व्हाट्सऐप करें: हम रास्ते में क्या करना है बताएँगे और स्लॉट ख़ाली रखेंगे।",
        hours: "इमरजेंसी कॉल सुबह 9 से रात 9 तक, मंगलवार से रविवार",
        urgent: ["निकला हुआ पक्का दाँत", "दाँत दर्द जिससे बच्चा सो न पाए", "चेहरे या मसूड़े में सूजन", "गिरने के बाद जगह से हटा दाँत"],
        canWait: ["हिलता दूध का दाँत जो गिरने वाला है", "बिना दर्द का छोटा टूटा किनारा", "बिना दर्द के निकली फ़िलिंग"],
      },
    },
    kids: {
      intro: "Everything at this clinic is planned for children and their parents: short appointments, a parent in the room, and prevention before treatment. Here is what to expect, age by age.",
      firstVisit: [
        { title: "Book a morning slot", body: "Young children are usually most settled before lunch. Weekend mornings are open too.", hi: { title: "सुबह का स्लॉट बुक करें", body: "छोटे बच्चे दोपहर से पहले सबसे अच्छे मूड में होते हैं। वीकेंड की सुबह भी खुली है।" } },
        { title: "Talk it up at home", body: "Say the dentist will count their teeth. Read a picture book about a dentist visit together.", hi: { title: "घर पर बात करें", body: "कहें कि डेंटिस्ट उनके दाँत गिनेंगे। साथ में डेंटिस्ट विज़िट वाली चित्र-पुस्तक पढ़ें।" } },
        { title: "Meet, look, count", body: "Your child meets the team and the chair, then a gentle look on your lap or in the chair.", hi: { title: "मिलना, देखना, गिनना", body: "बच्चा टीम और कुर्सी से मिलता है, फिर आपकी गोद या कुर्सी पर हल्की जाँच।" } },
        { title: "Go home with a plan", body: "Brushing, toothpaste, snacks and the next visit, written down for you.", hi: { title: "योजना के साथ घर", body: "ब्रश, टूथपेस्ट, नाश्ता और अगली विज़िट, आपके लिए लिखकर।" } },
      ],
      ageBands: [
        { title: "Babies and toddlers (0 to 3)", body: "First visit by the first birthday. Brush twice a day with a rice-grain smear of fluoride toothpaste; no bottles in bed.", hi: { title: "शिशु और छोटे बच्चे (0 से 3)", body: "पहले जन्मदिन तक पहली विज़िट। चावल के दाने जितने फ़्लोराइड टूथपेस्ट से दिन में दो बार ब्रश; बिस्तर में बोतल नहीं।" } },
        { title: "Young children (4 to 8)", body: "Six-monthly check-ups and fluoride. Sealants when the first adult molars arrive around six. Parents brush until about eight.", hi: { title: "छोटे बच्चे (4 से 8)", body: "हर छह महीने चेक-अप और फ़्लोराइड। लगभग छह साल में पहली पक्की दाढ़ आने पर सीलेंट। लगभग आठ साल तक माता-पिता ब्रश कराएँ।" } },
        { title: "Pre-teens (9 to 14)", body: "Sealants on the second molars, an orthodontic check, and a mouthguard for sport.", hi: { title: "किशोरावस्था से पहले (9 से 14)", body: "दूसरी दाढ़ों पर सीलेंट, ऑर्थोडॉन्टिक जाँच, और खेल के लिए माउथगार्ड।" } },
      ],
      prevention: [
        { title: "Fluoride toothpaste", body: "A rice-grain smear under three, a pea-sized amount from three. Spit, do not rinse.", hi: { title: "फ़्लोराइड टूथपेस्ट", body: "तीन साल से कम में चावल के दाने जितना, तीन से मटर के दाने जितना। थूकें, कुल्ला न करें।" } },
        { title: "Fluoride varnish", body: "Painted on every three to six months for children at higher risk.", hi: { title: "फ़्लोराइड वार्निश", body: "ज़्यादा ख़तरे वाले बच्चों के लिए हर तीन से छह महीने।" } },
        { title: "Sealants", body: "Protect the grooves of new back teeth.", hi: { title: "सीलेंट", body: "नए पीछे के दाँतों की दरारों की सुरक्षा।" } },
        { title: "Snacks and drinks", body: "Sweets with meals, not between. Water and milk between meals; juice is a treat.", hi: { title: "नाश्ता और पेय", body: "मिठाई खाने के साथ, बीच में नहीं। खाने के बीच पानी और दूध; जूस कभी-कभी।" } },
      ],
      habits: [
        { title: "Thumb and dummy sucking", body: "Usually harmless before four. After that we help with gentle encouragement, and rarely an appliance.", hi: { title: "अँगूठा और चुसनी चूसना", body: "चार साल से पहले आमतौर पर नुकसान नहीं। उसके बाद हल्के प्रोत्साहन से, और कभी-कभी उपकरण से मदद करते हैं।" } },
        { title: "Bottle at bedtime", body: "The most common cause of early decay. Finish feeds before sleep.", hi: { title: "सोते समय बोतल", body: "जल्दी कीड़े का सबसे आम कारण। सोने से पहले दूध ख़त्म कराएँ।" } },
        { title: "Mouth breathing and grinding", body: "Mention them at the check-up; we may suggest an ENT or orthodontic check.", hi: { title: "मुँह से साँस और दाँत पीसना", body: "चेक-अप में बताएँ; हम ENT या ऑर्थोडॉन्टिक जाँच की सलाह दे सकते हैं।" } },
      ],
      comfort: [
        { title: "Tell-show-do", body: "We explain in your child's words, show on a finger or a toy, then do.", hi: { title: "बताओ-दिखाओ-करो", body: "हम बच्चे के शब्दों में समझाते हैं, उँगली या खिलौने पर दिखाते हैं, फिर करते हैं।" } },
        { title: "A parent in the room", body: "Always. Hold a hand or sit close.", hi: { title: "कमरे में माता-पिता", body: "हमेशा। हाथ पकड़ें या पास बैठें।" } },
        { title: "Numbing gel first", body: "Before any injection, and we wait until the area is numb.", hi: { title: "पहले सुन्न करने वाला जेल", body: "किसी भी इंजेक्शन से पहले, और जगह सुन्न होने तक हम रुकते हैं।" } },
        { title: "Sedation information", body: "For a few children we discuss sedation or general anaesthesia at a partner hospital, with benefits and risks. It is never routine and always your decision.", hi: { title: "सेडेशन की जानकारी", body: "कुछ बच्चों के लिए हम साथी अस्पताल में सेडेशन या जनरल एनेस्थीसिया पर फ़ायदे और जोखिम के साथ बात करते हैं। यह कभी सामान्य नहीं होता और फ़ैसला हमेशा आपका होता है।" } },
      ],
      specialCare: "Children with autism, ADHD, Down syndrome, cerebral palsy or sensory needs are welcome. We offer the first slot of the day, a quiet room, dimmed lights and visits split into short steps. Tell us what helps your child when you book.",
      parentFaq: [
        { title: "When do milk teeth fall out?", body: "The front teeth usually loosen around six or seven; the back milk teeth stay until about ten to twelve.", hi: { title: "दूध के दाँत कब गिरते हैं?", body: "आगे के दाँत आमतौर पर छह-सात साल में हिलते हैं; पीछे के दूध के दाँत लगभग दस से बारह साल तक रहते हैं।" } },
        { title: "Is teething causing my baby's fever?", body: "Teething can cause mild irritability and drooling, but not a high fever. See your paediatrician for a fever.", hi: { title: "क्या दाँत निकलने से बच्चे को बुख़ार है?", body: "दाँत निकलने से हल्की चिड़चिड़ाहट और लार आ सकती है, पर तेज़ बुख़ार नहीं। बुख़ार के लिए बच्चों के डॉक्टर को दिखाएँ।" } },
        { title: "Should I brush my child's teeth or let them do it?", body: "Let them try, then finish it yourself until about age eight.", hi: { title: "ब्रश मैं करूँ या बच्चे को करने दूँ?", body: "पहले उन्हें करने दें, फिर लगभग आठ साल की उम्र तक ख़ुद पूरा करें।" } },
      ],
      hi: {
        intro: "इस क्लिनिक में सब कुछ बच्चों और उनके माता-पिता के लिए योजना से बना है: छोटी अपॉइंटमेंट, कमरे में माता-पिता, और इलाज से पहले बचाव। उम्र के हिसाब से क्या उम्मीद करें, यहाँ पढ़ें।",
        specialCare: "ऑटिज़्म, ADHD, डाउन सिंड्रोम, सेरेब्रल पाल्सी या संवेदी ज़रूरतों वाले बच्चों का स्वागत है। हम दिन का पहला स्लॉट, शांत कमरा, धीमी रोशनी और छोटे क़दमों में बँटी विज़िट देते हैं। बुकिंग के समय बताएँ कि आपके बच्चे के लिए क्या मददगार है।",
      },
    },
    booking: {
      reasons: [
        { id: "kids", label: "First visit", icon: "kids", treatment: "first-dental-visit", hi: { label: "पहली विज़िट" } },
        { id: "checkup", label: "Check-up and cleaning", icon: "checkup", treatment: "check-ups-and-cleaning", hi: { label: "चेक-अप और सफ़ाई" } },
        { id: "pain", label: "Toothache or swelling", icon: "pain", urgent: true, treatment: "pulp-treatment", hi: { label: "दाँत दर्द या सूजन" } },
        { id: "injury", label: "Injury to a tooth", icon: "broken", urgent: true, treatment: "dental-injuries", hi: { label: "दाँत पर चोट" } },
        { id: "cleaning", label: "Fluoride or sealants", icon: "sealant", treatment: "sealants", hi: { label: "फ़्लोराइड या सीलेंट" } },
        { id: "braces", label: "Early orthodontic check", icon: "braces", hi: { label: "शुरुआती ऑर्थोडॉन्टिक जाँच" } },
        { id: "not-sure", label: "Not sure", icon: "tooth", hi: { label: "पक्का नहीं पता" } },
      ],
      morning: ["10:00 am", "10:30 am", "11:00 am", "11:30 am", "12:00 pm", "12:30 pm"],
      evening: ["4:00 pm", "4:30 pm", "5:00 pm", "5:30 pm", "6:00 pm", "6:30 pm"],
      closedDays: [1],
      closedNote: "Closed on Mondays. Open on Saturdays and Sundays",
      hi: { closedNote: "सोमवार बंद। शनिवार और रविवार खुला" },
    },
    sessions: [
      { days: [0, 2, 3, 4, 5, 6], from: "10:00", to: "13:30" },
      { days: [0, 2, 3, 4, 5, 6], from: "16:00", to: "19:30" },
    ],
    reach: {
      transit: "City buses stop at the Sector 35 market; a few minutes' walk from there.",
      parking: "Parking in the market lot opposite the clinic.",
      access: "Ground floor, step-free, with room for prams and wheelchairs.",
      hi: { transit: "सिटी बसें सेक्टर 35 मार्केट पर रुकती हैं; वहाँ से कुछ मिनट पैदल।", parking: "क्लिनिक के सामने मार्केट की पार्किंग में।", access: "भूतल, बिना सीढ़ी, प्रैम और व्हीलचेयर के लिए जगह।" },
    },
    sterilisation: [
      { title: "Clean", body: "Every instrument is cleaned in an ultrasonic bath after each child.", hi: { title: "सफ़ाई", body: "हर बच्चे के बाद हर औज़ार अल्ट्रासोनिक बाथ में साफ़ होता है।" } },
      { title: "Seal", body: "Child-sized instrument sets are sealed in dated pouches.", hi: { title: "सील", body: "बच्चों के आकार के औज़ारों के सेट तारीख़ वाले पाउच में सील होते हैं।" } },
      { title: "Sterilise", body: "Class B autoclave cycles, tested and logged every day.", hi: { title: "स्टरलाइज़", body: "क्लास B ऑटोक्लेव चक्र, रोज़ जाँच और रिकॉर्ड।" } },
      { title: "Open in front of you", body: "Pouches opened at the chair. Gloves, bibs and cups are single use.", hi: { title: "आपके सामने खोलना", body: "पाउच कुर्सी पर खोले जाते हैं। दस्ताने, बिब और कप एक बार ही इस्तेमाल होते हैं।" } },
    ],
    trust: [
      { title: "Paediatric specialists", body: "Children are seen by dentists with an MDS in paediatric dentistry.", hi: { title: "बच्चों के विशेषज्ञ", body: "बच्चों को पीडियाट्रिक डेंटिस्ट्री में MDS वाले डेंटिस्ट देखते हैं।" } },
      { title: "You are always in the room", body: "No child is taken away from a parent for treatment.", hi: { title: "आप हमेशा कमरे में", body: "इलाज के लिए किसी बच्चे को माता-पिता से अलग नहीं किया जाता।" } },
      { title: "Prevention first", body: "We treat what needs treating and tell you what can simply be watched.", hi: { title: "पहले बचाव", body: "जो ज़रूरी है उसका इलाज करते हैं और बताते हैं कि किस पर बस नज़र रखनी है।" } },
      { title: "Written estimates", body: "Costs on paper before any treatment.", hi: { title: "लिखित अनुमान", body: "किसी भी इलाज से पहले ख़र्च काग़ज़ पर।" } },
    ],
    comfort: [
      { title: "Short appointments", body: "Most visits are under 30 minutes, planned around naps and school.", hi: { title: "छोटी अपॉइंटमेंट", body: "ज़्यादातर विज़िट 30 मिनट से कम, सोने और स्कूल के समय के हिसाब से।" } },
      { title: "Split into steps", body: "Treatment can be spread over several short visits if your child needs it.", hi: { title: "क़दमों में बँटा", body: "बच्चे को ज़रूरत हो तो इलाज कई छोटी विज़िट में बाँटा जा सकता है।" } },
      { title: "Calm rooms", body: "Soft colours, a ceiling screen and the option to dim the lights.", hi: { title: "शांत कमरे", body: "हल्के रंग, छत पर स्क्रीन और रोशनी कम करने का विकल्प।" } },
    ],
  },
});
