/**
 * d7-dental-chain: Mahua Dental Clinics, five branches across Delhi NCR.
 * A multi-branch group: branch finder and branch pages, a doctor directory
 * by branch, specialty and language, one sterilisation and pricing standard
 * in every branch, family care plans and corporate programmes.
 * Contract: E:/myagency/_assets/DENTAL-ARCHITECTURE.md; copy rules:
 * DENTAL-COMPLIANCE.md (8.3.2.1: only branches that exist). Everything here
 * is fiction: the group, the branches, the doctors, the reviews, the rating
 * and the trust figures are SAMPLE content and carry the SampleNote label
 * until the clinic replaces them. Branch addresses, phones and maps are
 * cleared on duplicate; names, hours and sessions are kept. Name forms
 * exactly as in TEMPLATE_NAMES (fromTemplate.ts).
 */
import { defineTemplateContent } from "../shape";
import { DENTAL_PAGE_SETS } from "../../site/pageSets";

export default defineTemplateContent("dental", {
  instituteName: "Mahua Dental Clinics",
  shortName: "Mahua Dental",
  tagline: "Check-ups, root canal, implants, braces and kids dentistry at every branch, seven days a week.",
  city: "New Delhi",
  state: "Delhi",
  country: "India",
  market: "india",
  currency: "INR",
  established: "Since 2009",
  establishedYear: "2009",
  sitePages: [...DENTAL_PAGE_SETS["d7-dental-chain"]],
  heroImage: "/demo/img/dental/hero-multi-chair-floor-800.webp",
  sectionPhotos: { about: "/demo/img/dental/interior-teal-operatory-640.webp" },
  photos: [
    { src: "/demo/img/dental/hero-multi-chair-floor-800.webp", alt: "", category: "Clinics", caption: "Treatment floor", hi: { category: "क्लिनिक", caption: "इलाज का फ़्लोर" } },
    { src: "/demo/img/dental/interior-waiting-teal-640.webp", alt: "", category: "Clinics", caption: "Reception and waiting area", hi: { category: "क्लिनिक", caption: "रिसेप्शन और प्रतीक्षा कक्ष" } },
    { src: "/demo/img/dental/doctor-xray-review-640.webp", alt: "", category: "Care", caption: "Reviewing an X-ray with a patient", hi: { category: "देखभाल", caption: "मरीज़ के साथ एक्स-रे देखना" } },
    { src: "/demo/img/dental/sterile-autoclave-640.webp", alt: "", category: "Sterilisation", caption: "Autoclave in the sterilisation room", hi: { category: "स्टरलाइज़ेशन", caption: "स्टरलाइज़ेशन कक्ष में ऑटोक्लेव" } },
  ],
  about:
    "Mahua Dental Clinics began in 2009 as a single clinic in Lajpat Nagar. It now has five branches across Delhi NCR, each with the same sterilisation protocol, the same price list and the same way of explaining treatment before it starts.\n\nEvery branch has general dentists on site all day, and our MDS specialists move between branches on fixed days, so you can see an endodontist, an orthodontist or an implant surgeon without travelling across the city. Your records are shared between branches, so you can book wherever is nearest this week.",
  mission: "The same standard of dental care in every branch, close to where you live and work.",
  vision: "A dentist within easy reach for every family in Delhi NCR, with nothing to guess about price or process.",
  hi: {
    instituteName: "महुआ डेंटल क्लिनिक्स",
    shortName: "महुआ डेंटल",
    tagline: "हर शाखा में चेक-अप, रूट कैनाल, इम्प्लांट, ब्रेसेज़ और बच्चों के दाँत, हफ़्ते के सातों दिन।",
    city: "नई दिल्ली",
    state: "दिल्ली",
    established: "2009 से",
    establishedYear: "2009",
    about:
      "महुआ डेंटल क्लिनिक्स 2009 में लाजपत नगर में एक क्लिनिक से शुरू हुआ। आज दिल्ली NCR में इसकी पाँच शाखाएँ हैं, हर एक में वही स्टरलाइज़ेशन प्रक्रिया, वही क़ीमत सूची और इलाज शुरू होने से पहले समझाने का वही तरीक़ा।\n\nहर शाखा में पूरे दिन जनरल डेंटिस्ट रहते हैं, और हमारे MDS विशेषज्ञ तय दिनों पर शाखाओं में आते हैं, ताकि आपको एंडोडॉन्टिस्ट, ऑर्थोडॉन्टिस्ट या इम्प्लांट सर्जन के लिए शहर पार न करना पड़े। आपके रिकॉर्ड सभी शाखाओं में साझा होते हैं, इसलिए इस हफ़्ते जो सबसे पास हो, वहाँ बुक कर सकते हैं।",
    mission: "हर शाखा में दाँतों की देखभाल का एक जैसा स्तर, आपके घर और काम के पास।",
    vision: "दिल्ली NCR के हर परिवार की पहुँच में एक डेंटिस्ट, क़ीमत या प्रक्रिया में अंदाज़े की कोई गुंजाइश नहीं।",
  },
  contact: {
    phone: "+91 00000 00000",
    whatsapp: "910000000000",
    email: "care@example.com",
    addressLines: ["Example Road", "Lajpat Nagar, New Delhi 110000"],
    hours: "Mon to Sat, 9 am to 9 pm. Sun, 10 am to 2 pm. Hours vary by branch",
    landmark: "Head office above the Lajpat Nagar branch",
    mapQuery: "Lajpat Nagar, New Delhi",
    hi: {
      addressLines: ["उदाहरण रोड", "लाजपत नगर, नई दिल्ली 110000"],
      hours: "सोम से शनि, सुबह 9 से रात 9। रवि, सुबह 10 से दोपहर 2। शाखा के अनुसार समय अलग",
      landmark: "लाजपत नगर शाखा के ऊपर मुख्य कार्यालय",
    },
  },
  stats: [
    { value: "5", label: "Branches across Delhi NCR", basis: "Delhi, Noida and Gurugram", hi: { label: "शाखाएँ दिल्ली NCR में", basis: "दिल्ली, नोएडा और गुरुग्राम" } },
    { value: "17", label: "Years since our first clinic", basis: "Lajpat Nagar, 2009", hi: { label: "साल पहले क्लिनिक से", basis: "लाजपत नगर, 2009" } },
    { value: "5", label: "MDS specialists across branches", basis: "Endodontics, orthodontics, prosthodontics, oral surgery, paediatrics", hi: { label: "MDS विशेषज्ञ सभी शाखाओं में", basis: "एंडोडॉन्टिक्स, ऑर्थोडॉन्टिक्स, प्रोस्थोडॉन्टिक्स, ओरल सर्जरी, बच्चों की डेंटिस्ट्री" } },
    { value: "7", label: "Days a week", basis: "Sunday mornings at every branch", hi: { label: "दिन हफ़्ते में", basis: "हर शाखा में रविवार सुबह" } },
  ],
  rating: { value: "4.7", count: "1,086", source: "Google reviews across five branches, checked Sep 2026", hi: { source: "पाँचों शाखाओं के गूगल रिव्यू, सितंबर 2026 में देखे गए" } },
  reviews: [
    { quote: "Started my root canal at the Dwarka branch and finished the crown in Lajpat Nagar near my office. Records were already there and the price was the same.", relation: "Patient, root canal and crown", rating: "5", source: "Google review", date: "Sep 2026", consent: true, category: "Root canal", branch: "dwarka-sector-12", hi: { quote: "मेरा रूट कैनाल द्वारका शाखा में शुरू हुआ और दफ़्तर के पास लाजपत नगर में क्राउन पूरा हुआ। रिकॉर्ड पहले से वहाँ थे और क़ीमत भी वही थी।", relation: "मरीज़, रूट कैनाल और क्राउन", source: "गूगल रिव्यू", date: "सितंबर 2026", category: "रूट कैनाल" } },
    { quote: "The orthodontist comes to Noida on Tuesdays, so my daughter's braces check-ups never clash with school. Clear monthly payment plan.", relation: "Parent, braces", rating: "5", source: "Google review", date: "Aug 2026", consent: true, category: "Braces", branch: "noida-sector-62", hi: { quote: "ऑर्थोडॉन्टिस्ट मंगलवार को नोएडा आती हैं, इसलिए बेटी के ब्रेसेज़ की जाँच कभी स्कूल से नहीं टकराती। मासिक भुगतान की साफ़ योजना।", relation: "माता-पिता, ब्रेसेज़", source: "गूगल रिव्यू", date: "अगस्त 2026", category: "ब्रेसेज़" } },
    { quote: "Our company's dental day was organised at the Gurugram branch. Straightforward check-ups, no pressure to buy treatment.", relation: "Employee, corporate check-up", rating: "5", source: "Google review", date: "Jul 2026", consent: true, category: "Check-up", branch: "gurugram-sector-56", hi: { quote: "हमारी कंपनी का डेंटल डे गुरुग्राम शाखा में हुआ। सीधे चेक-अप, इलाज ख़रीदने का कोई दबाव नहीं।", relation: "कर्मचारी, कॉर्पोरेट चेक-अप", source: "गूगल रिव्यू", date: "जुलाई 2026", category: "चेक-अप" } },
    { quote: "Implant planned on a 3D scan in Lajpat Nagar. The surgeon explained the bone graft clearly and the itemised estimate held.", relation: "Patient, implant", rating: "5", source: "Google review", date: "Jun 2026", consent: true, category: "Implants", branch: "lajpat-nagar", hi: { quote: "लाजपत नगर में 3D स्कैन पर इम्प्लांट की योजना बनी। सर्जन ने बोन ग्राफ़्ट साफ़ समझाया और मदवार अनुमान पर क़ायम रहे।", relation: "मरीज़, इम्प्लांट", source: "गूगल रिव्यू", date: "जून 2026", category: "इम्प्लांट" } },
    { quote: "Took my son for his first filling at Rohini. The children's dentist was patient and let me stay beside him.", relation: "Parent, child's filling", rating: "5", source: "Google review", date: "May 2026", consent: true, category: "Kids", branch: "rohini-sector-9", hi: { quote: "बेटे की पहली फ़िलिंग के लिए रोहिणी ले गई। बच्चों की डेंटिस्ट ने धैर्य रखा और मुझे उसके पास रहने दिया।", relation: "माता-पिता, बच्चे की फ़िलिंग", source: "गूगल रिव्यू", date: "मई 2026", category: "बच्चे" } },
    { quote: "Sunday morning emergency for a cracked tooth. Seen quickly at Dwarka, though the waiting room was full.", relation: "Patient, emergency visit", rating: "4", source: "Google review", date: "Apr 2026", consent: true, category: "Emergency", branch: "dwarka-sector-12", hi: { quote: "रविवार सुबह फटे दाँत की इमरजेंसी। द्वारका में जल्दी देखा गया, हालाँकि प्रतीक्षा कक्ष भरा था।", relation: "मरीज़, इमरजेंसी विज़िट", source: "गूगल रिव्यू", date: "अप्रैल 2026", category: "इमरजेंसी" } },
    { quote: "Family care plan covers our check-ups and cleanings for the year. Easy to book at whichever branch suits the day.", relation: "Plan member, family of four", rating: "4", source: "Google review", date: "Mar 2026", consent: true, category: "Plans", branch: "gurugram-sector-56", hi: { quote: "फ़ैमिली केयर प्लान में साल भर के हमारे चेक-अप और सफ़ाई शामिल है। जिस दिन जो शाखा ठीक लगे, वहाँ बुक करना आसान है।", relation: "प्लान सदस्य, चार लोगों का परिवार", source: "गूगल रिव्यू", date: "मार्च 2026", category: "प्लान" } },
  ],
  faq: [
    { title: "Can I visit a different branch for my next appointment?", body: "Yes. Your records, X-rays and treatment plan are shared across all five branches, and prices are the same everywhere.", group: "Branches", hi: { title: "क्या अगली अपॉइंटमेंट के लिए दूसरी शाखा जा सकते हैं?", body: "हाँ। आपके रिकॉर्ड, एक्स-रे और इलाज की योजना पाँचों शाखाओं में साझा होते हैं, और क़ीमतें हर जगह एक जैसी हैं।", group: "शाखाएँ" } },
    { title: "Which branch has the specialist I need?", body: "Each doctor's profile lists the branches and days they are at. General dentists are at every branch all day.", group: "Branches", hi: { title: "मुझे जिस विशेषज्ञ की ज़रूरत है, वह किस शाखा में हैं?", body: "हर डॉक्टर की प्रोफ़ाइल में उनकी शाखाएँ और दिन दिए हैं। जनरल डेंटिस्ट हर शाखा में पूरे दिन रहते हैं।", group: "शाखाएँ" } },
    { title: "What does a consultation cost?", body: "Rs 400 with a general dentist and Rs 700 with a specialist, at every branch. Plan members' check-ups are included in the plan.", group: "Fees", hi: { title: "परामर्श का ख़र्च कितना है?", body: "हर शाखा में जनरल डेंटिस्ट के साथ 400 रुपये और विशेषज्ञ के साथ 700 रुपये। प्लान सदस्यों के चेक-अप प्लान में शामिल हैं।", group: "फ़ीस" } },
    { title: "What does the family care plan include?", body: "Two check-ups, two cleanings and routine X-rays a year for each member, at any branch. Other treatment is charged at the standard price list.", group: "Plans", hi: { title: "फ़ैमिली केयर प्लान में क्या शामिल है?", body: "हर सदस्य के लिए साल में दो चेक-अप, दो सफ़ाई और सामान्य एक्स-रे, किसी भी शाखा में। बाक़ी इलाज सामान्य क़ीमत सूची के अनुसार।", group: "प्लान" } },
    { title: "Do you offer EMI?", body: "EMI options may be available through partner lenders, subject to their approval, for treatment above Rs 15,000.", group: "Fees", hi: { title: "क्या EMI मिलती है?", body: "15,000 रुपये से ज़्यादा के इलाज पर साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।", group: "फ़ीस" } },
    { title: "Is sterilisation the same at every branch?", body: "Yes. Every branch follows one written protocol with a Class B autoclave, sealed pouches and a daily test log, checked by our clinical team every month.", group: "Safety", hi: { title: "क्या हर शाखा में स्टरलाइज़ेशन एक जैसा है?", body: "हाँ। हर शाखा एक लिखित प्रक्रिया अपनाती है, क्लास B ऑटोक्लेव, सील पाउच और रोज़ के टेस्ट रिकॉर्ड के साथ, जिसे हमारी क्लिनिकल टीम हर महीने जाँचती है।", group: "सुरक्षा" } },
    { title: "Can I get a same-day appointment?", body: "For pain, swelling or a broken tooth, each branch keeps emergency slots. Same-day slots depend on availability, so call or WhatsApp first.", group: "Booking", hi: { title: "क्या उसी दिन अपॉइंटमेंट मिल सकता है?", body: "दर्द, सूजन या टूटे दाँत के लिए हर शाखा इमरजेंसी स्लॉट रखती है। उसी दिन के स्लॉट उपलब्धता पर निर्भर हैं, इसलिए पहले फ़ोन या व्हाट्सऐप करें।", group: "बुकिंग" } },
    { title: "Can I choose a female dentist?", body: "Yes. Filter the doctors page by gender and branch, or mention it when you book.", group: "Booking", hi: { title: "क्या महिला डेंटिस्ट चुन सकते हैं?", body: "हाँ। डॉक्टरों के पेज पर लिंग और शाखा से छाँटें, या बुकिंग के समय बताएँ।", group: "बुकिंग" } },
    { title: "Do you work with companies?", body: "Yes. We arrange check-up days at a branch near your office and a simple plan for employees. Write to us for details.", group: "Corporate", hi: { title: "क्या आप कंपनियों के साथ काम करते हैं?", body: "हाँ। हम आपके दफ़्तर के पास की शाखा में चेक-अप डे और कर्मचारियों के लिए आसान प्लान की व्यवस्था करते हैं। जानकारी के लिए लिखें।", group: "कॉर्पोरेट" } },
  ],
  posts: [
    {
      slug: "toothache-at-night", title: "Toothache at night: what helps until morning", date: "16 Sep 2026", category: "Emergency", treatment: "root-canal-treatment",
      author: "Dr. Sandeep Yadav", reviewedBy: "Medically reviewed by Dr. Sandeep Yadav, MDS (Conservative Dentistry and Endodontics)",
      excerpt: "Why tooth pain gets worse at night, what you can safely do, and when to go to a hospital instead.",
      body: "Tooth pain often feels worse lying down because more blood flows to the head, raising pressure around an inflamed nerve.\n\nWhat helps: take a painkiller you have used safely before, at the dose on the pack. Sleep with your head raised on an extra pillow. Rinse with warm salt water. Hold a cold pack against the cheek for 15 minutes at a time.\n\nWhat to avoid: aspirin or clove oil held against the gum can burn it. Very hot or cold food and drink will set the pain off.\n\nGo to a hospital emergency department or call 112 if the swelling spreads towards the eye or neck, or you have trouble breathing or swallowing.\n\nOtherwise, call or WhatsApp us in the morning. Night pain usually means the nerve is inflamed, and it rarely settles on its own.",
      hi: {
        title: "रात में दाँत दर्द: सुबह तक क्या मदद करता है", date: "16 सितंबर 2026", category: "इमरजेंसी", author: "डॉ. संदीप यादव", reviewedBy: "डॉ. संदीप यादव, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "रात में दाँत दर्द क्यों बढ़ता है, आप सुरक्षित रूप से क्या कर सकते हैं, और कब इसकी जगह अस्पताल जाना चाहिए।",
        body: "लेटने पर दाँत दर्द अक्सर ज़्यादा लगता है क्योंकि सिर की ओर ज़्यादा ख़ून जाता है, जिससे सूजी नस के आसपास दबाव बढ़ता है।\n\nक्या मदद करता है: पहले सुरक्षित इस्तेमाल की हुई दर्द की दवा पैक पर लिखी ख़ुराक में लें। एक अतिरिक्त तकिये से सिर ऊँचा रखकर सोएँ। गुनगुने नमक वाले पानी से कुल्ला करें। गाल पर 15-15 मिनट ठंडी सिकाई करें।\n\nक्या न करें: मसूड़े पर रखी एस्पिरिन या लौंग का तेल उसे जला सकता है। बहुत गरम या ठंडा खाना-पीना दर्द भड़काएगा।\n\nअगर सूजन आँख या गर्दन की ओर फैले, या साँस लेने या निगलने में दिक़्क़त हो, तो अस्पताल के इमरजेंसी विभाग जाएँ या 112 पर कॉल करें।\n\nनहीं तो सुबह हमें फ़ोन या व्हाट्सऐप करें। रात का दर्द आमतौर पर बताता है कि नस सूजी है, और यह शायद ही अपने आप ठीक होता है।",
      },
    },
    {
      slug: "how-often-check-up", title: "How often do you really need a dental check-up?", date: "2 Sep 2026", category: "Prevention", treatment: "dental-check-up",
      author: "Dr. Ritu Bhatia", reviewedBy: "Medically reviewed by Dr. Ritu Bhatia, MDS (Prosthodontics and Crown and Bridge)",
      excerpt: "Every six months is a good default, but your gums, fillings and habits decide the right interval for you.",
      body: "Six months is a sensible default for most adults and children. It is short enough to catch decay while a small filling will do.\n\nSome people need to come more often: every three to four months if you have gum disease, diabetes, smoke or chew tobacco, or have many fillings or crowns.\n\nSome can come less often: once a year if your teeth and gums have been healthy for several years and you have few or no fillings.\n\nAt each check-up we look at every tooth, the gums, the bite and the soft tissues of the mouth, including early signs of oral cancer, which is common in India among tobacco users.\n\nAsk your dentist to tell you your interval and why.",
      hi: {
        title: "दाँतों का चेक-अप असल में कितनी बार चाहिए?", date: "2 सितंबर 2026", category: "बचाव", author: "डॉ. रितु भाटिया", reviewedBy: "डॉ. रितु भाटिया, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "हर छह महीने अच्छा सामान्य नियम है, पर आपके मसूड़े, फ़िलिंग और आदतें आपके लिए सही अंतर तय करती हैं।",
        body: "ज़्यादातर वयस्कों और बच्चों के लिए छह महीने समझदारी भरा सामान्य अंतर है। यह इतना छोटा है कि कीड़ा तब पकड़ा जाए जब छोटी फ़िलिंग काफ़ी हो।\n\nकुछ लोगों को ज़्यादा बार आना चाहिए: अगर मसूड़ों की बीमारी, डायबिटीज़ हो, धूम्रपान या तंबाकू का सेवन करते हों, या कई फ़िलिंग या क्राउन हों, तो हर तीन-चार महीने।\n\nकुछ कम बार आ सकते हैं: अगर कई सालों से दाँत और मसूड़े स्वस्थ रहे हों और फ़िलिंग कम या न हों, तो साल में एक बार।\n\nहर चेक-अप में हम हर दाँत, मसूड़े, काटना और मुँह की नरम त्वचा देखते हैं, जिसमें मुँह के कैंसर के शुरुआती संकेत भी शामिल हैं, जो भारत में तंबाकू इस्तेमाल करने वालों में आम है।\n\nअपने डेंटिस्ट से अपना अंतर और उसका कारण पूछें।",
      },
    },
    {
      slug: "sensitive-teeth", title: "Sensitive teeth: common causes and what helps", date: "18 Aug 2026", category: "Everyday care", treatment: "teeth-cleaning",
      author: "Dr. Sandeep Yadav", reviewedBy: "Medically reviewed by Dr. Sandeep Yadav, MDS (Conservative Dentistry and Endodontics)",
      excerpt: "A sharp twinge with cold water has several possible causes. Some need a toothpaste, others a dentist.",
      body: "Sensitivity is a short, sharp pain with cold, sweet or sour food that goes within seconds.\n\nCommon causes: brushing too hard, which wears enamel near the gums; gums that have receded and exposed the root; grinding; acidic drinks; a cracked tooth or a new cavity.\n\nWhat helps at home: a soft brush with gentle strokes, a desensitising toothpaste used twice a day for at least two weeks, and fewer acidic drinks between meals.\n\nSee a dentist if one tooth is sensitive, if the pain lingers after the cold is gone, or if it wakes you at night. Those point to decay, a crack or an inflamed nerve rather than simple sensitivity.",
      hi: {
        title: "संवेदनशील दाँत: आम कारण और क्या मदद करता है", date: "18 अगस्त 2026", category: "रोज़ की देखभाल", author: "डॉ. संदीप यादव", reviewedBy: "डॉ. संदीप यादव, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स) द्वारा चिकित्सकीय समीक्षा",
        excerpt: "ठंडे पानी से तेज़ झनझनाहट के कई संभावित कारण हैं। कुछ में टूथपेस्ट चाहिए, कुछ में डेंटिस्ट।",
        body: "संवेदनशीलता ठंडे, मीठे या खट्टे खाने से होने वाला छोटा, तेज़ दर्द है जो कुछ सेकंड में चला जाता है।\n\nआम कारण: बहुत ज़ोर से ब्रश करना, जिससे मसूड़ों के पास इनेमल घिसता है; मसूड़ों का पीछे हटकर जड़ खुल जाना; दाँत पीसना; खट्टे पेय; फटा दाँत या नया कीड़ा।\n\nघर पर क्या मदद करता है: नरम ब्रश से हल्के हाथ से ब्रश, कम से कम दो हफ़्ते दिन में दो बार संवेदनशीलता वाला टूथपेस्ट, और खाने के बीच कम खट्टे पेय।\n\nडेंटिस्ट को दिखाएँ अगर एक ही दाँत संवेदनशील हो, ठंडा हटने के बाद भी दर्द रहे, या रात में नींद खुले। ये साधारण संवेदनशीलता नहीं, कीड़ा, दरार या सूजी नस की ओर इशारा करते हैं।",
      },
    },
  ],
  dental: {
    legalName: "Mahua Dental Clinics Private Limited (sample)",
    hi: { legalName: "महुआ डेंटल क्लिनिक्स प्राइवेट लिमिटेड (नमूना)" },
    hero: {
      variant: "calm-branch",
      pill: "Five dental clinics across Delhi NCR",
      headline: "One standard of care, *near you*.",
      lead: "Check-ups, root canal, implants, braces and kids dentistry in Dwarka, Lajpat Nagar, Rohini, Noida and Gurugram. Open seven days.",
      credential: "Dr. Ritu Bhatia, BDS, MDS (Prosthodontics and Crown and Bridge), Clinical Director",
      hi: {
        pill: "दिल्ली NCR में पाँच डेंटल क्लिनिक",
        headline: "देखभाल का एक स्तर, *आपके पास*।",
        lead: "द्वारका, लाजपत नगर, रोहिणी, नोएडा और गुरुग्राम में चेक-अप, रूट कैनाल, इम्प्लांट, ब्रेसेज़ और बच्चों के दाँत। सातों दिन खुला।",
        credential: "डॉ. रितु भाटिया, BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज), क्लिनिकल डायरेक्टर",
      },
    },
    branches: [
      {
        slug: "lajpat-nagar", name: "Lajpat Nagar", city: "New Delhi", photo: "/demo/img/dental/interior-teal-operatory-640.webp",
        addressLines: ["Example Road, Lajpat Nagar", "New Delhi 110000"], phone: "+91 00000 00000", whatsapp: "910000000000", mapQuery: "Lajpat Nagar, New Delhi",
        landmark: "First floor, near the central market", hours: "Mon to Sat, 9 am to 9 pm. Sun, 10 am to 2 pm",
        sessions: [{ days: [1, 2, 3, 4, 5, 6], from: "09:00", to: "21:00" }, { days: [0], from: "10:00", to: "14:00" }],
        doctors: ["ritu-bhatia", "ayesha-khan", "manish-tyagi", "deepak-negi"],
        access: "Lift to the first floor; step-free from the street.", parking: "Paid parking at the market; limited street parking.", transit: "A short walk from Lajpat Nagar metro station.",
        hi: { name: "लाजपत नगर", city: "नई दिल्ली", addressLines: ["उदाहरण रोड, लाजपत नगर", "नई दिल्ली 110000"], landmark: "पहली मंज़िल, सेंट्रल मार्केट के पास", hours: "सोम से शनि, सुबह 9 से रात 9। रवि, सुबह 10 से दोपहर 2", access: "पहली मंज़िल तक लिफ़्ट; सड़क से बिना सीढ़ी।", parking: "मार्केट में पेड पार्किंग; सड़क पर सीमित पार्किंग।", transit: "लाजपत नगर मेट्रो स्टेशन से थोड़ी दूरी पर पैदल।" },
      },
      {
        slug: "dwarka-sector-12", name: "Dwarka Sector 12", city: "New Delhi", photo: "/demo/img/dental/interior-waiting-teal-640.webp",
        addressLines: ["Example Road, Dwarka Sector 12", "New Delhi 110000"], phone: "+91 00000 00000", whatsapp: "910000000000", mapQuery: "Dwarka Sector 12, New Delhi",
        landmark: "Ground floor of a shopping complex", hours: "Mon to Sat, 9 am to 9 pm. Sun, 10 am to 2 pm",
        sessions: [{ days: [1, 2, 3, 4, 5, 6], from: "09:00", to: "21:00" }, { days: [0], from: "10:00", to: "14:00" }],
        doctors: ["sandeep-yadav", "deepak-negi", "manish-tyagi"],
        access: "Ground floor, step-free.", parking: "Parking in the complex.", transit: "A few minutes' walk from Dwarka Sector 12 metro station.",
        hi: { name: "द्वारका सेक्टर 12", city: "नई दिल्ली", addressLines: ["उदाहरण रोड, द्वारका सेक्टर 12", "नई दिल्ली 110000"], landmark: "एक शॉपिंग कॉम्प्लेक्स का भूतल", hours: "सोम से शनि, सुबह 9 से रात 9। रवि, सुबह 10 से दोपहर 2", access: "भूतल, बिना सीढ़ी।", parking: "कॉम्प्लेक्स में पार्किंग।", transit: "द्वारका सेक्टर 12 मेट्रो स्टेशन से कुछ मिनट पैदल।" },
      },
      {
        slug: "rohini-sector-9", name: "Rohini Sector 9", city: "New Delhi", photo: "/demo/img/dental/interior-teal-suite-640.webp",
        addressLines: ["Example Road, Rohini Sector 9", "New Delhi 110000"], phone: "+91 00000 00000", whatsapp: "910000000000", mapQuery: "Rohini Sector 9, New Delhi",
        landmark: "First floor, above a bank branch", hours: "Mon to Sat, 10 am to 8 pm. Sun, 10 am to 2 pm",
        sessions: [{ days: [1, 2, 3, 4, 5, 6], from: "10:00", to: "20:00" }, { days: [0], from: "10:00", to: "14:00" }],
        doctors: ["sandeep-yadav", "priyanka-sethi"],
        access: "Lift to the first floor.", parking: "Street parking on the service road.", transit: "Near Rohini Sector 9 metro station.",
        hi: { name: "रोहिणी सेक्टर 9", city: "नई दिल्ली", addressLines: ["उदाहरण रोड, रोहिणी सेक्टर 9", "नई दिल्ली 110000"], landmark: "पहली मंज़िल, एक बैंक शाखा के ऊपर", hours: "सोम से शनि, सुबह 10 से रात 8। रवि, सुबह 10 से दोपहर 2", access: "पहली मंज़िल तक लिफ़्ट।", parking: "सर्विस रोड पर सड़क किनारे पार्किंग।", transit: "रोहिणी सेक्टर 9 मेट्रो स्टेशन के पास।" },
      },
      {
        slug: "noida-sector-62", name: "Noida Sector 62", city: "Noida", photo: "/demo/img/dental/doctor-clinic-floor-640.webp",
        addressLines: ["Example Road, Sector 62", "Noida 201000"], phone: "+91 00000 00000", whatsapp: "910000000000", mapQuery: "Sector 62, Noida",
        landmark: "Ground floor of an office complex", hours: "Mon to Sat, 9 am to 9 pm. Sun, 10 am to 2 pm",
        sessions: [{ days: [1, 2, 3, 4, 5, 6], from: "09:00", to: "21:00" }, { days: [0], from: "10:00", to: "14:00" }],
        doctors: ["ayesha-khan", "shruti-arora"],
        access: "Ground floor, step-free.", parking: "Visitor parking in the complex basement.", transit: "A short auto ride from the nearest metro station.",
        hi: { name: "नोएडा सेक्टर 62", city: "नोएडा", addressLines: ["उदाहरण रोड, सेक्टर 62", "नोएडा 201000"], landmark: "एक दफ़्तर परिसर का भूतल", hours: "सोम से शनि, सुबह 9 से रात 9। रवि, सुबह 10 से दोपहर 2", access: "भूतल, बिना सीढ़ी।", parking: "परिसर के बेसमेंट में विज़िटर पार्किंग।", transit: "सबसे पास के मेट्रो स्टेशन से ऑटो से थोड़ी दूरी।" },
      },
      {
        slug: "gurugram-sector-56", name: "Gurugram Sector 56", city: "Gurugram", photo: "/demo/img/dental/interior-lounge-corridor-640.webp",
        addressLines: ["Example Road, Sector 56", "Gurugram 122000"], phone: "+91 00000 00000", whatsapp: "910000000000", mapQuery: "Sector 56, Gurugram",
        landmark: "First floor of a neighbourhood shopping centre", hours: "Mon to Sat, 9 am to 9 pm. Sun, 10 am to 2 pm",
        sessions: [{ days: [1, 2, 3, 4, 5, 6], from: "09:00", to: "21:00" }, { days: [0], from: "10:00", to: "14:00" }],
        doctors: ["ritu-bhatia", "priyanka-sethi", "manish-tyagi"],
        access: "Lift to the first floor.", parking: "Surface parking at the shopping centre.", transit: "A short walk from the nearest rapid metro station.",
        hi: { name: "गुरुग्राम सेक्टर 56", city: "गुरुग्राम", addressLines: ["उदाहरण रोड, सेक्टर 56", "गुरुग्राम 122000"], landmark: "एक पड़ोस के शॉपिंग सेंटर की पहली मंज़िल", hours: "सोम से शनि, सुबह 9 से रात 9। रवि, सुबह 10 से दोपहर 2", access: "पहली मंज़िल तक लिफ़्ट।", parking: "शॉपिंग सेंटर में खुली पार्किंग।", transit: "सबसे पास के रैपिड मेट्रो स्टेशन से थोड़ी दूरी पर पैदल।" },
      },
    ],
    doctors: [
      {
        slug: "ritu-bhatia", name: "Dr. Ritu Bhatia", photo: "/demo/img/people/dentist-w04-240.webp", gender: "female", lead: true,
        qualification: "BDS, MDS (Prosthodontics and Crown and Bridge)", specialisation: "Prosthodontist",
        focus: "Implant crowns, bridges, dentures, full-mouth rehabilitation; clinical standards across branches", experience: "19 years in practice",
        languages: ["Hindi", "English", "Punjabi"], regNo: "Reg. no. A-00000 (sample)", days: "Lajpat Nagar Mon, Wed, Fri; Gurugram Tue, Thu, Sat",
        branches: ["lajpat-nagar", "gurugram-sector-56"],
        bio: "Dr. Ritu Bhatia opened the first clinic in Lajpat Nagar in 2009 and is the group's clinical director. She still sees patients four days a week for crowns, bridges, dentures and implant restorations.\n\nThe rest of her time goes into making every branch work the same way: one sterilisation protocol, one price list, one way of writing an estimate. She audits each branch every month.",
        quote: "A patient should get the same care in Rohini as in Gurugram. That is the whole job of a group.",
        training: ["BDS, 2003 (sample)", "MDS, Prosthodontics and Crown and Bridge, 2007 (sample)", "Implant prosthetics course, 2013 (sample)"],
        memberships: ["Indian Prosthodontic Society (sample)", "Indian Dental Association (sample)"],
        hi: {
          name: "डॉ. रितु भाटिया", qualification: "BDS, MDS (प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज)", specialisation: "प्रोस्थोडॉन्टिस्ट",
          focus: "इम्प्लांट क्राउन, ब्रिज, डेंचर, पूरे मुँह का पुनर्निर्माण; सभी शाखाओं के क्लिनिकल मानक", experience: "19 साल का अनुभव",
          languages: ["हिंदी", "अंग्रेज़ी", "पंजाबी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "लाजपत नगर सोम, बुध, शुक्र; गुरुग्राम मंगल, गुरु, शनि",
          bio: "डॉ. रितु भाटिया ने 2009 में लाजपत नगर में पहला क्लिनिक खोला और वे समूह की क्लिनिकल डायरेक्टर हैं। वे अब भी हफ़्ते में चार दिन क्राउन, ब्रिज, डेंचर और इम्प्लांट पर दाँतों के लिए मरीज़ देखती हैं।\n\nबाक़ी समय वे हर शाखा को एक तरह से चलाने में लगाती हैं: एक स्टरलाइज़ेशन प्रक्रिया, एक क़ीमत सूची, अनुमान लिखने का एक तरीक़ा। वे हर महीने हर शाखा की जाँच करती हैं।",
          quote: "मरीज़ को रोहिणी में भी वही देखभाल मिलनी चाहिए जो गुरुग्राम में। किसी समूह का पूरा काम यही है।",
          training: ["BDS, 2003 (नमूना)", "MDS, प्रोस्थोडॉन्टिक्स और क्राउन एंड ब्रिज, 2007 (नमूना)", "इम्प्लांट प्रोस्थेटिक्स कोर्स, 2013 (नमूना)"],
          memberships: ["इंडियन प्रोस्थोडॉन्टिक सोसाइटी (नमूना)", "इंडियन डेंटल एसोसिएशन (नमूना)"],
        },
      },
      {
        slug: "sandeep-yadav", name: "Dr. Sandeep Yadav", photo: "/demo/img/people/dentist-m01-240.webp", gender: "male",
        qualification: "BDS, MDS (Conservative Dentistry and Endodontics)", specialisation: "Endodontist",
        focus: "Root canal treatment and re-treatment, cracked teeth", experience: "12 years in practice",
        languages: ["Hindi", "English", "Haryanvi"], regNo: "Reg. no. A-00000 (sample)", days: "Dwarka Mon, Wed, Fri, Sun; Rohini Tue, Thu, Sat",
        branches: ["dwarka-sector-12", "rohini-sector-9"],
        bio: "Dr. Sandeep Yadav leads root canal treatment across the group and sees most re-treatments of teeth that still hurt after an earlier root canal. He uses rotary instruments and magnification, and shows each patient the X-ray before and after.\n\nHe also writes and reviews the group's patient guides on pain and emergencies.",
        quote: "Pain at night is a message. It is worth finding out what the tooth is telling you.",
        training: ["BDS, 2009 (sample)", "MDS, Conservative Dentistry and Endodontics, 2013 (sample)"],
        memberships: ["Indian Endodontic Society (sample)"],
        hi: {
          name: "डॉ. संदीप यादव", qualification: "BDS, MDS (कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स)", specialisation: "एंडोडॉन्टिस्ट",
          focus: "रूट कैनाल और दोबारा इलाज, दरार वाले दाँत", experience: "12 साल का अनुभव",
          languages: ["हिंदी", "अंग्रेज़ी", "हरियाणवी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "द्वारका सोम, बुध, शुक्र, रवि; रोहिणी मंगल, गुरु, शनि",
          bio: "डॉ. संदीप यादव पूरे समूह में रूट कैनाल इलाज की अगुवाई करते हैं और पहले के रूट कैनाल के बाद भी दर्द वाले ज़्यादातर दाँतों का दोबारा इलाज देखते हैं। वे रोटरी औज़ार और मैग्निफ़िकेशन इस्तेमाल करते हैं, और हर मरीज़ को इलाज से पहले और बाद का एक्स-रे दिखाते हैं।\n\nदर्द और इमरजेंसी पर समूह की मरीज़ गाइड भी वही लिखते और जाँचते हैं।",
          quote: "रात का दर्द एक संदेश है। दाँत क्या कह रहा है, यह जानना ज़रूरी है।",
          training: ["BDS, 2009 (नमूना)", "MDS, कंज़र्वेटिव डेंटिस्ट्री और एंडोडॉन्टिक्स, 2013 (नमूना)"],
          memberships: ["इंडियन एंडोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "ayesha-khan", name: "Dr. Ayesha Khan", photo: "/demo/img/people/dentist-w02-240.webp", gender: "female",
        qualification: "BDS, MDS (Orthodontics and Dentofacial Orthopaedics)", specialisation: "Orthodontist",
        focus: "Braces and clear aligners for teenagers and adults", experience: "10 years in practice",
        languages: ["Hindi", "Urdu", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Noida Tue, Thu, Sat; Lajpat Nagar Mon, Wed, Fri",
        branches: ["noida-sector-62", "lajpat-nagar"],
        bio: "Dr. Ayesha Khan runs the group's orthodontic clinics in Noida and Lajpat Nagar. She plans braces and aligner cases on a 3D scan and schedules check-ins around school and office hours, including early evenings.\n\nShe is careful to say when aligners are not the right choice and braces will do the job more predictably.",
        quote: "The right appliance is the one that will actually work for your teeth and your routine.",
        training: ["BDS, 2011 (sample)", "MDS, Orthodontics and Dentofacial Orthopaedics, 2016 (sample)"],
        memberships: ["Indian Orthodontic Society (sample)"],
        hi: {
          name: "डॉ. आयशा ख़ान", qualification: "BDS, MDS (ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स)", specialisation: "ऑर्थोडॉन्टिस्ट",
          focus: "किशोरों और वयस्कों के लिए ब्रेसेज़ और क्लियर अलाइनर", experience: "10 साल का अनुभव",
          languages: ["हिंदी", "उर्दू", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "नोएडा मंगल, गुरु, शनि; लाजपत नगर सोम, बुध, शुक्र",
          bio: "डॉ. आयशा ख़ान नोएडा और लाजपत नगर में समूह के ऑर्थोडॉन्टिक क्लिनिक चलाती हैं। वे ब्रेसेज़ और अलाइनर की योजना 3D स्कैन पर बनाती हैं और जाँच को स्कूल और दफ़्तर के समय के हिसाब से, शाम समेत, रखती हैं।\n\nजब अलाइनर सही विकल्प न हों और ब्रेसेज़ ज़्यादा भरोसे से काम करें, तो वे यह साफ़ बताती हैं।",
          quote: "सही उपकरण वही है जो आपके दाँतों और आपकी दिनचर्या में असल में काम करे।",
          training: ["BDS, 2011 (नमूना)", "MDS, ऑर्थोडॉन्टिक्स और डेंटोफ़ेशियल ऑर्थोपेडिक्स, 2016 (नमूना)"],
          memberships: ["इंडियन ऑर्थोडॉन्टिक सोसाइटी (नमूना)"],
        },
      },
      {
        slug: "manish-tyagi", name: "Dr. Manish Tyagi", photo: "/demo/img/people/dentist-m02-240.webp", gender: "male", visiting: true,
        qualification: "BDS, MDS (Oral and Maxillofacial Surgery)", specialisation: "Oral and maxillofacial surgeon", focus: "Implant surgery, wisdom teeth, bone grafts",
        experience: "15 years in practice", languages: ["Hindi", "English"], regNo: "Reg. no. A-00000 (sample)", days: "Lajpat Nagar Tue; Dwarka Thu; Gurugram Sat",
        branches: ["lajpat-nagar", "dwarka-sector-12", "gurugram-sector-56"],
        hi: { name: "डॉ. मनीष त्यागी", qualification: "BDS, MDS (ओरल एंड मैक्सिलोफ़ेशियल सर्जरी)", specialisation: "ओरल और मैक्सिलोफ़ेशियल सर्जन", focus: "इम्प्लांट सर्जरी, अक़्ल दाढ़, बोन ग्राफ़्ट", experience: "15 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "लाजपत नगर मंगल; द्वारका गुरु; गुरुग्राम शनि" },
      },
      {
        slug: "priyanka-sethi", name: "Dr. Priyanka Sethi", photo: "/demo/img/people/dentist-w05-240.webp", gender: "female",
        qualification: "BDS, MDS (Paediatric and Preventive Dentistry)", specialisation: "Paediatric dentist", focus: "Children's check-ups, fillings, sealants and first visits",
        experience: "8 years in practice", languages: ["Hindi", "English", "Punjabi"], regNo: "Reg. no. A-00000 (sample)", days: "Rohini Mon, Wed, Fri; Gurugram Tue, Thu, Sun",
        branches: ["rohini-sector-9", "gurugram-sector-56"],
        hi: { name: "डॉ. प्रियंका सेठी", qualification: "BDS, MDS (पीडियाट्रिक और प्रिवेंटिव डेंटिस्ट्री)", specialisation: "बच्चों की डेंटिस्ट", focus: "बच्चों का चेक-अप, फ़िलिंग, सीलेंट और पहली विज़िट", experience: "8 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "पंजाबी"], regNo: "रजि. नं. A-00000 (नमूना)", days: "रोहिणी सोम, बुध, शुक्र; गुरुग्राम मंगल, गुरु, रवि" },
      },
      {
        slug: "deepak-negi", name: "Dr. Deepak Negi", photo: "/demo/img/people/dentist-m03-240.webp", gender: "male",
        qualification: "BDS", specialisation: "General dentist", focus: "Check-ups, fillings, cleaning, extractions",
        experience: "7 years in practice", languages: ["Hindi", "English", "Garhwali"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        branches: ["dwarka-sector-12", "lajpat-nagar"],
        hi: { name: "डॉ. दीपक नेगी", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "चेक-अप, फ़िलिंग, सफ़ाई, दाँत निकालना", experience: "7 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "गढ़वाली"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि" },
      },
      {
        slug: "shruti-arora", name: "Dr. Shruti Arora", photo: "/demo/img/people/dentist-w03-240.webp", gender: "female",
        qualification: "BDS", specialisation: "General dentist", focus: "Check-ups, fillings, cleaning, whitening",
        experience: "5 years in practice", languages: ["Hindi", "English", "Bengali"], regNo: "Reg. no. A-00000 (sample)", days: "Mon to Sat",
        branches: ["noida-sector-62"],
        hi: { name: "डॉ. श्रुति अरोड़ा", qualification: "BDS", specialisation: "जनरल डेंटिस्ट", focus: "चेक-अप, फ़िलिंग, सफ़ाई, व्हाइटनिंग", experience: "5 साल का अनुभव", languages: ["हिंदी", "अंग्रेज़ी", "बांग्ला"], regNo: "रजि. नं. A-00000 (नमूना)", days: "सोम से शनि" },
      },
    ],
    treatments: [
      {
        slug: "dental-check-up", name: "Dental check-up", category: "General dentistry", icon: "checkup", image: "/demo/img/dental/patient-man-checkup-640.webp", featured: true, reason: "checkup",
        summary: "A full examination at any branch, with X-rays only when needed and a written plan.",
        what: "A check-up looks at every tooth, the gums, the bite and the soft tissues of the mouth, including early signs of oral cancer. X-rays are taken only when they will change a decision. Your findings go into one record that every branch can see.",
        symptoms: ["More than six months since your last check-up", "Bleeding gums", "Sensitivity or food trapping"],
        whoNeedsIt: ["Adults and children every six to twelve months", "Tobacco users, who need oral cancer screening"],
        steps: [
          { title: "Examine", body: "Teeth, gums, bite and soft tissues.", hi: { title: "जाँच", body: "दाँत, मसूड़े, काटना और नरम त्वचा।" } },
          { title: "X-ray if needed", body: "Digital, low dose, shown to you.", hi: { title: "ज़रूरत हो तो एक्स-रे", body: "डिजिटल, कम डोज़, आपको दिखाया जाता है।" } },
          { title: "Plan", body: "What is needed now, what can wait, and a written estimate.", hi: { title: "योजना", body: "अभी क्या ज़रूरी है, क्या रुक सकता है, और लिखित अनुमान।" } },
        ],
        duration: "One visit", visits: "About 20 minutes", recovery: "None.",
        comfort: "No injections for a check-up.",
        faqs: [{ title: "Is the check-up included in the care plan?", body: "Yes. Plan members get two check-ups a year at any branch.", hi: { title: "क्या चेक-अप केयर प्लान में शामिल है?", body: "हाँ। प्लान सदस्यों को किसी भी शाखा में साल में दो चेक-अप मिलते हैं।" } }],
        fromPrice: "400", priceNote: "consultation",
        hi: {
          name: "दाँतों का चेक-अप", category: "सामान्य डेंटिस्ट्री",
          summary: "किसी भी शाखा में पूरी जाँच, ज़रूरत हो तभी एक्स-रे और लिखित योजना।",
          what: "चेक-अप में हर दाँत, मसूड़े, काटना और मुँह की नरम त्वचा देखी जाती है, जिसमें मुँह के कैंसर के शुरुआती संकेत भी शामिल हैं। एक्स-रे तभी लिया जाता है जब उससे फ़ैसला बदले। आपकी जानकारी एक ही रिकॉर्ड में जाती है जिसे हर शाखा देख सकती है।",
          symptoms: ["पिछले चेक-अप को छह महीने से ज़्यादा", "मसूड़ों से ख़ून", "झनझनाहट या खाना फँसना"],
          whoNeedsIt: ["बड़े और बच्चे हर छह से बारह महीने", "तंबाकू इस्तेमाल करने वाले, जिन्हें मुँह के कैंसर की जाँच चाहिए"],
          duration: "एक विज़िट", visits: "लगभग 20 मिनट", recovery: "कुछ नहीं।",
          comfort: "चेक-अप में इंजेक्शन नहीं।", priceNote: "परामर्श",
        },
      },
      {
        slug: "teeth-cleaning", name: "Teeth cleaning", category: "General dentistry", icon: "cleaning", image: "/demo/img/dental/doctor-at-work-blue-640.webp", reason: "cleaning",
        summary: "Scaling and polishing to remove tartar and stains, at every branch.",
        what: "Scaling removes hardened tartar above and just below the gums; polishing removes surface stain. It is the first step for bleeding gums and bad breath, and part of every care plan.",
        symptoms: ["Bleeding gums", "Tartar or stains", "Bad breath"],
        whoNeedsIt: ["Most adults every six to twelve months"],
        steps: [
          { title: "Scale", body: "Ultrasonic scaling with water spray.", hi: { title: "स्केलिंग", body: "पानी की फुहार के साथ अल्ट्रासोनिक स्केलिंग।" } },
          { title: "Polish", body: "Surface stains removed.", hi: { title: "पॉलिश", body: "ऊपरी दाग़ हटाए जाते हैं।" } },
          { title: "Advise", body: "Brushing and flossing shown for your teeth.", hi: { title: "सलाह", body: "आपके दाँतों के लिए ब्रश और फ़्लॉस का तरीक़ा।" } },
        ],
        duration: "One visit", visits: "30 to 45 minutes", recovery: "Mild sensitivity for a day.",
        comfort: "Usually no anaesthetic; sensitive areas can be numbed.",
        faqs: [{ title: "Does cleaning damage enamel?", body: "No. Scaling removes deposits, not enamel.", hi: { title: "क्या सफ़ाई से इनेमल को नुकसान होता है?", body: "नहीं। स्केलिंग जमा परत हटाती है, इनेमल नहीं।" } }],
        fromPrice: "1,200", priceNote: "full mouth",
        hi: {
          name: "दाँतों की सफ़ाई", category: "सामान्य डेंटिस्ट्री",
          summary: "हर शाखा में टार्टर और दाग़ हटाने के लिए स्केलिंग और पॉलिश।",
          what: "स्केलिंग मसूड़ों के ऊपर और ठीक नीचे जमा सख़्त टार्टर हटाती है; पॉलिश ऊपरी दाग़ हटाती है। मसूड़ों से ख़ून और मुँह की बदबू में यह पहला क़दम है, और हर केयर प्लान का हिस्सा है।",
          symptoms: ["मसूड़ों से ख़ून", "टार्टर या दाग़", "मुँह की बदबू"],
          whoNeedsIt: ["ज़्यादातर वयस्क हर छह से बारह महीने"],
          duration: "एक विज़िट", visits: "30 से 45 मिनट", recovery: "एक दिन हल्की झनझनाहट।",
          comfort: "आमतौर पर सुन्न करने की ज़रूरत नहीं; संवेदनशील जगह सुन्न की जा सकती है।", priceNote: "पूरा मुँह",
        },
      },
      {
        slug: "fillings", name: "Tooth-coloured fillings", category: "General dentistry", icon: "filling", image: "/demo/img/dental/doctor-lamp-adjust-640.webp", reason: "checkup",
        summary: "Composite fillings for cavities, matched to your tooth and done in one visit.",
        what: "Decay is removed and the tooth rebuilt with composite resin that bonds to it and matches its colour. It sets with a light, so you can eat normally the same day.",
        symptoms: ["Sensitivity to sweets or cold", "A hole or dark spot", "A broken old filling"],
        whoNeedsIt: ["Adults and children with small or medium cavities"],
        steps: [
          { title: "Numb if needed", body: "Local anaesthesia for deeper cavities.", hi: { title: "ज़रूरत हो तो सुन्न", body: "गहरे कीड़े के लिए लोकल एनेस्थीसिया।" } },
          { title: "Clean and fill", body: "Decay removed, composite placed in layers.", hi: { title: "सफ़ाई और भरना", body: "कीड़ा हटाकर परतों में कम्पोज़िट।" } },
          { title: "Shape", body: "Polished to your bite.", hi: { title: "आकार", body: "आपके काटने के हिसाब से पॉलिश।" } },
        ],
        duration: "One visit", visits: "30 to 45 minutes per tooth", recovery: "Mild sensitivity for a few days.",
        comfort: "Done under local anaesthesia when the cavity is deep.",
        faqs: [{ title: "Can I eat after a filling?", body: "Yes, once the numbness wears off, so you do not bite your cheek.", hi: { title: "क्या फ़िलिंग के बाद खा सकते हैं?", body: "हाँ, सुन्नपन जाने के बाद, ताकि गाल न कटे।" } }],
        fromPrice: "1,000", priceNote: "per tooth",
        hi: {
          name: "दाँत के रंग की फ़िलिंग", category: "सामान्य डेंटिस्ट्री",
          summary: "कीड़ों के लिए कम्पोज़िट फ़िलिंग, आपके दाँत से मिलती और एक विज़िट में।",
          what: "कीड़ा हटाकर दाँत को कम्पोज़िट रेज़िन से फिर बनाया जाता है जो उससे चिपकता है और उसके रंग से मिलता है। यह लाइट से सख़्त होता है, इसलिए उसी दिन सामान्य खा सकते हैं।",
          symptoms: ["मीठे या ठंडे से झनझनाहट", "छेद या काला धब्बा", "टूटी पुरानी फ़िलिंग"],
          whoNeedsIt: ["छोटे या मध्यम कीड़े वाले बड़े और बच्चे"],
          duration: "एक विज़िट", visits: "प्रति दाँत 30 से 45 मिनट", recovery: "कुछ दिन हल्की झनझनाहट।",
          comfort: "गहरे कीड़े में लोकल एनेस्थीसिया में।", priceNote: "प्रति दाँत",
        },
      },
      {
        slug: "root-canal-treatment", name: "Root canal treatment", category: "Root canal", icon: "root-canal", image: "/demo/img/dental/tech-xray-monitor-640.webp", featured: true, reason: "root-canal",
        summary: "Saves an infected tooth, planned by an endodontist and done at the branch nearest you.",
        what: "Root canal treatment removes infected or inflamed pulp, cleans the canals and seals them. Simple cases are treated by our general dentists at every branch; complex cases and re-treatments by our endodontist on his branch days.",
        symptoms: ["Lingering pain with hot or cold", "Pain on biting", "Night pain", "Swelling near a tooth"],
        whoNeedsIt: ["Teeth whose nerve is damaged but which can still be saved"],
        steps: [
          { title: "Diagnose", body: "X-ray and tests to confirm the tooth.", hi: { title: "निदान", body: "दाँत पक्का करने के लिए एक्स-रे और टेस्ट।" } },
          { title: "Clean and seal", body: "Under local anaesthesia, in one or two visits.", hi: { title: "सफ़ाई और सील", body: "लोकल एनेस्थीसिया में, एक या दो विज़िट में।" } },
          { title: "Crown", body: "A crown on back teeth, often at any branch.", hi: { title: "क्राउन", body: "पीछे के दाँतों पर क्राउन, अक्सर किसी भी शाखा में।" } },
        ],
        duration: "1 to 2 visits, plus a crown", visits: "45 to 90 minutes each. Single-visit root canal where clinically suitable.",
        recovery: "Tender to bite for 2 to 3 days.",
        comfort: "Root canal treatment under local anaesthesia, with comfort breaks when you need them.",
        faqs: [{ title: "Can I start at one branch and finish at another?", body: "Yes. Your records and X-rays move with you, and the price is the same.", hi: { title: "क्या एक शाखा में शुरू करके दूसरी में पूरा करा सकते हैं?", body: "हाँ। आपके रिकॉर्ड और एक्स-रे आपके साथ जाते हैं, और क़ीमत वही रहती है।" } }],
        fromPrice: "4,500", priceNote: "per tooth, front teeth",
        hi: {
          name: "रूट कैनाल ट्रीटमेंट", category: "रूट कैनाल",
          summary: "संक्रमित दाँत बचाता है, एंडोडॉन्टिस्ट की योजना से और आपके सबसे पास की शाखा में।",
          what: "रूट कैनाल में संक्रमित या सूजा गूदा निकालकर नलिकाएँ साफ़ और सील की जाती हैं। आसान मामले हर शाखा में हमारे जनरल डेंटिस्ट करते हैं; जटिल मामले और दोबारा इलाज हमारे एंडोडॉन्टिस्ट अपनी शाखा के दिनों में।",
          symptoms: ["गरम या ठंडे से देर तक दर्द", "काटने पर दर्द", "रात में दर्द", "दाँत के पास सूजन"],
          whoNeedsIt: ["जिनकी नस ख़राब है पर दाँत अभी बच सकता है"],
          duration: "1 से 2 विज़िट, और क्राउन", visits: "हर विज़िट 45 से 90 मिनट। जहाँ क्लिनिकली सही हो, वहाँ एक विज़िट में रूट कैनाल।",
          recovery: "2 से 3 दिन काटने पर हल्का दर्द।",
          comfort: "रूट कैनाल लोकल एनेस्थीसिया में, और जब चाहें तब आराम के लिए रुकावट।", priceNote: "प्रति दाँत, आगे के दाँत",
        },
      },
      {
        slug: "crowns-and-bridges", name: "Crowns and bridges", category: "Implants and crowns", icon: "crown", image: "/demo/img/dental/implant-ceramic-crowns-640.webp", reason: "not-sure",
        summary: "Metal-ceramic and zirconia crowns and bridges, made by one lab for every branch.",
        what: "Crowns protect weak or root-canal-treated teeth; bridges replace a missing tooth using the teeth on either side. All branches use the same dental lab and the same materials, so the work and the price are the same wherever you are treated.",
        symptoms: ["A tooth after root canal treatment", "A large broken filling", "A single missing tooth"],
        whoNeedsIt: ["Adults needing to protect or replace a tooth"],
        steps: [
          { title: "Prepare", body: "Tooth shaped under local anaesthesia; temporary crown.", hi: { title: "तैयारी", body: "लोकल एनेस्थीसिया में दाँत को आकार; अस्थायी क्राउन।" } },
          { title: "Scan", body: "Digital scan and shade match sent to the lab.", hi: { title: "स्कैन", body: "डिजिटल स्कैन और रंग मिलान लैब को।" } },
          { title: "Fit", body: "Final crown checked and cemented.", hi: { title: "फ़िटिंग", body: "अंतिम क्राउन जाँचकर सीमेंट।" } },
        ],
        duration: "5 to 7 working days", visits: "2 visits", recovery: "Your bite settles in a few days.",
        comfort: "Shaping is done under local anaesthesia.",
        faqs: [{ title: "Which crown material should I choose?", body: "Metal-ceramic for strength at the back at a lower cost; zirconia for a natural look at the front.", hi: { title: "कौन सी क्राउन सामग्री चुनूँ?", body: "पीछे मज़बूती और कम ख़र्च के लिए मेटल-सिरेमिक; सामने प्राकृतिक रूप के लिए ज़िरकोनिया।" } }],
        fromPrice: "5,500", priceNote: "per crown, metal-ceramic",
        hi: {
          name: "क्राउन और ब्रिज", category: "इम्प्लांट और क्राउन",
          summary: "मेटल-सिरेमिक और ज़िरकोनिया क्राउन और ब्रिज, हर शाखा के लिए एक ही लैब में बने।",
          what: "क्राउन कमज़ोर या रूट कैनाल हुए दाँतों को बचाते हैं; ब्रिज दोनों ओर के दाँतों के सहारे गायब दाँत की जगह लेते हैं। सभी शाखाएँ एक ही डेंटल लैब और एक ही सामग्री इस्तेमाल करती हैं, इसलिए आप कहीं भी इलाज कराएँ, काम और क़ीमत एक जैसी है।",
          symptoms: ["रूट कैनाल के बाद का दाँत", "बड़ी टूटी फ़िलिंग", "एक गायब दाँत"],
          whoNeedsIt: ["जिन्हें दाँत बचाना या बदलना है"],
          duration: "5 से 7 कार्य दिवस", visits: "2 विज़िट", recovery: "कुछ दिनों में काटना सामान्य।",
          comfort: "आकार देना लोकल एनेस्थीसिया में होता है।", priceNote: "प्रति क्राउन, मेटल-सिरेमिक",
        },
      },
      {
        slug: "dental-implants", name: "Dental implants", category: "Implants and crowns", icon: "implant", image: "/demo/img/dental/implant-models-table-640.webp", featured: true, reason: "implants",
        summary: "Missing teeth replaced with implants, planned on a 3D scan by our surgeon and prosthodontist.",
        what: "An implant is a titanium post placed in the jawbone, topped with a crown once the bone has healed. Every implant is planned on a CBCT scan. Surgery is done by our oral surgeon at Lajpat Nagar, Dwarka or Gurugram; the crown can be fitted at any branch.",
        symptoms: ["A missing tooth", "A loose denture", "A failing bridge"],
        whoNeedsIt: ["Adults with enough bone, or who can have a graft"],
        steps: [
          { title: "Scan and plan", body: "CBCT scan, plan and itemised estimate.", hi: { title: "स्कैन और योजना", body: "CBCT स्कैन, योजना और मदवार अनुमान।" } },
          { title: "Place", body: "Under local anaesthesia at a surgical branch.", hi: { title: "लगाना", body: "सर्जिकल शाखा में लोकल एनेस्थीसिया में।" } },
          { title: "Crown", body: "Fitted after healing, at your nearest branch.", hi: { title: "क्राउन", body: "भरने के बाद, आपकी सबसे पास की शाखा में।" } },
        ],
        duration: "3 to 6 months", visits: "4 to 5 visits", recovery: "Swelling for 2 to 4 days after surgery.",
        comfort: "Placed under local anaesthesia.",
        faqs: [{ title: "Is the implant price the same at every branch?", body: "Yes. After the scan you get one itemised estimate that applies at any branch.", hi: { title: "क्या इम्प्लांट की क़ीमत हर शाखा में एक जैसी है?", body: "हाँ। स्कैन के बाद आपको एक मदवार अनुमान मिलता है जो हर शाखा में लागू होता है।" } }],
        priceNote: "Cost after consultation and X-ray",
        hi: {
          name: "डेंटल इम्प्लांट", category: "इम्प्लांट और क्राउन",
          summary: "गायब दाँत इम्प्लांट से, हमारे सर्जन और प्रोस्थोडॉन्टिस्ट द्वारा 3D स्कैन पर योजना के साथ।",
          what: "इम्प्लांट जबड़े की हड्डी में लगाया गया टाइटेनियम पोस्ट है, जिस पर हड्डी भरने के बाद क्राउन लगता है। हर इम्प्लांट की योजना CBCT स्कैन पर बनती है। सर्जरी हमारे ओरल सर्जन लाजपत नगर, द्वारका या गुरुग्राम में करते हैं; क्राउन किसी भी शाखा में लग सकता है।",
          symptoms: ["गायब दाँत", "ढीला डेंचर", "ख़राब होता ब्रिज"],
          whoNeedsIt: ["पर्याप्त हड्डी वाले वयस्क, या जिन्हें ग्राफ़्ट लग सके"],
          duration: "3 से 6 महीने", visits: "4 से 5 विज़िट", recovery: "सर्जरी के बाद 2 से 4 दिन सूजन।",
          comfort: "लोकल एनेस्थीसिया में लगाया जाता है।", priceNote: "परामर्श और एक्स-रे के बाद ख़र्च",
        },
      },
      {
        slug: "braces-and-aligners", name: "Braces and aligners", category: "Orthodontics", icon: "braces", image: "/demo/img/dental/ortho-aligners-vs-braces-640.webp", featured: true, reason: "braces",
        summary: "Metal and ceramic braces and clear aligners, planned by our orthodontist in Noida and Lajpat Nagar.",
        what: "Our orthodontist examines the bite, takes a 3D scan and explains which option suits you: metal braces, ceramic braces or clear aligners. Check-ins are at her branch days, including early evenings.",
        symptoms: ["Crowded or crooked teeth", "Gaps", "Upper teeth that stick out"],
        whoNeedsIt: ["Children from about 11, and adults with healthy gums"],
        steps: [
          { title: "Records", body: "Scan, photos and X-rays.", hi: { title: "रिकॉर्ड", body: "स्कैन, फ़ोटो और एक्स-रे।" } },
          { title: "Plan", body: "Options, time and a monthly payment plan in writing.", hi: { title: "योजना", body: "विकल्प, समय और मासिक भुगतान योजना लिखित में।" } },
          { title: "Treat and retain", body: "Check-ins every 4 to 8 weeks, then retainers.", hi: { title: "इलाज और रिटेनर", body: "हर 4 से 8 हफ़्ते जाँच, फिर रिटेनर।" } },
        ],
        duration: "Usually 12 to 24 months", visits: "A check-in every 4 to 8 weeks", recovery: "Soreness for 2 to 3 days after adjustments.",
        comfort: "No injections are needed.",
        faqs: [{ title: "Can I pay monthly?", body: "Yes. Braces are usually paid as a first amount and monthly instalments.", hi: { title: "क्या हर महीने भुगतान कर सकते हैं?", body: "हाँ। ब्रेसेज़ का भुगतान आमतौर पर पहली राशि और मासिक किस्तों में होता है।" } }],
        fromPrice: "35,000", priceNote: "metal braces, both jaws",
        hi: {
          name: "ब्रेसेज़ और अलाइनर", category: "ऑर्थोडॉन्टिक्स",
          summary: "मेटल और सिरेमिक ब्रेसेज़ और क्लियर अलाइनर, नोएडा और लाजपत नगर में हमारी ऑर्थोडॉन्टिस्ट की योजना से।",
          what: "हमारी ऑर्थोडॉन्टिस्ट काटने की जाँच करती हैं, 3D स्कैन लेती हैं और बताती हैं कि कौन सा विकल्प सही है: मेटल ब्रेसेज़, सिरेमिक ब्रेसेज़ या क्लियर अलाइनर। जाँच उनकी शाखा के दिनों में होती है, शाम समेत।",
          symptoms: ["भीड़ वाले या टेढ़े दाँत", "गैप", "ऊपर के दाँत आगे निकले"],
          whoNeedsIt: ["लगभग 11 साल से बच्चे, और स्वस्थ मसूड़ों वाले वयस्क"],
          duration: "आमतौर पर 12 से 24 महीने", visits: "हर 4 से 8 हफ़्ते जाँच", recovery: "सुधार के बाद 2 से 3 दिन दर्द।",
          comfort: "इंजेक्शन की ज़रूरत नहीं।", priceNote: "मेटल ब्रेसेज़, दोनों जबड़े",
        },
      },
      {
        slug: "teeth-whitening", name: "Teeth whitening", category: "Cosmetic", icon: "whitening", image: "/demo/img/dental/patient-woman-chair-640.webp", reason: "whitening",
        summary: "Supervised in-clinic whitening after a check and a clean.",
        what: "Peroxide gel lightens the natural colour of the teeth while the gums are protected. It does not change crowns or fillings, which we tell you about before we start.",
        symptoms: ["Yellowing", "Tea, coffee or tobacco stains"],
        whoNeedsIt: ["Adults with healthy teeth and gums; not in pregnancy"],
        steps: [
          { title: "Check and clean", body: "Decay and gums treated first.", hi: { title: "जाँच और सफ़ाई", body: "पहले कीड़े और मसूड़ों का इलाज।" } },
          { title: "Whiten", body: "Gel applied in rounds over about an hour.", hi: { title: "व्हाइटनिंग", body: "लगभग एक घंटे में कई बार जेल।" } },
          { title: "Aftercare", body: "No strongly coloured food for 48 hours.", hi: { title: "बाद की देखभाल", body: "48 घंटे गहरे रंग वाला खाना नहीं।" } },
        ],
        duration: "One visit", visits: "About 90 minutes", recovery: "Sensitivity for a day or two.",
        comfort: "No anaesthetic is needed.",
        faqs: [{ title: "Are results the same for everyone?", body: "No. Results vary from person to person; your starting shade matters most.", hi: { title: "क्या सबके नतीजे एक जैसे होते हैं?", body: "नहीं। नतीजे हर व्यक्ति में अलग होते हैं; आपका शुरुआती रंग सबसे ज़्यादा मायने रखता है।" } }],
        fromPrice: "10,000", priceNote: "in-clinic, both jaws",
        hi: {
          name: "दाँत सफ़ेद करना", category: "कॉस्मेटिक",
          summary: "जाँच और सफ़ाई के बाद क्लिनिक में निगरानी वाली व्हाइटनिंग।",
          what: "मसूड़ों को सुरक्षित करके पेरॉक्साइड जेल दाँतों का प्राकृतिक रंग हल्का करता है। यह क्राउन या फ़िलिंग का रंग नहीं बदलता, जो हम शुरू करने से पहले बताते हैं।",
          symptoms: ["पीलापन", "चाय, कॉफ़ी या तंबाकू के दाग़"],
          whoNeedsIt: ["स्वस्थ दाँत और मसूड़ों वाले वयस्क; गर्भावस्था में नहीं"],
          duration: "एक विज़िट", visits: "लगभग 90 मिनट", recovery: "एक-दो दिन झनझनाहट।",
          comfort: "सुन्न करने की ज़रूरत नहीं।", priceNote: "क्लिनिक में, दोनों जबड़े",
        },
      },
      {
        slug: "kids-dentistry", name: "Kids dentistry", category: "Children", icon: "kids", image: "/demo/img/dental/kids-dentist-boy-smile-640.webp", reason: "kids",
        summary: "Check-ups, fluoride, sealants and fillings by our paediatric dentist in Rohini and Gurugram.",
        what: "Our paediatric dentist sees children from the first tooth. Visits are short, a parent stays in the room, and prevention comes first. General dentists at every branch see children for routine check-ups too.",
        symptoms: ["White or brown spots on teeth", "Pain with sweets", "Thumb sucking after four"],
        whoNeedsIt: ["Babies by the first birthday; children every six months"],
        steps: [
          { title: "Meet", body: "A look around the room first.", hi: { title: "मुलाक़ात", body: "पहले कमरे से पहचान।" } },
          { title: "Check", body: "A gentle examination with the child's help.", hi: { title: "जाँच", body: "बच्चे की मदद से हल्की जाँच।" } },
          { title: "Prevent or treat", body: "Fluoride, sealants or a filling at the child's pace.", hi: { title: "बचाव या इलाज", body: "बच्चे की रफ़्तार से फ़्लोराइड, सीलेंट या फ़िलिंग।" } },
        ],
        duration: "One visit for a check-up", visits: "20 to 40 minutes", recovery: "None for a check-up.",
        comfort: "Tell-show-do, and a parent in the room throughout.",
        faqs: [{ title: "Are children included in the family plan?", body: "Yes. The family care plan covers check-ups and cleanings for children too.", hi: { title: "क्या बच्चे फ़ैमिली प्लान में शामिल हैं?", body: "हाँ। फ़ैमिली केयर प्लान बच्चों के चेक-अप और सफ़ाई भी कवर करता है।" } }],
        fromPrice: "600", priceNote: "per sealant",
        hi: {
          name: "बच्चों के दाँत", category: "बच्चे",
          summary: "रोहिणी और गुरुग्राम में हमारी बच्चों की डेंटिस्ट द्वारा चेक-अप, फ़्लोराइड, सीलेंट और फ़िलिंग।",
          what: "हमारी बच्चों की डेंटिस्ट पहले दाँत से बच्चों को देखती हैं। विज़िट छोटी होती हैं, माता-पिता कमरे में रहते हैं, और बचाव पहले आता है। हर शाखा के जनरल डेंटिस्ट भी बच्चों के सामान्य चेक-अप करते हैं।",
          symptoms: ["दाँतों पर सफ़ेद या भूरे धब्बे", "मीठे से दर्द", "चार साल के बाद अँगूठा चूसना"],
          whoNeedsIt: ["पहले जन्मदिन तक के शिशु; बच्चे हर छह महीने"],
          duration: "चेक-अप के लिए एक विज़िट", visits: "20 से 40 मिनट", recovery: "चेक-अप के बाद कुछ नहीं।",
          comfort: "बताओ-दिखाओ-करो, और पूरे समय कमरे में माता-पिता।", priceNote: "प्रति सीलेंट",
        },
      },
      {
        slug: "wisdom-tooth-removal", name: "Wisdom tooth removal", category: "Oral surgery", icon: "wisdom", image: "/demo/img/dental/tech-3d-imaging-640.webp", reason: "wisdom",
        summary: "Surgical removal of impacted wisdom teeth by our oral surgeon, planned on an X-ray or 3D scan.",
        what: "When a wisdom tooth is stuck and causes repeated swelling or harms the tooth in front, our oral surgeon removes it under local anaesthesia. A 3D scan is used when the roots lie close to the nerve.",
        symptoms: ["Recurring swelling at the back of the jaw", "Pain opening wide", "Food trapped behind the last molar"],
        whoNeedsIt: ["Adults with symptomatic wisdom teeth"],
        steps: [
          { title: "Scan", body: "X-ray, and CBCT if needed.", hi: { title: "स्कैन", body: "एक्स-रे, और ज़रूरत हो तो CBCT।" } },
          { title: "Remove", body: "Under local anaesthesia at a surgical branch.", hi: { title: "निकालना", body: "सर्जिकल शाखा में लोकल एनेस्थीसिया में।" } },
          { title: "Review", body: "A check after a week at any branch.", hi: { title: "जाँच", body: "एक हफ़्ते बाद किसी भी शाखा में जाँच।" } },
        ],
        duration: "One visit, plus a review", visits: "30 to 60 minutes", recovery: "Swelling for 3 to 5 days.",
        comfort: "Done under local anaesthesia.",
        faqs: [{ title: "Will I need time off work?", body: "Most people take one or two days off after a surgical removal.", hi: { title: "क्या काम से छुट्टी लेनी पड़ेगी?", body: "सर्जिकल निकासी के बाद ज़्यादातर लोग एक-दो दिन की छुट्टी लेते हैं।" } }],
        fromPrice: "5,000", priceNote: "per tooth, surgical",
        hi: {
          name: "अक़्ल दाढ़ निकालना", category: "ओरल सर्जरी",
          summary: "हमारे ओरल सर्जन द्वारा फँसी अक़्ल दाढ़ की सर्जिकल निकासी, एक्स-रे या 3D स्कैन पर योजना के साथ।",
          what: "जब अक़्ल दाढ़ फँसी हो और बार-बार सूजन करे या आगे के दाँत को नुकसान दे, तो हमारे ओरल सर्जन उसे लोकल एनेस्थीसिया में निकालते हैं। जड़ें नस के पास हों तो 3D स्कैन इस्तेमाल होता है।",
          symptoms: ["जबड़े के पीछे बार-बार सूजन", "मुँह पूरा खोलने में दर्द", "आख़िरी दाढ़ के पीछे खाना फँसना"],
          whoNeedsIt: ["तकलीफ़ देने वाली अक़्ल दाढ़ वाले वयस्क"],
          duration: "एक विज़िट, और जाँच", visits: "30 से 60 मिनट", recovery: "3 से 5 दिन सूजन।",
          comfort: "लोकल एनेस्थीसिया में किया जाता है।", priceNote: "प्रति दाँत, सर्जिकल",
        },
      },
    ],
    specialties: [
      { title: "General dentistry", body: "Check-ups, cleaning and fillings at every branch, all day.", group: "General dentistry", hi: { title: "सामान्य डेंटिस्ट्री", body: "हर शाखा में पूरे दिन चेक-अप, सफ़ाई और फ़िलिंग।", group: "सामान्य डेंटिस्ट्री" } },
      { title: "Root canal", body: "Endodontist-led root canal and re-treatment.", group: "Root canal", hi: { title: "रूट कैनाल", body: "एंडोडॉन्टिस्ट की अगुवाई में रूट कैनाल और दोबारा इलाज।", group: "रूट कैनाल" } },
      { title: "Implants and crowns", body: "Implants, crowns, bridges and dentures, planned by a prosthodontist.", group: "Implants and crowns", hi: { title: "इम्प्लांट और क्राउन", body: "प्रोस्थोडॉन्टिस्ट की योजना से इम्प्लांट, क्राउन, ब्रिज और डेंचर।", group: "इम्प्लांट और क्राउन" } },
      { title: "Orthodontics", body: "Braces and clear aligners by an orthodontist.", group: "Orthodontics", hi: { title: "ऑर्थोडॉन्टिक्स", body: "ऑर्थोडॉन्टिस्ट द्वारा ब्रेसेज़ और क्लियर अलाइनर।", group: "ऑर्थोडॉन्टिक्स" } },
      { title: "Children", body: "A paediatric dentist for first visits and milk teeth.", group: "Children", hi: { title: "बच्चे", body: "पहली विज़िट और दूध के दाँतों के लिए बच्चों की डेंटिस्ट।", group: "बच्चे" } },
      { title: "Oral surgery", body: "Wisdom teeth and implant surgery by an oral surgeon.", group: "Oral surgery", hi: { title: "ओरल सर्जरी", body: "ओरल सर्जन द्वारा अक़्ल दाढ़ और इम्प्लांट सर्जरी।", group: "ओरल सर्जरी" } },
      { title: "Cosmetic", body: "Whitening, supervised in the clinic.", group: "Cosmetic", hi: { title: "कॉस्मेटिक", body: "क्लिनिक में निगरानी वाली व्हाइटनिंग।", group: "कॉस्मेटिक" } },
    ],
    technology: [
      { title: "Digital X-rays at every branch", benefit: "A lower dose than film, on screen in seconds and shared with every branch.", group: "diagnosis", icon: "xray", image: "/demo/img/dental/tech-xray-monitor-640.webp", hi: { title: "हर शाखा में डिजिटल एक्स-रे", benefit: "फ़िल्म से कम डोज़, कुछ सेकंड में स्क्रीन पर और हर शाखा के साथ साझा।" } },
      { title: "3D CBCT imaging", benefit: "Implants and wisdom tooth surgery planned in three dimensions at our surgical branches.", group: "diagnosis", icon: "cbct", image: "/demo/img/dental/tech-3d-imaging-640.webp", hi: { title: "3D CBCT इमेजिंग", benefit: "हमारी सर्जिकल शाखाओं में इम्प्लांट और अक़्ल दाढ़ की सर्जरी की योजना तीन आयामों में।" } },
      { title: "Shared patient records", benefit: "Your notes, X-rays and plan are available at any branch you visit.", group: "speed", icon: "calendar", hi: { title: "साझा मरीज़ रिकॉर्ड", benefit: "आपके नोट, एक्स-रे और योजना हर उस शाखा में मिलते हैं जहाँ आप जाएँ।" } },
      { title: "Intraoral scanner", benefit: "Digital impressions for crowns and aligners, without impression trays.", group: "precision", icon: "scan", image: "/demo/img/dental/tech-intraoral-scanner-640.webp", hi: { title: "इंट्राओरल स्कैनर", benefit: "क्राउन और अलाइनर के लिए डिजिटल नाप, साँचे की ट्रे के बिना।" } },
      { title: "Class B autoclaves", benefit: "The same sterilisation equipment and daily test log in every branch.", group: "hygiene", icon: "sterile", image: "/demo/img/dental/sterile-autoclave-640.webp", hi: { title: "क्लास B ऑटोक्लेव", benefit: "हर शाखा में वही स्टरलाइज़ेशन उपकरण और रोज़ का टेस्ट रिकॉर्ड।" } },
    ],
    fees: [
      { treatment: "Consultation, general dentist", slug: "dental-check-up", from: "400", unit: "per visit", group: "Consultation", hi: { treatment: "परामर्श, जनरल डेंटिस्ट", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "Consultation, specialist", from: "700", unit: "per visit", group: "Consultation", hi: { treatment: "परामर्श, विशेषज्ञ", unit: "प्रति विज़िट", group: "परामर्श" } },
      { treatment: "Teeth cleaning", slug: "teeth-cleaning", from: "1,200", unit: "full mouth", group: "General dentistry", hi: { treatment: "दाँतों की सफ़ाई", unit: "पूरा मुँह", group: "सामान्य डेंटिस्ट्री" } },
      { treatment: "Tooth-coloured filling", slug: "fillings", from: "1,000", unit: "per tooth", group: "General dentistry", hi: { treatment: "दाँत के रंग की फ़िलिंग", unit: "प्रति दाँत", group: "सामान्य डेंटिस्ट्री" } },
      { treatment: "Root canal treatment (front tooth)", slug: "root-canal-treatment", from: "4,500", unit: "per tooth", group: "Root canal", hi: { treatment: "रूट कैनाल (आगे का दाँत)", unit: "प्रति दाँत", group: "रूट कैनाल" } },
      { treatment: "Root canal treatment (molar)", slug: "root-canal-treatment", from: "6,500", unit: "per tooth", group: "Root canal", note: "Crown charged separately", hi: { treatment: "रूट कैनाल (दाढ़)", unit: "प्रति दाँत", group: "रूट कैनाल", note: "क्राउन का शुल्क अलग" } },
      { treatment: "Crown, metal-ceramic", slug: "crowns-and-bridges", from: "5,500", unit: "per crown", group: "Implants and crowns", hi: { treatment: "क्राउन, मेटल-सिरेमिक", unit: "प्रति क्राउन", group: "इम्प्लांट और क्राउन" } },
      { treatment: "Crown, zirconia", slug: "crowns-and-bridges", from: "11,000", unit: "per crown", group: "Implants and crowns", hi: { treatment: "क्राउन, ज़िरकोनिया", unit: "प्रति क्राउन", group: "इम्प्लांट और क्राउन" } },
      { treatment: "Dental implant with crown", slug: "dental-implants", consult: true, group: "Implants and crowns", hi: { treatment: "क्राउन के साथ डेंटल इम्प्लांट", group: "इम्प्लांट और क्राउन" } },
      { treatment: "Metal braces", slug: "braces-and-aligners", from: "35,000", unit: "both jaws", group: "Orthodontics", hi: { treatment: "मेटल ब्रेसेज़", unit: "दोनों जबड़े", group: "ऑर्थोडॉन्टिक्स" } },
      { treatment: "Clear aligners", slug: "braces-and-aligners", consult: true, group: "Orthodontics", hi: { treatment: "क्लियर अलाइनर", group: "ऑर्थोडॉन्टिक्स" } },
      { treatment: "In-clinic whitening", slug: "teeth-whitening", from: "10,000", unit: "both jaws", group: "Cosmetic", hi: { treatment: "क्लिनिक में व्हाइटनिंग", unit: "दोनों जबड़े", group: "कॉस्मेटिक" } },
      { treatment: "Sealant (child)", slug: "kids-dentistry", from: "600", unit: "per tooth", group: "Children", hi: { treatment: "सीलेंट (बच्चा)", unit: "प्रति दाँत", group: "बच्चे" } },
      { treatment: "Wisdom tooth removal (surgical)", slug: "wisdom-tooth-removal", from: "5,000", unit: "per tooth", group: "Oral surgery", hi: { treatment: "अक़्ल दाढ़ निकालना (सर्जिकल)", unit: "प्रति दाँत", group: "ओरल सर्जरी" } },
    ],
    payment: {
      emi: "EMI options may be available through partner lenders, subject to their approval.",
      emiExample: "Illustration only: Rs 36,000 over 12 months is about Rs 3,000 a month before any lender charges.",
      partners: ["Card EMI through your bank", "A healthcare finance partner (sample)"],
      modes: ["UPI", "Debit and credit cards", "Net banking", "Cash"],
      insurance: "Reimbursement with some insurers and corporate policies where dental treatment is covered; ask at any branch. Itemised bills and reports provided.",
      consultFee: "Consultation: Rs 400 with a general dentist, Rs 700 with a specialist, at every branch.",
      hi: {
        emi: "साथी संस्थाओं के ज़रिए EMI विकल्प मिल सकते हैं, उनकी मंज़ूरी पर।",
        emiExample: "सिर्फ़ उदाहरण: 12 महीने में 36,000 रुपये, किसी भी शुल्क से पहले लगभग 3,000 रुपये महीना।",
        partners: ["आपके बैंक के कार्ड पर EMI", "एक हेल्थकेयर फ़ाइनेंस साथी (नमूना)"],
        modes: ["UPI", "डेबिट और क्रेडिट कार्ड", "नेट बैंकिंग", "नक़द"],
        insurance: "जहाँ दाँतों का इलाज कवर हो, वहाँ कुछ बीमा कंपनियों और कॉर्पोरेट पॉलिसी से भरपाई; किसी भी शाखा में पूछें। मदवार बिल और रिपोर्ट दी जाती हैं।",
        consultFee: "परामर्श: हर शाखा में जनरल डेंटिस्ट के साथ 400 रुपये, विशेषज्ञ के साथ 700 रुपये।",
      },
    },
    plans: [
      { name: "Individual care plan", price: "1,800", period: "per year", includes: ["Two check-ups", "Two cleanings", "Routine X-rays at check-ups", "Booking at any branch"], note: "Other treatment is charged at the standard price list.", hi: { name: "व्यक्तिगत केयर प्लान", price: "1,800", period: "प्रति वर्ष", includes: ["दो चेक-अप", "दो सफ़ाई", "चेक-अप पर सामान्य एक्स-रे", "किसी भी शाखा में बुकिंग"], note: "बाक़ी इलाज सामान्य क़ीमत सूची के अनुसार।" } },
      { name: "Family care plan", price: "5,400", period: "per year, up to four members", includes: ["Two check-ups for each member", "Two cleanings for each member", "Fluoride for children at check-ups", "Booking at any branch"], note: "Other treatment is charged at the standard price list.", hi: { name: "फ़ैमिली केयर प्लान", price: "5,400", period: "प्रति वर्ष, चार सदस्यों तक", includes: ["हर सदस्य के दो चेक-अप", "हर सदस्य की दो सफ़ाई", "चेक-अप पर बच्चों को फ़्लोराइड", "किसी भी शाखा में बुकिंग"], note: "बाक़ी इलाज सामान्य क़ीमत सूची के अनुसार।" } },
      { name: "Senior care plan", price: "2,400", period: "per year", includes: ["Two check-ups", "Two cleanings", "Denture checks and cleaning", "Priority morning slots"], note: "For patients over 60. Other treatment is charged at the standard price list.", hi: { name: "वरिष्ठ केयर प्लान", price: "2,400", period: "प्रति वर्ष", includes: ["दो चेक-अप", "दो सफ़ाई", "डेंचर की जाँच और सफ़ाई", "सुबह के स्लॉट में प्राथमिकता"], note: "60 से ऊपर के मरीज़ों के लिए। बाक़ी इलाज सामान्य क़ीमत सूची के अनुसार।" } },
    ],
    corporate: [
      { title: "Check-up days at a branch", body: "Your team books check-ups at the branch nearest your office, on a day set aside for you.", hi: { title: "शाखा में चेक-अप डे", body: "आपकी टीम आपके दफ़्तर के सबसे पास की शाखा में, आपके लिए तय दिन पर चेक-अप बुक करती है।" } },
      { title: "An employee care plan", body: "Check-ups and cleanings for employees and their families at any branch.", hi: { title: "कर्मचारी केयर प्लान", body: "कर्मचारियों और उनके परिवारों के लिए किसी भी शाखा में चेक-अप और सफ़ाई।" } },
      { title: "Itemised bills for claims", body: "Bills and reports in the format your insurer or HR team needs.", hi: { title: "क्लेम के लिए मदवार बिल", body: "आपकी बीमा कंपनी या HR टीम के ज़रूरी फ़ॉर्मेट में बिल और रिपोर्ट।" } },
      { title: "One contact person", body: "A named coordinator for bookings and questions.", hi: { title: "एक संपर्क व्यक्ति", body: "बुकिंग और सवालों के लिए एक नामित समन्वयक।" } },
    ],
    emergency: {
      headline: "Tooth pain? Same-day emergency appointments",
      intro: "Every branch keeps emergency slots for severe pain, swelling and broken teeth, including Sunday mornings. Call or WhatsApp and we will tell you which branch can see you soonest.",
      phone: "+91 00000 00000",
      whatsapp: "910000000000",
      hours: "Emergency line answered 8 am to 10 pm, all week",
      urgent: ["Severe toothache", "Swelling of the face, gum or jaw", "A knocked-out or broken tooth", "Bleeding after an extraction that pressure does not stop"],
      firstAid: [
        { title: "Knocked-out adult tooth", body: "Hold it by the crown, rinse briefly in milk, put it back or keep it in milk, and come to the nearest branch within the hour.", hi: { title: "पक्का दाँत निकल गया", body: "ऊपर के हिस्से से पकड़ें, दूध में हल्का धोएँ, वापस लगाएँ या दूध में रखें, और एक घंटे के अंदर सबसे पास की शाखा आएँ।" } },
        { title: "Broken tooth", body: "Rinse with warm water, keep the pieces, and use a cold pack on the cheek.", hi: { title: "टूटा दाँत", body: "गुनगुने पानी से कुल्ला करें, टुकड़े संभालें, और गाल पर ठंडी सिकाई करें।" } },
        { title: "Bleeding after an extraction", body: "Bite on folded clean gauze for 30 minutes without checking. Do not rinse or spit.", hi: { title: "दाँत निकलने के बाद ख़ून", body: "साफ़ मुड़ी गॉज़ को 30 मिनट बिना देखे दबाएँ। कुल्ला न करें, थूकें नहीं।" } },
        { title: "Swelling", body: "Cold pack outside, head raised, and call us. Do not apply heat.", hi: { title: "सूजन", body: "बाहर ठंडी सिकाई, सिर ऊँचा, और हमें फ़ोन करें। गरम सिकाई न करें।" } },
      ],
      canWait: ["A lost filling without pain", "A small chip without pain", "Mild sensitivity to cold", "A loose crown still in place"],
      hi: {
        headline: "दाँत में दर्द? उसी दिन इमरजेंसी अपॉइंटमेंट",
        intro: "हर शाखा तेज़ दर्द, सूजन और टूटे दाँतों के लिए इमरजेंसी स्लॉट रखती है, रविवार सुबह भी। फ़ोन या व्हाट्सऐप करें, हम बताएँगे कि कौन सी शाखा सबसे जल्दी देख सकती है।",
        hours: "इमरजेंसी लाइन सुबह 8 से रात 10 तक, पूरे हफ़्ते",
        urgent: ["तेज़ दाँत दर्द", "चेहरे, मसूड़े या जबड़े में सूजन", "निकला या टूटा दाँत", "दाँत निकालने के बाद ख़ून जो दबाने से न रुके"],
        canWait: ["बिना दर्द के निकली फ़िलिंग", "बिना दर्द का छोटा टूटा किनारा", "ठंडे से हल्की झनझनाहट", "ढीला क्राउन जो अपनी जगह पर है"],
      },
    },
    booking: {
      reasons: [
        { id: "pain", label: "Tooth pain or swelling", icon: "pain", urgent: true, treatment: "root-canal-treatment", hi: { label: "दाँत में दर्द या सूजन" } },
        { id: "checkup", label: "Check-up", icon: "checkup", treatment: "dental-check-up", hi: { label: "चेक-अप" } },
        { id: "cleaning", label: "Cleaning", icon: "cleaning", treatment: "teeth-cleaning", hi: { label: "सफ़ाई" } },
        { id: "root-canal", label: "Root canal", icon: "root-canal", treatment: "root-canal-treatment", hi: { label: "रूट कैनाल" } },
        { id: "implants", label: "Missing tooth or implants", icon: "implant", treatment: "dental-implants", hi: { label: "गायब दाँत या इम्प्लांट" } },
        { id: "braces", label: "Braces or aligners", icon: "braces", treatment: "braces-and-aligners", hi: { label: "ब्रेसेज़ या अलाइनर" } },
        { id: "kids", label: "For my child", icon: "kids", treatment: "kids-dentistry", hi: { label: "बच्चे के लिए" } },
        { id: "not-sure", label: "Not sure", icon: "tooth", hi: { label: "पक्का नहीं पता" } },
      ],
      morning: ["9:00 am", "10:00 am", "11:00 am", "12:00 pm", "1:00 pm"],
      evening: ["5:00 pm", "6:00 pm", "7:00 pm", "8:00 pm"],
      closedDays: [],
      closedNote: "Sunday: 10 am to 2 pm at every branch",
      hi: { closedNote: "रविवार: हर शाखा में सुबह 10 से दोपहर 2" },
    },
    sessions: [
      { days: [1, 2, 3, 4, 5, 6], from: "09:00", to: "21:00" },
      { days: [0], from: "10:00", to: "14:00" },
    ],
    sterilisation: [
      { title: "One written protocol", body: "Every branch follows the same steps, trained and audited monthly.", hi: { title: "एक लिखित प्रक्रिया", body: "हर शाखा वही क़दम अपनाती है, प्रशिक्षण और हर महीने जाँच के साथ।" } },
      { title: "Clean and seal", body: "Instruments cleaned in an ultrasonic bath and sealed in dated pouches.", hi: { title: "सफ़ाई और सील", body: "औज़ार अल्ट्रासोनिक बाथ में साफ़ होकर तारीख़ वाले पाउच में सील।" } },
      { title: "Sterilise and log", body: "Class B autoclave cycles, tested and logged every day.", hi: { title: "स्टरलाइज़ और रिकॉर्ड", body: "क्लास B ऑटोक्लेव चक्र, रोज़ जाँच और रिकॉर्ड।" } },
      { title: "Open in front of you", body: "Pouches opened at your chair; disposables used once.", hi: { title: "आपके सामने खोलना", body: "पाउच आपकी कुर्सी पर खोले जाते हैं; डिस्पोज़ेबल एक बार ही।" } },
    ],
    trust: [
      { title: "One price list", body: "The same starting prices at all five branches.", hi: { title: "एक क़ीमत सूची", body: "पाँचों शाखाओं में वही शुरुआती क़ीमतें।" } },
      { title: "Records that travel with you", body: "Book at whichever branch is nearest this week.", hi: { title: "आपके साथ चलने वाले रिकॉर्ड", body: "इस हफ़्ते जो शाखा सबसे पास हो, वहाँ बुक करें।" } },
      { title: "Specialists on fixed days", body: "Each specialist's branch days are published on their profile.", hi: { title: "तय दिनों पर विशेषज्ञ", body: "हर विशेषज्ञ की शाखा के दिन उनकी प्रोफ़ाइल पर दिए हैं।" } },
      { title: "Monthly clinical audits", body: "Sterilisation and records checked at every branch.", hi: { title: "हर महीने क्लिनिकल जाँच", body: "हर शाखा में स्टरलाइज़ेशन और रिकॉर्ड की जाँच।" } },
    ],
    comfort: [
      { title: "Local anaesthesia, checked first", body: "We confirm the area is numb before starting.", hi: { title: "लोकल एनेस्थीसिया, पहले जाँच", body: "शुरू करने से पहले पक्का करते हैं कि जगह सुन्न है।" } },
      { title: "Pause when you need to", body: "Raise a hand and we stop.", hi: { title: "ज़रूरत हो तो रुकें", body: "हाथ उठाएँ और हम रुक जाएँगे।" } },
      { title: "Choose your dentist", body: "Filter by language and gender, and book the same dentist each time.", hi: { title: "अपना डेंटिस्ट चुनें", body: "भाषा और लिंग से छाँटें, और हर बार उसी डेंटिस्ट के साथ बुक करें।" } },
    ],
  },
});
